#!/bin/sh
CLOSURE=~/closure/closure-library-read-only
CALCDEPS=$CLOSURE/closure/bin
CLOSURECSS=$CLOSURE/closure/goog/css
ROOT=~/HTE2
HTE2=$ROOT/js
HTE2CSS=$ROOT/css
HTE2COMP=~/HTE2_Compiled/jsc
HTE2CSSCOMP=~/HTE2_Compiled/cssc
COMPILER=~/compiler-latest

#here should go files with goog.* dependencies
python $CALCDEPS/calcdeps.py -i $HTE2/hte.js -i $HTE2/mouseHandler.js -i $HTE2/keyHandler.js -p $CLOSURE/ -o script > $HTE2COMP/hte_comp.js

#files here should go in the order they appear on the page
cat $HTE2COMP/hte_comp.js $HTE2/pubsub.js $HTE2/mouseHandler.js $HTE2/tracker.js $HTE2/cursor.js $HTE2/measurer.js $HTE2/styling.js $HTE2/workbench.js $HTE2/line.js $HTE2/keyHandler.js $HTE2/UI.js $HTE2/bootstrap.js > $HTE2COMP/hteconcat.js

#compiling with different options
java -jar $COMPILER/compiler.jar --js $HTE2COMP/hteconcat.js --js_output_file $HTE2COMP/hte.js
java -jar $COMPILER/compiler.jar  --compilation_level ADVANCED_OPTIMIZATIONS --js $HTE2COMP/hteconcat.js --js_output_file $HTE2COMP/hte_adv.js

#compiling css
cat $HTE2CSS/reset.css $CLOSURECSS/common.css $CLOSURECSS/toolbar.css $CLOSURECSS/menu.css $CLOSURECSS/menuitem.css $HTE2CSS/main.css > $HTE2CSSCOMP/css.css
mv $HTE2CSSCOMP/css.css $ROOT/cssc/css.css
mv $HTE2COMP/hte_adv.js $ROOT/jsc/hte_adv.js




