function aa(){return function(){}}function ba(a){return function(b){this[a]=b}}function e(a){return function(){return this[a]}}function o(a){return function(){return a}}var s,t=this;function ca(a,b){for(var c=a.split("."),d=b||t,f;f=c.shift();)if(d[f])d=d[f];else return null;return d}function u(){}function w(a){a.S=function(){return a.Ve||(a.Ve=new a)}}
function da(a){var b=typeof a;if(b=="object")if(a){if(a instanceof Array||!(a instanceof Object)&&Object.prototype.toString.call(a)=="[object Array]"||typeof a.length=="number"&&typeof a.splice!="undefined"&&typeof a.propertyIsEnumerable!="undefined"&&!a.propertyIsEnumerable("splice"))return"array";if(!(a instanceof Object)&&(Object.prototype.toString.call(a)=="[object Function]"||typeof a.call!="undefined"&&typeof a.propertyIsEnumerable!="undefined"&&!a.propertyIsEnumerable("call")))return"function"}else return"null";
else if(b=="function"&&typeof a.call=="undefined")return"object";return b}function x(a){return da(a)=="array"}function ea(a){var b=da(a);return b=="array"||b=="object"&&typeof a.length=="number"}function y(a){return typeof a=="string"}function ga(a){return typeof a=="number"}function ha(a){return da(a)=="function"}function ia(a){a=da(a);return a=="object"||a=="array"||a=="function"}function ja(a){if(a.hasOwnProperty&&a.hasOwnProperty(ka))return a[ka];a[ka]||(a[ka]=++la);return a[ka]}
var ka="closure_uid_"+Math.floor(Math.random()*2147483648).toString(36),la=0;function ma(a,b){var c=b||t;if(arguments.length>2){var d=Array.prototype.slice.call(arguments,2);return function(){var f=Array.prototype.slice.call(arguments);Array.prototype.unshift.apply(f,d);return a.apply(c,f)}}else return function(){return a.apply(c,arguments)}}
function na(a){var b=Array.prototype.slice.call(arguments,1);return function(){var c=Array.prototype.slice.call(arguments);c.unshift.apply(c,b);return a.apply(this,c)}}var oa=Date.now||function(){return+new Date};function z(a,b){function c(){}c.prototype=b.prototype;a.b=b.prototype;a.prototype=new c;a.prototype.constructor=a}function pa(a){this.stack=Error().stack||"";if(a)this.message=String(a)}z(pa,Error);pa.prototype.name="CustomError";
function qa(a){for(var b=1;b<arguments.length;b++){var c=String(arguments[b]).replace(/\$/g,"$$$$");a=a.replace(/\%s/,c)}return a}function sa(a){return a.replace(/^[\s\xa0]+|[\s\xa0]+$/g,"")}
function ta(a,b){if(b)return a.replace(ua,"&amp;").replace(va,"&lt;").replace(wa,"&gt;").replace(xa,"&quot;");else{if(!ya.test(a))return a;if(a.indexOf("&")!=-1)a=a.replace(ua,"&amp;");if(a.indexOf("<")!=-1)a=a.replace(va,"&lt;");if(a.indexOf(">")!=-1)a=a.replace(wa,"&gt;");if(a.indexOf('"')!=-1)a=a.replace(xa,"&quot;");return a}}var ua=/&/g,va=/</g,wa=/>/g,xa=/\"/g,ya=/[&<>\"]/;
function za(a,b){for(var c=0,d=sa(String(a)).split("."),f=sa(String(b)).split("."),g=Math.max(d.length,f.length),h=0;c==0&&h<g;h++){var j=d[h]||"",i=f[h]||"",k=RegExp("(\\d*)(\\D*)","g"),m=RegExp("(\\d*)(\\D*)","g");do{var l=k.exec(j)||["","",""],n=m.exec(i)||["","",""];if(l[0].length==0&&n[0].length==0)break;c=Aa(l[1].length==0?0:parseInt(l[1],10),n[1].length==0?0:parseInt(n[1],10))||Aa(l[2].length==0,n[2].length==0)||Aa(l[2],n[2])}while(c==0)}return c}
function Aa(a,b){if(a<b)return-1;else if(a>b)return 1;return 0}function Ba(a,b){b.unshift(a);pa.call(this,qa.apply(null,b));b.shift();this.zf=a}z(Ba,pa);Ba.prototype.name="AssertionError";function Ca(a,b){if(!a){var c=Array.prototype.slice.call(arguments,2),d="Assertion failed";if(b){d+=": "+b;var f=c}throw new Ba(""+d,f||[]);}}function Da(a){throw new Ba("Failure"+(a?": "+a:""),Array.prototype.slice.call(arguments,1));}
var A=Array.prototype,Ea=A.indexOf?function(a,b,c){Ca(a.length!=null);return A.indexOf.call(a,b,c)}:function(a,b,c){c=c==null?0:c<0?Math.max(0,a.length+c):c;if(y(a)){if(!y(b)||b.length!=1)return-1;return a.indexOf(b,c)}for(c=c;c<a.length;c++)if(c in a&&a[c]===b)return c;return-1},Fa=A.forEach?function(a,b,c){Ca(a.length!=null);A.forEach.call(a,b,c)}:function(a,b,c){for(var d=a.length,f=y(a)?a.split(""):a,g=0;g<d;g++)g in f&&b.call(c,f[g],g,a)},Ga=A.map?function(a,b,c){Ca(a.length!=null);return A.map.call(a,
b,c)}:function(a,b,c){for(var d=a.length,f=Array(d),g=y(a)?a.split(""):a,h=0;h<d;h++)if(h in g)f[h]=b.call(c,g[h],h,a);return f},Ha=A.every?function(a,b,c){Ca(a.length!=null);return A.every.call(a,b,c)}:function(a,b,c){for(var d=a.length,f=y(a)?a.split(""):a,g=0;g<d;g++)if(g in f&&!b.call(c,f[g],g,a))return false;return true};function Ia(a,b){return Ea(a,b)>=0}function Ja(a,b){var c=Ea(a,b),d;if(d=c>=0){Ca(a.length!=null);A.splice.call(a,c,1)}return d}
function Ka(){return A.concat.apply(A,arguments)}function La(a){if(x(a))return Ka(a);else{for(var b=[],c=0,d=a.length;c<d;c++)b[c]=a[c];return b}}function Ma(a){for(var b=1;b<arguments.length;b++){var c=arguments[b],d;if(x(c)||(d=ea(c))&&c.hasOwnProperty("callee"))a.push.apply(a,c);else if(d)for(var f=a.length,g=c.length,h=0;h<g;h++)a[f+h]=c[h];else a.push(c)}}function Na(a){Ca(a.length!=null);return A.splice.apply(a,Oa(arguments,1))}
function Oa(a,b,c){Ca(a.length!=null);return arguments.length<=2?A.slice.call(a,b):A.slice.call(a,b,c)}var Pa;function Qa(a){return(a=a.className)&&typeof a.split=="function"?a.split(/\s+/):[]}function Ra(a){var b=Qa(a),c;c=Oa(arguments,1);for(var d=0,f=0;f<c.length;f++)if(!Ia(b,c[f])){b.push(c[f]);d++}c=d==c.length;a.className=b.join(" ");return c}
function Sa(a){var b=Qa(a),c;c=Oa(arguments,1);for(var d=0,f=0;f<b.length;f++)if(Ia(c,b[f])){Na(b,f--,1);d++}c=d==c.length;a.className=b.join(" ");return c}function B(a,b){this.x=a!==undefined?a:0;this.y=b!==undefined?b:0}B.prototype.cb=function(){return new B(this.x,this.y)};B.prototype.toString=function(){return"("+this.x+", "+this.y+")"};function Ta(a,b){return new B(a.x-b.x,a.y-b.y)}function C(a,b){this.width=a;this.height=b}
function Ua(a,b){if(a==b)return true;if(!a||!b)return false;return a.width==b.width&&a.height==b.height}C.prototype.cb=function(){return new C(this.width,this.height)};C.prototype.toString=function(){return"("+this.width+" x "+this.height+")"};C.prototype.floor=function(){this.width=Math.floor(this.width);this.height=Math.floor(this.height);return this};C.prototype.round=function(){this.width=Math.round(this.width);this.height=Math.round(this.height);return this};
function Va(a,b,c){for(var d in a)b.call(c,a[d],d,a)}function Wa(a){for(var b in a)return false;return true}function Xa(a,b){var c;if(c=b in a)delete a[b];return c}function Ya(a,b,c){if(b in a)throw Error('The object already contains the key "'+b+'"');a[b]=c}function Za(a){var b={};for(var c in a)b[c]=a[c];return b}var $a=["constructor","hasOwnProperty","isPrototypeOf","propertyIsEnumerable","toLocaleString","toString","valueOf"];
function ab(a){for(var b,c,d=1;d<arguments.length;d++){c=arguments[d];for(b in c)a[b]=c[b];for(var f=0;f<$a.length;f++){b=$a[f];if(Object.prototype.hasOwnProperty.call(c,b))a[b]=c[b]}}}function bb(){var a=arguments.length;if(a==1&&x(arguments[0]))return bb.apply(null,arguments[0]);if(a%2)throw Error("Uneven number of arguments");for(var b={},c=0;c<a;c+=2)b[arguments[c]]=arguments[c+1];return b}var cb,db,eb,fb,gb,hb,ib;function jb(){return t.navigator?t.navigator.userAgent:null}
function lb(){return t.navigator}gb=fb=eb=db=cb=false;var mb;if(mb=jb()){var nb=lb();cb=mb.indexOf("Opera")==0;db=!cb&&mb.indexOf("MSIE")!=-1;fb=(eb=!cb&&mb.indexOf("WebKit")!=-1)&&mb.indexOf("Mobile")!=-1;gb=!cb&&!eb&&nb.product=="Gecko"}var ob=cb,D=db,E=gb,F=eb,pb=fb,qb,rb=lb();qb=rb&&rb.platform||"";hb=qb.indexOf("Mac")!=-1;ib=qb.indexOf("Win")!=-1;var sb=!!lb()&&(lb().appVersion||"").indexOf("X11")!=-1,tb,ub="",vb;
if(ob&&t.opera){var wb=t.opera.version;ub=typeof wb=="function"?wb():wb}else{if(E)vb=/rv\:([^\);]+)(\)|;)/;else if(D)vb=/MSIE\s+([^\);]+)(\)|;)/;else if(F)vb=/WebKit\/(\S+)/;if(vb){var xb=vb.exec(jb());ub=xb?xb[1]:""}}tb=ub;var yb={};function G(a){return yb[a]||(yb[a]=za(tb,a)>=0)}function H(a){return a?new zb(I(a)):Pa||(Pa=new zb)}
function Ab(a,b,c,d){a=d||a;b=b&&b!="*"?b.toUpperCase():"";if(a.querySelectorAll&&a.querySelector&&(!F||Bb(document)||G("528"))&&(b||c))return a.querySelectorAll(b+(c?"."+c:""));if(c&&a.getElementsByClassName){a=a.getElementsByClassName(c);if(b){d={};for(var f=0,g=0,h;h=a[g];g++)if(b==h.nodeName)d[f++]=h;d.length=f;return d}else return a}a=a.getElementsByTagName(b||"*");if(c){d={};for(g=f=0;h=a[g];g++){b=h.className;if(typeof b.split=="function"&&Ia(b.split(/\s+/),c))d[f++]=h}d.length=f;return d}else return a}
function Cb(a,b){Va(b,function(c,d){if(d=="style")a.style.cssText=c;else if(d=="class")a.className=c;else if(d=="for")a.htmlFor=c;else if(d in Db)a.setAttribute(Db[d],c);else a[d]=c})}var Db={cellpadding:"cellPadding",cellspacing:"cellSpacing",colspan:"colSpan",rowspan:"rowSpan",valign:"vAlign",height:"height",width:"width",usemap:"useMap",frameborder:"frameBorder",type:"type"};
function Eb(a){var b=a.document;if(F&&!G("500")&&!pb){if(typeof a.innerHeight=="undefined")a=window;b=a.innerHeight;var c=a.document.documentElement.scrollHeight;if(a==a.top)if(c<b)b-=15;return new C(a.innerWidth,b)}a=Bb(b);if(ob&&!G("9.50"))a=false;a=a?b.documentElement:b.body;return new C(a.clientWidth,a.clientHeight)}function Fb(a,b,c,d){function f(h){if(h)b.appendChild(y(h)?a.createTextNode(h):h)}for(d=d;d<c.length;d++){var g=c[d];ea(g)&&!(ia(g)&&g.nodeType>0)?Fa(Gb(g)?La(g):g,f):f(g)}}
function Bb(a){return a.compatMode=="CSS1Compat"}function Hb(a){for(var b;b=a.firstChild;)a.removeChild(b)}function Jb(a){return a&&a.parentNode?a.parentNode.removeChild(a):null}function Kb(a){for(a=a.firstChild;a&&a.nodeType!=1;)a=a.nextSibling;return a}function Lb(a,b){if(a.contains&&b.nodeType==1)return a==b||a.contains(b);if(typeof a.compareDocumentPosition!="undefined")return a==b||Boolean(a.compareDocumentPosition(b)&16);for(;b&&a!=b;)b=b.parentNode;return b==a}
function I(a){return a.nodeType==9?a:a.ownerDocument||a.document}function Mb(a,b){if("textContent"in a)a.textContent=b;else if(a.firstChild&&a.firstChild.nodeType==3){for(;a.lastChild!=a.firstChild;)a.removeChild(a.lastChild);a.firstChild.data=b}else{Hb(a);a.appendChild(I(a).createTextNode(b))}}var Nb={SCRIPT:1,STYLE:1,HEAD:1,IFRAME:1,OBJECT:1},Ob={IMG:" ",BR:"\n"};function Pb(a){var b=a.getAttributeNode("tabindex");if(b&&b.specified){a=a.tabIndex;return ga(a)&&a>=0}return false}
function Qb(a){if(D&&"innerText"in a)a=a.innerText.replace(/(\r\n|\r|\n)/g,"\n");else{var b=[];Rb(a,b,true);a=b.join("")}a=a.replace(/\xAD/g,"");a=a.replace(/ +/g," ");if(a!=" ")a=a.replace(/^\s*/,"");return a}function Rb(a,b,c){if(!(a.nodeName in Nb))if(a.nodeType==3)c?b.push(String(a.nodeValue).replace(/(\r\n|\r|\n)/g,"")):b.push(a.nodeValue);else if(a.nodeName in Ob)b.push(Ob[a.nodeName]);else for(a=a.firstChild;a;){Rb(a,b,c);a=a.nextSibling}}
function Gb(a){if(a&&typeof a.length=="number")if(ia(a))return typeof a.item=="function"||typeof a.item=="string";else if(ha(a))return typeof a.item=="function";return false}function zb(a){this.l=a||t.document||document}s=zb.prototype;s.w=H;function Sb(a){return a.l}s.a=function(a){return y(a)?this.l.getElementById(a):a};s.ab=zb.prototype.a;
s.e=function(){var a=this.l,b=arguments,c=b[0],d=b[1];if(D&&d&&(d.name||d.type)){c=["<",c];d.name&&c.push(' name="',ta(d.name),'"');if(d.type){c.push(' type="',ta(d.type),'"');var f={};ab(f,d);d=f;delete d.type}c.push(">");c=c.join("")}c=a.createElement(c);if(d)if(y(d))c.className=d;else x(d)?Ra.apply(null,[c].concat(d)):Cb(c,d);b.length>2&&Fb(a,c,b,2);return c};s.createElement=function(a){return this.l.createElement(a)};s.createTextNode=function(a){return this.l.createTextNode(a)};
function Tb(a){a=!F&&Bb(a.l)?a.l.documentElement:a.l.body;return new B(a.scrollLeft,a.scrollTop)}s.appendChild=function(a,b){a.appendChild(b)};s.Gd=Kb;s.contains=Lb;var Ub=[];function Vb(){}Vb.prototype.Ac=false;Vb.prototype.C=function(){if(!this.Ac){this.Ac=true;this.f()}};Vb.prototype.f=aa();var Wb;function J(a,b){this.type=a;this.currentTarget=this.target=b}z(J,Vb);s=J.prototype;s.f=function(){delete this.type;delete this.target;delete this.currentTarget};s.Xa=false;s.Ob=true;
s.stopPropagation=function(){this.Xa=true};s.preventDefault=function(){this.Ob=false};function Xb(a){a.preventDefault()}function K(a,b){a&&this.kb(a,b)}z(K,J);var Yb=[1,4,2];s=K.prototype;s.target=null;s.relatedTarget=null;s.offsetX=0;s.offsetY=0;s.clientX=0;s.clientY=0;s.screenX=0;s.screenY=0;s.button=0;s.keyCode=0;s.charCode=0;s.ctrlKey=false;s.altKey=false;s.shiftKey=false;s.metaKey=false;s.ef=false;s.ua=null;
s.kb=function(a,b){var c=this.type=a.type;this.target=a.target||a.srcElement;this.currentTarget=b;var d=a.relatedTarget;if(d){if(E)try{d=d.nodeName&&d}catch(f){d=null}}else if(c=="mouseover")d=a.fromElement;else if(c=="mouseout")d=a.toElement;this.relatedTarget=d;this.offsetX=a.offsetX!==undefined?a.offsetX:a.layerX;this.offsetY=a.offsetY!==undefined?a.offsetY:a.layerY;this.clientX=a.clientX!==undefined?a.clientX:a.pageX;this.clientY=a.clientY!==undefined?a.clientY:a.pageY;this.screenX=a.screenX||
0;this.screenY=a.screenY||0;this.button=a.button;this.keyCode=a.keyCode||0;this.charCode=a.charCode||(c=="keypress"?a.keyCode:0);this.ctrlKey=a.ctrlKey;this.altKey=a.altKey;this.shiftKey=a.shiftKey;this.metaKey=a.metaKey;this.ef=hb?a.metaKey:a.ctrlKey;this.ua=a;delete this.Ob;delete this.Xa};function Zb(a,b){return D?a.type=="click"?b==0:!!(a.ua.button&Yb[b]):a.ua.button==b}
s.stopPropagation=function(){K.b.stopPropagation.call(this);if(this.ua.stopPropagation)this.ua.stopPropagation();else this.ua.cancelBubble=true};var $b=D&&!G("8");K.prototype.preventDefault=function(){K.b.preventDefault.call(this);var a=this.ua;if(a.preventDefault)a.preventDefault();else{a.returnValue=false;if($b)try{if(a.ctrlKey||a.keyCode>=112&&a.keyCode<=123)a.keyCode=-1}catch(b){}}};K.prototype.f=function(){K.b.f.call(this);this.relatedTarget=this.currentTarget=this.target=this.ua=null};
function ac(){}var bc=0;s=ac.prototype;s.key=0;s.ob=false;s.rd=false;s.kb=function(a,b,c,d,f,g){if(ha(a))this.Td=true;else if(a&&a.handleEvent&&ha(a.handleEvent))this.Td=false;else throw Error("Invalid listener argument");this.mb=a;this.be=b;this.src=c;this.type=d;this.capture=!!f;this.dc=g;this.rd=false;this.key=++bc;this.ob=false};s.handleEvent=function(a){if(this.Td)return this.mb.call(this.dc||this.src,a);return this.mb.handleEvent.call(this.mb,a)};
function L(a,b){this.Yd=b;this.Qa=[];if(a>this.Yd)throw Error("[goog.structs.SimplePool] Initial cannot be greater than max");for(var c=0;c<a;c++)this.Qa.push(this.za?this.za():{})}z(L,Vb);L.prototype.za=null;L.prototype.yd=null;function cc(a){if(a.Qa.length)return a.Qa.pop();return a.za?a.za():{}}function dc(a,b){a.Qa.length<a.Yd?a.Qa.push(b):ec(a,b)}function ec(a,b){if(a.yd)a.yd(b);else if(ia(b))if(ha(b.C))b.C();else for(var c in b)delete b[c]}
L.prototype.f=function(){L.b.f.call(this);for(var a=this.Qa;a.length;)ec(this,a.pop());delete this.Qa};var fc;var gc=(fc="ScriptEngine"in t&&t.ScriptEngine()=="JScript")?t.ScriptEngineMajorVersion()+"."+t.ScriptEngineMinorVersion()+"."+t.ScriptEngineBuildVersion():"0",hc,ic,jc,kc,lc,mc,nc,oc,pc,qc,rc;
(function(){function a(){return{ra:0,oa:0}}function b(){return[]}function c(){function n(q){return h.call(n.src,n.key,q)}return n}function d(){return new ac}function f(){return new K}var g=fc&&!(za(gc,"5.7")>=0),h;mc=function(n){h=n};if(g){hc=function(){return cc(j)};ic=function(n){dc(j,n)};jc=function(){return cc(i)};kc=function(n){dc(i,n)};lc=function(){return cc(k)};nc=function(){dc(k,c())};oc=function(){return cc(m)};pc=function(n){dc(m,n)};qc=function(){return cc(l)};rc=function(n){dc(l,n)};
var j=new L(0,600);j.za=a;var i=new L(0,600);i.za=b;var k=new L(0,600);k.za=c;var m=new L(0,600);m.za=d;var l=new L(0,600);l.za=f}else{hc=a;ic=u;jc=b;kc=u;lc=c;nc=u;oc=d;pc=u;qc=f;rc=u}})();var sc={},M={},tc={},uc={};
function N(a,b,c,d,f){if(b)if(x(b)){for(var g=0;g<b.length;g++)N(a,b[g],c,d,f);return null}else{d=!!d;var h=M;b in h||(h[b]=hc());h=h[b];if(!(d in h)){h[d]=hc();h.ra++}h=h[d];var j=ja(a),i;h.oa++;if(h[j]){i=h[j];for(g=0;g<i.length;g++){h=i[g];if(h.mb==c&&h.dc==f){if(h.ob)break;return i[g].key}}}else{i=h[j]=jc();h.ra++}g=lc();g.src=a;h=oc();h.kb(c,g,a,b,d,f);c=h.key;g.key=c;i.push(h);sc[c]=h;tc[j]||(tc[j]=jc());tc[j].push(h);if(a.addEventListener){if(a==t||!a.wd)a.addEventListener(b,g,d)}else a.attachEvent(vc(b),
g);return c}else throw Error("Invalid event type");}function wc(a,b,c,d,f){if(x(b)){for(var g=0;g<b.length;g++)wc(a,b[g],c,d,f);return null}d=!!d;a=xc(a,b,d);if(!a)return false;for(g=0;g<a.length;g++)if(a[g].mb==c&&a[g].capture==d&&a[g].dc==f)return O(a[g].key);return false}
function O(a){if(!sc[a])return false;var b=sc[a];if(b.ob)return false;var c=b.src,d=b.type,f=b.be,g=b.capture;if(c.removeEventListener){if(c==t||!c.wd)c.removeEventListener(d,f,g)}else c.detachEvent&&c.detachEvent(vc(d),f);c=ja(c);f=M[d][g][c];if(tc[c]){var h=tc[c];Ja(h,b);h.length==0&&delete tc[c]}b.ob=true;f.ae=true;yc(d,g,c,f);delete sc[a];return true}
function yc(a,b,c,d){if(!d.ic)if(d.ae){for(var f=0,g=0;f<d.length;f++)if(d[f].ob){var h=d[f].be;h.src=null;nc(h);pc(d[f])}else{if(f!=g)d[g]=d[f];g++}d.length=g;d.ae=false;if(g==0){kc(d);delete M[a][b][c];M[a][b].ra--;if(M[a][b].ra==0){ic(M[a][b]);delete M[a][b];M[a].ra--}if(M[a].ra==0){ic(M[a]);delete M[a]}}}}
function zc(a,b,c){var d=0,f=a==null,g=b==null,h=c==null;c=!!c;if(f)Va(tc,function(i){for(var k=i.length-1;k>=0;k--){var m=i[k];if((g||b==m.type)&&(h||c==m.capture)){O(m.key);d++}}});else{a=ja(a);if(tc[a]){a=tc[a];for(f=a.length-1;f>=0;f--){var j=a[f];if((g||b==j.type)&&(h||c==j.capture)){O(j.key);d++}}}}return d}function xc(a,b,c){var d=M;if(b in d){d=d[b];if(c in d){d=d[c];a=ja(a);if(d[a])return d[a]}}return null}function vc(a){if(a in uc)return uc[a];return uc[a]="on"+a}
function Ac(a,b,c,d,f){var g=1;b=ja(b);if(a[b]){a.oa--;a=a[b];if(a.ic)a.ic++;else a.ic=1;try{for(var h=a.length,j=0;j<h;j++){var i=a[j];if(i&&!i.ob)g&=Bc(i,f)!==false}}finally{a.ic--;yc(c,d,b,a)}}return Boolean(g)}function Bc(a,b){var c=a.handleEvent(b);a.rd&&O(a.key);return c}
function Cc(a,b){if(!sc[a])return true;var c=sc[a],d=c.type,f=M;if(!(d in f))return true;f=f[d];var g,h;if(Wb===undefined)Wb=D&&!t.addEventListener;if(Wb){g=b||ca("window.event");var j=true in f,i=false in f;if(j){if(g.keyCode<0||g.returnValue!=undefined)return true;a:{var k=false;if(g.keyCode==0)try{g.keyCode=-1;break a}catch(m){k=true}if(k||g.returnValue==undefined)g.returnValue=true}}k=qc();k.kb(g,this);g=true;try{if(j){for(var l=jc(),n=k.currentTarget;n;n=n.parentNode)l.push(n);h=f[true];h.oa=
h.ra;for(var q=l.length-1;!k.Xa&&q>=0&&h.oa;q--){k.currentTarget=l[q];g&=Ac(h,l[q],d,true,k)}if(i){h=f[false];h.oa=h.ra;for(q=0;!k.Xa&&q<l.length&&h.oa;q++){k.currentTarget=l[q];g&=Ac(h,l[q],d,false,k)}}}else g=Bc(c,k)}finally{if(l){l.length=0;kc(l)}k.C();rc(k)}return g}d=new K(b,this);try{g=Bc(c,d)}finally{d.C()}return g}mc(Cc);Ub[Ub.length]=function(a){Cc=a.Ef(Cc);mc(Cc)};function P(){}z(P,Vb);s=P.prototype;s.wd=true;s.mc=null;s.cd=ba("mc");s.addEventListener=function(a,b,c,d){N(this,a,b,c,d)};
s.removeEventListener=function(a,b,c,d){wc(this,a,b,c,d)};
s.dispatchEvent=function(a){a=a;if(y(a))a=new J(a,this);else if(a instanceof J)a.target=a.target||this;else{var b=a;a=new J(a.type,this);ab(a,b)}b=1;var c,d=a.type,f=M;if(d in f){f=f[d];d=true in f;var g;if(d){c=[];for(g=this;g;g=g.mc)c.push(g);g=f[true];g.oa=g.ra;for(var h=c.length-1;!a.Xa&&h>=0&&g.oa;h--){a.currentTarget=c[h];b&=Ac(g,c[h],a.type,true,a)&&a.Ob!=false}}if(false in f){g=f[false];g.oa=g.ra;if(d)for(h=0;!a.Xa&&h<c.length&&g.oa;h++){a.currentTarget=c[h];b&=Ac(g,c[h],a.type,false,a)&&
a.Ob!=false}else for(c=this;!a.Xa&&c&&g.oa;c=c.mc){a.currentTarget=c;b&=Ac(g,c,a.type,false,a)&&a.Ob!=false}}a=Boolean(b)}else a=true;return a};s.f=function(){P.b.f.call(this);zc(this);this.mc=null};function Dc(a){this.$a=a||window;this.hc=N(this.$a,"resize",this.Re,false,this);this.sb=Eb(this.$a||window);if(F&&ib||ob&&this.$a.self!=this.$a.top)this.vc=window.setInterval(ma(this.ud,this),Ec)}z(Dc,P);var Ec=500;s=Dc.prototype;s.hc=null;s.$a=null;s.sb=null;s.vc=null;
s.Jd=function(){return this.sb?this.sb.cb():null};s.f=function(){Dc.b.f.call(this);if(this.hc){O(this.hc);this.hc=null}if(this.vc){window.clearInterval(this.vc);this.vc=null}this.sb=this.$a=null};s.Re=function(){this.ud()};s.ud=function(){var a=Eb(this.$a||window);if(!Ua(a,this.sb)){this.sb=a;this.dispatchEvent("resize")}};function Fc(a,b,c,d){this.top=a;this.right=b;this.bottom=c;this.left=d}Fc.prototype.cb=function(){return new Fc(this.top,this.right,this.bottom,this.left)};
Fc.prototype.toString=function(){return"("+this.top+"t, "+this.right+"r, "+this.bottom+"b, "+this.left+"l)"};Fc.prototype.contains=function(a){return!this||!a?false:a instanceof Fc?a.left>=this.left&&a.right<=this.right&&a.top>=this.top&&a.bottom<=this.bottom:a.x>=this.left&&a.x<=this.right&&a.y>=this.top&&a.y<=this.bottom};function Gc(a,b,c,d){this.left=a;this.top=b;this.width=c;this.height=d}Gc.prototype.cb=function(){return new Gc(this.left,this.top,this.width,this.height)};
Gc.prototype.toString=function(){return"("+this.left+", "+this.top+" - "+this.width+"w x "+this.height+"h)"};Gc.prototype.contains=function(a){return a instanceof Gc?this.left<=a.left&&this.left+this.width>=a.left+a.width&&this.top<=a.top&&this.top+this.height>=a.top+a.height:a.x>=this.left&&a.x<=this.left+this.width&&a.y>=this.top&&a.y<=this.top+this.height};Gc.prototype.Jd=function(){return new C(this.width,this.height)};
function Hc(a,b){var c=I(a);if(c.defaultView&&c.defaultView.getComputedStyle)if(c=c.defaultView.getComputedStyle(a,""))return c[b];return null}function Ic(a,b){return Hc(a,b)||(a.currentStyle?a.currentStyle[b]:null)||a.style[b]}function Jc(a,b,c){var d,f=E&&(hb||sb)&&G("1.9");if(b instanceof B){d=b.x;b=b.y}else{d=b;b=c}Kc("left",f,a,d);Kc("top",f,a,b)}
function Lc(a){var b=a.getBoundingClientRect();if(D){a=a.ownerDocument;b.left-=a.documentElement.clientLeft+a.body.clientLeft;b.top-=a.documentElement.clientTop+a.body.clientTop}return b}
function Mc(a){if(D)return a.offsetParent;var b=I(a),c=Ic(a,"position"),d=c=="fixed"||c=="absolute";for(a=a.parentNode;a&&a!=b;a=a.parentNode){c=Ic(a,"position");d=d&&c=="static"&&a!=b.documentElement&&a!=b.body;if(!d&&(a.scrollWidth>a.clientWidth||a.scrollHeight>a.clientHeight||c=="fixed"||c=="absolute"))return a}return null}
function Nc(a){var b=new Fc(0,Infinity,Infinity,0),c=H(a),d=c.l.body,f=!F&&Bb(c.l)?c.l.documentElement:c.l.body,g;for(a=a;a=Mc(a);)if((!D||a.clientWidth!=0)&&(!F||a.clientHeight!=0||a!=d)&&(a.scrollWidth!=a.clientWidth||a.scrollHeight!=a.clientHeight)&&Ic(a,"overflow")!="visible"){var h=Oc(a),j;j=a;if(E&&!G("1.9")){var i=parseFloat(Hc(j,"borderLeftWidth"));if(Pc(j)){var k=j.offsetWidth-j.clientWidth-i-parseFloat(Hc(j,"borderRightWidth"));i+=k}j=new B(i,parseFloat(Hc(j,"borderTopWidth")))}else j=new B(j.clientLeft,
j.clientTop);h.x+=j.x;h.y+=j.y;b.top=Math.max(b.top,h.y);b.right=Math.min(b.right,h.x+a.clientWidth);b.bottom=Math.min(b.bottom,h.y+a.clientHeight);b.left=Math.max(b.left,h.x);g=g||a!=f}d=f.scrollLeft;f=f.scrollTop;if(F){b.left+=d;b.top+=f}else{b.left=Math.max(b.left,d);b.top=Math.max(b.top,f)}if(!g||F){b.right+=d;b.bottom+=f}c=Eb(c.l.parentWindow||c.l.defaultView||window);b.right=Math.min(b.right,d+c.width);b.bottom=Math.min(b.bottom,f+c.height);return b.top>=0&&b.left>=0&&b.bottom>b.top&&b.right>
b.left?b:null}
function Oc(a){var b,c=I(a),d=Ic(a,"position"),f=E&&c.getBoxObjectFor&&!a.getBoundingClientRect&&d=="absolute"&&(b=c.getBoxObjectFor(a))&&(b.screenX<0||b.screenY<0),g=new B(0,0),h;b=c?c.nodeType==9?c:I(c):document;if(h=D){h=H(b);h=!Bb(h.l)}h=h?b.body:b.documentElement;if(a==h)return g;if(a.getBoundingClientRect){b=Lc(a);a=Tb(H(c));g.x=b.left+a.x;g.y=b.top+a.y}else if(c.getBoxObjectFor&&!f){b=c.getBoxObjectFor(a);a=c.getBoxObjectFor(h);g.x=b.screenX-a.screenX;g.y=b.screenY-a.screenY}else{f=a;do{g.x+=
f.offsetLeft;g.y+=f.offsetTop;if(f!=a){g.x+=f.clientLeft||0;g.y+=f.clientTop||0}if(F&&Ic(f,"position")=="fixed"){g.x+=c.body.scrollLeft;g.y+=c.body.scrollTop;break}f=f.offsetParent}while(f&&f!=a);if(ob||F&&d=="absolute")g.y-=c.body.offsetTop;for(f=a;(f=Mc(f))&&f!=c.body&&f!=h;){g.x-=f.scrollLeft;if(!ob||f.tagName!="TR")g.y-=f.scrollTop}}return g}
function Qc(a){var b=new B;if(a.nodeType==1)if(a.getBoundingClientRect){var c=Lc(a);b.x=c.left;b.y=c.top}else{c=Tb(H(a));a=Oc(a);b.x=a.x-c.x;b.y=a.y-c.y}else{b.x=a.clientX;b.y=a.clientY}return b}function Rc(a,b,c){if(b instanceof C){c=b.height;b=b.width}else{if(c==undefined)throw Error("missing height argument");c=c}Sc(a,b);Tc(a,c)}function Kc(a,b,c,d){if(typeof d=="number")d=(b?Math.round(d):d)+"px";c.style[a]=d}var Tc=na(Kc,"height",true),Sc=na(Kc,"width",true);
function Uc(a){var b=ob&&!G("10");if(Ic(a,"display")!="none")return b?new C(a.offsetWidth||a.clientWidth,a.offsetHeight||a.clientHeight):new C(a.offsetWidth,a.offsetHeight);var c=a.style,d=c.display,f=c.visibility,g=c.position;c.visibility="hidden";c.position="absolute";c.display="inline";if(b){b=a.offsetWidth||a.clientWidth;a=a.offsetHeight||a.clientHeight}else{b=a.offsetWidth;a=a.offsetHeight}c.display=d;c.position=g;c.visibility=f;return new C(b,a)}
function Vc(a){var b=Oc(a);a=Uc(a);return new Gc(b.x,b.y,a.width,a.height)}function Wc(a,b){a.style.display=b?"":"none"}function Pc(a){return"rtl"==Ic(a,"direction")}var Xc=E?"MozUserSelect":F?"WebkitUserSelect":null;function Yc(a,b,c){c=!c?a.getElementsByTagName("*"):null;if(Xc){b=b?"none":"";a.style[Xc]=b;if(c){a=0;for(var d;d=c[a];a++)d.style[Xc]=b}}else if(D||ob){b=b?"on":"";a.setAttribute("unselectable",b);if(c)for(a=0;d=c[a];a++)d.setAttribute("unselectable",b)}}function Zc(){}
function $c(a,b){var c=[];ad(a,b,c);return c.join("")}
function ad(a,b,c){switch(typeof b){case "string":bd(a,b,c);break;case "number":c.push(isFinite(b)&&!isNaN(b)?b:"null");break;case "boolean":c.push(b);break;case "undefined":c.push("null");break;case "object":if(b==null){c.push("null");break}if(x(b)){var d=b.length;c.push("[");for(var f="",g=0;g<d;g++){c.push(f);ad(a,b[g],c);f=","}c.push("]");break}c.push("{");d="";for(f in b)if(b.hasOwnProperty(f)){g=b[f];if(typeof g!="function"){c.push(d);bd(a,f,c);c.push(":");ad(a,g,c);d=","}}c.push("}");break;
case "function":break;default:throw Error("Unknown type: "+typeof b);}}var cd={'"':'\\"',"\\":"\\\\","/":"\\/","\u0008":"\\b","\u000c":"\\f","\n":"\\n","\r":"\\r","\t":"\\t","\u000b":"\\u000b"},dd=/\uffff/.test("\uffff")?/[\\\"\x00-\x1f\x7f-\uffff]/g:/[\\\"\x00-\x1f\x7f-\xff]/g;function bd(a,b,c){c.push('"',b.replace(dd,function(d){if(d in cd)return cd[d];var f=d.charCodeAt(0),g="\\u";if(f<16)g+="000";else if(f<256)g+="00";else if(f<4096)g+="0";return cd[d]=g+f.toString(16)}),'"')}
function ed(){this.pa=[];this.Oa={}}z(ed,Vb);s=ed.prototype;s.ma=1;s.nc=0;function Q(a,b,c,d){var f=a.Oa[b];f||(f=a.Oa[b]=[]);var g=a.ma;a.pa[g]=b;a.pa[g+1]=c;a.pa[g+2]=d;a.ma=g+3;f.push(g);return g}s.le=function(a){if(this.nc!=0){if(!this.Mb)this.Mb=[];this.Mb.push(a);return false}var b=this.pa[a];if(b){var c=this.Oa[b];c&&Ja(c,a);delete this.pa[a];delete this.pa[a+1];delete this.pa[a+2]}return!!b};
s.G=function(a){var b=this.Oa[a];if(b){this.nc++;for(var c=Oa(arguments,1),d=0,f=b.length;d<f;d++){var g=b[d];this.pa[g+1].apply(this.pa[g+2],c)}this.nc--;if(this.Mb&&this.nc==0)for(;b=this.Mb.pop();)this.le(b);return d!=0}return false};s.clear=function(a){if(a){var b=this.Oa[a];if(b){Fa(b,this.le,this);delete this.Oa[a]}}else{this.pa.length=0;this.Oa={}}};s.f=function(){ed.b.f.call(this);delete this.pa;delete this.Oa;delete this.Mb};function fd(a,b){if(E){a.setAttribute("role",b);a.Bf=b}}
function R(a,b,c){E&&a.setAttribute("aria-"+b,c)}function gd(a,b,c,d,f){if(!D&&!(F&&G("525")))return true;if(hb&&f)return hd(a);if(f&&!d)return false;if(!c&&(b==17||b==18))return false;if(D&&d&&b==a)return false;switch(a){case 13:return true;case 27:return!F}return hd(a)}
function hd(a){if(a>=48&&a<=57)return true;if(a>=96&&a<=106)return true;if(a>=65&&a<=90)return true;if(F&&a==0)return true;switch(a){case 32:case 63:case 107:case 109:case 110:case 111:case 186:case 189:case 187:case 188:case 190:case 191:case 192:case 222:case 219:case 220:case 221:return true;default:return false}}function id(a){a&&jd(this,a)}z(id,P);s=id.prototype;s.m=null;s.ec=null;s.Qc=null;s.fc=null;s.Hb=-1;s.Va=-1;
var kd={"3":13,"12":144,"63232":38,"63233":40,"63234":37,"63235":39,"63236":112,"63237":113,"63238":114,"63239":115,"63240":116,"63241":117,"63242":118,"63243":119,"63244":120,"63245":121,"63246":122,"63247":123,"63248":44,"63272":46,"63273":36,"63275":35,"63276":33,"63277":34,"63289":144,"63302":45},ld={Up:38,Down:40,Left:37,Right:39,Enter:13,F1:112,F2:113,F3:114,F4:115,F5:116,F6:117,F7:118,F8:119,F9:120,F10:121,F11:122,F12:123,"U+007F":46,Home:36,End:35,PageUp:33,PageDown:34,Insert:45},md={61:187,
59:186},nd=D||F&&G("525");s=id.prototype;s.Hc=function(a){if(nd&&!gd(a.keyCode,this.Hb,a.shiftKey,a.ctrlKey,a.altKey))this.handleEvent(a);else this.Va=E&&a.keyCode in md?md[a.keyCode]:a.keyCode};s.Le=function(){this.Va=this.Hb=-1};
s.handleEvent=function(a){var b=a.ua,c,d;if(D&&a.type=="keypress"){c=this.Va;d=c!=13&&c!=27?b.keyCode:0}else if(F&&a.type=="keypress"){c=this.Va;d=b.charCode>=0&&b.charCode<63232&&hd(c)?b.charCode:0}else if(ob){c=this.Va;d=hd(c)?b.keyCode:0}else{c=b.keyCode||this.Va;d=b.charCode||0;if(hb&&d==63&&!c)c=191}var f=c,g=b.keyIdentifier;if(c)if(c>=63232&&c in kd)f=kd[c];else{if(c==25&&a.shiftKey)f=9}else if(g&&g in ld)f=ld[g];a=f==this.Hb;this.Hb=f;b=new od(f,d,a,b);try{this.dispatchEvent(b)}finally{b.C()}};
s.a=e("m");function jd(a,b){a.fc&&a.detach();a.m=b;a.ec=N(a.m,"keypress",a);a.Qc=N(a.m,"keydown",a.Hc,false,a);a.fc=N(a.m,"keyup",a.Le,false,a)}s.detach=function(){if(this.ec){O(this.ec);O(this.Qc);O(this.fc);this.fc=this.Qc=this.ec=null}this.m=null;this.Va=this.Hb=-1};s.f=function(){id.b.f.call(this);this.detach()};function od(a,b,c,d){d&&this.kb(d,void 0);this.type="key";this.keyCode=a;this.charCode=b;this.repeat=c}z(od,K);function pd(a){this.Pd=a}z(pd,Vb);var qd=new L(0,100);
pd.prototype.h=function(a,b,c,d,f){if(x(b))for(var g=0;g<b.length;g++)this.h(a,b[g],c,d,f);else{a=N(a,b,c||this,d||false,f||this.Pd||this);if(this.ea)this.ea[a]=true;else if(this.ma){this.ea=cc(qd);this.ea[this.ma]=true;this.ma=null;this.ea[a]=true}else this.ma=a}return this};
pd.prototype.ca=function(a,b,c,d,f){if(this.ma||this.ea)if(x(b))for(var g=0;g<b.length;g++)this.ca(a,b[g],c,d,f);else{a:{c=c||this;f=f||this.Pd||this;d=!!(d||false);if(a=xc(a,b,d))for(b=0;b<a.length;b++)if(a[b].mb==c&&a[b].capture==d&&a[b].dc==f){a=a[b];break a}a=null}if(a){a=a.key;O(a);if(this.ea)Xa(this.ea,a);else if(this.ma==a)this.ma=null}}return this};function rd(a){if(a.ea){for(var b in a.ea){O(b);delete a.ea[b]}dc(qd,a.ea);a.ea=null}else a.ma&&O(a.ma)}
pd.prototype.f=function(){pd.b.f.call(this);rd(this)};pd.prototype.handleEvent=function(){throw Error("EventHandler.handleEvent not implemented");};function sd(){}w(sd);sd.prototype.$e=0;sd.S();function S(a){this.Fa=a||H();this.Pb=td}z(S,P);S.prototype.Te=sd.S();var td=null;
function ud(a,b){switch(a){case 1:return b?"disable":"enable";case 2:return b?"highlight":"unhighlight";case 4:return b?"activate":"deactivate";case 8:return b?"select":"unselect";case 16:return b?"check":"uncheck";case 32:return b?"focus":"blur";case 64:return b?"open":"close";default:}throw Error("Invalid component state");}s=S.prototype;s.jb=null;s.Fa=null;s.p=false;s.m=null;s.Pb=null;s.Vc=null;s.r=null;s.J=null;s.ja=null;s.oe=false;
function vd(a){return a.jb||(a.jb=":"+(a.Te.$e++).toString(36))}function wd(a,b){if(a.r&&a.r.ja){Xa(a.r.ja,a.jb);Ya(a.r.ja,b,a)}a.jb=b}s.a=e("m");s.U=function(){return this.hb||(this.hb=new pd(this))};function xd(a,b){if(a==b)throw Error("Unable to set parent component");if(b&&a.r&&a.jb&&yd(a.r,a.jb)&&a.r!=b)throw Error("Unable to set parent component");a.r=b;S.b.cd.call(a,b)}s.cd=function(a){if(this.r&&this.r!=a)throw Error("Method not supported");S.b.cd.call(this,a)};s.w=e("Fa");
s.e=function(){this.m=this.Fa.createElement("div")};s.pb=function(a){zd(this,a)};function zd(a,b,c){if(a.p)throw Error("Component already rendered");a.m||a.e();b?b.insertBefore(a.m,c||null):a.Fa.l.body.appendChild(a.m);if(!a.r||a.r.p)a.K()}s.B=function(a){if(this.p)throw Error("Component already rendered");else if(a&&this.ia(a)){this.oe=true;if(!this.Fa||this.Fa.l!=I(a))this.Fa=H(a);this.sa(a);this.K()}else throw Error("Invalid element to decorate");};s.ia=o(true);s.sa=ba("m");
s.K=function(){this.p=true;Ad(this,function(a){!a.p&&a.a()&&a.K()})};s.va=function(){Ad(this,function(a){a.p&&a.va()});this.hb&&rd(this.hb);this.p=false};s.f=function(){S.b.f.call(this);this.p&&this.va();if(this.hb){this.hb.C();delete this.hb}Ad(this,function(a){a.C()});!this.oe&&this.m&&Jb(this.m);this.r=this.Vc=this.m=this.ja=this.J=null};s.da=function(a,b){this.wb(a,Bd(this),b)};
s.wb=function(a,b,c){if(a.p&&(c||!this.p))throw Error("Component already rendered");if(b<0||b>Bd(this))throw Error("Child component index out of bounds");if(!this.ja||!this.J){this.ja={};this.J=[]}if(a.r==this){this.ja[vd(a)]=a;Ja(this.J,a)}else Ya(this.ja,vd(a),a);xd(a,this);Na(this.J,b,0,a);if(a.p&&this.p&&a.r==this){c=this.L();c.insertBefore(a.a(),c.childNodes[b]||null)}else if(c){this.m||this.e();b=T(this,b+1);zd(a,this.L(),b?b.m:null)}else this.p&&!a.p&&a.m&&a.K()};s.L=e("m");
function Cd(a){if(a.Pb==null)a.Pb=Pc(a.p?a.m:a.Fa.l.body);return a.Pb}s.rb=function(a){if(this.p)throw Error("Component already rendered");this.Pb=a};function Bd(a){return a.J?a.J.length:0}function yd(a,b){var c;if(a.ja&&b){c=a.ja;c=b in c?c[b]:void 0;c=c||null}else c=null;return c}function T(a,b){return a.J?a.J[b]||null:null}function Ad(a,b,c){a.J&&Fa(a.J,b,c)}function Dd(a,b){return a.J&&b?Ea(a.J,b):-1}
s.removeChild=function(a,b){if(a){var c=y(a)?a:vd(a);a=yd(this,c);if(c&&a){Xa(this.ja,c);Ja(this.J,a);if(b){a.va();a.m&&Jb(a.m)}xd(a,null)}}if(!a)throw Error("Child is not in parent component");return a};function Ed(){}var Hd;w(Ed);s=Ed.prototype;s.wa=aa();s.e=function(a){return a.w().e("div",this.gb(a).join(" "),a.ya)};s.L=function(a){return a};s.yb=function(a,b,c){if(a=a.a?a.a():a)if(D&&!G("7")){var d=Id(this,Qa(a),b);d.push(b);na(c?Ra:Sa,a).apply(null,d)}else c?Ra(a,b):Sa(a,b)};s.ia=o(true);
s.B=function(a,b){b.id&&wd(a,b.id);var c=this.L(b);if(c&&c.firstChild)Jd(a,c.firstChild.nextSibling?La(c.childNodes):c.firstChild);else a.ya=null;var d=0,f=this.g(),g=this.g(),h=false,j=false;c=false;var i=Qa(b);Fa(i,function(l){if(!h&&l==f){h=true;if(g==f)j=true}else if(!j&&l==g)j=true;else d|=this.Ec(l)},this);a.N=d;if(!h){i.push(f);if(g==f)j=true}j||i.push(g);var k=a.la;k&&i.push.apply(i,k);if(D&&!G("7")){var m=Id(this,i);if(m.length>0){i.push.apply(i,m);c=true}}if(!h||!j||k||c)b.className=i.join(" ");
return b};s.lb=function(a){Cd(a)&&this.rb(a.a(),true);a.z()&&this.Ma(a,a.o)};s.Qb=function(a,b){Yc(a,!b,!D&&!ob)};s.rb=function(a,b){this.yb(a,this.g()+"-rtl",b)};s.Ja=function(a){var b;if(a.O&32&&(b=a.D()))return Pb(b);return false};s.Ma=function(a,b){var c;if(a.O&32&&(c=a.D())){if(!b&&U(a,32)){try{c.blur()}catch(d){}U(a,32)&&a.Sa(null)}if(Pb(c)!=b){c=c;if(b)c.tabIndex=0;else c.removeAttribute("tabIndex")}}};s.ga=function(a,b){Wc(a,b)};
s.ba=function(a,b,c){var d=a.a();if(d){var f=this.Ab(b);f&&this.yb(a,f,c);this.vb(d,b,c)}};s.vb=function(a,b,c){if(E){Hd||(Hd=bb(1,"disabled",4,"pressed",8,"selected",16,"checked",64,"expanded"));(b=Hd[b])&&R(a,b,c)}};s.Ya=function(a,b){var c=this.L(a);if(c){Hb(c);if(b)if(y(b))Mb(c,b);else{var d=function(f){if(f){var g=I(c);c.appendChild(y(f)?g.createTextNode(f):f)}};if(x(b))Fa(b,d);else ea(b)&&!("nodeType"in b)?Fa(La(b),d):d(b)}}};s.D=function(a){return a.a()};s.g=o("goog-control");
s.gb=function(a){var b=this.g(),c=[b],d=this.g();d!=b&&c.push(d);b=a.N;for(d=[];b;){var f=b&-b;d.push(this.Ab(f));b&=~f}c.push.apply(c,d);(a=a.la)&&c.push.apply(c,a);D&&!G("7")&&c.push.apply(c,Id(this,c));return c};function Id(a,b,c){var d=[];if(c)b=b.concat([c]);Fa([],function(f){if(Ha(f,na(Ia,b))&&(!c||Ia(f,c)))d.push(f.join("_"))});return d}s.Ab=function(a){this.Xb||Kd(this);return this.Xb[a]};
s.Ec=function(a){if(!this.ke){this.Xb||Kd(this);var b=this.Xb,c={};for(var d in b)c[b[d]]=d;this.ke=c}a=parseInt(this.ke[a],10);return isNaN(a)?0:a};function Kd(a){var b=a.g();a.Xb=bb(1,b+"-disabled",2,b+"-hover",4,b+"-active",8,b+"-selected",16,b+"-checked",32,b+"-focused",64,b+"-open")}function Ld(a,b){if(!a)throw Error("Invalid class name "+a);if(!ha(b))throw Error("Invalid decorator function "+b);Md[a]=b}var Nd={},Md={};
function V(a,b,c){S.call(this,c);if(!(b=b)){b=this.constructor;for(var d;b;){d=ja(b);if(d=Nd[d])break;b=b.b?b.b.constructor:null}b=d?ha(d.S)?d.S():new d:null}this.d=b;this.ya=a}z(V,S);s=V.prototype;s.ya=null;s.N=0;s.O=39;s.pd=255;s.gd=0;s.o=true;s.la=null;s.Jc=true;s.Wb=false;function Od(a,b){a.p&&b!=a.Jc&&Pd(a,b);a.Jc=b}s.D=function(){return this.d.D(this)};s.ac=function(){return this.R||(this.R=new id)};
s.yb=function(a,b){if(b){if(a){if(this.la)Ia(this.la,a)||this.la.push(a);else this.la=[a];this.d.yb(this,a,true)}}else if(a&&this.la){Ja(this.la,a);if(this.la.length==0)this.la=null;this.d.yb(this,a,false)}};s.e=function(){var a=this.d.e(this);this.m=a;if(E){var b=this.d.wa();b&&fd(a,b)}this.Wb||this.d.Qb(a,false);this.o||this.d.ga(a,false)};s.L=function(){return this.d.L(this.a())};s.ia=function(a){return this.d.ia(a)};
s.sa=function(a){this.m=a=this.d.B(this,a);if(E){var b=this.d.wa();b&&fd(a,b)}this.Wb||this.d.Qb(a,false);this.o=a.style.display!="none"};s.K=function(){V.b.K.call(this);this.d.lb(this);if(this.O&-2){this.Jc&&Pd(this,true);if(this.O&32){var a=this.D();if(a){var b=this.ac();jd(b,a);this.U().h(b,"key",this.Ba).h(a,"focus",this.cc).h(a,"blur",this.Sa)}}}};
function Pd(a,b){var c=a.U(),d=a.a();if(b){c.h(d,"mouseover",a.Lc).h(d,"mousedown",a.Ta).h(d,"mouseup",a.Fb).h(d,"mouseout",a.Kc);D&&c.h(d,"dblclick",a.Md)}else{c.ca(d,"mouseover",a.Lc).ca(d,"mousedown",a.Ta).ca(d,"mouseup",a.Fb).ca(d,"mouseout",a.Kc);D&&c.ca(d,"dblclick",a.Md)}}s.va=function(){V.b.va.call(this);this.R&&this.R.detach();this.o&&this.z()&&this.d.Ma(this,false)};s.f=function(){V.b.f.call(this);if(this.R){this.R.C();delete this.R}delete this.d;this.la=this.ya=null};
s.Ya=function(a){this.d.Ya(this.a(),a);this.ya=a};function Jd(a,b){a.ya=b}function Qd(a,b){var c=a.ya;if(!c||y(c))return c;return(c=x(c)?Ga(c,b).join(""):Qb(c))&&sa(c)}s.zb=function(){return Qd(this,Qb)};s.rb=function(a){V.b.rb.call(this,a);var b=this.a();b&&this.d.rb(b,a)};s.Qb=function(a){this.Wb=a;var b=this.a();b&&this.d.Qb(b,a)};s.ga=function(a,b){if(b||this.o!=a&&this.dispatchEvent(a?"show":"hide")){var c=this.a();c&&this.d.ga(c,a);this.z()&&this.d.Ma(this,a);this.o=a;return true}return false};
s.z=function(){return!U(this,1)};s.La=function(a){var b=this.r;if(!(b&&typeof b.z=="function"&&!b.z())&&Rd(this,1,!a)){if(!a){this.setActive(false);this.xa(false)}this.o&&this.d.Ma(this,a);this.ba(1,!a)}};s.xa=function(a){Rd(this,2,a)&&this.ba(2,a)};s.setActive=function(a){Rd(this,4,a)&&this.ba(4,a)};s.dd=function(a){Rd(this,8,a)&&this.ba(8,a)};function Sd(a,b){Rd(a,16,b)&&a.ba(16,b)}s.t=function(a){Rd(this,64,a)&&this.ba(64,a)};function U(a,b){return!!(a.N&b)}
s.ba=function(a,b){if(this.O&a&&b!=U(this,a)){this.d.ba(this,a,b);this.N=b?this.N|a:this.N&~a}};function Td(a,b,c){if(a.p&&U(a,b)&&!c)throw Error("Component already rendered");!c&&U(a,b)&&a.ba(b,false);a.O=c?a.O|b:a.O&~b}function W(a,b){return!!(a.pd&b)&&!!(a.O&b)}function Rd(a,b,c){return!!(a.O&b)&&U(a,b)!=c&&(!(a.gd&b)||a.dispatchEvent(ud(b,c)))&&!a.Ac}s.Lc=function(a){!Ud(a,this.a())&&this.dispatchEvent("enter")&&this.z()&&W(this,2)&&this.xa(true)};
s.Kc=function(a){if(!Ud(a,this.a())&&this.dispatchEvent("leave")){W(this,4)&&this.setActive(false);W(this,2)&&this.xa(false)}};function Ud(a,b){return!!a.relatedTarget&&Lb(b,a.relatedTarget)}s.Ta=function(a){if(this.z()){W(this,2)&&this.xa(true);if(Zb(a,0)){W(this,4)&&this.setActive(true);this.d.Ja(this)&&this.D().focus()}}!this.Wb&&Zb(a,0)&&a.preventDefault()};s.Fb=function(a){if(this.z()){W(this,2)&&this.xa(true);U(this,4)&&this.nb(a)&&W(this,4)&&this.setActive(false)}};
s.Md=function(a){this.z()&&this.nb(a)};s.nb=function(a){W(this,16)&&Sd(this,!U(this,16));W(this,8)&&this.dd(true);W(this,64)&&this.t(!U(this,64));var b=new J("action",this);if(a)for(var c=["altKey","ctrlKey","metaKey","shiftKey","platformModifierKey"],d,f=0;d=c[f];f++)b[d]=a[d];return this.dispatchEvent(b)};s.cc=function(){W(this,32)&&Rd(this,32,true)&&this.ba(32,true)};s.Sa=function(){W(this,4)&&this.setActive(false);W(this,32)&&Rd(this,32,false)&&this.ba(32,false)};
s.Ba=function(a){if(this.o&&this.z()&&this.ib(a)){a.preventDefault();a.stopPropagation();return true}return false};s.ib=function(a){return a.keyCode==13&&this.nb(a)};if(!ha(V))throw Error("Invalid component class "+V);if(!ha(Ed))throw Error("Invalid renderer class "+Ed);var Vd=ja(V);Nd[Vd]=Ed;Ld("goog-control",function(){return new V(null)});function Wd(){}z(Wd,Ed);w(Wd);Wd.prototype.e=function(a){return a.w().e("div",this.g())};
Wd.prototype.B=function(a,b){if(b.tagName=="HR"){var c=b;b=this.e(a);c.parentNode&&c.parentNode.insertBefore(b,c);Jb(c)}else Ra(b,this.g());return b};Wd.prototype.Ya=aa();Wd.prototype.g=o("goog-menuseparator");function Xd(a,b){V.call(this,null,a||Wd.S(),b);Td(this,1,false);Td(this,2,false);Td(this,4,false);Td(this,32,false);this.N=1}z(Xd,V);Xd.prototype.K=function(){Xd.b.K.call(this);fd(this.a(),"separator")};Ld("goog-menuseparator",function(){return new Xd});function Yd(){}w(Yd);s=Yd.prototype;
s.wa=aa();function Zd(a,b,c){if(b)b.tabIndex=c?0:-1}s.e=function(a){return a.w().e("div",this.gb(a).join(" "))};s.L=function(a){return a};s.ia=function(a){return a.tagName=="DIV"};s.B=function(a,b){b.id&&wd(a,b.id);var c=this.g(),d=false,f=Qa(b);f&&Fa(f,function(g){if(g==c)d=true;else if(g)if(g==c+"-disabled")a.La(false);else if(g==c+"-horizontal")a.bd($d);else g==c+"-vertical"&&a.bd(ae)},this);d||Ra(b,c);be(this,a,b);return b};
function be(a,b,c,d){if(c){d=d||c.firstChild;for(var f;d&&d.parentNode==c;){f=d.nextSibling;if(d.nodeType==1){var g=a.Bb(d);if(g){g.m=d;b.z()||g.La(false);b.da(g);g.B(d)}}else if(!d.nodeValue||sa(d.nodeValue)=="")c.removeChild(d);d=f}}}s.Bb=function(a){a:{for(var b=Qa(a),c=0,d=b.length;c<d;c++)if(a=b[c]in Md?Md[b[c]]():null){a=a;break a}a=null}return a};s.lb=function(a){a=a.a();Yc(a,true,E);if(D)a.hideFocus=true;var b=this.wa();b&&fd(a,b)};s.D=function(a){return a.a()};s.g=o("goog-container");
s.gb=function(a){var b=this.g(),c=[b,a.s==$d?b+"-horizontal":b+"-vertical"];a.z()||c.push(b+"-disabled");return c};s.Fd=function(){return ae};function X(a,b,c){S.call(this,c);this.d=b||Yd.S();this.s=a||this.d.Fd()}z(X,S);var $d="horizontal",ae="vertical";s=X.prototype;s.Ud=null;s.R=null;s.d=null;s.s=null;s.o=true;s.ka=true;s.Bc=true;s.Q=-1;s.F=null;s.Ca=false;s.ue=false;s.df=true;s.Ea=null;s.D=function(){return this.Ud||this.d.D(this)};s.ac=function(){return this.R||(this.R=new id(this.D()))};
s.e=function(){this.m=this.d.e(this)};s.L=function(){return this.d.L(this.a())};s.ia=function(a){return this.d.ia(a)};s.sa=function(a){this.m=this.d.B(this,a);if(a.style.display=="none")this.o=false};
s.K=function(){X.b.K.call(this);Ad(this,function(b){b.p&&ce(this,b)},this);var a=this.a();this.d.lb(this);this.ga(this.o,true);this.U().h(this,"enter",this.Fc).h(this,"highlight",this.Gc).h(this,"unhighlight",this.Mc).h(this,"open",this.Pe).h(this,"close",this.Ie).h(a,"mousedown",this.Ta).h(I(a),"mouseup",this.Ke).h(a,["mousedown","mouseup","mouseover","mouseout"],this.He);this.Ja()&&de(this,true)};
function de(a,b){var c=a.U(),d=a.D();b?c.h(d,"focus",a.cc).h(d,"blur",a.Sa).h(a.ac(),"key",a.Ba):c.ca(d,"focus",a.cc).ca(d,"blur",a.Sa).ca(a.ac(),"key",a.Ba)}s.va=function(){ee(this,-1);this.F&&this.F.t(false);this.Ca=false;X.b.va.call(this)};s.f=function(){X.b.f.call(this);if(this.R){this.R.C();this.R=null}this.d=this.F=this.Ea=null};s.Fc=o(true);
s.Gc=function(a){var b=Dd(this,a.target);if(b>-1&&b!=this.Q){var c=T(this,this.Q);c&&c.xa(false);this.Q=b;c=T(this,this.Q);this.Ca&&c.setActive(true);if(this.df&&this.F&&c!=this.F)c.O&64?c.t(true):this.F.t(false)}R(this.a(),"activedescendant",a.target.a().id)};s.Mc=function(a){if(a.target==T(this,this.Q))this.Q=-1;R(this.a(),"activedescendant","")};s.Pe=function(a){if((a=a.target)&&a!=this.F&&a.r==this){this.F&&this.F.t(false);this.F=a}};s.Ie=function(a){if(a.target==this.F)this.F=null};
s.Ta=function(a){if(this.ka)this.Ca=true;var b=this.D(),c;a:{if(b)if((c=b.getAttributeNode("tabindex"))&&c.specified){c=b.tabIndex;c=ga(c)&&c>=0;break a}c=false}c?b.focus():a.preventDefault()};s.Ke=function(){this.Ca=false};
s.He=function(a){var b;a:{b=a.target;if(this.Ea)for(var c=this.a();b&&b.parentNode&&b!=c;){var d=b.id;if(d in this.Ea){b=this.Ea[d];break a}b=b.parentNode}b=null}if(b)switch(a.type){case "mousedown":b.Ta(a);break;case "mouseup":b.Fb(a);break;case "mouseover":b.Lc(a);break;case "mouseout":b.Kc(a);break}};s.cc=aa();s.Sa=function(){ee(this,-1);this.Ca=false;this.F&&this.F.t(false)};s.Ba=function(a){if(this.z()&&this.o&&(Bd(this)!=0||this.Ud)&&this.ib(a)){a.preventDefault();a.stopPropagation();return true}return false};
s.ib=function(a){var b=T(this,this.Q);if(b&&typeof b.Ba=="function"&&b.Ba(a))return true;if(this.F&&this.F!=b&&typeof this.F.Ba=="function"&&this.F.Ba(a))return true;switch(a.keyCode){case 27:if(this.Ja())this.D().blur();else return false;break;case 36:fe(this);break;case 35:ge(this);break;case 38:if(this.s==ae)he(this);else return false;break;case 37:if(this.s==$d)Cd(this)?ie(this):he(this);else return false;break;case 40:if(this.s==ae)ie(this);else return false;break;case 39:if(this.s==$d)Cd(this)?
he(this):ie(this);else return false;break;default:return false}return true};function ce(a,b){var c=b.a();c=c.id||(c.id=vd(b));if(!a.Ea)a.Ea={};a.Ea[c]=b}s.da=function(a,b){X.b.da.call(this,a,b)};s.wb=function(a,b,c){a.gd|=2;a.gd|=64;if(this.Ja()||!this.ue)Td(a,32,false);Od(a,false);X.b.wb.call(this,a,b,c);c&&this.p&&ce(this,a);b<=this.Q&&this.Q++};
s.removeChild=function(a,b){if(a=y(a)?yd(this,a):a){var c=Dd(this,a);if(c!=-1)if(c==this.Q)a.xa(false);else c<this.Q&&this.Q--;(c=a.a())&&c.id&&Xa(this.Ea,c.id)}a=X.b.removeChild.call(this,a,b);Od(a,true);return a};s.bd=function(a){if(this.a())throw Error("Component already rendered");this.s=a};s.ga=function(a,b){if(b||this.o!=a&&this.dispatchEvent(a?"show":"hide")){this.o=a;var c=this.a();if(c){Wc(c,a);this.Ja()&&Zd(this.d,this.D(),this.ka&&this.o);b||this.dispatchEvent(this.o?"aftershow":"afterhide")}return true}return false};
s.z=e("ka");s.La=function(a){if(this.ka!=a&&this.dispatchEvent(a?"enable":"disable")){if(a){this.ka=true;Ad(this,function(b){if(b.pe)delete b.pe;else b.La(true)})}else{Ad(this,function(b){if(b.z())b.La(false);else b.pe=true});this.Ca=this.ka=false}this.Ja()&&Zd(this.d,this.D(),a&&this.o)}};s.Ja=e("Bc");s.Ma=function(a){a!=this.Bc&&this.p&&de(this,a);this.Bc=a;this.ka&&this.o&&Zd(this.d,this.D(),a)};function ee(a,b){var c=T(a,b);if(c)c.xa(true);else a.Q>-1&&T(a,a.Q).xa(false)}
s.xa=function(a){ee(this,Dd(this,a))};function fe(a){je(a,function(b,c){return(b+1)%c},Bd(a)-1)}function ge(a){je(a,function(b,c){b--;return b<0?c-1:b},0)}function ie(a){je(a,function(b,c){return(b+1)%c},a.Q)}function he(a){je(a,function(b,c){b--;return b<0?c-1:b},a.Q)}function je(a,b,c){c=c<0?Dd(a,a.F):c;var d=Bd(a);c=b.call(a,c,d);for(var f=0;f<=d;){var g=T(a,c);if(g&&a.sd(g)){ee(a,c);return true}f++;c=b.call(a,c,d)}return false}s.sd=function(a){return a.o&&a.z()&&!!(a.O&2)};function ke(){}
z(ke,Wd);w(ke);ke.prototype.e=function(a){return a.w().e("div",this.g()+" goog-inline-block","\u00a0")};ke.prototype.B=function(a,b){b=ke.b.B.call(this,a,b);Ra(b,"goog-inline-block");return b};ke.prototype.g=o("goog-toolbar-separator");function le(){}z(le,Yd);w(le);le.prototype.wa=o("toolbar");le.prototype.Bb=function(a){return a.tagName=="HR"?new Xd(ke.S()):le.b.Bb.call(this,a)};le.prototype.g=o("goog-toolbar");le.prototype.Fd=function(){return $d};function me(a,b,c){X.call(this,b,a||le.S(),c)}
z(me,X);function ne(){}z(ne,Ed);w(ne);s=ne.prototype;s.wa=o("button");s.vb=function(a,b,c){if(E)b==16?R(a,"pressed",c):ne.b.vb.call(this,a,b,c)};s.e=function(a){var b=ne.b.e.call(this,a),c=a.Eb();c&&this.fd(b,c);(c=a.n())&&this.u(b,c);a.O&16&&this.vb(b,16,false);return b};s.B=function(a,b){b=ne.b.B.call(this,a,b);var c=this.n(b);a.qa=c;a.jd=this.Eb(b);a.O&16&&this.vb(b,16,false);return b};s.n=u;s.u=u;s.Eb=function(a){return a.title};s.fd=function(a,b){if(a)a.title=b||""};s.g=o("goog-button");
function oe(){}z(oe,ne);w(oe);s=oe.prototype;s.wa=aa();s.e=function(a){pe(this,a);return a.w().e("button",{"class":this.gb(a).join(" "),disabled:!a.z(),title:a.Eb()||"",value:a.n()||""},a.zb()||"")};s.ia=function(a){return a.tagName=="BUTTON"||a.tagName=="INPUT"&&(a.type=="button"||a.type=="submit"||a.type=="reset")};s.B=function(a,b){pe(this,a);b.disabled&&Ra(b,this.Ab(1));return oe.b.B.call(this,a,b)};s.lb=function(a){a.U().h(a.a(),"click",a.nb)};s.Qb=u;s.rb=u;s.Ja=function(a){return a.z()};
s.Ma=u;s.ba=function(a,b,c){oe.b.ba.call(this,a,b,c);if((a=a.a())&&b==1)a.disabled=c};s.n=function(a){return a.value};s.u=function(a,b){if(a)a.value=b};s.vb=u;function pe(a,b){Od(b,false);b.pd&=-256;Td(b,32,false)}function qe(a,b,c){V.call(this,a,b||oe.S(),c)}z(qe,V);s=qe.prototype;s.n=e("qa");s.u=function(a){this.qa=a;this.d.u(this.a(),a)};s.Eb=e("jd");s.fd=function(a){this.jd=a;this.d.fd(this.a(),a)};s.f=function(){qe.b.f.call(this);delete this.qa;delete this.jd};
s.K=function(){qe.b.K.call(this);if(this.O&32){var a=this.D();a&&this.U().h(a,"keyup",this.ib)}};s.ib=function(a){if(a.keyCode==13&&a.type=="key"||a.keyCode==32&&a.type=="keyup")return this.nb(a);return a.keyCode==32};Ld("goog-button",function(){return new qe(null)});function re(){}z(re,ne);w(re);s=re.prototype;s.e=function(a){var b={"class":"goog-inline-block "+this.gb(a).join(" "),title:a.Eb()||""};return a.w().e("div",b,this.Yb(a.ya,a.w()))};s.L=function(a){return a&&a.firstChild.firstChild};
s.Yb=function(a,b){return b.e("div","goog-inline-block "+(this.g()+"-outer-box"),b.e("div","goog-inline-block "+(this.g()+"-inner-box"),a))};s.ia=function(a){return a.tagName=="DIV"};s.B=function(a,b){se(b,true);se(b,false);var c;a:{if((c=a.w().Gd(b))&&c.className.indexOf(this.g()+"-outer-box")!=-1)if((c=a.w().Gd(c))&&c.className.indexOf(this.g()+"-inner-box")!=-1){c=true;break a}c=false}c||b.appendChild(this.Yb(b.childNodes,a.w()));Ra(b,"goog-inline-block",this.g());return re.b.B.call(this,a,b)};
s.g=o("goog-custom-button");function se(a,b){if(a)for(var c=b?a.firstChild:a.lastChild,d;c&&c.parentNode==a;){d=b?c.nextSibling:c.previousSibling;if(c.nodeType==3){var f=c.nodeValue;if(sa(f)=="")a.removeChild(c);else{c.nodeValue=b?f.replace(/^[\s\xa0]+/,""):f.replace(/[\s\xa0]+$/,"");break}}else break;c=d}}function te(a,b,c){qe.call(this,a,b||re.S(),c);Td(this,16,true)}z(te,qe);Ld("goog-toggle-button",function(){return new te(null)});function ue(){}z(ue,re);w(ue);ue.prototype.g=o("goog-toolbar-button");
function ve(a,b,c){te.call(this,a,b||ue.S(),c)}z(ve,te);Ld("goog-toolbar-toggle-button",function(){return new ve(null)});function we(a,b,c){qe.call(this,a,b||ue.S(),c)}z(we,qe);Ld("goog-toolbar-button",function(){return new we(null)});function xe(a,b){this.Gb=a||1;this.Sb=b||ye;this.yc=ma(this.pf,this);this.Sc=oa()}z(xe,P);xe.prototype.enabled=false;var ye=t.window;s=xe.prototype;s.Z=null;s.setInterval=function(a){this.Gb=a;if(this.Z&&this.enabled){this.stop();this.start()}else this.Z&&this.stop()};
s.pf=function(){if(this.enabled){var a=oa()-this.Sc;if(a>0&&a<this.Gb*0.8)this.Z=this.Sb.setTimeout(this.yc,this.Gb-a);else{this.dispatchEvent(ze);if(this.enabled){this.Z=this.Sb.setTimeout(this.yc,this.Gb);this.Sc=oa()}}}};s.start=function(){this.enabled=true;if(!this.Z){this.Z=this.Sb.setTimeout(this.yc,this.Gb);this.Sc=oa()}};s.stop=function(){this.enabled=false;if(this.Z){this.Sb.clearTimeout(this.Z);this.Z=null}};s.f=function(){xe.b.f.call(this);this.stop();delete this.Sb};var ze="tick";
function Ae(a,b,c,d,f,g,h,j){var i,k=c.offsetParent;if(k){var m=k.tagName=="HTML"||k.tagName=="BODY";if(!m||Ic(k,"position")!="static"){i=Oc(k);m||(i=Ta(i,new B(k.scrollLeft,k.scrollTop)))}}k=Vc(a);if(m=Nc(a)){var l=new Gc(m.left,m.top,m.right-m.left,m.bottom-m.top);m=Math.max(k.left,l.left);var n=Math.min(k.left+k.width,l.left+l.width);if(m<=n){var q=Math.max(k.top,l.top);l=Math.min(k.top+k.height,l.top+l.height);if(q<=l){k.left=m;k.top=q;k.width=n-m;k.height=l-q}}}m=H(a);q=H(c);if(m.l!=q.l){n=m.l.body;
q=q.l.parentWindow||q.l.defaultView;l=new B(0,0);var v=I(n)?I(n).parentWindow||I(n).defaultView:window,ra=n;do{var r=v==q?Oc(ra):Qc(ra);l.x+=r.x;l.y+=r.y}while(v&&v!=q&&(ra=v.frameElement)&&(v=v.parent));q=l;q=Ta(q,Oc(n));if(D&&!Bb(m.l))q=Ta(q,Tb(m));k.left+=q.x;k.top+=q.y}a=(b&4&&Pc(a)?b^2:b)&-5;b=new B(a&2?k.left+k.width:k.left,a&1?k.top+k.height:k.top);if(i)b=Ta(b,i);if(f){b.x+=(a&2?-1:1)*f.x;b.y+=(a&1?-1:1)*f.y}var p;if(h)if((p=Nc(c))&&i){p.top=Math.max(0,p.top-i.y);p.right-=i.x;p.bottom-=i.y;
p.left=Math.max(0,p.left-i.x)}a:{f=b;p=p;f=f.cb();i=0;a=(d&4&&Pc(c)?d^2:d)&-5;d=Uc(c);j=j?j.cb():d;if(g||a!=0){if(a&2)f.x-=j.width+(g?g.right:0);else if(g)f.x+=g.left;if(a&1)f.y-=j.height+(g?g.bottom:0);else if(g)f.y+=g.top}if(h){if(p){g=f;i=0;if(g.x<p.left&&h&1){g.x=p.left;i|=1}if(g.x<p.left&&g.x+j.width>p.right&&h&16){j.width-=g.x+j.width-p.right;i|=4}if(g.x+j.width>p.right&&h&1){g.x=Math.max(p.right-j.width,p.left);i|=1}if(h&2)i|=(g.x<p.left?16:0)|(g.x+j.width>p.right?32:0);if(g.y<p.top&&h&4){g.y=
p.top;i|=2}if(g.y>=p.top&&g.y+j.height>p.bottom&&h&32){j.height-=g.y+j.height-p.bottom;i|=8}if(g.y+j.height>p.bottom&&h&4){g.y=Math.max(p.bottom-j.height,p.top);i|=2}if(h&8)i|=(g.y<p.top?64:0)|(g.y+j.height>p.bottom?128:0);h=i}else h=256;i=h;if(i&496){c=i;break a}}Jc(c,f);Ua(d,j)||Rc(c,j);c=i}return c}function Be(){}Be.prototype.Nb=aa();function Ce(a,b){this.element=a;this.db=b}z(Ce,Be);Ce.prototype.Nb=function(a,b,c){Ae(this.element,this.db,a,b,undefined,c)};
function De(a,b,c){Ce.call(this,a,b);this.te=c}z(De,Ce);De.prototype.Nb=function(a,b,c,d){var f=Ae(this.element,this.db,a,b,null,c,10,d);if(f&496){var g=this.db,h=b;if(f&48){g^=2;h^=2}if(f&192){g^=1;h^=1}f=Ae(this.element,g,a,h,null,c,10,d);if(f&496)this.te?Ae(this.element,this.db,a,b,null,c,5,d):Ae(this.element,this.db,a,b,null,c,0,d)}};function Ee(a,b,c,d){De.call(this,a,b,c);this.gf=d}z(Ee,De);
Ee.prototype.Nb=function(a,b,c,d){this.gf?Ae(this.element,this.db,a,b,null,c,33,d):Ee.b.Nb.call(this,a,b,c,d)};function Fe(){this.vd=[]}z(Fe,Ed);w(Fe);function Ge(a,b){var c=a.vd[b];if(!c){switch(b){case 0:c=a.g()+"-highlight";break;case 1:c=a.g()+"-checkbox";break;case 2:c=a.g()+"-content";break}a.vd[b]=c}return c}s=Fe.prototype;s.wa=o("menuitem");s.e=function(a){var b=a.w().e("div",this.gb(a).join(" "),He(this,a.ya,a.w()));Ie(this,a,b,!!(a.O&8)||!!(a.O&16));return b};s.L=function(a){return a&&a.firstChild};
s.B=function(a,b){var c=Kb(b),d=Ge(this,2);c&&c.className.indexOf(d)!=-1||b.appendChild(He(this,b.childNodes,a.w()));if(Ia(Qa(b),"goog-option")){a.pc(true);this.pc(a,b,true)}return Fe.b.B.call(this,a,b)};s.Ya=function(a,b){var c=this.L(a),d=Je(this,a)?c.firstChild:null;Fe.b.Ya.call(this,a,b);if(d&&!Je(this,a))c.insertBefore(d,c.firstChild||null)};function He(a,b,c){a=Ge(a,2);return c.e("div",a,b)}s.pc=function(a,b,c){if(b){fd(b,c?"menuitemcheckbox":this.wa());Ie(this,a,b,c)}};
function Je(a,b){var c=a.L(b);if(c){c=c.firstChild;var d=Ge(a,1);return!!c&&!!c.className&&c.className.indexOf(d)!=-1}return false}function Ie(a,b,c,d){if(d!=Je(a,c)){d?Ra(c,"goog-option"):Sa(c,"goog-option");c=a.L(c);if(d){a=Ge(a,1);c.insertBefore(b.w().e("div",a),c.firstChild||null)}else c.removeChild(c.firstChild)}}s.Ab=function(a){switch(a){case 2:return Ge(this,0);case 16:case 8:return"goog-option-selected";default:return Fe.b.Ab.call(this,a)}};
s.Ec=function(a){var b=Ge(this,0);switch(a){case "goog-option-selected":return 16;case b:return 2;default:return Fe.b.Ec.call(this,a)}};s.g=o("goog-menuitem");function Y(a,b,c,d){V.call(this,a,d||Fe.S(),c);this.u(b)}z(Y,V);Y.prototype.n=function(){var a=this.Vc;return a!=null?a:this.zb()};Y.prototype.u=ba("Vc");Y.prototype.pc=function(a){Td(this,16,a);var b=this.a();b&&this.d.pc(this,b,a)};Y.prototype.zb=function(){return Qd(this,function(a){return Ia(Qa(a),"goog-menuitem-accel")?"":Qb(a)})};
Ld("goog-menuitem",function(){return new Y(null)});function Ke(){}z(Ke,Yd);w(Ke);s=Ke.prototype;s.wa=o("menu");s.ia=function(a){return a.tagName=="UL"||Ke.b.ia.call(this,a)};s.Bb=function(a){return a.tagName=="HR"?new Xd:Ke.b.Bb.call(this,a)};s.Pa=function(a,b){return Lb(a.a(),b)};s.g=o("goog-menu");s.lb=function(a){Ke.b.lb.call(this,a);a=a.a();R(a,"haspopup","true")};Ld("goog-menuseparator",function(){return new Xd});function Le(a,b){X.call(this,ae,b||Ke.S(),a);this.Ma(false)}z(Le,X);s=Le.prototype;
s.xc=true;s.ve=false;s.g=function(){return this.d.g()};s.Pa=function(a){if(this.d.Pa(this,a))return true;for(var b=0,c=Bd(this);b<c;b++){var d=T(this,b);if(typeof d.Pa=="function"&&d.Pa(a))return true}return false};s.I=function(a){this.da(a,true)};s.bb=function(a,b){this.wb(a,b,true)};s.Db=function(a){return T(this,a)};s.Cc=function(){return Bd(this)};
s.fe=function(a,b){var c=this.o;c||Wc(this.a(),true);var d=this.a(),f=a,g=b,h=Oc(d);if(f instanceof B){g=f.y;f=f.x}Jc(d,d.offsetLeft+(f-h.x),d.offsetTop+(g-h.y));c||Wc(this.a(),false)};s.Fe=function(){return this.o?Oc(this.a()):null};s.ga=function(a,b){var c=Le.b.ga.call(this,a,b);c&&a&&this.p&&this.xc&&this.D().focus();return c};s.Fc=function(a){this.xc&&this.D().focus();return Le.b.Fc.call(this,a)};s.sd=function(a){return(this.ve||a.z())&&a.o&&!!(a.O&2)};
s.sa=function(a){var b=this.d,c;c=this.w();c=Ab(c.l,"div",b.g()+"-content",a);for(var d,f=0;d=c[f];f++)be(b,this,d);Le.b.sa.call(this,a)};function Me(){}z(Me,re);w(Me);if(E)Me.prototype.Ya=function(a,b){var c=Me.b.L.call(this,a&&a.firstChild);if(c){var d=this.createCaption(b,H(a)),f=c.parentNode;f&&f.replaceChild(d,c)}};s=Me.prototype;s.L=function(a){a=Me.b.L.call(this,a&&a.firstChild);if(E&&a&&a.__goog_wrapper_div)a=a.firstChild;return a};
s.B=function(a,b){var c=Ab(document,"*","goog-menu",b)[0];if(c){Wc(c,false);I(c).body.appendChild(c);var d=new Le;d.B(c);a.Rb(d)}return Me.b.B.call(this,a,b)};s.Yb=function(a,b){return Me.b.Yb.call(this,[this.createCaption(a,b),b.e("div","goog-inline-block "+(this.g()+"-dropdown"),"\u00a0")],b)};s.createCaption=function(a,b){return b.e("div","goog-inline-block "+(this.g()+"-caption"),a)};s.g=o("goog-menu-button");
function Z(a,b,c,d){qe.call(this,a,c||Me.S(),d);Td(this,64,true);b&&this.Rb(b);this.Z=new xe(500)}z(Z,qe);s=Z.prototype;s.od=true;s.Zc=false;s.Pc=false;s.K=function(){Z.b.K.call(this);this.c&&Ne(this,this.c,true);R(this.a(),"haspopup","true")};s.va=function(){Z.b.va.call(this);if(this.c){this.t(false);this.c.va();Ne(this,this.c,false);var a=this.c.a();a&&Jb(a)}};s.f=function(){Z.b.f.call(this);if(this.c){this.c.C();delete this.c}this.Z.C()};
s.Ta=function(a){Z.b.Ta.call(this,a);if(U(this,4)){this.t(!U(this,64));if(this.c)this.c.Ca=U(this,64)}};s.Fb=function(a){Z.b.Fb.call(this,a);if(this.c&&!U(this,4))this.c.Ca=false};s.nb=function(){this.setActive(false);return true};s.Je=function(a){this.c&&this.c.o&&!this.Pa(a.target)&&this.t(false)};s.Pa=function(a){return a&&Lb(this.a(),a)||this.c&&this.c.Pa(a)||false};
s.ib=function(a){if(a.keyCode==32){a.preventDefault();if(a.type!="keyup")return false}else if(a.type!="key")return false;if(this.c&&this.c.o){var b=this.c.Ba(a);if(a.keyCode==27){this.t(false);return true}return b}if(a.keyCode==40||a.keyCode==38||a.keyCode==32){this.t(true);return true}return false};s.Ic=function(){this.t(false)};s.Me=function(){U(this,4)||this.t(false)};s.Sa=function(a){this.Pc||this.t(false);Z.b.Sa.call(this,a)};function Oe(a){a.c||a.Rb(new Le(a.w()));return a.c||null}
s.Rb=function(a){var b=this.c;if(a!=b){if(b){this.t(false);this.p&&Ne(this,b,false);delete this.c}if(a){this.c=a;xd(a,this);a.ga(false);var c=this.Pc;(a.xc=c)&&a.Ma(true);this.p&&Ne(this,a,true)}}return b};s.I=function(a){Oe(this).da(a,true)};s.bb=function(a,b){Oe(this).wb(a,b,true)};s.Db=function(a){return this.c?T(this.c,a):null};s.Cc=function(){return this.c?Bd(this.c):0};s.ga=function(a,b){var c=Z.b.ga.call(this,a,b);c&&!this.o&&this.t(false);return c};
s.La=function(a){Z.b.La.call(this,a);this.z()||this.t(false)};
s.t=function(a){Z.b.t.call(this,a);if(this.c&&U(this,64)==a){if(a){this.c.p||this.c.pb();this.ne=Nc(this.a());this.qd=Vc(this.a());Pe(this);ee(this.c,-1)}else{this.setActive(false);this.c.Ca=false;if(this.lc!=null){this.lc=undefined;var b=this.c.a();b&&Rc(b,"","")}}this.c.ga(a);b=this.U();var c=a?b.h:b.ca;c.call(b,Sb(this.w()),"mousedown",this.Je,true);this.Pc&&c.call(b,this.c,"blur",this.Me);c.call(b,this.Z,ze,this.bf);a?this.Z.start():this.Z.stop()}};
function Pe(a){if(a.c.p){var b=a.od?5:7;b=new Ee(a.a(),b,!a.Zc,a.Zc);var c=a.c.a();if(!a.c.o){c.style.visibility="hidden";Wc(c,true)}if(!a.lc&&a.Zc)a.lc=Uc(c);b.Nb(c,a.od?4:6,null,a.lc);if(!a.c.o){Wc(c,false);c.style.visibility="visible"}}}
s.bf=function(){var a=Vc(this.a()),b=Nc(this.a()),c;c=this.qd;c=c==a?true:!c||!a?false:c.left==a.left&&c.width==a.width&&c.top==a.top&&c.height==a.height;if(!(c=!c)){c=this.ne;c=c==b?true:!c||!b?false:c.top==b.top&&c.right==b.right&&c.bottom==b.bottom&&c.left==b.left;c=!c}if(c){this.qd=a;this.ne=b;Pe(this)}};function Ne(a,b,c){var d=a.U();c=c?d.h:d.ca;c.call(d,b,"action",a.Ic);c.call(d,b,"highlight",a.Gc);c.call(d,b,"unhighlight",a.Mc)}s.Gc=function(a){R(this.a(),"activedescendant",a.target.a().id)};
s.Mc=function(){T(this.c,this.c.Q)||R(this.a(),"activedescendant","")};Ld("goog-menu-button",function(){return new Z(null)});function Qe(a){this.Ua=[];Re(this,a)}z(Qe,P);s=Qe.prototype;s.Ka=null;s.ce=null;s.Cc=function(){return this.Ua.length};s.Db=function(a){return this.Ua[a]||null};function Re(a,b){if(b){Fa(b,function(c){Se(this,c,false)},a);Ma(a.Ua,b)}}s.I=function(a){this.bb(a,this.Cc())};s.bb=function(a,b){if(a){Se(this,a,false);Na(this.Ua,b,0,a)}};s.bc=e("Ka");
s.Za=function(a){if(a!=this.Ka){Se(this,this.Ka,false);this.Ka=a;Se(this,a,true)}this.dispatchEvent("select")};s.Dc=function(){return this.Ka?Ea(this.Ua,this.Ka):-1};s.ge=function(a){this.Za(this.Db(a))};s.clear=function(){var a=this.Ua;if(!x(a))for(var b=a.length-1;b>=0;b--)delete a[b];a.length=0;this.Ka=null};s.f=function(){Qe.b.f.call(this);delete this.Ua;this.Ka=null};function Se(a,b,c){if(b)if(typeof a.ce=="function")a.ce(b,c);else typeof b.dd=="function"&&b.dd(c)}
function $(a,b,c,d){Z.call(this,a,b,c,d);this.Zb=a;Te(this)}z($,Z);s=$.prototype;s.q=null;s.Zb=null;s.K=function(){$.b.K.call(this);Te(this)};s.sa=function(a){$.b.sa.call(this,a);if(a=this.zb()){this.Zb=a;Te(this)}else this.ge(0)};s.f=function(){$.b.f.call(this);if(this.q){this.q.C();this.q=null}this.Zb=null};s.Ic=function(a){this.Za(a.target);$.b.Ic.call(this,a);a.stopPropagation();this.dispatchEvent("action")};s.Se=function(){var a=this.bc();$.b.u.call(this,a&&a.n());Te(this)};
s.Rb=function(a){var b=$.b.Rb.call(this,a);if(a!=b){this.q&&this.q.clear();if(a)this.q?Ad(a,function(c){this.q.I(c)},this):Ue(this,a)}return b};s.I=function(a){$.b.I.call(this,a);this.q?this.q.I(a):Ue(this,Oe(this))};s.bb=function(a,b){$.b.bb.call(this,a,b);this.q?this.q.bb(a,b):Ue(this,Oe(this))};s.Za=function(a){this.q&&this.q.Za(a)};s.ge=function(a){this.q&&this.Za(this.q.Db(a))};
s.u=function(a){if(a!=null&&this.q)for(var b=0,c;c=this.q.Db(b);b++)if(c&&typeof c.n=="function"&&c.n()==a){this.Za(c);return}this.Za(null)};s.bc=function(){return this.q?this.q.bc():null};s.Dc=function(){return this.q?this.q.Dc():-1};function Ue(a,b){a.q=new Qe;b&&Ad(b,function(c){this.q.I(c)},a);a.U().h(a.q,"select",a.Se)}function Te(a){var b=a.bc();a.Ya(b?b.zb():a.Zb)}s.t=function(a){$.b.t.call(this,a);U(this,64)&&ee(Oe(this),this.Dc())};Ld("goog-select",function(){return new $(null)});
function Ve(){}z(Ve,Me);w(Ve);Ve.prototype.g=o("goog-toolbar-menu-button");function We(a,b,c,d){$.call(this,a,b,c||Ve.S(),d)}z(We,$);Ld("goog-toolbar-select",function(){return new We(null)});function Xe(a){this.m=a;this.Xd=N(this.m,E?"DOMMouseScroll":"mousewheel",this)}z(Xe,P);
Xe.prototype.handleEvent=function(a){var b=0,c=0,d=0;a=a.ua;if(a.type=="mousewheel"){c=1;if(D||F&&(ib||G("532.0")))c=40;d=-a.wheelDelta/c;if(a.wheelDeltaX!==undefined){b=-a.wheelDeltaX/c;c=-a.wheelDeltaY/c}else c=d}else{d=a.detail;if(d>100)d=3;else if(d<-100)d=-3;if(a.axis!==undefined&&a.axis===a.HORIZONTAL_AXIS)b=d;else c=d}if(ga(this.Zd))b=Math.min(Math.max(b,-this.Zd),this.Zd);if(ga(this.$d))c=Math.min(Math.max(c,-this.$d),this.$d);b=new Ye(d,a,b,c);try{this.dispatchEvent(b)}finally{b.C()}};
Xe.prototype.f=function(){Xe.b.f.call(this);O(this.Xd);delete this.Xd};function Ye(a,b,c,d){b&&this.kb(b,void 0);this.type="mousewheel";this.detail=a;this.eb=c;this.fb=d}z(Ye,K);function Ze(a,b,c,d){if(!x(a)||!x(b))throw Error("Start and end parameters must be arrays");if(a.length!=b.length)throw Error("Start and end points must be the same length");this.tb=a;this.ze=b;this.duration=c;this.md=d;this.coords=[]}z(Ze,P);var $e={},af=null;
function bf(){ye.clearTimeout(af);var a=oa();for(var b in $e)cf($e[b],a);af=Wa($e)?null:ye.setTimeout(bf,20)}function df(a){a=ja(a);delete $e[a];if(af&&Wa($e)){ye.clearTimeout(af);af=null}}s=Ze.prototype;s.N=0;s.Ed=0;s.aa=0;s.startTime=null;s.Ad=null;s.Rc=null;
s.play=function(a){if(a||this.N==0){this.aa=0;this.coords=this.tb}else if(this.N==1)return false;df(this);this.startTime=oa();if(this.N==-1)this.startTime-=this.duration*this.aa;this.Ad=this.startTime+this.duration;this.Rc=this.startTime;this.aa||this.Kb();ef(this,"play");this.N==-1&&ef(this,"resume");this.N=1;a=ja(this);a in $e||($e[a]=this);af||(af=ye.setTimeout(bf,20));cf(this,this.startTime);return true};s.stop=function(a){df(this);this.N=0;if(a)this.aa=1;ff(this,this.aa);ef(this,"stop");this.kc()};
s.f=function(){this.N!=0&&this.stop(false);ef(this,"destroy");Ze.b.f.call(this)};function cf(a,b){a.aa=(b-a.startTime)/(a.Ad-a.startTime);if(a.aa>=1)a.aa=1;a.Ed=1E3/(b-a.Rc);a.Rc=b;ha(a.md)?ff(a,a.md(a.aa)):ff(a,a.aa);if(a.aa==1){a.N=0;df(a);ef(a,"finish");a.kc()}else a.N==1&&a.Wc()}function ff(a,b){a.coords=Array(a.tb.length);for(var c=0;c<a.tb.length;c++)a.coords[c]=(a.ze[c]-a.tb[c])*b+a.tb[c]}s.Wc=function(){ef(this,"animate")};s.Kb=function(){ef(this,"begin")};s.kc=function(){ef(this,"end")};
function ef(a,b){a.dispatchEvent(new gf(b,a))}function gf(a,b){J.call(this,a);this.coords=b.coords;this.x=b.coords[0];this.y=b.coords[1];this.Ff=b.coords[2];this.duration=b.duration;this.aa=b.aa;this.vf=b.Ed;this.Cf=b.N;this.sf=b}z(gf,J);function jf(a,b,c){this.target=a;this.handle=b||a;this.Vd=c||new Gc(NaN,NaN,NaN,NaN);this.l=I(a);this.ta=new pd(this);N(this.handle,"mousedown",this.he,false,this)}z(jf,P);var kf=D||E&&G("1.9.3");s=jf.prototype;s.screenX=0;s.screenY=0;s.ie=0;s.je=0;s.eb=0;s.fb=0;
s.ka=true;s.Ga=false;s.Rd=0;s.We=0;s.Ue=false;s.U=e("ta");s.La=ba("ka");s.f=function(){jf.b.f.call(this);wc(this.handle,"mousedown",this.he,false,this);this.ta.C();delete this.target;delete this.handle;delete this.ta};
s.he=function(a){if(this.ka&&!this.Ga&&(a.type!="mousedown"||Zb(a,0))){if(this.Rd==0){lf(this,a);if(this.Ga)a.preventDefault();else return}else a.preventDefault();var b=this.l,c=b.documentElement,d=!kf;this.ta.h(b,"mousemove",this.Xe,d);this.ta.h(b,"mouseup",this.$b,d);if(kf){c.setCapture(false);this.ta.h(c,"losecapture",this.$b)}else this.ta.h(b?b.parentWindow||b.defaultView:window,"blur",this.$b);D&&this.Ue&&this.ta.h(b,"dragstart",Xb);this.hf&&this.ta.h(this.hf,"scroll",this.af,d);this.screenX=
this.ie=a.screenX;this.screenY=this.je=a.screenY;this.eb=this.target.offsetLeft;this.fb=this.target.offsetTop;this.Lb=Tb(H(this.l));this.We=oa()}};function lf(a,b){if(a.dispatchEvent(new mf("start",a,b.clientX,b.clientY,b))!==false)a.Ga=true}s.$b=function(a,b){rd(this.ta);kf&&this.l.releaseCapture();if(this.Ga){this.Ga=false;this.dispatchEvent(new mf("end",this,a.clientX,a.clientY,a,nf(this,this.eb),of(this,this.fb),b))}};
s.Xe=function(a){if(this.ka){var b=a.screenX-this.screenX,c=a.screenY-this.screenY;this.screenX=a.screenX;this.screenY=a.screenY;if(!this.Ga){var d=this.ie-this.screenX,f=this.je-this.screenY;if(d*d+f*f>this.Rd){lf(this,a);if(!this.Ga){this.$b(a);return}}}c=pf(this,b,c);b=c.x;c=c.y;if(this.Ga)if(this.dispatchEvent(new mf("beforedrag",this,a.clientX,a.clientY,a,b,c))!==false){qf(this,a,b,c,false);a.preventDefault()}}};
function pf(a,b,c){var d=Tb(H(a.l));b+=d.x-a.Lb.x;c+=d.y-a.Lb.y;a.Lb=d;a.eb+=b;a.fb+=c;return new B(nf(a,a.eb),of(a,a.fb))}s.af=function(a){var b=pf(this,0,0);a.clientX=this.Lb.x-this.screenX;a.clientY=this.Lb.x-this.screenY;qf(this,a,b.x,b.y,true)};function qf(a,b,c,d){a.zc(c,d);a.dispatchEvent(new mf("drag",a,b.clientX,b.clientY,b,c,d))}function nf(a,b){var c=a.Vd,d=!isNaN(c.left)?c.left:null;c=!isNaN(c.width)?c.width:0;return Math.min(d!=null?d+c:Infinity,Math.max(d!=null?d:-Infinity,b))}
function of(a,b){var c=a.Vd,d=!isNaN(c.top)?c.top:null;c=!isNaN(c.height)?c.height:0;return Math.min(d!=null?d+c:Infinity,Math.max(d!=null?d:-Infinity,b))}s.zc=function(a,b){this.target.style.left=a+"px";this.target.style.top=b+"px"};function mf(a,b,c,d,f,g,h,j){J.call(this,a);this.clientX=c;this.clientY=d;this.tf=f;this.left=g!==undefined?g:b.eb;this.top=h!==undefined?h:b.fb;this.zd=b;this.uf=!!j}z(mf,J);function rf(a,b,c,d,f){Ze.call(this,b,c,d,f);this.element=a}z(rf,Ze);rf.prototype.tc=u;
rf.prototype.Wc=function(){this.tc();rf.b.Wc.call(this)};rf.prototype.kc=function(){this.tc();rf.b.kc.call(this)};rf.prototype.Kb=function(){this.tc();rf.b.Kb.call(this)};function sf(a,b,c){if(b.length!=2||c.length!=2)throw Error("Start and end points must be 2D");rf.apply(this,arguments)}z(sf,rf);sf.prototype.tc=function(){this.element.style.left=Math.round(this.coords[0])+"px";this.element.style.top=Math.round(this.coords[1])+"px"};
function tf(a,b,c,d){sf.call(this,a,[a.offsetLeft,a.offsetTop],b,c,d)}z(tf,sf);tf.prototype.Kb=function(){this.tb=[this.element.offsetLeft,this.element.offsetTop];tf.b.Kb.call(this)};function uf(){}z(uf,P);s=uf.prototype;s.qa=0;s.na=0;s.fa=100;s.$=0;s.Na=1;s.X=false;s.Wa=false;s.u=function(a){a=vf(this,a);if(this.qa!=a){this.qa=a+this.$>this.fa?this.fa-this.$:a<this.na?this.na:a;!this.X&&!this.Wa&&this.dispatchEvent("change")}};s.n=function(){return vf(this,this.qa)};
s.qb=function(a){a=vf(this,a);if(this.$!=a){this.$=a<0?0:this.qa+a>this.fa?this.fa-this.qa:a;!this.X&&!this.Wa&&this.dispatchEvent("change")}};s.Aa=function(){var a;a=this.$;a=this.Na==null?a:Math.round(a/this.Na)*this.Na;return a};s.ad=function(a){if(this.na!=a){var b=this.X;this.X=true;this.na=a;if(a+this.$>this.fa)this.$=this.fa-this.na;a>this.qa&&this.u(a);if(a>this.fa){this.$=0;this.qc(a);this.u(a)}this.X=b;!this.X&&!this.Wa&&this.dispatchEvent("change")}};s.M=function(){return vf(this,this.na)};
s.qc=function(a){a=vf(this,a);if(this.fa!=a){var b=this.X;this.X=true;this.fa=a;a<this.qa+this.$&&this.u(a-this.$);if(a<this.na){this.$=0;this.ad(a);this.u(this.fa)}if(a<this.na+this.$)this.$=this.fa-this.na;this.X=b;!this.X&&!this.Wa&&this.dispatchEvent("change")}};s.P=function(){return vf(this,this.fa)};s.ed=function(a){if(this.Na!=a){this.Na=a;a=this.X;this.X=true;this.qc(this.P());this.qb(this.Aa());this.u(this.n());this.X=a;!this.X&&!this.Wa&&this.dispatchEvent("change")}};
function vf(a,b){if(a.Na==null)return b;return a.na+Math.round((b-a.na)/a.Na)*a.Na}function wf(a){S.call(this,a);this.i=new uf;N(this.i,"change",this.Qe,false,this)}z(wf,S);s=wf.prototype;s.s="horizontal";s.Oc=false;s.Ye=false;s.Da=10;s.Jb=0;s.e=function(){wf.b.e.call(this);this.sa(this.w().e("div",this.g(this.s)))};
s.sa=function(a){wf.b.sa.call(this,a);Ra(a,this.g(this.s));a=this.a();a=Ab(document,null,"goog-twothumbslider-value-thumb",a)[0];var b=this.a();b=Ab(document,null,"goog-twothumbslider-extent-thumb",b)[0];if(!a){a=xf(this,"goog-twothumbslider-value-thumb");this.a().appendChild(a)}if(!b){b=xf(this,"goog-twothumbslider-extent-thumb");this.a().appendChild(b)}this.A=a;this.W=b;fd(this.a(),"slider");yf(this)};
s.K=function(){wf.b.K.call(this);this.uc=new jf(this.A);this.Dd=new jf(this.W);this.uc.zc=this.Dd.zc=u;this.R=new id(this.a());this.jc=new Xe(this.a());this.U().h(this.uc,"beforedrag",this.Ld).h(this.Dd,"beforedrag",this.Ld).h(this.R,"key",this.Hc).h(this.a(),"mousedown",this.Ne).h(this.jc,"mousewheel",this.Oe);this.a().tabIndex=0;zf(this)};
s.Ld=function(a){var b=a.zd==this.uc?this.A:this.W,c;if(this.s=="vertical"){c=this.a().clientHeight-b.offsetHeight;c=(c-a.top)/c*(this.P()-this.M())+this.M()}else{c=this.a().clientWidth-b.offsetWidth;c=a.left/c*(this.P()-this.M())+this.M()}c=a.zd==this.uc?Math.min(Math.max(c,this.M()),this.n()+this.Aa()):Math.min(Math.max(c,this.n()),this.P());Af(this,b,c)};
s.Hc=function(a){var b=true;switch(a.keyCode){case 36:Bf(this,this.M());break;case 35:Bf(this,this.P());break;case 33:Cf(this,this.Da);break;case 34:Cf(this,-this.Da);break;case 37:case 40:Cf(this,a.shiftKey?-this.Da:-this.kd);break;case 39:case 38:Cf(this,a.shiftKey?this.Da:this.kd);break;default:b=false}b&&a.preventDefault()};
s.Ne=function(a){this.a().focus&&this.a().focus();var b=a.target;if(!Lb(this.A,b)&&!Lb(this.W,b))if(this.Ye)Bf(this,Df(this,a));else{this.hd(a);this.ha=Ef(this,Df(this,a));this.Sd=this.s=="vertical"?this.gc<this.ha.offsetTop:this.gc>this.ha.offsetLeft+this.ha.offsetWidth;a=I(this.a());this.U().h(a,"mouseup",this.Nd,true).h(this.a(),"mousemove",this.hd);if(!this.Ia){this.Ia=new xe(200);this.U().h(this.Ia,ze,this.Od)}this.Od();this.Ia.start()}};s.Oe=function(a){Cf(this,(a.detail>0?-1:1)*this.kd);a.preventDefault()};
s.Od=function(){var a;if(this.s=="vertical"){var b=this.gc,c=this.ha.offsetTop;if(this.Sd){if(b<c)a=Ff(this,this.ha)+this.Da}else if(b>c+this.ha.offsetHeight)a=Ff(this,this.ha)-this.Da}else{b=this.gc;c=this.ha.offsetLeft;if(this.Sd){if(b>c+this.ha.offsetWidth)a=Ff(this,this.ha)+this.Da}else if(b<c)a=Ff(this,this.ha)-this.Da}a!==undefined&&Af(this,this.ha,a)};s.Nd=function(){this.Ia&&this.Ia.stop();var a=I(this.a());this.U().ca(a,"mouseup",this.Nd,true).ca(this.a(),"mousemove",this.hd)};
function Gf(a,b){var c,d=a.a();c=Qc(b);d=Qc(d);c=new B(c.x-d.x,c.y-d.y);return a.s=="vertical"?c.y:c.x}s.hd=function(a){this.gc=Gf(this,a)};function Df(a,b){var c=a.M(),d=a.P();if(a.s=="vertical"){var f=a.A.offsetHeight,g=a.a().clientHeight-f;f=Gf(a,b)-f/2;return(d-c)*(g-f)/g+c}else{f=a.A.offsetWidth;g=a.a().clientWidth-f;f=Gf(a,b)-f/2;return(d-c)*f/g+c}}
function Ff(a,b){if(b==a.A)return a.i.n();else if(b==a.W)return a.i.n()+a.i.Aa();else throw Error("Illegal thumb element. Neither minThumb nor maxThumb");}function Cf(a,b){var c=Ff(a,a.A)+b,d=Ff(a,a.W)+b;c=Math.min(Math.max(c,a.M()),a.P()-a.Jb);d=Math.min(Math.max(d,a.M()+a.Jb),a.P());Hf(a,c,d-c)}
function Af(a,b,c){var d=null;if(b==a.W&&c<=a.i.P()&&c>=a.i.n()+a.Jb)d=c-a.i.n();var f=d||a.i.Aa();if(b==a.A&&c>=a.M()&&c<=a.i.n()+f-a.Jb){b=f-(c-a.i.n());if(vf(a.i,c)+vf(a.i,b)==vf(a.i,c+b)){Hf(a,c,b);d=null}}d!=null&&a.i.qb(d)}function Hf(a,b,c){if(a.M()<=b&&b<=a.P()-c&&a.Jb<=c&&c<=a.P()-b)if(!(b==a.n()&&c==a.Aa())){a.i.Wa=true;a.i.qb(0);a.i.u(b);a.i.qb(c);a.i.Wa=false;zf(a);a.dispatchEvent("change")}}s.M=function(){return this.i.M()};s.ad=function(a){this.i.ad(a)};s.P=function(){return this.i.P()};
s.qc=function(a){this.i.qc(a)};function Ef(a,b){return b<=a.i.n()+a.i.Aa()/2?a.A:a.W}s.Qe=function(){zf(this);yf(this);this.dispatchEvent("change")};function zf(a){if(a.A&&!a.Oc){var b=If(a,Ff(a,a.A)),c=If(a,Ff(a,a.W));if(a.s=="vertical"){a.A.style.top=b.y+"px";a.W.style.top=c.y+"px"}else{a.A.style.left=b.x+"px";a.W.style.left=c.x+"px"}}}
function If(a,b){var c=new B;if(a.A){var d=a.M(),f=a.P();d=b==d&&d==f?0:(b-d)/(f-d);if(a.s=="vertical"){f=a.A.offsetHeight;f=a.a().clientHeight-f;c.y=f-Math.round(d*f)}else{f=a.a().clientWidth-a.A.offsetWidth;c.x=Math.round(d*f)}}return c}function Bf(a,b){b=Math.min(a.P(),Math.max(b,a.M()));a.xb&&a.xb.stop(true);var c=Ef(a,b),d=If(a,b);d=new tf(c,a.s=="vertical"?[c.offsetLeft,d.y]:[d.x,c.offsetTop],100);a.xb=d;a.U().h(d,"end",a.ye);a.Oc=true;Af(a,c,b);d.play(false)}s.ye=function(){this.Oc=false};
s.bd=function(a){if(this.s!=a){var b=this.g(this.s),c=this.g(a);this.s=a;if(this.a()){a=this.a();for(var d=Qa(a),f=false,g=0;g<d.length;g++)if(d[g]==b){Na(d,g--,1);f=true}if(f){d.push(c);a.className=d.join(" ")}this.A.style.left=this.A.style.top="";this.W.style.left=this.W.style.top="";zf(this)}}};
s.f=function(){wf.b.f.call(this);this.Ia&&this.Ia.C();delete this.Ia;this.xb&&this.xb.C();delete this.xb;delete this.A;delete this.W;this.i.C();delete this.i;if(this.R){this.R.C();delete this.R}if(this.jc){this.jc.C();delete this.jc}};s.kd=1;s.ed=function(a){this.i.ed(a)};s.n=function(){return this.i.n()};s.u=function(a){Af(this,this.A,a)};s.Aa=function(){return this.i.Aa()};s.qb=function(a){Af(this,this.W,this.i.n()+a)};s.ga=function(a){Wc(this.a(),a);a&&zf(this)};
function yf(a){var b=a.a();if(b){R(b,"valuemin",a.M());R(b,"valuemax",a.P());R(b,"valuenow",a.n())}}function Jf(a){wf.call(this,a);this.i.u(this.M());this.i.qb(this.P()-this.M())}z(Jf,wf);Jf.prototype.g=function(a){return"goog-twothumbslider-"+a};function xf(a,b){var c=a.w().e("div",b);fd(c,"button");return c}hte2.ab=function(a){return document.getElementById(a)};hte2.ld=function(a,b){var c=[],d,f,g;d=b.getElementsByTagName("*");f=d.length;for(g=0;g<f;g+=1)d[g].className===a&&c.push(d[g]);return c};
function Kf(a){return Lf(a||arguments.callee.caller,[])}
function Lf(a,b){var c=[];if(Ia(b,a))c.push("[...circular reference...]");else if(a&&b.length<50){c.push(Mf(a)+"(");for(var d=a.arguments,f=0;f<d.length;f++){f>0&&c.push(", ");var g;g=d[f];switch(typeof g){case "object":g=g?"object":"null";break;case "string":g=g;break;case "number":g=String(g);break;case "boolean":g=g?"true":"false";break;case "function":g=(g=Mf(g))?g:"[fn]";break;case "undefined":default:g=typeof g;break}if(g.length>40)g=g.substr(0,40)+"...";c.push(g)}b.push(a);c.push(")\n");try{c.push(Lf(a.caller,
b))}catch(h){c.push("[exception trying to get caller]\n")}}else a?c.push("[...long stack...]"):c.push("[end]");return c.join("")}function Mf(a){a=String(a);if(!Nf[a]){var b=/function ([^\(]+)/.exec(a);Nf[a]=b?b[1]:"[Anonymous]"}return Nf[a]}var Nf={};function Of(a,b,c,d,f){this.reset(a,b,c,d,f)}Of.prototype.jf=0;Of.prototype.Cd=null;Of.prototype.Bd=null;var Pf=0;Of.prototype.reset=function(a,b,c,d,f){this.jf=typeof f=="number"?f:Pf++;this.Df=d||oa();this.Ib=a;this.Af=b;this.yf=c;delete this.Cd;delete this.Bd};
Of.prototype.de=ba("Ib");function Qf(a){this.Ze=a}Qf.prototype.r=null;Qf.prototype.Ib=null;Qf.prototype.J=null;Qf.prototype.Qd=null;function Rf(a,b){this.name=a;this.value=b}Rf.prototype.toString=e("name");var Sf=new Rf("CONFIG",700);Qf.prototype.de=ba("Ib");function Tf(a){if(a.Ib)return a.Ib;if(a.r)return Tf(a.r);Da("Root logger has no level set.");return null}
Qf.prototype.log=function(a,b,c){if(a.value>=Tf(this).value){a=this.Ce(a,b,c);for(b=this;b;){c=b;var d=a;if(c.Qd)for(var f=0,g=void 0;g=c.Qd[f];f++)g(d);b=b.r}}};
Qf.prototype.Ce=function(a,b,c){var d=new Of(a,String(b),this.Ze);if(c){d.Cd=c;var f;var g=arguments.callee.caller;try{var h,j=ca("window.location.href");h=typeof c=="string"?{message:c,name:"Unknown error",lineNumber:"Not available",fileName:j,stack:"Not available"}:!c.lineNumber||!c.fileName||!c.stack?{message:c.message,name:c.name,lineNumber:c.lineNumber||c.xf||"Not available",fileName:c.fileName||c.filename||c.sourceURL||j,stack:c.stack||"Not available"}:c;f="Message: "+ta(h.message)+'\nUrl: <a href="view-source:'+
h.fileName+'" target="_new">'+h.fileName+"</a>\nLine: "+h.lineNumber+"\n\nBrowser stack:\n"+ta(h.stack+"-> ")+"[end]\n\nJS stack traversal:\n"+ta(Kf(g)+"-> ")}catch(i){f="Exception trying to expose exception! You win, we lose. "+i}d.Bd=f}return d};var Uf={},Vf=null;function Wf(a){if(!Vf){Vf=new Qf("");Uf[""]=Vf;Vf.de(Sf)}var b;if(!(b=Uf[a])){b=new Qf(a);var c=a.lastIndexOf("."),d=a.substr(0,c);c=a.substr(c+1);d=Wf(d);if(!d.J)d.J={};d.J[c]=b;b.r=d;b=Uf[a]=b}return b}Wf("goog.dom.SavedRange");Wf("goog.dom.browserrange.IeRange");
hte2.Ub=function(){N(hte2.H.Ra(),"click",this.$c)};hte2.Ub.prototype={$c:function(a){var b;b=a.target;a=a.clientX;a-=hte2.H.Ra().offsetLeft;if(b.nodeName==="SPAN"){a-=parseInt(b.parentNode.style.paddingLeft,10);hte2.j.ee(b.parentNode,a-8)}}};hte2.Tb=function(){var a=new id(document);N(a,"key",this.Nc)};
hte2.Tb.prototype={Nc:function(a){var b;a.preventDefault();switch(a.keyCode){case 37:hte2.j.sc();break;case 39:hte2.j.ub();break;case 38:hte2.j.Uc();break;case 40:hte2.j.Tc();break;case 8:hte2.j.sc();hte2.H.oc(hte2.v.T(hte2.j.Ha()).Y);break;case 46:hte2.H.oc(hte2.v.T(hte2.j.Ha()).Y);break;case 13:hte2.H.Vb(hte2.v.T(hte2.j.Ha()).Y-1);hte2.j.ub();break;default:if(a.charCode!==undefined&&a.charCode!==0){b=hte2.v.T(hte2.j.Ha()).Y-1;hte2.H.nd(a.charCode,b);hte2.j.ub()}break}hte2.j.Yc()}};hte2.k=new ed;
hte2.Ub=function(){N(hte2.H.Ra(),"click",this.$c)};hte2.Ub.prototype={$c:function(a){var b;b=a.target;a=a.clientX;a-=hte2.H.Ra().offsetLeft;if(b.nodeName==="SPAN"){a-=parseInt(b.parentNode.style.paddingLeft,10);hte2.j.ee(b.parentNode,a-8)}}};
hte2.j=function(){var a,b=0,c=0,d,f=[],g;g=function(h){var j=f.length,i;for(i=0;i<j;i+=1)f[i].cf(h)};return d={Ha:function(){return b},De:function(){return c},rc:function(h){c=h;hte2.k.G("positionSet",c)},se:function(h){f.push(h)},ee:function(h,j){a=h;var i=hte2.v.T(j,true);b=i.Xc;d.rc(i.Y);g(i)},mf:function(h,j){a=h;var i=hte2.v.T(j);b=i.Xc;d.rc(i.Y);g(i)},Hd:function(){return a},Uc:function(){if(a.previousSibling.id!=="hte-cursor"){a=a.previousSibling;var h=hte2.v.T(b);hte2.k.G("positionSet",h.Y);
g(h)}},Tc:function(){if(a.nextSibling){a=a.nextSibling;var h=hte2.v.T(b);hte2.k.G("positionSet",h.Y);g(h)}},sc:function(){var h;b-=1;if(b<0){d.Uc();b=a.firstChild.firstChild.nodeValue.length}h=hte2.v.T(b);d.rc(h.Y);g(h)},ub:function(){var h,j,i=0;b+=1;h=a.childNodes;for(j=0;j<h.length;j+=1)if(h[j].firstChild)i+=h[j].firstChild.nodeValue.length;if(b>i){d.Tc();b-=i}h=hte2.v.T(b);d.rc(h.Y);g(h)},Yc:function(){g(hte2.v.T(b))}}}();
hte2.qe=function(){var a,b,c=0,d,f;a=hte2.ab("hte-cursor");setInterval(function(){a.style.display=a.style.display==="block"?"none":"block"},600);return b={fe:function(g,h){a.style.left=g+"px";a.style.top=h+"px";d=g;f=h;a.style.display="block"},Fe:function(){return{x:d,y:f}},lf:function(g){a.style.height=g+"px"},nf:function(g){c=g},wf:function(){return c},cf:function(g){b.fe(g.x,g.y);b.lf(g.height);b.nf(g.Xc)}}}();
hte2.v=function(){var a,b,c,d;a=hte2.ab("hte-measurer");b=function(){var f,g,h,j=0;for(f=hte2.j.Hd().previousSibling;f&&f.id!=="hte-cursor";){g=f.childNodes;for(h=0;h<g.length;h+=1)if(g[h].firstChild)j+=g[h].firstChild.nodeValue.length;f=f.previousSibling}return j-1};c=function(f){return f.offsetTop};d=function(f){return f.offsetHeight};return{T:function(f,g){var h=0,j,i=0,k,m,l,n,q=1,v;i=parseInt(hte2.H.Ra().style.paddingLeft,10);m=hte2.j.Hd();n=m.childNodes;j=function(){return q<f};k=function(){return i<=
f};k=g?k:j;for(j=0;j<n.length;j+=1){l=n[j].firstChild;if(l!==null)for(l=l.nodeValue;k();){a.innerHTML='<span style="'+hte2.V.xe(n[j])+'">'+l.charAt(h)+"</span>";i+=a.firstChild.offsetWidth;h+=1;q+=1;v=n[j];if(h===l.length)break}h=0}v||(v=n[0]);return{x:i+parseInt(m.style.paddingLeft,10),y:c(v),height:d(v),Xc:q,Y:b()+q}},Cb:function(f){a.innerHTML=f;return a.offsetWidth}}}();
hte2.V=function(){var a,b=hte2.xd.styling,c,d,f,g=false,h,j=hte2.xd.paragraphs;f=d={style:{fs:12,ff:"Arial",fw:"normal",fst:"normal"},start:0,end:13};c={ff:["font-family","","fontFamily"],fw:["font-weight","","fontWeight"],fs:["font-size","pt","fontSize"],td:["text-decoration","","textDecoration"],fst:["font-style","","fontStyle"]};h=function(i,k,m){var l,n;for(l=0;l<b.length;l+=1)if(b[l].start<i&&b[l].end>=i){n=b[l].end;b[l].end=i-1;b.splice(l+1,0,{style:m,start:i,end:k});b[l+2]?b.splice(l+2,0,{style:b[l].style,
start:k+1,end:b[l+2].start-1}):b.splice(l+2,0,{style:b[l].style,start:k+1,end:n})}};return a={Kd:function(){return b},Vb:function(i){var k;for(k=0;k<j.length;k+=1)if(i<j[k].end){j.splice(k+1,0,{width:j[k].width,pl:j[k].pl,pr:j[k].pr,start:i,end:j[k].end});j[k].end=i-1;break}},kf:function(i){var k,m=b;if(i){for(k=0;k<b.length;k+=1)if(b[k].start<=i-1)m=b[k];f=m.style;d=Za(m.style);g=false;hte2.k.G("styleChanged",d)}return d},we:function(i){d[i[0]]=i[1];g=true},me:function(i,k){var m,l=[];for(m=0;m<
b.length;m+=1){if(i<b[m].start&&b[m].start!==0)b[m].start+=k==="add"?1:-1;if(i<=b[m].end)b[m].end+=k==="add"?1:-1;l.push(b[m])}b=l;l=[];for(m=0;m<j.length;m+=1){if(k!=="add"&&i===j[m].start){j[m-1].end=j[m].end-1;j[m+1].start=j[m].end+1;j.splice(m,1)}if(i<j[m].start)j[m].start+=k==="add"?1:-1;if(i<=j[m].end)j[m].end+=k==="add"?1:-1;l.push(j[m])}j=l;g&&h(i+1,i+1,Za(d))},Ae:function(i){var k,m="";for(k in i)if(i.hasOwnProperty(k))m+=c[k][0]+":"+i[k]+c[k][1]+";";return m},xe:function(i){var k,m="";for(k in c)if(c.hasOwnProperty(k))if(i.style[c[k][2]])m+=
c[k][0]+":"+i.style[c[k][2]]+";";return m},Be:function(){return j},Ee:function(i){return j[i]?j[i]:j[j.length-1]},Id:function(i){var k,m=0;for(k=0;k<j.length;k+=1)if(j[k].start<=i&&i<=j[k].end){m=k;break}return j[m]},of:function(i,k,m){var l=a.Id(hte2.j.De());if(l.width!==i){l.width=i;l.pl=k;l.pr=m;hte2.k.G("rerender")}}}}();
hte2.H=function(){var a,b,c,d,f,g;a=(new zb).ab("hte-workbench");c=hte2.xd.docText.split("");f=function(){var h;h=c.join("").split("\n");h=h.join(" \n ");return h.split(" ")};d=function(h,j){var i,k;i=c.slice(0,j+1);k=c.slice(j+1);i.push(h);c=i.concat(k);hte2.V.me(j,"add")};g=hte2.V.Ae;return{pb:function(){var h=hte2.V.Kd(),j,i,k=0,m,l="",n=0,q,v,ra,r,p,kb,fa,Fd,Gd,hf=0,Ib;q=f();m=i=0;p=hte2.ld("hte-line",a);kb=false;for(j=0;j<q.length;j+=1){Ib=hte2.V.Ee(hf);b=parseInt(Ib.width,10);r=q[j]+String.fromCharCode(160);
v=n;ra=n+(r.length-1);if(r!=="\n"+String.fromCharCode(160))if(h[i].start<v&&ra<=h[i].end){fa=hte2.v.Cb('<span style="'+g(h[i].style)+'">'+r+"</span>");if(m+fa<b){m+=fa;l+=r}else{j-=1;kb=true;n-=r.length}}else if(ra>h[i].end){for(Gd="";r.length!==0;){ra-=1;r=r.split("");Gd+=r.pop();r=r.join("");if(ra===h[i].end){if(v<=h[i].start){r=r.split("");r.splice(0,h[i].start-v);r=r.join("");fa=hte2.v.Cb('<span style="'+g(h[i].style)+'">'+r+"</span>");Fd='<span style="'+g(h[i].style)+'">'+r+"</span>"}else{fa=
hte2.v.Cb('<span style="'+g(h[i].style)+'">'+r+"</span>");Fd=r+"</span>"}i+=1;j-=1;break}}v=hte2.v.Cb('<span style="'+g(h[i].style)+'">'+Gd+"</span>");if(m+(fa+v)<b){m+=fa;l+=Fd}else{i-=1;kb=true}n-=r.length}else{fa=hte2.v.Cb('<span style="'+g(h[i].style)+'">'+r.substr(h[i].start-v)+"</span>");if(m+fa<b){l+='<span style="'+g(h[i].style)+'">'+r.substr(h[i].start-v);m+=fa}else{j-=1;kb=true;n-=r.length}}else n-=2;n+=r.length;if(kb||r==="\n"+String.fromCharCode(160)){kb=false;l+="</span>";if(p.length===
0){m=(new hte2.wc(Ib.pl)).Wd;a.appendChild(m);m.innerHTML=l}else if(p[k]){p[k].style.paddingLeft=Ib.pl+"px";p[k].innerHTML=l;k+=1}else{m=(new hte2.wc(Ib.pl)).Wd;a.appendChild(m);m.innerHTML=l}l='<span style="'+g(h[i].style)+'">';m=0;if(r==="\n"+String.fromCharCode(160))hf+=1}}if(p.length!==0&&p.length>k)for(j=k;j<p.length;j+=1)p[k].parentNode&&p[k].parentNode.removeChild(p[k])},oc:function(h){c.splice(h,1);hte2.V.me(h,"remove");hte2.k.G("rerender")},Vb:function(h){d("\n",h);hte2.V.Vb(h);hte2.k.G("rerender")},
nd:function(h,j){d(String.fromCharCode(h),j);hte2.k.G("rerender")},Ra:function(){return a},Ge:function(){return c}}}();hte2.wc=function(a){var b;b=document.createElement("div");b.className="hte-line";b.style.paddingLeft=a+"px";this.Wd=b};hte2.wc.prototype={};hte2.Tb=function(){var a=new id(document);N(a,"key",this.Nc)};
hte2.Tb.prototype={Nc:function(a){var b;a.preventDefault();switch(a.keyCode){case 37:hte2.j.sc();break;case 39:hte2.j.ub();break;case 38:hte2.j.Uc();break;case 40:hte2.j.Tc();break;case 8:hte2.j.sc();hte2.H.oc(hte2.v.T(hte2.j.Ha()).Y);break;case 46:hte2.H.oc(hte2.v.T(hte2.j.Ha()).Y);break;case 13:hte2.H.Vb(hte2.v.T(hte2.j.Ha()).Y-1);hte2.j.ub();break;default:if(a.charCode!==undefined&&a.charCode!==0){b=hte2.v.T(hte2.j.Ha()).Y-1;hte2.H.nd(a.charCode,b);hte2.j.ub()}break}hte2.j.Yc()}};
hte2.re=function(){var a,b=new zb,c,d,f,g,h,j,i,k,m;c=new ve(b.e("div",{id:"hte-boldbutton"},b.createTextNode(String.fromCharCode(160))));Q(hte2.k,"styleChanged",function(l){l.fw==="bold"?Sd(c,true):Sd(c,false)});N(c,"action",function(){U(c,16)?hte2.k.G("updateComputedStyle",["fw","bold"]):hte2.k.G("updateComputedStyle",["fw","normal"])});d=new ve(b.e("div",{id:"hte-italicbutton"},b.createTextNode(String.fromCharCode(160))));Q(hte2.k,"styleChanged",function(l){l.fst==="italic"?Sd(d,true):Sd(d,false)});
N(d,"action",function(){U(d,16)?hte2.k.G("updateComputedStyle",["fst","italic"]):hte2.k.G("updateComputedStyle",["fst","normal"])});g=new ve(b.e("div",{id:"hte-underlinebutton"},b.createTextNode(String.fromCharCode(160))));Q(hte2.k,"styleChanged",function(l){l.td==="underline"?Sd(g,true):Sd(g,false)});N(g,"action",function(){U(g,16)?hte2.k.G("updateComputedStyle",["td","underline"]):hte2.k.G("updateComputedStyle",["td","none"])});h=new ve(b.e("div",{id:"hte-linethroughbutton"},b.createTextNode(String.fromCharCode(160))));
Q(hte2.k,"styleChanged",function(l){l.td==="line-through"?Sd(h,true):Sd(h,false)});N(h,"action",function(){U(h,16)?hte2.k.G("updateComputedStyle",["td","line-through"]):hte2.k.G("updateComputedStyle",["td","none"])});j=new We("");j.I(new Y("8"));j.I(new Y("10"));j.I(new Y("11"));j.I(new Y("12"));j.I(new Y("14"));j.I(new Y("18"));j.I(new Y("24"));j.I(new Y("36"));j.u("12");Q(hte2.k,"styleChanged",function(l){j.u(l.fs)});N(j,"action",function(){hte2.k.G("updateComputedStyle",["fs",j.n()])});i=new We("");
i.I(new Y("Arial"));i.I(new Y("Courier new"));i.I(new Y("Times New Roman"));i.u("Arial");Q(hte2.k,"styleChanged",function(l){i.u(l.ff)});N(i,"action",function(){hte2.k.G("updateComputedStyle",["ff",i.n()])});f=new we(b.e("div",{id:"hte-savebutton"},b.createTextNode("Save")));N(f,"action",function(){var l={docText:hte2.H.Ge().join(""),styling:hte2.V.Kd(),paragraphs:hte2.V.Be()};console.log($c(new Zc,l))});a=new me;a.da(f,true);a.da(c,true);a.da(d,true);a.da(g,true);a.da(h,true);a.da(j,true);a.da(i,
true);a.pb(b.ab("hte-panel"));k=new Jf;k.e();a=k.a();a.style.width="100%";a.style.height="10px";k.ed(1);m=parseInt(hte2.H.Ra().style.width,10)/100;k.addEventListener("change",function(){var l,n;l=k.n()*m;n=(k.n()+k.Aa())*m;hte2.k.G("pWidth",n-l,l,n)});k.pb(b.ab("hte-slider"));return{qf:function(l){l=hte2.V.Id(l);Hf(k,l.pl/m,(l.pr-l.pl)/m)}}}();
(function(){var a=new Dc,b;b=function(){var c=a.Jd().height-60;Tc(y("hte-workbench-container")?document.getElementById("hte-workbench-container"):"hte-workbench-container",c)};b();N(a,"resize",function(){b()});hte2.H.pb();hte2.j.se(hte2.qe);hte2.j.mf(hte2.ld("hte-line",hte2.H.Ra())[0],1);new hte2.Ub;new hte2.Tb;Q(hte2.k,"rerender",hte2.H.pb);Q(hte2.k,"rangeReady",hte2.V.rf);Q(hte2.k,"positionSet",hte2.V.kf);Q(hte2.k,"positionSet",hte2.re.qf);Q(hte2.k,"updateComputedStyle",hte2.V.we);Q(hte2.k,"pWidth",
hte2.V.of);Q(hte2.k,"pWidth",hte2.j.Yc)})();
