function aa(){return function(){}}function ba(a){return function(b){this[a]=b}}function e(a){return function(){return this[a]}}function n(a){return function(){return a}}var s,ca=ca||{},t=this;function da(a,b){for(var c=a.split("."),d=b||t,f;f=c.shift();)if(d[f])d=d[f];else return null;return d}function u(){}function w(a){a.W=function(){return a.yf||(a.yf=new a)}}
function ea(a){var b=typeof a;if(b=="object")if(a){if(a instanceof Array||!(a instanceof Object)&&Object.prototype.toString.call(a)=="[object Array]"||typeof a.length=="number"&&typeof a.splice!="undefined"&&typeof a.propertyIsEnumerable!="undefined"&&!a.propertyIsEnumerable("splice"))return"array";if(!(a instanceof Object)&&(Object.prototype.toString.call(a)=="[object Function]"||typeof a.call!="undefined"&&typeof a.propertyIsEnumerable!="undefined"&&!a.propertyIsEnumerable("call")))return"function"}else return"null";
else if(b=="function"&&typeof a.call=="undefined")return"object";return b}function x(a){return ea(a)=="array"}function fa(a){var b=ea(a);return b=="array"||b=="object"&&typeof a.length=="number"}function y(a){return typeof a=="string"}function ga(a){return typeof a=="number"}function ha(a){return ea(a)=="function"}function ia(a){a=ea(a);return a=="object"||a=="array"||a=="function"}function z(a){if(a.hasOwnProperty&&a.hasOwnProperty(ka))return a[ka];a[ka]||(a[ka]=++la);return a[ka]}
var ka="closure_uid_"+Math.floor(Math.random()*2147483648).toString(36),la=0;function ma(a,b){var c=b||t;if(arguments.length>2){var d=Array.prototype.slice.call(arguments,2);return function(){var f=Array.prototype.slice.call(arguments);Array.prototype.unshift.apply(f,d);return a.apply(c,f)}}else return function(){return a.apply(c,arguments)}}
function na(a){var b=Array.prototype.slice.call(arguments,1);return function(){var c=Array.prototype.slice.call(arguments);c.unshift.apply(c,b);return a.apply(this,c)}}var oa=Date.now||function(){return+new Date};function A(a,b){function c(){}c.prototype=b.prototype;a.a=b.prototype;a.prototype=new c;a.prototype.constructor=a}function pa(a){this.stack=Error().stack||"";if(a)this.message=String(a)}A(pa,Error);pa.prototype.name="CustomError";
function qa(a){for(var b=1;b<arguments.length;b++){var c=String(arguments[b]).replace(/\$/g,"$$$$");a=a.replace(/\%s/,c)}return a}function ra(a){return a.replace(/^[\s\xa0]+|[\s\xa0]+$/g,"")}
function sa(a,b){if(b)return a.replace(ua,"&amp;").replace(va,"&lt;").replace(wa,"&gt;").replace(xa,"&quot;");else{if(!ya.test(a))return a;if(a.indexOf("&")!=-1)a=a.replace(ua,"&amp;");if(a.indexOf("<")!=-1)a=a.replace(va,"&lt;");if(a.indexOf(">")!=-1)a=a.replace(wa,"&gt;");if(a.indexOf('"')!=-1)a=a.replace(xa,"&quot;");return a}}var ua=/&/g,va=/</g,wa=/>/g,xa=/\"/g,ya=/[&<>\"]/;
function za(a,b){for(var c=0,d=ra(String(a)).split("."),f=ra(String(b)).split("."),g=Math.max(d.length,f.length),h=0;c==0&&h<g;h++){var j=d[h]||"",i=f[h]||"",k=RegExp("(\\d*)(\\D*)","g"),m=RegExp("(\\d*)(\\D*)","g");do{var l=k.exec(j)||["","",""],o=m.exec(i)||["","",""];if(l[0].length==0&&o[0].length==0)break;c=Aa(l[1].length==0?0:parseInt(l[1],10),o[1].length==0?0:parseInt(o[1],10))||Aa(l[2].length==0,o[2].length==0)||Aa(l[2],o[2])}while(c==0)}return c}
function Aa(a,b){if(a<b)return-1;else if(a>b)return 1;return 0}function Ba(a,b){b.unshift(a);pa.call(this,qa.apply(null,b));b.shift();this.fg=a}A(Ba,pa);Ba.prototype.name="AssertionError";function Ca(a,b){if(!a){var c=Array.prototype.slice.call(arguments,2),d="Assertion failed";if(b){d+=": "+b;var f=c}throw new Ba(""+d,f||[]);}}function Da(a){throw new Ba("Failure"+(a?": "+a:""),Array.prototype.slice.call(arguments,1));}
var B=Array.prototype,Ea=B.indexOf?function(a,b,c){Ca(a.length!=null);return B.indexOf.call(a,b,c)}:function(a,b,c){c=c==null?0:c<0?Math.max(0,a.length+c):c;if(y(a)){if(!y(b)||b.length!=1)return-1;return a.indexOf(b,c)}for(c=c;c<a.length;c++)if(c in a&&a[c]===b)return c;return-1},C=B.forEach?function(a,b,c){Ca(a.length!=null);B.forEach.call(a,b,c)}:function(a,b,c){for(var d=a.length,f=y(a)?a.split(""):a,g=0;g<d;g++)g in f&&b.call(c,f[g],g,a)},Fa=B.map?function(a,b,c){Ca(a.length!=null);return B.map.call(a,
b,c)}:function(a,b,c){for(var d=a.length,f=Array(d),g=y(a)?a.split(""):a,h=0;h<d;h++)if(h in g)f[h]=b.call(c,g[h],h,a);return f},Ga=B.every?function(a,b,c){Ca(a.length!=null);return B.every.call(a,b,c)}:function(a,b,c){for(var d=a.length,f=y(a)?a.split(""):a,g=0;g<d;g++)if(g in f&&!b.call(c,f[g],g,a))return false;return true};function Ha(a,b){return Ea(a,b)>=0}function Ia(a,b){var c=Ea(a,b),d;if(d=c>=0){Ca(a.length!=null);B.splice.call(a,c,1)}return d}
function Ja(){return B.concat.apply(B,arguments)}function Ka(a){if(x(a))return Ja(a);else{for(var b=[],c=0,d=a.length;c<d;c++)b[c]=a[c];return b}}function La(a){for(var b=1;b<arguments.length;b++){var c=arguments[b],d;if(x(c)||(d=fa(c))&&c.hasOwnProperty("callee"))a.push.apply(a,c);else if(d)for(var f=a.length,g=c.length,h=0;h<g;h++)a[f+h]=c[h];else a.push(c)}}function Ma(a){Ca(a.length!=null);return B.splice.apply(a,Na(arguments,1))}
function Na(a,b,c){Ca(a.length!=null);return arguments.length<=2?B.slice.call(a,b):B.slice.call(a,b,c)}var Oa;function Pa(a){return(a=a.className)&&typeof a.split=="function"?a.split(/\s+/):[]}function Qa(a){var b=Pa(a),c;c=Na(arguments,1);for(var d=0,f=0;f<c.length;f++)if(!Ha(b,c[f])){b.push(c[f]);d++}c=d==c.length;a.className=b.join(" ");return c}
function Ra(a){var b=Pa(a),c;c=Na(arguments,1);for(var d=0,f=0;f<b.length;f++)if(Ha(c,b[f])){Ma(b,f--,1);d++}c=d==c.length;a.className=b.join(" ");return c}function D(a,b){this.x=a!==undefined?a:0;this.y=b!==undefined?b:0}D.prototype.Ja=function(){return new D(this.x,this.y)};D.prototype.toString=function(){return"("+this.x+", "+this.y+")"};function Sa(a,b){return new D(a.x-b.x,a.y-b.y)}function E(a,b){this.width=a;this.height=b}
function Ta(a,b){if(a==b)return true;if(!a||!b)return false;return a.width==b.width&&a.height==b.height}E.prototype.Ja=function(){return new E(this.width,this.height)};E.prototype.toString=function(){return"("+this.width+" x "+this.height+")"};E.prototype.floor=function(){this.width=Math.floor(this.width);this.height=Math.floor(this.height);return this};E.prototype.round=function(){this.width=Math.round(this.width);this.height=Math.round(this.height);return this};
function Ua(a,b,c){for(var d in a)b.call(c,a[d],d,a)}function Va(a){var b=[],c=0;for(var d in a)b[c++]=a[d];return b}function Wa(a){var b=[],c=0;for(var d in a)b[c++]=d;return b}function Xa(a){for(var b in a)return false;return true}function Ya(a,b){var c;if(c=b in a)delete a[b];return c}function Za(a,b,c){if(b in a)throw Error('The object already contains the key "'+b+'"');a[b]=c}function $a(a){var b={};for(var c in a)b[c]=a[c];return b}
var ab=["constructor","hasOwnProperty","isPrototypeOf","propertyIsEnumerable","toLocaleString","toString","valueOf"];function bb(a){for(var b,c,d=1;d<arguments.length;d++){c=arguments[d];for(b in c)a[b]=c[b];for(var f=0;f<ab.length;f++){b=ab[f];if(Object.prototype.hasOwnProperty.call(c,b))a[b]=c[b]}}}
function cb(){var a=arguments.length;if(a==1&&x(arguments[0]))return cb.apply(null,arguments[0]);if(a%2)throw Error("Uneven number of arguments");for(var b={},c=0;c<a;c+=2)b[arguments[c]]=arguments[c+1];return b}var db,eb,fb,gb,hb,ib,jb;function kb(){return t.navigator?t.navigator.userAgent:null}function lb(){return t.navigator}hb=gb=fb=eb=db=false;var mb;
if(mb=kb()){var nb=lb();db=mb.indexOf("Opera")==0;eb=!db&&mb.indexOf("MSIE")!=-1;gb=(fb=!db&&mb.indexOf("WebKit")!=-1)&&mb.indexOf("Mobile")!=-1;hb=!db&&!fb&&nb.product=="Gecko"}var ob=db,F=eb,G=hb,H=fb,pb=gb,qb,sb=lb();qb=sb&&sb.platform||"";ib=qb.indexOf("Mac")!=-1;jb=qb.indexOf("Win")!=-1;var tb=!!lb()&&(lb().appVersion||"").indexOf("X11")!=-1,ub,vb="",wb;
if(ob&&t.opera){var xb=t.opera.version;vb=typeof xb=="function"?xb():xb}else{if(G)wb=/rv\:([^\);]+)(\)|;)/;else if(F)wb=/MSIE\s+([^\);]+)(\)|;)/;else if(H)wb=/WebKit\/(\S+)/;if(wb){var yb=wb.exec(kb());vb=yb?yb[1]:""}}ub=vb;var zb={};function I(a){return zb[a]||(zb[a]=za(ub,a)>=0)}function J(a){return a?new Ab(K(a)):Oa||(Oa=new Ab)}
function Bb(a,b,c,d){a=d||a;b=b&&b!="*"?b.toUpperCase():"";if(a.querySelectorAll&&a.querySelector&&(!H||Cb(document)||I("528"))&&(b||c))return a.querySelectorAll(b+(c?"."+c:""));if(c&&a.getElementsByClassName){a=a.getElementsByClassName(c);if(b){d={};for(var f=0,g=0,h;h=a[g];g++)if(b==h.nodeName)d[f++]=h;d.length=f;return d}else return a}a=a.getElementsByTagName(b||"*");if(c){d={};for(g=f=0;h=a[g];g++){b=h.className;if(typeof b.split=="function"&&Ha(b.split(/\s+/),c))d[f++]=h}d.length=f;return d}else return a}
function Db(a,b){Ua(b,function(c,d){if(d=="style")a.style.cssText=c;else if(d=="class")a.className=c;else if(d=="for")a.htmlFor=c;else if(d in Eb)a.setAttribute(Eb[d],c);else a[d]=c})}var Eb={cellpadding:"cellPadding",cellspacing:"cellSpacing",colspan:"colSpan",rowspan:"rowSpan",valign:"vAlign",height:"height",width:"width",usemap:"useMap",frameborder:"frameBorder",type:"type"};
function Fb(a){var b=a.document;if(H&&!I("500")&&!pb){if(typeof a.innerHeight=="undefined")a=window;b=a.innerHeight;var c=a.document.documentElement.scrollHeight;if(a==a.top)if(c<b)b-=15;return new E(a.innerWidth,b)}a=Cb(b);if(ob&&!I("9.50"))a=false;a=a?b.documentElement:b.body;return new E(a.clientWidth,a.clientHeight)}function Gb(a,b,c,d){function f(h){if(h)b.appendChild(y(h)?a.createTextNode(h):h)}for(d=d;d<c.length;d++){var g=c[d];fa(g)&&!(ia(g)&&g.nodeType>0)?C(Hb(g)?Ka(g):g,f):f(g)}}
function Cb(a){return a.compatMode=="CSS1Compat"}function Ib(a){for(var b;b=a.firstChild;)a.removeChild(b)}function Jb(a){return a&&a.parentNode?a.parentNode.removeChild(a):null}function Kb(a){for(a=a.firstChild;a&&a.nodeType!=1;)a=a.nextSibling;return a}function Lb(a,b){if(a.contains&&b.nodeType==1)return a==b||a.contains(b);if(typeof a.compareDocumentPosition!="undefined")return a==b||Boolean(a.compareDocumentPosition(b)&16);for(;b&&a!=b;)b=b.parentNode;return b==a}
function K(a){return a.nodeType==9?a:a.ownerDocument||a.document}function Mb(a,b){if("textContent"in a)a.textContent=b;else if(a.firstChild&&a.firstChild.nodeType==3){for(;a.lastChild!=a.firstChild;)a.removeChild(a.lastChild);a.firstChild.data=b}else{Ib(a);a.appendChild(K(a).createTextNode(b))}}var Nb={SCRIPT:1,STYLE:1,HEAD:1,IFRAME:1,OBJECT:1},Ob={IMG:" ",BR:"\n"};function Pb(a){var b=a.getAttributeNode("tabindex");if(b&&b.specified){a=a.tabIndex;return ga(a)&&a>=0}return false}
function Qb(a){if(F&&"innerText"in a)a=a.innerText.replace(/(\r\n|\r|\n)/g,"\n");else{var b=[];Rb(a,b,true);a=b.join("")}a=a.replace(/\xAD/g,"");a=a.replace(/ +/g," ");if(a!=" ")a=a.replace(/^\s*/,"");return a}function Rb(a,b,c){if(!(a.nodeName in Nb))if(a.nodeType==3)c?b.push(String(a.nodeValue).replace(/(\r\n|\r|\n)/g,"")):b.push(a.nodeValue);else if(a.nodeName in Ob)b.push(Ob[a.nodeName]);else for(a=a.firstChild;a;){Rb(a,b,c);a=a.nextSibling}}
function Hb(a){if(a&&typeof a.length=="number")if(ia(a))return typeof a.item=="function"||typeof a.item=="string";else if(ha(a))return typeof a.item=="function";return false}function Ab(a){this.m=a||t.document||document}s=Ab.prototype;s.C=J;function Tb(a){return a.m}s.b=function(a){return y(a)?this.m.getElementById(a):a};s.ib=Ab.prototype.b;
s.f=function(){var a=this.m,b=arguments,c=b[0],d=b[1];if(F&&d&&(d.name||d.type)){c=["<",c];d.name&&c.push(' name="',sa(d.name),'"');if(d.type){c.push(' type="',sa(d.type),'"');var f={};bb(f,d);d=f;delete d.type}c.push(">");c=c.join("")}c=a.createElement(c);if(d)if(y(d))c.className=d;else x(d)?Qa.apply(null,[c].concat(d)):Db(c,d);b.length>2&&Gb(a,c,b,2);return c};s.createElement=function(a){return this.m.createElement(a)};s.createTextNode=function(a){return this.m.createTextNode(a)};
function Ub(a){a=!H&&Cb(a.m)?a.m.documentElement:a.m.body;return new D(a.scrollLeft,a.scrollTop)}s.appendChild=function(a,b){a.appendChild(b)};s.ee=Kb;s.contains=Lb;var Vb=[];function Wb(){}Wb.prototype.Sc=false;Wb.prototype.B=function(){if(!this.Sc){this.Sc=true;this.c()}};Wb.prototype.c=aa();var Xb;function L(a,b){this.type=a;this.currentTarget=this.target=b}A(L,Wb);s=L.prototype;s.c=function(){delete this.type;delete this.target;delete this.currentTarget};s.db=false;s.Zb=true;
s.stopPropagation=function(){this.db=true};s.preventDefault=function(){this.Zb=false};function Yb(a){a.preventDefault()}function Zb(a,b){a&&this.rb(a,b)}A(Zb,L);var $b=[1,4,2];s=Zb.prototype;s.target=null;s.relatedTarget=null;s.offsetX=0;s.offsetY=0;s.clientX=0;s.clientY=0;s.screenX=0;s.screenY=0;s.button=0;s.keyCode=0;s.charCode=0;s.ctrlKey=false;s.altKey=false;s.shiftKey=false;s.metaKey=false;s.Jf=false;s.wa=null;
s.rb=function(a,b){var c=this.type=a.type;this.target=a.target||a.srcElement;this.currentTarget=b;var d=a.relatedTarget;if(d){if(G)try{d=d.nodeName&&d}catch(f){d=null}}else if(c=="mouseover")d=a.fromElement;else if(c=="mouseout")d=a.toElement;this.relatedTarget=d;this.offsetX=a.offsetX!==undefined?a.offsetX:a.layerX;this.offsetY=a.offsetY!==undefined?a.offsetY:a.layerY;this.clientX=a.clientX!==undefined?a.clientX:a.pageX;this.clientY=a.clientY!==undefined?a.clientY:a.pageY;this.screenX=a.screenX||
0;this.screenY=a.screenY||0;this.button=a.button;this.keyCode=a.keyCode||0;this.charCode=a.charCode||(c=="keypress"?a.keyCode:0);this.ctrlKey=a.ctrlKey;this.altKey=a.altKey;this.shiftKey=a.shiftKey;this.metaKey=a.metaKey;this.Jf=ib?a.metaKey:a.ctrlKey;this.wa=a;delete this.Zb;delete this.db};function ac(a,b){return F?a.type=="click"?b==0:!!(a.wa.button&$b[b]):a.wa.button==b}
s.stopPropagation=function(){Zb.a.stopPropagation.call(this);if(this.wa.stopPropagation)this.wa.stopPropagation();else this.wa.cancelBubble=true};var bc=F&&!I("8");Zb.prototype.preventDefault=function(){Zb.a.preventDefault.call(this);var a=this.wa;if(a.preventDefault)a.preventDefault();else{a.returnValue=false;if(bc)try{if(a.ctrlKey||a.keyCode>=112&&a.keyCode<=123)a.keyCode=-1}catch(b){}}};Zb.prototype.c=function(){Zb.a.c.call(this);this.relatedTarget=this.currentTarget=this.target=this.wa=null};
function cc(){}var dc=0;s=cc.prototype;s.key=0;s.vb=false;s.Sd=false;s.rb=function(a,b,c,d,f,g){if(ha(a))this.re=true;else if(a&&a.handleEvent&&ha(a.handleEvent))this.re=false;else throw Error("Invalid listener argument");this.tb=a;this.Ce=b;this.src=c;this.type=d;this.capture=!!f;this.rc=g;this.Sd=false;this.key=++dc;this.vb=false};s.handleEvent=function(a){if(this.re)return this.tb.call(this.rc||this.src,a);return this.tb.handleEvent.call(this.tb,a)};
function ec(a,b){this.xe=b;this.Wa=[];if(a>this.xe)throw Error("[goog.structs.SimplePool] Initial cannot be greater than max");for(var c=0;c<a;c++)this.Wa.push(this.Ca?this.Ca():{})}A(ec,Wb);ec.prototype.Ca=null;ec.prototype.Xd=null;function fc(a){if(a.Wa.length)return a.Wa.pop();return a.Ca?a.Ca():{}}function gc(a,b){a.Wa.length<a.xe?a.Wa.push(b):hc(a,b)}function hc(a,b){if(a.Xd)a.Xd(b);else if(ia(b))if(ha(b.B))b.B();else for(var c in b)delete b[c]}
ec.prototype.c=function(){ec.a.c.call(this);for(var a=this.Wa;a.length;)hc(this,a.pop());delete this.Wa};var ic;var jc=(ic="ScriptEngine"in t&&t.ScriptEngine()=="JScript")?t.ScriptEngineMajorVersion()+"."+t.ScriptEngineMinorVersion()+"."+t.ScriptEngineBuildVersion():"0",kc,lc,mc,nc,oc,pc,qc,rc,sc,tc,uc;
(function(){function a(){return{Y:0,ra:0}}function b(){return[]}function c(){function o(q){return h.call(o.src,o.key,q)}return o}function d(){return new cc}function f(){return new Zb}var g=ic&&!(za(jc,"5.7")>=0),h;pc=function(o){h=o};if(g){kc=function(){return fc(j)};lc=function(o){gc(j,o)};mc=function(){return fc(i)};nc=function(o){gc(i,o)};oc=function(){return fc(k)};qc=function(){gc(k,c())};rc=function(){return fc(m)};sc=function(o){gc(m,o)};tc=function(){return fc(l)};uc=function(o){gc(l,o)};
var j=new ec(0,600);j.Ca=a;var i=new ec(0,600);i.Ca=b;var k=new ec(0,600);k.Ca=c;var m=new ec(0,600);m.Ca=d;var l=new ec(0,600);l.Ca=f}else{kc=a;lc=u;mc=b;nc=u;oc=c;qc=u;rc=d;sc=u;tc=f;uc=u}})();var vc={},M={},wc={},xc={};
function N(a,b,c,d,f){if(b)if(x(b)){for(var g=0;g<b.length;g++)N(a,b[g],c,d,f);return null}else{d=!!d;var h=M;b in h||(h[b]=kc());h=h[b];if(!(d in h)){h[d]=kc();h.Y++}h=h[d];var j=z(a),i;h.ra++;if(h[j]){i=h[j];for(g=0;g<i.length;g++){h=i[g];if(h.tb==c&&h.rc==f){if(h.vb)break;return i[g].key}}}else{i=h[j]=mc();h.Y++}g=oc();g.src=a;h=rc();h.rb(c,g,a,b,d,f);c=h.key;g.key=c;i.push(h);vc[c]=h;wc[j]||(wc[j]=mc());wc[j].push(h);if(a.addEventListener){if(a==t||!a.Wd)a.addEventListener(b,g,d)}else a.attachEvent(yc(b),
g);return c}else throw Error("Invalid event type");}function zc(a,b,c,d,f){if(x(b)){for(var g=0;g<b.length;g++)zc(a,b[g],c,d,f);return null}d=!!d;a=Ac(a,b,d);if(!a)return false;for(g=0;g<a.length;g++)if(a[g].tb==c&&a[g].capture==d&&a[g].rc==f)return O(a[g].key);return false}
function O(a){if(!vc[a])return false;var b=vc[a];if(b.vb)return false;var c=b.src,d=b.type,f=b.Ce,g=b.capture;if(c.removeEventListener){if(c==t||!c.Wd)c.removeEventListener(d,f,g)}else c.detachEvent&&c.detachEvent(yc(d),f);c=z(c);f=M[d][g][c];if(wc[c]){var h=wc[c];Ia(h,b);h.length==0&&delete wc[c]}b.vb=true;f.Ae=true;Bc(d,g,c,f);delete vc[a];return true}
function Bc(a,b,c,d){if(!d.xc)if(d.Ae){for(var f=0,g=0;f<d.length;f++)if(d[f].vb){var h=d[f].Ce;h.src=null;qc(h);sc(d[f])}else{if(f!=g)d[g]=d[f];g++}d.length=g;d.Ae=false;if(g==0){nc(d);delete M[a][b][c];M[a][b].Y--;if(M[a][b].Y==0){lc(M[a][b]);delete M[a][b];M[a].Y--}if(M[a].Y==0){lc(M[a]);delete M[a]}}}}
function Cc(a,b,c){var d=0,f=a==null,g=b==null,h=c==null;c=!!c;if(f)Ua(wc,function(i){for(var k=i.length-1;k>=0;k--){var m=i[k];if((g||b==m.type)&&(h||c==m.capture)){O(m.key);d++}}});else{a=z(a);if(wc[a]){a=wc[a];for(f=a.length-1;f>=0;f--){var j=a[f];if((g||b==j.type)&&(h||c==j.capture)){O(j.key);d++}}}}return d}function Ac(a,b,c){var d=M;if(b in d){d=d[b];if(c in d){d=d[c];a=z(a);if(d[a])return d[a]}}return null}function yc(a){if(a in xc)return xc[a];return xc[a]="on"+a}
function Dc(a,b,c,d,f){var g=1;b=z(b);if(a[b]){a.ra--;a=a[b];if(a.xc)a.xc++;else a.xc=1;try{for(var h=a.length,j=0;j<h;j++){var i=a[j];if(i&&!i.vb)g&=Ec(i,f)!==false}}finally{a.xc--;Bc(c,d,b,a)}}return Boolean(g)}function Ec(a,b){var c=a.handleEvent(b);a.Sd&&O(a.key);return c}
function Fc(a,b){if(!vc[a])return true;var c=vc[a],d=c.type,f=M;if(!(d in f))return true;f=f[d];var g,h;if(Xb===undefined)Xb=F&&!t.addEventListener;if(Xb){g=b||da("window.event");var j=true in f,i=false in f;if(j){if(g.keyCode<0||g.returnValue!=undefined)return true;a:{var k=false;if(g.keyCode==0)try{g.keyCode=-1;break a}catch(m){k=true}if(k||g.returnValue==undefined)g.returnValue=true}}k=tc();k.rb(g,this);g=true;try{if(j){for(var l=mc(),o=k.currentTarget;o;o=o.parentNode)l.push(o);h=f[true];h.ra=
h.Y;for(var q=l.length-1;!k.db&&q>=0&&h.ra;q--){k.currentTarget=l[q];g&=Dc(h,l[q],d,true,k)}if(i){h=f[false];h.ra=h.Y;for(q=0;!k.db&&q<l.length&&h.ra;q++){k.currentTarget=l[q];g&=Dc(h,l[q],d,false,k)}}}else g=Ec(c,k)}finally{if(l){l.length=0;nc(l)}k.B();uc(k)}return g}d=new Zb(b,this);try{g=Ec(c,d)}finally{d.B()}return g}pc(Fc);Vb[Vb.length]=function(a){Fc=a.Xf(Fc);pc(Fc)};function P(){}A(P,Wb);s=P.prototype;s.Wd=true;s.Bc=null;s.Dd=ba("Bc");s.addEventListener=function(a,b,c,d){N(this,a,b,c,d)};
s.removeEventListener=function(a,b,c,d){zc(this,a,b,c,d)};
s.dispatchEvent=function(a){a=a;if(y(a))a=new L(a,this);else if(a instanceof L)a.target=a.target||this;else{var b=a;a=new L(a.type,this);bb(a,b)}b=1;var c,d=a.type,f=M;if(d in f){f=f[d];d=true in f;var g;if(d){c=[];for(g=this;g;g=g.Bc)c.push(g);g=f[true];g.ra=g.Y;for(var h=c.length-1;!a.db&&h>=0&&g.ra;h--){a.currentTarget=c[h];b&=Dc(g,c[h],a.type,true,a)&&a.Zb!=false}}if(false in f){g=f[false];g.ra=g.Y;if(d)for(h=0;!a.db&&h<c.length&&g.ra;h++){a.currentTarget=c[h];b&=Dc(g,c[h],a.type,false,a)&&a.Zb!=
false}else for(c=this;!a.db&&c&&g.ra;c=c.Bc){a.currentTarget=c;b&=Dc(g,c,a.type,false,a)&&a.Zb!=false}}a=Boolean(b)}else a=true;return a};s.c=function(){P.a.c.call(this);Cc(this);this.Bc=null};function Gc(a){this.hb=a||window;this.wc=N(this.hb,"resize",this.uf,false,this);this.zb=Fb(this.hb||window);if(H&&jb||ob&&this.hb.self!=this.hb.top)this.Lc=window.setInterval(ma(this.Ud,this),Hc)}A(Gc,P);var Hc=500;s=Gc.prototype;s.wc=null;s.hb=null;s.zb=null;s.Lc=null;
s.he=function(){return this.zb?this.zb.Ja():null};s.c=function(){Gc.a.c.call(this);if(this.wc){O(this.wc);this.wc=null}if(this.Lc){window.clearInterval(this.Lc);this.Lc=null}this.zb=this.hb=null};s.uf=function(){this.Ud()};s.Ud=function(){var a=Fb(this.hb||window);if(!Ta(a,this.zb)){this.zb=a;this.dispatchEvent("resize")}};function Ic(a,b,c,d){this.top=a;this.right=b;this.bottom=c;this.left=d}Ic.prototype.Ja=function(){return new Ic(this.top,this.right,this.bottom,this.left)};
Ic.prototype.toString=function(){return"("+this.top+"t, "+this.right+"r, "+this.bottom+"b, "+this.left+"l)"};Ic.prototype.contains=function(a){return!this||!a?false:a instanceof Ic?a.left>=this.left&&a.right<=this.right&&a.top>=this.top&&a.bottom<=this.bottom:a.x>=this.left&&a.x<=this.right&&a.y>=this.top&&a.y<=this.bottom};function Jc(a,b,c,d){this.left=a;this.top=b;this.width=c;this.height=d}Jc.prototype.Ja=function(){return new Jc(this.left,this.top,this.width,this.height)};
Jc.prototype.toString=function(){return"("+this.left+", "+this.top+" - "+this.width+"w x "+this.height+"h)"};Jc.prototype.contains=function(a){return a instanceof Jc?this.left<=a.left&&this.left+this.width>=a.left+a.width&&this.top<=a.top&&this.top+this.height>=a.top+a.height:a.x>=this.left&&a.x<=this.left+this.width&&a.y>=this.top&&a.y<=this.top+this.height};Jc.prototype.he=function(){return new E(this.width,this.height)};
function Kc(a,b){var c=K(a);if(c.defaultView&&c.defaultView.getComputedStyle)if(c=c.defaultView.getComputedStyle(a,""))return c[b];return null}function Lc(a,b){return Kc(a,b)||(a.currentStyle?a.currentStyle[b]:null)||a.style[b]}function Mc(a,b,c){var d,f=G&&(ib||tb)&&I("1.9");if(b instanceof D){d=b.x;b=b.y}else{d=b;b=c}Nc("left",f,a,d);Nc("top",f,a,b)}
function Oc(a){var b=a.getBoundingClientRect();if(F){a=a.ownerDocument;b.left-=a.documentElement.clientLeft+a.body.clientLeft;b.top-=a.documentElement.clientTop+a.body.clientTop}return b}
function Pc(a){if(F)return a.offsetParent;var b=K(a),c=Lc(a,"position"),d=c=="fixed"||c=="absolute";for(a=a.parentNode;a&&a!=b;a=a.parentNode){c=Lc(a,"position");d=d&&c=="static"&&a!=b.documentElement&&a!=b.body;if(!d&&(a.scrollWidth>a.clientWidth||a.scrollHeight>a.clientHeight||c=="fixed"||c=="absolute"))return a}return null}
function Qc(a){var b=new Ic(0,Infinity,Infinity,0),c=J(a),d=c.m.body,f=!H&&Cb(c.m)?c.m.documentElement:c.m.body,g;for(a=a;a=Pc(a);)if((!F||a.clientWidth!=0)&&(!H||a.clientHeight!=0||a!=d)&&(a.scrollWidth!=a.clientWidth||a.scrollHeight!=a.clientHeight)&&Lc(a,"overflow")!="visible"){var h=Rc(a),j;j=a;if(G&&!I("1.9")){var i=parseFloat(Kc(j,"borderLeftWidth"));if(Sc(j)){var k=j.offsetWidth-j.clientWidth-i-parseFloat(Kc(j,"borderRightWidth"));i+=k}j=new D(i,parseFloat(Kc(j,"borderTopWidth")))}else j=new D(j.clientLeft,
j.clientTop);h.x+=j.x;h.y+=j.y;b.top=Math.max(b.top,h.y);b.right=Math.min(b.right,h.x+a.clientWidth);b.bottom=Math.min(b.bottom,h.y+a.clientHeight);b.left=Math.max(b.left,h.x);g=g||a!=f}d=f.scrollLeft;f=f.scrollTop;if(H){b.left+=d;b.top+=f}else{b.left=Math.max(b.left,d);b.top=Math.max(b.top,f)}if(!g||H){b.right+=d;b.bottom+=f}c=Fb(c.m.parentWindow||c.m.defaultView||window);b.right=Math.min(b.right,d+c.width);b.bottom=Math.min(b.bottom,f+c.height);return b.top>=0&&b.left>=0&&b.bottom>b.top&&b.right>
b.left?b:null}
function Rc(a){var b,c=K(a),d=Lc(a,"position"),f=G&&c.getBoxObjectFor&&!a.getBoundingClientRect&&d=="absolute"&&(b=c.getBoxObjectFor(a))&&(b.screenX<0||b.screenY<0),g=new D(0,0),h;b=c?c.nodeType==9?c:K(c):document;if(h=F){h=J(b);h=!Cb(h.m)}h=h?b.body:b.documentElement;if(a==h)return g;if(a.getBoundingClientRect){b=Oc(a);a=Ub(J(c));g.x=b.left+a.x;g.y=b.top+a.y}else if(c.getBoxObjectFor&&!f){b=c.getBoxObjectFor(a);a=c.getBoxObjectFor(h);g.x=b.screenX-a.screenX;g.y=b.screenY-a.screenY}else{f=a;do{g.x+=
f.offsetLeft;g.y+=f.offsetTop;if(f!=a){g.x+=f.clientLeft||0;g.y+=f.clientTop||0}if(H&&Lc(f,"position")=="fixed"){g.x+=c.body.scrollLeft;g.y+=c.body.scrollTop;break}f=f.offsetParent}while(f&&f!=a);if(ob||H&&d=="absolute")g.y-=c.body.offsetTop;for(f=a;(f=Pc(f))&&f!=c.body&&f!=h;){g.x-=f.scrollLeft;if(!ob||f.tagName!="TR")g.y-=f.scrollTop}}return g}
function Tc(a){var b=new D;if(a.nodeType==1)if(a.getBoundingClientRect){var c=Oc(a);b.x=c.left;b.y=c.top}else{c=Ub(J(a));a=Rc(a);b.x=a.x-c.x;b.y=a.y-c.y}else{b.x=a.clientX;b.y=a.clientY}return b}function Uc(a,b,c){if(b instanceof E){c=b.height;b=b.width}else{if(c==undefined)throw Error("missing height argument");c=c}Vc(a,b);Wc(a,c)}function Nc(a,b,c,d){if(typeof d=="number")d=(b?Math.round(d):d)+"px";c.style[a]=d}var Wc=na(Nc,"height",true),Vc=na(Nc,"width",true);
function Xc(a){var b=ob&&!I("10");if(Lc(a,"display")!="none")return b?new E(a.offsetWidth||a.clientWidth,a.offsetHeight||a.clientHeight):new E(a.offsetWidth,a.offsetHeight);var c=a.style,d=c.display,f=c.visibility,g=c.position;c.visibility="hidden";c.position="absolute";c.display="inline";if(b){b=a.offsetWidth||a.clientWidth;a=a.offsetHeight||a.clientHeight}else{b=a.offsetWidth;a=a.offsetHeight}c.display=d;c.position=g;c.visibility=f;return new E(b,a)}
function Yc(a){var b=Rc(a);a=Xc(a);return new Jc(b.x,b.y,a.width,a.height)}function Zc(a,b){a.style.display=b?"":"none"}function Sc(a){return"rtl"==Lc(a,"direction")}var $c=G?"MozUserSelect":H?"WebkitUserSelect":null;function ad(a,b,c){c=!c?a.getElementsByTagName("*"):null;if($c){b=b?"none":"";a.style[$c]=b;if(c){a=0;for(var d;d=c[a];a++)d.style[$c]=b}}else if(F||ob){b=b?"on":"";a.setAttribute("unselectable",b);if(c)for(a=0;d=c[a];a++)d.setAttribute("unselectable",b)}}function bd(){}
function cd(a,b){var c=[];dd(a,b,c);return c.join("")}
function dd(a,b,c){switch(typeof b){case "string":ed(a,b,c);break;case "number":c.push(isFinite(b)&&!isNaN(b)?b:"null");break;case "boolean":c.push(b);break;case "undefined":c.push("null");break;case "object":if(b==null){c.push("null");break}if(x(b)){var d=b.length;c.push("[");for(var f="",g=0;g<d;g++){c.push(f);dd(a,b[g],c);f=","}c.push("]");break}c.push("{");d="";for(f in b)if(b.hasOwnProperty(f)){g=b[f];if(typeof g!="function"){c.push(d);ed(a,f,c);c.push(":");dd(a,g,c);d=","}}c.push("}");break;
case "function":break;default:throw Error("Unknown type: "+typeof b);}}var fd={'"':'\\"',"\\":"\\\\","/":"\\/","\u0008":"\\b","\u000c":"\\f","\n":"\\n","\r":"\\r","\t":"\\t","\u000b":"\\u000b"},gd=/\uffff/.test("\uffff")?/[\\\"\x00-\x1f\x7f-\uffff]/g:/[\\\"\x00-\x1f\x7f-\xff]/g;function ed(a,b,c){c.push('"',b.replace(gd,function(d){if(d in fd)return fd[d];var f=d.charCodeAt(0),g="\\u";if(f<16)g+="000";else if(f<256)g+="00";else if(f<4096)g+="0";return fd[d]=g+f.toString(16)}),'"')}
function hd(){this.sa=[];this.Ta={}}A(hd,Wb);s=hd.prototype;s.pa=1;s.Cc=0;function Q(a,b,c,d){var f=a.Ta[b];f||(f=a.Ta[b]=[]);var g=a.pa;a.sa[g]=b;a.sa[g+1]=c;a.sa[g+2]=d;a.pa=g+3;f.push(g);return g}s.Me=function(a){if(this.Cc!=0){if(!this.Xb)this.Xb=[];this.Xb.push(a);return false}var b=this.sa[a];if(b){var c=this.Ta[b];c&&Ia(c,a);delete this.sa[a];delete this.sa[a+1];delete this.sa[a+2]}return!!b};
s.J=function(a){var b=this.Ta[a];if(b){this.Cc++;for(var c=Na(arguments,1),d=0,f=b.length;d<f;d++){var g=b[d];this.sa[g+1].apply(this.sa[g+2],c)}this.Cc--;if(this.Xb&&this.Cc==0)for(;b=this.Xb.pop();)this.Me(b);return d!=0}return false};s.clear=function(a){if(a){var b=this.Ta[a];if(b){C(b,this.Me,this);delete this.Ta[a]}}else{this.sa.length=0;this.Ta={}}};s.c=function(){hd.a.c.call(this);delete this.sa;delete this.Ta;delete this.Xb};function id(a,b){if(G){a.setAttribute("role",b);a.hg=b}}
function jd(a,b,c){G&&a.setAttribute("aria-"+b,c)}function kd(a,b,c,d,f){if(!F&&!(H&&I("525")))return true;if(ib&&f)return ld(a);if(f&&!d)return false;if(!c&&(b==17||b==18))return false;if(F&&d&&b==a)return false;switch(a){case 13:return true;case 27:return!H}return ld(a)}
function ld(a){if(a>=48&&a<=57)return true;if(a>=96&&a<=106)return true;if(a>=65&&a<=90)return true;if(H&&a==0)return true;switch(a){case 32:case 63:case 107:case 109:case 110:case 111:case 186:case 189:case 187:case 188:case 190:case 191:case 192:case 222:case 219:case 220:case 221:return true;default:return false}}function md(a){a&&nd(this,a)}A(md,P);s=md.prototype;s.n=null;s.tc=null;s.nd=null;s.uc=null;s.Sb=-1;s.bb=-1;
var od={"3":13,"12":144,"63232":38,"63233":40,"63234":37,"63235":39,"63236":112,"63237":113,"63238":114,"63239":115,"63240":116,"63241":117,"63242":118,"63243":119,"63244":120,"63245":121,"63246":122,"63247":123,"63248":44,"63272":46,"63273":36,"63275":35,"63276":33,"63277":34,"63289":144,"63302":45},pd={Up:38,Down:40,Left:37,Right:39,Enter:13,F1:112,F2:113,F3:114,F4:115,F5:116,F6:117,F7:118,F8:119,F9:120,F10:121,F11:122,F12:123,"U+007F":46,Home:36,End:35,PageUp:33,PageDown:34,Insert:45},qd={61:187,
59:186},rd=F||H&&I("525");s=md.prototype;s.bd=function(a){if(rd&&!kd(a.keyCode,this.Sb,a.shiftKey,a.ctrlKey,a.altKey))this.handleEvent(a);else this.bb=G&&a.keyCode in qd?qd[a.keyCode]:a.keyCode};s.of=function(){this.bb=this.Sb=-1};
s.handleEvent=function(a){var b=a.wa,c,d;if(F&&a.type=="keypress"){c=this.bb;d=c!=13&&c!=27?b.keyCode:0}else if(H&&a.type=="keypress"){c=this.bb;d=b.charCode>=0&&b.charCode<63232&&ld(c)?b.charCode:0}else if(ob){c=this.bb;d=ld(c)?b.keyCode:0}else{c=b.keyCode||this.bb;d=b.charCode||0;if(ib&&d==63&&!c)c=191}var f=c,g=b.keyIdentifier;if(c)if(c>=63232&&c in od)f=od[c];else{if(c==25&&a.shiftKey)f=9}else if(g&&g in pd)f=pd[g];a=f==this.Sb;this.Sb=f;b=new sd(f,d,a,b);try{this.dispatchEvent(b)}finally{b.B()}};
s.b=e("n");function nd(a,b){a.uc&&a.detach();a.n=b;a.tc=N(a.n,"keypress",a);a.nd=N(a.n,"keydown",a.bd,false,a);a.uc=N(a.n,"keyup",a.of,false,a)}s.detach=function(){if(this.tc){O(this.tc);O(this.nd);O(this.uc);this.uc=this.nd=this.tc=null}this.n=null;this.bb=this.Sb=-1};s.c=function(){md.a.c.call(this);this.detach()};function sd(a,b,c,d){d&&this.rb(d,void 0);this.type="key";this.keyCode=a;this.charCode=b;this.repeat=c}A(sd,Zb);function td(a){this.ne=a}A(td,Wb);var ud=new ec(0,100);
td.prototype.h=function(a,b,c,d,f){if(x(b))for(var g=0;g<b.length;g++)this.h(a,b[g],c,d,f);else{a=N(a,b,c||this,d||false,f||this.ne||this);if(this.p)this.p[a]=true;else if(this.pa){this.p=fc(ud);this.p[this.pa]=true;this.pa=null;this.p[a]=true}else this.pa=a}return this};
td.prototype.ha=function(a,b,c,d,f){if(this.pa||this.p)if(x(b))for(var g=0;g<b.length;g++)this.ha(a,b[g],c,d,f);else{a:{c=c||this;f=f||this.ne||this;d=!!(d||false);if(a=Ac(a,b,d))for(b=0;b<a.length;b++)if(a[b].tb==c&&a[b].capture==d&&a[b].rc==f){a=a[b];break a}a=null}if(a){a=a.key;O(a);if(this.p)Ya(this.p,a);else if(this.pa==a)this.pa=null}}return this};function vd(a){if(a.p){for(var b in a.p){O(b);delete a.p[b]}gc(ud,a.p);a.p=null}else a.pa&&O(a.pa)}td.prototype.c=function(){td.a.c.call(this);vd(this)};
td.prototype.handleEvent=function(){throw Error("EventHandler.handleEvent not implemented");};function wd(){}w(wd);wd.prototype.Ef=0;wd.W();function R(a){this.Ka=a||J();this.$b=xd}A(R,P);R.prototype.wf=wd.W();var xd=null;
function yd(a,b){switch(a){case 1:return b?"disable":"enable";case 2:return b?"highlight":"unhighlight";case 4:return b?"activate":"deactivate";case 8:return b?"select":"unselect";case 16:return b?"check":"uncheck";case 32:return b?"focus":"blur";case 64:return b?"open":"close";default:}throw Error("Invalid component state");}s=R.prototype;s.qb=null;s.Ka=null;s.r=false;s.n=null;s.$b=null;s.sd=null;s.t=null;s.M=null;s.na=null;s.Qe=false;
function zd(a){return a.qb||(a.qb=":"+(a.wf.Ef++).toString(36))}function Ad(a,b){if(a.t&&a.t.na){Ya(a.t.na,a.qb);Za(a.t.na,b,a)}a.qb=b}s.b=e("n");s.Z=function(){return this.ob||(this.ob=new td(this))};function Bd(a,b){if(a==b)throw Error("Unable to set parent component");if(b&&a.t&&a.qb&&Cd(a.t,a.qb)&&a.t!=b)throw Error("Unable to set parent component");a.t=b;R.a.Dd.call(a,b)}s.Dd=function(a){if(this.t&&this.t!=a)throw Error("Method not supported");R.a.Dd.call(this,a)};s.C=e("Ka");
s.f=function(){this.n=this.Ka.createElement("div")};s.wb=function(a){Dd(this,a)};function Dd(a,b,c){if(a.r)throw Error("Component already rendered");a.n||a.f();b?b.insertBefore(a.n,c||null):a.Ka.m.body.appendChild(a.n);if(!a.t||a.t.r)a.N()}s.G=function(a){if(this.r)throw Error("Component already rendered");else if(a&&this.ma(a)){this.Qe=true;if(!this.Ka||this.Ka.m!=K(a))this.Ka=J(a);this.ua(a);this.N()}else throw Error("Invalid element to decorate");};s.ma=n(true);s.ua=ba("n");
s.N=function(){this.r=true;Ed(this,function(a){!a.r&&a.b()&&a.N()})};s.xa=function(){Ed(this,function(a){a.r&&a.xa()});this.ob&&vd(this.ob);this.r=false};s.c=function(){R.a.c.call(this);this.r&&this.xa();if(this.ob){this.ob.B();delete this.ob}Ed(this,function(a){a.B()});!this.Qe&&this.n&&Jb(this.n);this.t=this.sd=this.n=this.na=this.M=null};s.ia=function(a,b){this.Eb(a,Fd(this),b)};
s.Eb=function(a,b,c){if(a.r&&(c||!this.r))throw Error("Component already rendered");if(b<0||b>Fd(this))throw Error("Child component index out of bounds");if(!this.na||!this.M){this.na={};this.M=[]}if(a.t==this){this.na[zd(a)]=a;Ia(this.M,a)}else Za(this.na,zd(a),a);Bd(a,this);Ma(this.M,b,0,a);if(a.r&&this.r&&a.t==this){c=this.O();c.insertBefore(a.b(),c.childNodes[b]||null)}else if(c){this.n||this.f();b=S(this,b+1);Dd(a,this.O(),b?b.n:null)}else this.r&&!a.r&&a.n&&a.N()};s.O=e("n");
function Gd(a){if(a.$b==null)a.$b=Sc(a.r?a.n:a.Ka.m.body);return a.$b}s.yb=function(a){if(this.r)throw Error("Component already rendered");this.$b=a};function Fd(a){return a.M?a.M.length:0}function Cd(a,b){var c;if(a.na&&b){c=a.na;c=b in c?c[b]:void 0;c=c||null}else c=null;return c}function S(a,b){return a.M?a.M[b]||null:null}function Ed(a,b,c){a.M&&C(a.M,b,c)}function Hd(a,b){return a.M&&b?Ea(a.M,b):-1}
s.removeChild=function(a,b){if(a){var c=y(a)?a:zd(a);a=Cd(this,c);if(c&&a){Ya(this.na,c);Ia(this.M,a);if(b){a.xa();a.n&&Jb(a.n)}Bd(a,null)}}if(!a)throw Error("Child is not in parent component");return a};function Id(){}var Jd;w(Id);s=Id.prototype;s.ya=aa();s.f=function(a){return a.C().f("div",this.nb(a).join(" "),a.Ba)};s.O=function(a){return a};s.Gb=function(a,b,c){if(a=a.b?a.b():a)if(F&&!I("7")){var d=Kd(this,Pa(a),b);d.push(b);na(c?Qa:Ra,a).apply(null,d)}else c?Qa(a,b):Ra(a,b)};s.ma=n(true);
s.G=function(a,b){b.id&&Ad(a,b.id);var c=this.O(b);if(c&&c.firstChild)Ld(a,c.firstChild.nextSibling?Ka(c.childNodes):c.firstChild);else a.Ba=null;var d=0,f=this.g(),g=this.g(),h=false,j=false;c=false;var i=Pa(b);C(i,function(l){if(!h&&l==f){h=true;if(g==f)j=true}else if(!j&&l==g)j=true;else d|=this.Zc(l)},this);a.i=d;if(!h){i.push(f);if(g==f)j=true}j||i.push(g);var k=a.oa;k&&i.push.apply(i,k);if(F&&!I("7")){var m=Kd(this,i);if(m.length>0){i.push.apply(i,m);c=true}}if(!h||!j||k||c)b.className=i.join(" ");
return b};s.sb=function(a){Gd(a)&&this.yb(a.b(),true);a.D()&&this.Ra(a,a.q)};s.ac=function(a,b){ad(a,!b,!F&&!ob)};s.yb=function(a,b){this.Gb(a,this.g()+"-rtl",b)};s.Oa=function(a){var b;if(a.R&32&&(b=a.H()))return Pb(b);return false};s.Ra=function(a,b){var c;if(a.R&32&&(c=a.H())){if(!b&&a.i&32){try{c.blur()}catch(d){}a.i&32&&a.Ya(null)}if(Pb(c)!=b){c=c;if(b)c.tabIndex=0;else c.removeAttribute("tabIndex")}}};s.ka=function(a,b){Zc(a,b)};
s.ga=function(a,b,c){var d=a.b();if(d){var f=this.Ib(b);f&&this.Gb(a,f,c);this.Cb(d,b,c)}};s.Cb=function(a,b,c){if(G){Jd||(Jd=cb(1,"disabled",4,"pressed",8,"selected",16,"checked",64,"expanded"));(b=Jd[b])&&jd(a,b,c)}};s.eb=function(a,b){var c=this.O(a);if(c){Ib(c);if(b)if(y(b))Mb(c,b);else{var d=function(f){if(f){var g=K(c);c.appendChild(y(f)?g.createTextNode(f):f)}};if(x(b))C(b,d);else fa(b)&&!("nodeType"in b)?C(Ka(b),d):d(b)}}};s.H=function(a){return a.b()};s.g=n("goog-control");
s.nb=function(a){var b=this.g(),c=[b],d=this.g();d!=b&&c.push(d);b=a.i;for(d=[];b;){var f=b&-b;d.push(this.Ib(f));b&=~f}c.push.apply(c,d);(a=a.oa)&&c.push.apply(c,a);F&&!I("7")&&c.push.apply(c,Kd(this,c));return c};function Kd(a,b,c){var d=[];if(c)b=b.concat([c]);C([],function(f){if(Ga(f,na(Ha,b))&&(!c||Ha(f,c)))d.push(f.join("_"))});return d}s.Ib=function(a){this.jc||Md(this);return this.jc[a]};
s.Zc=function(a){if(!this.Le){this.jc||Md(this);var b=this.jc,c={};for(var d in b)c[b[d]]=d;this.Le=c}a=parseInt(this.Le[a],10);return isNaN(a)?0:a};function Md(a){var b=a.g();a.jc=cb(1,b+"-disabled",2,b+"-hover",4,b+"-active",8,b+"-selected",16,b+"-checked",32,b+"-focused",64,b+"-open")}function Nd(a,b){if(!a)throw Error("Invalid class name "+a);if(!ha(b))throw Error("Invalid decorator function "+b);Od[a]=b}var Pd={},Od={};
function T(a,b,c){R.call(this,c);if(!(b=b)){b=this.constructor;for(var d;b;){d=z(b);if(d=Pd[d])break;b=b.a?b.a.constructor:null}b=d?ha(d.W)?d.W():new d:null}this.e=b;this.Ba=a}A(T,R);s=T.prototype;s.Ba=null;s.i=0;s.R=39;s.Qd=255;s.Hd=0;s.q=true;s.oa=null;s.dd=true;s.hc=false;function Qd(a,b){a.r&&b!=a.dd&&Rd(a,b);a.dd=b}s.H=function(){return this.e.H(this)};s.nc=function(){return this.V||(this.V=new md)};
s.Gb=function(a,b){if(b){if(a){if(this.oa)Ha(this.oa,a)||this.oa.push(a);else this.oa=[a];this.e.Gb(this,a,true)}}else if(a&&this.oa){Ia(this.oa,a);if(this.oa.length==0)this.oa=null;this.e.Gb(this,a,false)}};s.f=function(){var a=this.e.f(this);this.n=a;if(G){var b=this.e.ya();b&&id(a,b)}this.hc||this.e.ac(a,false);this.q||this.e.ka(a,false)};s.O=function(){return this.e.O(this.b())};s.ma=function(a){return this.e.ma(a)};
s.ua=function(a){this.n=a=this.e.G(this,a);if(G){var b=this.e.ya();b&&id(a,b)}this.hc||this.e.ac(a,false);this.q=a.style.display!="none"};s.N=function(){T.a.N.call(this);this.e.sb(this);if(this.R&-2){this.dd&&Rd(this,true);if(this.R&32){var a=this.H();if(a){var b=this.nc();nd(b,a);this.Z().h(b,"key",this.Ea).h(a,"focus",this.qc).h(a,"blur",this.Ya)}}}};
function Rd(a,b){var c=a.Z(),d=a.b();if(b){c.h(d,"mouseover",a.fd).h(d,"mousedown",a.Za).h(d,"mouseup",a.Nb).h(d,"mouseout",a.ed);F&&c.h(d,"dblclick",a.ke)}else{c.ha(d,"mouseover",a.fd).ha(d,"mousedown",a.Za).ha(d,"mouseup",a.Nb).ha(d,"mouseout",a.ed);F&&c.ha(d,"dblclick",a.ke)}}s.xa=function(){T.a.xa.call(this);this.V&&this.V.detach();this.q&&this.D()&&this.e.Ra(this,false)};s.c=function(){T.a.c.call(this);if(this.V){this.V.B();delete this.V}delete this.e;this.oa=this.Ba=null};
s.eb=function(a){this.e.eb(this.b(),a);this.Ba=a};function Ld(a,b){a.Ba=b}function Sd(a,b){var c=a.Ba;if(!c||y(c))return c;return(c=x(c)?Fa(c,b).join(""):Qb(c))&&ra(c)}s.Hb=function(){return Sd(this,Qb)};s.yb=function(a){T.a.yb.call(this,a);var b=this.b();b&&this.e.yb(b,a)};s.ac=function(a){this.hc=a;var b=this.b();b&&this.e.ac(b,a)};s.ka=function(a,b){if(b||this.q!=a&&this.dispatchEvent(a?"show":"hide")){var c=this.b();c&&this.e.ka(c,a);this.D()&&this.e.Ra(this,a);this.q=a;return true}return false};
s.D=function(){return!!!(this.i&1)};s.Ga=function(a){var b=this.t;if(!(b&&typeof b.D=="function"&&!b.D())&&Td(this,1,!a)){if(!a){this.setActive(false);this.za(false)}this.q&&this.e.Ra(this,a);this.ga(1,!a)}};s.za=function(a){Td(this,2,a)&&this.ga(2,a)};s.Pb=function(){return!!(this.i&4)};s.setActive=function(a){Td(this,4,a)&&this.ga(4,a)};s.Ed=function(a){Td(this,8,a)&&this.ga(8,a)};function Ud(a,b){Td(a,16,b)&&a.ga(16,b)}s.w=function(a){Td(this,64,a)&&this.ga(64,a)};
s.ga=function(a,b){if(this.R&a&&b!=!!(this.i&a)){this.e.ga(this,a,b);this.i=b?this.i|a:this.i&~a}};function Vd(a,b,c){if(a.r&&a.i&b&&!c)throw Error("Component already rendered");!c&&a.i&b&&a.ga(b,false);a.R=c?a.R|b:a.R&~b}function U(a,b){return!!(a.Qd&b)&&!!(a.R&b)}function Td(a,b,c){return!!(a.R&b)&&!!(a.i&b)!=c&&(!(a.Hd&b)||a.dispatchEvent(yd(b,c)))&&!a.Sc}s.fd=function(a){!Yd(a,this.b())&&this.dispatchEvent("enter")&&this.D()&&U(this,2)&&this.za(true)};
s.ed=function(a){if(!Yd(a,this.b())&&this.dispatchEvent("leave")){U(this,4)&&this.setActive(false);U(this,2)&&this.za(false)}};function Yd(a,b){return!!a.relatedTarget&&Lb(b,a.relatedTarget)}s.Za=function(a){if(this.D()){U(this,2)&&this.za(true);if(ac(a,0)){U(this,4)&&this.setActive(true);this.e.Oa(this)&&this.H().focus()}}!this.hc&&ac(a,0)&&a.preventDefault()};s.Nb=function(a){if(this.D()){U(this,2)&&this.za(true);this.Pb()&&this.ub(a)&&U(this,4)&&this.setActive(false)}};
s.ke=function(a){this.D()&&this.ub(a)};s.ub=function(a){U(this,16)&&Ud(this,!!!(this.i&16));U(this,8)&&this.Ed(true);U(this,64)&&this.w(!!!(this.i&64));var b=new L("action",this);if(a)for(var c=["altKey","ctrlKey","metaKey","shiftKey","platformModifierKey"],d,f=0;d=c[f];f++)b[d]=a[d];return this.dispatchEvent(b)};s.qc=function(){U(this,32)&&Td(this,32,true)&&this.ga(32,true)};s.Ya=function(){U(this,4)&&this.setActive(false);U(this,32)&&Td(this,32,false)&&this.ga(32,false)};
s.Ea=function(a){if(this.q&&this.D()&&this.pb(a)){a.preventDefault();a.stopPropagation();return true}return false};s.pb=function(a){return a.keyCode==13&&this.ub(a)};if(!ha(T))throw Error("Invalid component class "+T);if(!ha(Id))throw Error("Invalid renderer class "+Id);var Zd=z(T);Pd[Zd]=Id;Nd("goog-control",function(){return new T(null)});function $d(){}A($d,Id);w($d);$d.prototype.f=function(a){return a.C().f("div",this.g())};
$d.prototype.G=function(a,b){if(b.tagName=="HR"){var c=b;b=this.f(a);c.parentNode&&c.parentNode.insertBefore(b,c);Jb(c)}else Qa(b,this.g());return b};$d.prototype.eb=aa();$d.prototype.g=n("goog-menuseparator");function ae(a,b){T.call(this,null,a||$d.W(),b);Vd(this,1,false);Vd(this,2,false);Vd(this,4,false);Vd(this,32,false);this.i=1}A(ae,T);ae.prototype.N=function(){ae.a.N.call(this);id(this.b(),"separator")};Nd("goog-menuseparator",function(){return new ae});function be(){}w(be);s=be.prototype;
s.ya=aa();function ce(a,b,c){if(b)b.tabIndex=c?0:-1}s.f=function(a){return a.C().f("div",this.nb(a).join(" "))};s.O=function(a){return a};s.ma=function(a){return a.tagName=="DIV"};s.G=function(a,b){b.id&&Ad(a,b.id);var c=this.g(),d=false,f=Pa(b);f&&C(f,function(g){if(g==c)d=true;else if(g)if(g==c+"-disabled")a.Ga(false);else if(g==c+"-horizontal")a.Cd(de);else g==c+"-vertical"&&a.Cd(ee)},this);d||Qa(b,c);fe(this,a,b);return b};
function fe(a,b,c,d){if(c){d=d||c.firstChild;for(var f;d&&d.parentNode==c;){f=d.nextSibling;if(d.nodeType==1){var g=a.Jb(d);if(g){g.n=d;b.D()||g.Ga(false);b.ia(g);g.G(d)}}else if(!d.nodeValue||ra(d.nodeValue)=="")c.removeChild(d);d=f}}}s.Jb=function(a){a:{for(var b=Pa(a),c=0,d=b.length;c<d;c++)if(a=b[c]in Od?Od[b[c]]():null){a=a;break a}a=null}return a};s.sb=function(a){a=a.b();ad(a,true,G);if(F)a.hideFocus=true;var b=this.ya();b&&id(a,b)};s.H=function(a){return a.b()};s.g=n("goog-container");
s.nb=function(a){var b=this.g(),c=[b,a.v==de?b+"-horizontal":b+"-vertical"];a.D()||c.push(b+"-disabled");return c};s.de=function(){return ee};function V(a,b,c){R.call(this,c);this.e=b||be.W();this.v=a||this.e.de()}A(V,R);var de="horizontal",ee="vertical";s=V.prototype;s.se=null;s.V=null;s.e=null;s.v=null;s.q=true;s.S=true;s.Uc=true;s.U=-1;s.I=null;s.Fa=false;s.We=false;s.If=true;s.Ia=null;s.H=function(){return this.se||this.e.H(this)};s.nc=function(){return this.V||(this.V=new md(this.H()))};
s.f=function(){this.n=this.e.f(this)};s.O=function(){return this.e.O(this.b())};s.ma=function(a){return this.e.ma(a)};s.ua=function(a){this.n=this.e.G(this,a);if(a.style.display=="none")this.q=false};
s.N=function(){V.a.N.call(this);Ed(this,function(b){b.r&&ge(this,b)},this);var a=this.b();this.e.sb(this);this.ka(this.q,true);this.Z().h(this,"enter",this.$c).h(this,"highlight",this.ad).h(this,"unhighlight",this.gd).h(this,"open",this.sf).h(this,"close",this.lf).h(a,"mousedown",this.Za).h(K(a),"mouseup",this.nf).h(a,["mousedown","mouseup","mouseover","mouseout"],this.kf);this.Oa()&&he(this,true)};
function he(a,b){var c=a.Z(),d=a.H();b?c.h(d,"focus",a.qc).h(d,"blur",a.Ya).h(a.nc(),"key",a.Ea):c.ha(d,"focus",a.qc).ha(d,"blur",a.Ya).ha(a.nc(),"key",a.Ea)}s.xa=function(){ie(this,-1);this.I&&this.I.w(false);this.Fa=false;V.a.xa.call(this)};s.c=function(){V.a.c.call(this);if(this.V){this.V.B();this.V=null}this.e=this.I=this.Ia=null};s.$c=n(true);
s.ad=function(a){var b=Hd(this,a.target);if(b>-1&&b!=this.U){var c=S(this,this.U);c&&c.za(false);this.U=b;c=S(this,this.U);this.Fa&&c.setActive(true);if(this.If&&this.I&&c!=this.I)c.R&64?c.w(true):this.I.w(false)}jd(this.b(),"activedescendant",a.target.b().id)};s.gd=function(a){if(a.target==S(this,this.U))this.U=-1;jd(this.b(),"activedescendant","")};s.sf=function(a){if((a=a.target)&&a!=this.I&&a.t==this){this.I&&this.I.w(false);this.I=a}};s.lf=function(a){if(a.target==this.I)this.I=null};
s.Za=function(a){if(this.S)this.Fa=true;var b=this.H(),c;a:{if(b)if((c=b.getAttributeNode("tabindex"))&&c.specified){c=b.tabIndex;c=ga(c)&&c>=0;break a}c=false}c?b.focus():a.preventDefault()};s.nf=function(){this.Fa=false};
s.kf=function(a){var b;a:{b=a.target;if(this.Ia)for(var c=this.b();b&&b.parentNode&&b!=c;){var d=b.id;if(d in this.Ia){b=this.Ia[d];break a}b=b.parentNode}b=null}if(b)switch(a.type){case "mousedown":b.Za(a);break;case "mouseup":b.Nb(a);break;case "mouseover":b.fd(a);break;case "mouseout":b.ed(a);break}};s.qc=aa();s.Ya=function(){ie(this,-1);this.Fa=false;this.I&&this.I.w(false)};s.Ea=function(a){if(this.D()&&this.q&&(Fd(this)!=0||this.se)&&this.pb(a)){a.preventDefault();a.stopPropagation();return true}return false};
s.pb=function(a){var b=S(this,this.U);if(b&&typeof b.Ea=="function"&&b.Ea(a))return true;if(this.I&&this.I!=b&&typeof this.I.Ea=="function"&&this.I.Ea(a))return true;switch(a.keyCode){case 27:if(this.Oa())this.H().blur();else return false;break;case 36:je(this);break;case 35:ke(this);break;case 38:if(this.v==ee)le(this);else return false;break;case 37:if(this.v==de)Gd(this)?me(this):le(this);else return false;break;case 40:if(this.v==ee)me(this);else return false;break;case 39:if(this.v==de)Gd(this)?
le(this):me(this);else return false;break;default:return false}return true};function ge(a,b){var c=b.b();c=c.id||(c.id=zd(b));if(!a.Ia)a.Ia={};a.Ia[c]=b}s.ia=function(a,b){V.a.ia.call(this,a,b)};s.Eb=function(a,b,c){a.Hd|=2;a.Hd|=64;if(this.Oa()||!this.We)Vd(a,32,false);Qd(a,false);V.a.Eb.call(this,a,b,c);c&&this.r&&ge(this,a);b<=this.U&&this.U++};
s.removeChild=function(a,b){if(a=y(a)?Cd(this,a):a){var c=Hd(this,a);if(c!=-1)if(c==this.U)a.za(false);else c<this.U&&this.U--;(c=a.b())&&c.id&&Ya(this.Ia,c.id)}a=V.a.removeChild.call(this,a,b);Qd(a,true);return a};s.Cd=function(a){if(this.b())throw Error("Component already rendered");this.v=a};s.ka=function(a,b){if(b||this.q!=a&&this.dispatchEvent(a?"show":"hide")){this.q=a;var c=this.b();if(c){Zc(c,a);this.Oa()&&ce(this.e,this.H(),this.S&&this.q);b||this.dispatchEvent(this.q?"aftershow":"afterhide")}return true}return false};
s.D=e("S");s.Ga=function(a){if(this.S!=a&&this.dispatchEvent(a?"enable":"disable")){if(a){this.S=true;Ed(this,function(b){if(b.Re)delete b.Re;else b.Ga(true)})}else{Ed(this,function(b){if(b.D())b.Ga(false);else b.Re=true});this.Fa=this.S=false}this.Oa()&&ce(this.e,this.H(),a&&this.q)}};s.Oa=e("Uc");s.Ra=function(a){a!=this.Uc&&this.r&&he(this,a);this.Uc=a;this.S&&this.q&&ce(this.e,this.H(),a)};function ie(a,b){var c=S(a,b);if(c)c.za(true);else a.U>-1&&S(a,a.U).za(false)}
s.za=function(a){ie(this,Hd(this,a))};function je(a){ne(a,function(b,c){return(b+1)%c},Fd(a)-1)}function ke(a){ne(a,function(b,c){b--;return b<0?c-1:b},0)}function me(a){ne(a,function(b,c){return(b+1)%c},a.U)}function le(a){ne(a,function(b,c){b--;return b<0?c-1:b},a.U)}function ne(a,b,c){c=c<0?Hd(a,a.I):c;var d=Fd(a);c=b.call(a,c,d);for(var f=0;f<=d;){var g=S(a,c);if(g&&a.Td(g)){ie(a,c);return true}f++;c=b.call(a,c,d)}return false}s.Td=function(a){return a.q&&a.D()&&!!(a.R&2)};function oe(){}
A(oe,$d);w(oe);oe.prototype.f=function(a){return a.C().f("div",this.g()+" goog-inline-block","\u00a0")};oe.prototype.G=function(a,b){b=oe.a.G.call(this,a,b);Qa(b,"goog-inline-block");return b};oe.prototype.g=n("goog-toolbar-separator");function pe(){}A(pe,be);w(pe);pe.prototype.ya=n("toolbar");pe.prototype.Jb=function(a){return a.tagName=="HR"?new ae(oe.W()):pe.a.Jb.call(this,a)};pe.prototype.g=n("goog-toolbar");pe.prototype.de=function(){return de};function qe(a,b,c){V.call(this,b,a||pe.W(),c)}
A(qe,V);function re(){}A(re,Id);w(re);s=re.prototype;s.ya=n("button");s.Cb=function(a,b,c){if(G)b==16?jd(a,"pressed",c):re.a.Cb.call(this,a,b,c)};s.f=function(a){var b=re.a.f.call(this,a),c=a.Mb();c&&this.Gd(b,c);(c=a.o())&&this.z(b,c);a.R&16&&this.Cb(b,16,false);return b};s.G=function(a,b){b=re.a.G.call(this,a,b);var c=this.o(b);a.ta=c;a.Jd=this.Mb(b);a.R&16&&this.Cb(b,16,false);return b};s.o=u;s.z=u;s.Mb=function(a){return a.title};s.Gd=function(a,b){if(a)a.title=b||""};s.g=n("goog-button");
function se(){}A(se,re);w(se);s=se.prototype;s.ya=aa();s.f=function(a){te(this,a);return a.C().f("button",{"class":this.nb(a).join(" "),disabled:!a.D(),title:a.Mb()||"",value:a.o()||""},a.Hb()||"")};s.ma=function(a){return a.tagName=="BUTTON"||a.tagName=="INPUT"&&(a.type=="button"||a.type=="submit"||a.type=="reset")};s.G=function(a,b){te(this,a);b.disabled&&Qa(b,this.Ib(1));return se.a.G.call(this,a,b)};s.sb=function(a){a.Z().h(a.b(),"click",a.ub)};s.ac=u;s.yb=u;s.Oa=function(a){return a.D()};
s.Ra=u;s.ga=function(a,b,c){se.a.ga.call(this,a,b,c);if((a=a.b())&&b==1)a.disabled=c};s.o=function(a){return a.value};s.z=function(a,b){if(a)a.value=b};s.Cb=u;function te(a,b){Qd(b,false);b.Qd&=-256;Vd(b,32,false)}function ue(a,b,c){T.call(this,a,b||se.W(),c)}A(ue,T);s=ue.prototype;s.o=e("ta");s.z=function(a){this.ta=a;this.e.z(this.b(),a)};s.Mb=e("Jd");s.Gd=function(a){this.Jd=a;this.e.Gd(this.b(),a)};s.c=function(){ue.a.c.call(this);delete this.ta;delete this.Jd};
s.N=function(){ue.a.N.call(this);if(this.R&32){var a=this.H();a&&this.Z().h(a,"keyup",this.pb)}};s.pb=function(a){if(a.keyCode==13&&a.type=="key"||a.keyCode==32&&a.type=="keyup")return this.ub(a);return a.keyCode==32};Nd("goog-button",function(){return new ue(null)});function ve(){}A(ve,re);w(ve);s=ve.prototype;s.f=function(a){var b={"class":"goog-inline-block "+this.nb(a).join(" "),title:a.Mb()||""};return a.C().f("div",b,this.kc(a.Ba,a.C()))};s.O=function(a){return a&&a.firstChild.firstChild};
s.kc=function(a,b){return b.f("div","goog-inline-block "+(this.g()+"-outer-box"),b.f("div","goog-inline-block "+(this.g()+"-inner-box"),a))};s.ma=function(a){return a.tagName=="DIV"};s.G=function(a,b){we(b,true);we(b,false);var c;a:{if((c=a.C().ee(b))&&c.className.indexOf(this.g()+"-outer-box")!=-1)if((c=a.C().ee(c))&&c.className.indexOf(this.g()+"-inner-box")!=-1){c=true;break a}c=false}c||b.appendChild(this.kc(b.childNodes,a.C()));Qa(b,"goog-inline-block",this.g());return ve.a.G.call(this,a,b)};
s.g=n("goog-custom-button");function we(a,b){if(a)for(var c=b?a.firstChild:a.lastChild,d;c&&c.parentNode==a;){d=b?c.nextSibling:c.previousSibling;if(c.nodeType==3){var f=c.nodeValue;if(ra(f)=="")a.removeChild(c);else{c.nodeValue=b?f.replace(/^[\s\xa0]+/,""):f.replace(/[\s\xa0]+$/,"");break}}else break;c=d}}function xe(a,b,c){ue.call(this,a,b||ve.W(),c);Vd(this,16,true)}A(xe,ue);Nd("goog-toggle-button",function(){return new xe(null)});function ye(){}A(ye,ve);w(ye);ye.prototype.g=n("goog-toolbar-button");
function ze(a,b,c){xe.call(this,a,b||ye.W(),c)}A(ze,xe);Nd("goog-toolbar-toggle-button",function(){return new ze(null)});function Ae(a,b,c){ue.call(this,a,b||ye.W(),c)}A(Ae,ue);Nd("goog-toolbar-button",function(){return new Ae(null)});function Be(a,b){this.Ob=a||1;this.dc=b||Ce;this.Qc=ma(this.Uf,this);this.pd=oa()}A(Be,P);Be.prototype.enabled=false;var Ce=t.window;s=Be.prototype;s.da=null;s.setInterval=function(a){this.Ob=a;if(this.da&&this.enabled){this.stop();this.start()}else this.da&&this.stop()};
s.Uf=function(){if(this.enabled){var a=oa()-this.pd;if(a>0&&a<this.Ob*0.8)this.da=this.dc.setTimeout(this.Qc,this.Ob-a);else{this.dispatchEvent(De);if(this.enabled){this.da=this.dc.setTimeout(this.Qc,this.Ob);this.pd=oa()}}}};s.start=function(){this.enabled=true;if(!this.da){this.da=this.dc.setTimeout(this.Qc,this.Ob);this.pd=oa()}};s.stop=function(){this.enabled=false;if(this.da){this.dc.clearTimeout(this.da);this.da=null}};s.c=function(){Be.a.c.call(this);this.stop();delete this.dc};var De="tick";
function Ee(a,b,c,d,f,g,h,j){var i,k=c.offsetParent;if(k){var m=k.tagName=="HTML"||k.tagName=="BODY";if(!m||Lc(k,"position")!="static"){i=Rc(k);m||(i=Sa(i,new D(k.scrollLeft,k.scrollTop)))}}k=Yc(a);if(m=Qc(a)){var l=new Jc(m.left,m.top,m.right-m.left,m.bottom-m.top);m=Math.max(k.left,l.left);var o=Math.min(k.left+k.width,l.left+l.width);if(m<=o){var q=Math.max(k.top,l.top);l=Math.min(k.top+k.height,l.top+l.height);if(q<=l){k.left=m;k.top=q;k.width=o-m;k.height=l-q}}}m=J(a);q=J(c);if(m.m!=q.m){o=m.m.body;
q=q.m.parentWindow||q.m.defaultView;l=new D(0,0);var v=K(o)?K(o).parentWindow||K(o).defaultView:window,ta=o;do{var r=v==q?Rc(ta):Tc(ta);l.x+=r.x;l.y+=r.y}while(v&&v!=q&&(ta=v.frameElement)&&(v=v.parent));q=l;q=Sa(q,Rc(o));if(F&&!Cb(m.m))q=Sa(q,Ub(m));k.left+=q.x;k.top+=q.y}a=(b&4&&Sc(a)?b^2:b)&-5;b=new D(a&2?k.left+k.width:k.left,a&1?k.top+k.height:k.top);if(i)b=Sa(b,i);if(f){b.x+=(a&2?-1:1)*f.x;b.y+=(a&1?-1:1)*f.y}var p;if(h)if((p=Qc(c))&&i){p.top=Math.max(0,p.top-i.y);p.right-=i.x;p.bottom-=i.y;
p.left=Math.max(0,p.left-i.x)}a:{f=b;p=p;f=f.Ja();i=0;a=(d&4&&Sc(c)?d^2:d)&-5;d=Xc(c);j=j?j.Ja():d;if(g||a!=0){if(a&2)f.x-=j.width+(g?g.right:0);else if(g)f.x+=g.left;if(a&1)f.y-=j.height+(g?g.bottom:0);else if(g)f.y+=g.top}if(h){if(p){g=f;i=0;if(g.x<p.left&&h&1){g.x=p.left;i|=1}if(g.x<p.left&&g.x+j.width>p.right&&h&16){j.width-=g.x+j.width-p.right;i|=4}if(g.x+j.width>p.right&&h&1){g.x=Math.max(p.right-j.width,p.left);i|=1}if(h&2)i|=(g.x<p.left?16:0)|(g.x+j.width>p.right?32:0);if(g.y<p.top&&h&4){g.y=
p.top;i|=2}if(g.y>=p.top&&g.y+j.height>p.bottom&&h&32){j.height-=g.y+j.height-p.bottom;i|=8}if(g.y+j.height>p.bottom&&h&4){g.y=Math.max(p.bottom-j.height,p.top);i|=2}if(h&8)i|=(g.y<p.top?64:0)|(g.y+j.height>p.bottom?128:0);h=i}else h=256;i=h;if(i&496){c=i;break a}}Mc(c,f);Ta(d,j)||Uc(c,j);c=i}return c}function Fe(){}Fe.prototype.Yb=aa();function Ge(a,b){this.element=a;this.kb=b}A(Ge,Fe);Ge.prototype.Yb=function(a,b,c){Ee(this.element,this.kb,a,b,undefined,c)};
function He(a,b,c){Ge.call(this,a,b);this.Ve=c}A(He,Ge);He.prototype.Yb=function(a,b,c,d){var f=Ee(this.element,this.kb,a,b,null,c,10,d);if(f&496){var g=this.kb,h=b;if(f&48){g^=2;h^=2}if(f&192){g^=1;h^=1}f=Ee(this.element,g,a,h,null,c,10,d);if(f&496)this.Ve?Ee(this.element,this.kb,a,b,null,c,5,d):Ee(this.element,this.kb,a,b,null,c,0,d)}};function Ie(a,b,c,d){He.call(this,a,b,c);this.Lf=d}A(Ie,He);
Ie.prototype.Yb=function(a,b,c,d){this.Lf?Ee(this.element,this.kb,a,b,null,c,33,d):Ie.a.Yb.call(this,a,b,c,d)};function Je(){this.Vd=[]}A(Je,Id);w(Je);function Ke(a,b){var c=a.Vd[b];if(!c){switch(b){case 0:c=a.g()+"-highlight";break;case 1:c=a.g()+"-checkbox";break;case 2:c=a.g()+"-content";break}a.Vd[b]=c}return c}s=Je.prototype;s.ya=n("menuitem");s.f=function(a){var b=a.C().f("div",this.nb(a).join(" "),Le(this,a.Ba,a.C()));Me(this,a,b,!!(a.R&8)||!!(a.R&16));return b};s.O=function(a){return a&&a.firstChild};
s.G=function(a,b){var c=Kb(b),d=Ke(this,2);c&&c.className.indexOf(d)!=-1||b.appendChild(Le(this,b.childNodes,a.C()));if(Ha(Pa(b),"goog-option")){a.Ec(true);this.Ec(a,b,true)}return Je.a.G.call(this,a,b)};s.eb=function(a,b){var c=this.O(a),d=Ne(this,a)?c.firstChild:null;Je.a.eb.call(this,a,b);if(d&&!Ne(this,a))c.insertBefore(d,c.firstChild||null)};function Le(a,b,c){a=Ke(a,2);return c.f("div",a,b)}s.Ec=function(a,b,c){if(b){id(b,c?"menuitemcheckbox":this.ya());Me(this,a,b,c)}};
function Ne(a,b){var c=a.O(b);if(c){c=c.firstChild;var d=Ke(a,1);return!!c&&!!c.className&&c.className.indexOf(d)!=-1}return false}function Me(a,b,c,d){if(d!=Ne(a,c)){d?Qa(c,"goog-option"):Ra(c,"goog-option");c=a.O(c);if(d){a=Ke(a,1);c.insertBefore(b.C().f("div",a),c.firstChild||null)}else c.removeChild(c.firstChild)}}s.Ib=function(a){switch(a){case 2:return Ke(this,0);case 16:case 8:return"goog-option-selected";default:return Je.a.Ib.call(this,a)}};
s.Zc=function(a){var b=Ke(this,0);switch(a){case "goog-option-selected":return 16;case b:return 2;default:return Je.a.Zc.call(this,a)}};s.g=n("goog-menuitem");function W(a,b,c,d){T.call(this,a,d||Je.W(),c);this.z(b)}A(W,T);W.prototype.o=function(){var a=this.sd;return a!=null?a:this.Hb()};W.prototype.z=ba("sd");W.prototype.Ec=function(a){Vd(this,16,a);var b=this.b();b&&this.e.Ec(this,b,a)};W.prototype.Hb=function(){return Sd(this,function(a){return Ha(Pa(a),"goog-menuitem-accel")?"":Qb(a)})};
Nd("goog-menuitem",function(){return new W(null)});function Oe(){}A(Oe,be);w(Oe);s=Oe.prototype;s.ya=n("menu");s.ma=function(a){return a.tagName=="UL"||Oe.a.ma.call(this,a)};s.Jb=function(a){return a.tagName=="HR"?new ae:Oe.a.Jb.call(this,a)};s.Ua=function(a,b){return Lb(a.b(),b)};s.g=n("goog-menu");s.sb=function(a){Oe.a.sb.call(this,a);a=a.b();jd(a,"haspopup","true")};Nd("goog-menuseparator",function(){return new ae});function Pe(a,b){V.call(this,ee,b||Oe.W(),a);this.Ra(false)}A(Pe,V);s=Pe.prototype;
s.Pc=true;s.Xe=false;s.g=function(){return this.e.g()};s.Ua=function(a){if(this.e.Ua(this,a))return true;for(var b=0,c=Fd(this);b<c;b++){var d=S(this,b);if(typeof d.Ua=="function"&&d.Ua(a))return true}return false};s.L=function(a){this.ia(a,true)};s.jb=function(a,b){this.Eb(a,b,true)};s.Lb=function(a){return S(this,a)};s.Wc=function(){return Fd(this)};
s.Ge=function(a,b){var c=this.q;c||Zc(this.b(),true);var d=this.b(),f=a,g=b,h=Rc(d);if(f instanceof D){g=f.y;f=f.x}Mc(d,d.offsetLeft+(f-h.x),d.offsetTop+(g-h.y));c||Zc(this.b(),false)};s.hf=function(){return this.q?Rc(this.b()):null};s.ka=function(a,b){var c=Pe.a.ka.call(this,a,b);c&&a&&this.r&&this.Pc&&this.H().focus();return c};s.$c=function(a){this.Pc&&this.H().focus();return Pe.a.$c.call(this,a)};s.Td=function(a){return(this.Xe||a.D())&&a.q&&!!(a.R&2)};
s.ua=function(a){var b=this.e,c;c=this.C();c=Bb(c.m,"div",b.g()+"-content",a);for(var d,f=0;d=c[f];f++)fe(b,this,d);Pe.a.ua.call(this,a)};function Qe(){}A(Qe,ve);w(Qe);if(G)Qe.prototype.eb=function(a,b){var c=Qe.a.O.call(this,a&&a.firstChild);if(c){var d=this.createCaption(b,J(a)),f=c.parentNode;f&&f.replaceChild(d,c)}};s=Qe.prototype;s.O=function(a){a=Qe.a.O.call(this,a&&a.firstChild);if(G&&a&&a.__goog_wrapper_div)a=a.firstChild;return a};
s.G=function(a,b){var c=Bb(document,"*","goog-menu",b)[0];if(c){Zc(c,false);K(c).body.appendChild(c);var d=new Pe;d.G(c);a.bc(d)}return Qe.a.G.call(this,a,b)};s.kc=function(a,b){return Qe.a.kc.call(this,[this.createCaption(a,b),b.f("div","goog-inline-block "+(this.g()+"-dropdown"),"\u00a0")],b)};s.createCaption=function(a,b){return b.f("div","goog-inline-block "+(this.g()+"-caption"),a)};s.g=n("goog-menu-button");
function X(a,b,c,d){ue.call(this,a,c||Qe.W(),d);Vd(this,64,true);b&&this.bc(b);this.da=new Be(500)}A(X,ue);s=X.prototype;s.Pd=true;s.zd=false;s.md=false;s.N=function(){X.a.N.call(this);this.d&&Re(this,this.d,true);jd(this.b(),"haspopup","true")};s.xa=function(){X.a.xa.call(this);if(this.d){this.w(false);this.d.xa();Re(this,this.d,false);var a=this.d.b();a&&Jb(a)}};s.c=function(){X.a.c.call(this);if(this.d){this.d.B();delete this.d}this.da.B()};
s.Za=function(a){X.a.Za.call(this,a);if(this.Pb()){this.w(!!!(this.i&64));if(this.d)this.d.Fa=!!(this.i&64)}};s.Nb=function(a){X.a.Nb.call(this,a);if(this.d&&!this.Pb())this.d.Fa=false};s.ub=function(){this.setActive(false);return true};s.mf=function(a){this.d&&this.d.q&&!this.Ua(a.target)&&this.w(false)};s.Ua=function(a){return a&&Lb(this.b(),a)||this.d&&this.d.Ua(a)||false};
s.pb=function(a){if(a.keyCode==32){a.preventDefault();if(a.type!="keyup")return false}else if(a.type!="key")return false;if(this.d&&this.d.q){var b=this.d.Ea(a);if(a.keyCode==27){this.w(false);return true}return b}if(a.keyCode==40||a.keyCode==38||a.keyCode==32){this.w(true);return true}return false};s.cd=function(){this.w(false)};s.pf=function(){this.Pb()||this.w(false)};s.Ya=function(a){this.md||this.w(false);X.a.Ya.call(this,a)};function Se(a){a.d||a.bc(new Pe(a.C()));return a.d||null}
s.bc=function(a){var b=this.d;if(a!=b){if(b){this.w(false);this.r&&Re(this,b,false);delete this.d}if(a){this.d=a;Bd(a,this);a.ka(false);var c=this.md;(a.Pc=c)&&a.Ra(true);this.r&&Re(this,a,true)}}return b};s.L=function(a){Se(this).ia(a,true)};s.jb=function(a,b){Se(this).Eb(a,b,true)};s.Lb=function(a){return this.d?S(this.d,a):null};s.Wc=function(){return this.d?Fd(this.d):0};s.ka=function(a,b){var c=X.a.ka.call(this,a,b);c&&!this.q&&this.w(false);return c};
s.Ga=function(a){X.a.Ga.call(this,a);this.D()||this.w(false)};
s.w=function(a){X.a.w.call(this,a);if(this.d&&!!(this.i&64)==a){if(a){this.d.r||this.d.wb();this.Pe=Qc(this.b());this.Rd=Yc(this.b());Te(this);ie(this.d,-1)}else{this.setActive(false);this.d.Fa=false;if(this.Ac!=null){this.Ac=undefined;var b=this.d.b();b&&Uc(b,"","")}}this.d.ka(a);b=this.Z();var c=a?b.h:b.ha;c.call(b,Tb(this.C()),"mousedown",this.mf,true);this.md&&c.call(b,this.d,"blur",this.pf);c.call(b,this.da,De,this.Gf);a?this.da.start():this.da.stop()}};
function Te(a){if(a.d.r){var b=a.Pd?5:7;b=new Ie(a.b(),b,!a.zd,a.zd);var c=a.d.b();if(!a.d.q){c.style.visibility="hidden";Zc(c,true)}if(!a.Ac&&a.zd)a.Ac=Xc(c);b.Yb(c,a.Pd?4:6,null,a.Ac);if(!a.d.q){Zc(c,false);c.style.visibility="visible"}}}
s.Gf=function(){var a=Yc(this.b()),b=Qc(this.b()),c;c=this.Rd;c=c==a?true:!c||!a?false:c.left==a.left&&c.width==a.width&&c.top==a.top&&c.height==a.height;if(!(c=!c)){c=this.Pe;c=c==b?true:!c||!b?false:c.top==b.top&&c.right==b.right&&c.bottom==b.bottom&&c.left==b.left;c=!c}if(c){this.Rd=a;this.Pe=b;Te(this)}};function Re(a,b,c){var d=a.Z();c=c?d.h:d.ha;c.call(d,b,"action",a.cd);c.call(d,b,"highlight",a.ad);c.call(d,b,"unhighlight",a.gd)}s.ad=function(a){jd(this.b(),"activedescendant",a.target.b().id)};
s.gd=function(){S(this.d,this.d.U)||jd(this.b(),"activedescendant","")};Nd("goog-menu-button",function(){return new X(null)});function Ue(a){this.ab=[];Ve(this,a)}A(Ue,P);s=Ue.prototype;s.Qa=null;s.De=null;s.Wc=function(){return this.ab.length};s.Lb=function(a){return this.ab[a]||null};function Ve(a,b){if(b){C(b,function(c){We(this,c,false)},a);La(a.ab,b)}}s.L=function(a){this.jb(a,this.Wc())};s.jb=function(a,b){if(a){We(this,a,false);Ma(this.ab,b,0,a)}};s.oc=e("Qa");
s.fb=function(a){if(a!=this.Qa){We(this,this.Qa,false);this.Qa=a;We(this,a,true)}this.dispatchEvent("select")};s.Yc=function(){return this.Qa?Ea(this.ab,this.Qa):-1};s.He=function(a){this.fb(this.Lb(a))};s.clear=function(){var a=this.ab;if(!x(a))for(var b=a.length-1;b>=0;b--)delete a[b];a.length=0;this.Qa=null};s.c=function(){Ue.a.c.call(this);delete this.ab;this.Qa=null};function We(a,b,c){if(b)if(typeof a.De=="function")a.De(b,c);else typeof b.Ed=="function"&&b.Ed(c)}
function Y(a,b,c,d){X.call(this,a,b,c,d);this.lc=a;Xe(this)}A(Y,X);s=Y.prototype;s.s=null;s.lc=null;s.N=function(){Y.a.N.call(this);Xe(this)};s.ua=function(a){Y.a.ua.call(this,a);if(a=this.Hb()){this.lc=a;Xe(this)}else this.He(0)};s.c=function(){Y.a.c.call(this);if(this.s){this.s.B();this.s=null}this.lc=null};s.cd=function(a){this.fb(a.target);Y.a.cd.call(this,a);a.stopPropagation();this.dispatchEvent("action")};s.vf=function(){var a=this.oc();Y.a.z.call(this,a&&a.o());Xe(this)};
s.bc=function(a){var b=Y.a.bc.call(this,a);if(a!=b){this.s&&this.s.clear();if(a)this.s?Ed(a,function(c){this.s.L(c)},this):Ye(this,a)}return b};s.L=function(a){Y.a.L.call(this,a);this.s?this.s.L(a):Ye(this,Se(this))};s.jb=function(a,b){Y.a.jb.call(this,a,b);this.s?this.s.jb(a,b):Ye(this,Se(this))};s.fb=function(a){this.s&&this.s.fb(a)};s.He=function(a){this.s&&this.fb(this.s.Lb(a))};
s.z=function(a){if(a!=null&&this.s)for(var b=0,c;c=this.s.Lb(b);b++)if(c&&typeof c.o=="function"&&c.o()==a){this.fb(c);return}this.fb(null)};s.oc=function(){return this.s?this.s.oc():null};s.Yc=function(){return this.s?this.s.Yc():-1};function Ye(a,b){a.s=new Ue;b&&Ed(b,function(c){this.s.L(c)},a);a.Z().h(a.s,"select",a.vf)}function Xe(a){var b=a.oc();a.eb(b?b.Hb():a.lc)}s.w=function(a){Y.a.w.call(this,a);this.i&64&&ie(Se(this),this.Yc())};Nd("goog-select",function(){return new Y(null)});
function Ze(){}A(Ze,Qe);w(Ze);Ze.prototype.g=n("goog-toolbar-menu-button");function $e(a,b,c,d){Y.call(this,a,b,c||Ze.W(),d)}A($e,Y);Nd("goog-toolbar-select",function(){return new $e(null)});function af(a){this.n=a;this.we=N(this.n,G?"DOMMouseScroll":"mousewheel",this)}A(af,P);
af.prototype.handleEvent=function(a){var b=0,c=0,d=0;a=a.wa;if(a.type=="mousewheel"){c=1;if(F||H&&(jb||I("532.0")))c=40;d=-a.wheelDelta/c;if(a.wheelDeltaX!==undefined){b=-a.wheelDeltaX/c;c=-a.wheelDeltaY/c}else c=d}else{d=a.detail;if(d>100)d=3;else if(d<-100)d=-3;if(a.axis!==undefined&&a.axis===a.HORIZONTAL_AXIS)b=d;else c=d}if(ga(this.ye))b=Math.min(Math.max(b,-this.ye),this.ye);if(ga(this.ze))c=Math.min(Math.max(c,-this.ze),this.ze);b=new bf(d,a,b,c);try{this.dispatchEvent(b)}finally{b.B()}};
af.prototype.c=function(){af.a.c.call(this);O(this.we);delete this.we};function bf(a,b,c,d){b&&this.rb(b,void 0);this.type="mousewheel";this.detail=a;this.lb=c;this.mb=d}A(bf,Zb);function cf(a,b,c,d){if(!x(a)||!x(b))throw Error("Start and end parameters must be arrays");if(a.length!=b.length)throw Error("Start and end points must be the same length");this.Ab=a;this.af=b;this.duration=c;this.Nd=d;this.coords=[]}A(cf,P);var df={},ef=null;
function ff(){Ce.clearTimeout(ef);var a=oa();for(var b in df)gf(df[b],a);ef=Xa(df)?null:Ce.setTimeout(ff,20)}function hf(a){a=z(a);delete df[a];if(ef&&Xa(df)){Ce.clearTimeout(ef);ef=null}}s=cf.prototype;s.i=0;s.ce=0;s.fa=0;s.startTime=null;s.Zd=null;s.od=null;
s.play=function(a){if(a||this.i==0){this.fa=0;this.coords=this.Ab}else if(this.i==1)return false;hf(this);this.startTime=oa();if(this.i==-1)this.startTime-=this.duration*this.fa;this.Zd=this.startTime+this.duration;this.od=this.startTime;this.fa||this.Vb();jf(this,"play");this.i==-1&&jf(this,"resume");this.i=1;a=z(this);a in df||(df[a]=this);ef||(ef=Ce.setTimeout(ff,20));gf(this,this.startTime);return true};s.stop=function(a){hf(this);this.i=0;if(a)this.fa=1;kf(this,this.fa);jf(this,"stop");this.zc()};
s.c=function(){this.i!=0&&this.stop(false);jf(this,"destroy");cf.a.c.call(this)};function gf(a,b){a.fa=(b-a.startTime)/(a.Zd-a.startTime);if(a.fa>=1)a.fa=1;a.ce=1E3/(b-a.od);a.od=b;ha(a.Nd)?kf(a,a.Nd(a.fa)):kf(a,a.fa);if(a.fa==1){a.i=0;hf(a);jf(a,"finish");a.zc()}else a.i==1&&a.ud()}function kf(a,b){a.coords=Array(a.Ab.length);for(var c=0;c<a.Ab.length;c++)a.coords[c]=(a.af[c]-a.Ab[c])*b+a.Ab[c]}s.ud=function(){jf(this,"animate")};s.Vb=function(){jf(this,"begin")};s.zc=function(){jf(this,"end")};
function jf(a,b){a.dispatchEvent(new lf(b,a))}function lf(a,b){L.call(this,a);this.coords=b.coords;this.x=b.coords[0];this.y=b.coords[1];this.kg=b.coords[2];this.duration=b.duration;this.fa=b.fa;this.bg=b.ce;this.ig=b.i;this.Zf=b}A(lf,L);function mf(a,b,c){this.target=a;this.handle=b||a;this.ve=c||new Jc(NaN,NaN,NaN,NaN);this.m=K(a);this.va=new td(this);N(this.handle,"mousedown",this.Ie,false,this)}A(mf,P);var nf=F||G&&I("1.9.3");s=mf.prototype;s.screenX=0;s.screenY=0;s.Je=0;s.Ke=0;s.lb=0;s.mb=0;
s.S=true;s.La=false;s.pe=0;s.Af=0;s.xf=false;s.Z=e("va");s.Ga=ba("S");s.c=function(){mf.a.c.call(this);zc(this.handle,"mousedown",this.Ie,false,this);this.va.B();delete this.target;delete this.handle;delete this.va};
s.Ie=function(a){if(this.S&&!this.La&&(a.type!="mousedown"||ac(a,0))){if(this.pe==0){of(this,a);if(this.La)a.preventDefault();else return}else a.preventDefault();var b=this.m,c=b.documentElement,d=!nf;this.va.h(b,"mousemove",this.Bf,d);this.va.h(b,"mouseup",this.mc,d);if(nf){c.setCapture(false);this.va.h(c,"losecapture",this.mc)}else this.va.h(b?b.parentWindow||b.defaultView:window,"blur",this.mc);F&&this.xf&&this.va.h(b,"dragstart",Yb);this.Mf&&this.va.h(this.Mf,"scroll",this.Ff,d);this.screenX=
this.Je=a.screenX;this.screenY=this.Ke=a.screenY;this.lb=this.target.offsetLeft;this.mb=this.target.offsetTop;this.Wb=Ub(J(this.m));this.Af=oa()}};function of(a,b){if(a.dispatchEvent(new pf("start",a,b.clientX,b.clientY,b))!==false)a.La=true}s.mc=function(a,b){vd(this.va);nf&&this.m.releaseCapture();if(this.La){this.La=false;this.dispatchEvent(new pf("end",this,a.clientX,a.clientY,a,qf(this,this.lb),rf(this,this.mb),b))}};
s.Bf=function(a){if(this.S){var b=a.screenX-this.screenX,c=a.screenY-this.screenY;this.screenX=a.screenX;this.screenY=a.screenY;if(!this.La){var d=this.Je-this.screenX,f=this.Ke-this.screenY;if(d*d+f*f>this.pe){of(this,a);if(!this.La){this.mc(a);return}}}c=sf(this,b,c);b=c.x;c=c.y;if(this.La)if(this.dispatchEvent(new pf("beforedrag",this,a.clientX,a.clientY,a,b,c))!==false){tf(this,a,b,c,false);a.preventDefault()}}};
function sf(a,b,c){var d=Ub(J(a.m));b+=d.x-a.Wb.x;c+=d.y-a.Wb.y;a.Wb=d;a.lb+=b;a.mb+=c;return new D(qf(a,a.lb),rf(a,a.mb))}s.Ff=function(a){var b=sf(this,0,0);a.clientX=this.Wb.x-this.screenX;a.clientY=this.Wb.x-this.screenY;tf(this,a,b.x,b.y,true)};function tf(a,b,c,d){a.Rc(c,d);a.dispatchEvent(new pf("drag",a,b.clientX,b.clientY,b,c,d))}function qf(a,b){var c=a.ve,d=!isNaN(c.left)?c.left:null;c=!isNaN(c.width)?c.width:0;return Math.min(d!=null?d+c:Infinity,Math.max(d!=null?d:-Infinity,b))}
function rf(a,b){var c=a.ve,d=!isNaN(c.top)?c.top:null;c=!isNaN(c.height)?c.height:0;return Math.min(d!=null?d+c:Infinity,Math.max(d!=null?d:-Infinity,b))}s.Rc=function(a,b){this.target.style.left=a+"px";this.target.style.top=b+"px"};function pf(a,b,c,d,f,g,h,j){L.call(this,a);this.clientX=c;this.clientY=d;this.$f=f;this.left=g!==undefined?g:b.lb;this.top=h!==undefined?h:b.mb;this.Yd=b;this.ag=!!j}A(pf,L);function uf(a,b,c,d,f){cf.call(this,b,c,d,f);this.element=a}A(uf,cf);uf.prototype.Jc=u;
uf.prototype.ud=function(){this.Jc();uf.a.ud.call(this)};uf.prototype.zc=function(){this.Jc();uf.a.zc.call(this)};uf.prototype.Vb=function(){this.Jc();uf.a.Vb.call(this)};function vf(a,b,c){if(b.length!=2||c.length!=2)throw Error("Start and end points must be 2D");uf.apply(this,arguments)}A(vf,uf);vf.prototype.Jc=function(){this.element.style.left=Math.round(this.coords[0])+"px";this.element.style.top=Math.round(this.coords[1])+"px"};
function wf(a,b,c,d){vf.call(this,a,[a.offsetLeft,a.offsetTop],b,c,d)}A(wf,vf);wf.prototype.Vb=function(){this.Ab=[this.element.offsetLeft,this.element.offsetTop];wf.a.Vb.call(this)};function xf(){}A(xf,P);s=xf.prototype;s.ta=0;s.qa=0;s.ja=100;s.ea=0;s.Sa=1;s.ba=false;s.cb=false;s.z=function(a){a=yf(this,a);if(this.ta!=a){this.ta=a+this.ea>this.ja?this.ja-this.ea:a<this.qa?this.qa:a;!this.ba&&!this.cb&&this.dispatchEvent("change")}};s.o=function(){return yf(this,this.ta)};
s.xb=function(a){a=yf(this,a);if(this.ea!=a){this.ea=a<0?0:this.ta+a>this.ja?this.ja-this.ta:a;!this.ba&&!this.cb&&this.dispatchEvent("change")}};s.Da=function(){var a;a=this.ea;a=this.Sa==null?a:Math.round(a/this.Sa)*this.Sa;return a};s.Bd=function(a){if(this.qa!=a){var b=this.ba;this.ba=true;this.qa=a;if(a+this.ea>this.ja)this.ea=this.ja-this.qa;a>this.ta&&this.z(a);if(a>this.ja){this.ea=0;this.Fc(a);this.z(a)}this.ba=b;!this.ba&&!this.cb&&this.dispatchEvent("change")}};
s.P=function(){return yf(this,this.qa)};s.Fc=function(a){a=yf(this,a);if(this.ja!=a){var b=this.ba;this.ba=true;this.ja=a;a<this.ta+this.ea&&this.z(a-this.ea);if(a<this.qa){this.ea=0;this.Bd(a);this.z(this.ja)}if(a<this.qa+this.ea)this.ea=this.ja-this.qa;this.ba=b;!this.ba&&!this.cb&&this.dispatchEvent("change")}};s.T=function(){return yf(this,this.ja)};
s.Fd=function(a){if(this.Sa!=a){this.Sa=a;a=this.ba;this.ba=true;this.Fc(this.T());this.xb(this.Da());this.z(this.o());this.ba=a;!this.ba&&!this.cb&&this.dispatchEvent("change")}};function yf(a,b){if(a.Sa==null)return b;return a.qa+Math.round((b-a.qa)/a.Sa)*a.Sa}function zf(a){R.call(this,a);this.j=new xf;N(this.j,"change",this.tf,false,this)}A(zf,R);s=zf.prototype;s.v="horizontal";s.ld=false;s.Cf=false;s.Ha=10;s.Ub=0;s.f=function(){zf.a.f.call(this);this.ua(this.C().f("div",this.g(this.v)))};
s.ua=function(a){zf.a.ua.call(this,a);Qa(a,this.g(this.v));a=this.b();a=Bb(document,null,"goog-twothumbslider-value-thumb",a)[0];var b=this.b();b=Bb(document,null,"goog-twothumbslider-extent-thumb",b)[0];if(!a){a=Af(this,"goog-twothumbslider-value-thumb");this.b().appendChild(a)}if(!b){b=Af(this,"goog-twothumbslider-extent-thumb");this.b().appendChild(b)}this.F=a;this.aa=b;id(this.b(),"slider");Bf(this)};
s.N=function(){zf.a.N.call(this);this.Kc=new mf(this.F);this.be=new mf(this.aa);this.Kc.Rc=this.be.Rc=u;this.V=new md(this.b());this.yc=new af(this.b());this.Z().h(this.Kc,"beforedrag",this.je).h(this.be,"beforedrag",this.je).h(this.V,"key",this.bd).h(this.b(),"mousedown",this.qf).h(this.yc,"mousewheel",this.rf);this.b().tabIndex=0;Cf(this)};
s.je=function(a){var b=a.Yd==this.Kc?this.F:this.aa,c;if(this.v=="vertical"){c=this.b().clientHeight-b.offsetHeight;c=(c-a.top)/c*(this.T()-this.P())+this.P()}else{c=this.b().clientWidth-b.offsetWidth;c=a.left/c*(this.T()-this.P())+this.P()}c=a.Yd==this.Kc?Math.min(Math.max(c,this.P()),this.o()+this.Da()):Math.min(Math.max(c,this.o()),this.T());Df(this,b,c)};
s.bd=function(a){var b=true;switch(a.keyCode){case 36:Ef(this,this.P());break;case 35:Ef(this,this.T());break;case 33:Ff(this,this.Ha);break;case 34:Ff(this,-this.Ha);break;case 37:case 40:Ff(this,a.shiftKey?-this.Ha:-this.Kd);break;case 39:case 38:Ff(this,a.shiftKey?this.Ha:this.Kd);break;default:b=false}b&&a.preventDefault()};
s.qf=function(a){this.b().focus&&this.b().focus();var b=a.target;if(!Lb(this.F,b)&&!Lb(this.aa,b))if(this.Cf)Ef(this,Gf(this,a));else{this.Id(a);this.la=Hf(this,Gf(this,a));this.qe=this.v=="vertical"?this.vc<this.la.offsetTop:this.vc>this.la.offsetLeft+this.la.offsetWidth;a=K(this.b());this.Z().h(a,"mouseup",this.le,true).h(this.b(),"mousemove",this.Id);if(!this.Na){this.Na=new Be(200);this.Z().h(this.Na,De,this.me)}this.me();this.Na.start()}};s.rf=function(a){Ff(this,(a.detail>0?-1:1)*this.Kd);a.preventDefault()};
s.me=function(){var a;if(this.v=="vertical"){var b=this.vc,c=this.la.offsetTop;if(this.qe){if(b<c)a=If(this,this.la)+this.Ha}else if(b>c+this.la.offsetHeight)a=If(this,this.la)-this.Ha}else{b=this.vc;c=this.la.offsetLeft;if(this.qe){if(b>c+this.la.offsetWidth)a=If(this,this.la)+this.Ha}else if(b<c)a=If(this,this.la)-this.Ha}a!==undefined&&Df(this,this.la,a)};s.le=function(){this.Na&&this.Na.stop();var a=K(this.b());this.Z().ha(a,"mouseup",this.le,true).ha(this.b(),"mousemove",this.Id)};
function Jf(a,b){var c,d=a.b();c=Tc(b);d=Tc(d);c=new D(c.x-d.x,c.y-d.y);return a.v=="vertical"?c.y:c.x}s.Id=function(a){this.vc=Jf(this,a)};function Gf(a,b){var c=a.P(),d=a.T();if(a.v=="vertical"){var f=a.F.offsetHeight,g=a.b().clientHeight-f;f=Jf(a,b)-f/2;return(d-c)*(g-f)/g+c}else{f=a.F.offsetWidth;g=a.b().clientWidth-f;f=Jf(a,b)-f/2;return(d-c)*f/g+c}}
function If(a,b){if(b==a.F)return a.j.o();else if(b==a.aa)return a.j.o()+a.j.Da();else throw Error("Illegal thumb element. Neither minThumb nor maxThumb");}function Ff(a,b){var c=If(a,a.F)+b,d=If(a,a.aa)+b;c=Math.min(Math.max(c,a.P()),a.T()-a.Ub);d=Math.min(Math.max(d,a.P()+a.Ub),a.T());Lf(a,c,d-c)}
function Df(a,b,c){var d=null;if(b==a.aa&&c<=a.j.T()&&c>=a.j.o()+a.Ub)d=c-a.j.o();var f=d||a.j.Da();if(b==a.F&&c>=a.P()&&c<=a.j.o()+f-a.Ub){b=f-(c-a.j.o());if(yf(a.j,c)+yf(a.j,b)==yf(a.j,c+b)){Lf(a,c,b);d=null}}d!=null&&a.j.xb(d)}function Lf(a,b,c){if(a.P()<=b&&b<=a.T()-c&&a.Ub<=c&&c<=a.T()-b)if(!(b==a.o()&&c==a.Da())){a.j.cb=true;a.j.xb(0);a.j.z(b);a.j.xb(c);a.j.cb=false;Cf(a);a.dispatchEvent("change")}}s.P=function(){return this.j.P()};s.Bd=function(a){this.j.Bd(a)};s.T=function(){return this.j.T()};
s.Fc=function(a){this.j.Fc(a)};function Hf(a,b){return b<=a.j.o()+a.j.Da()/2?a.F:a.aa}s.tf=function(){Cf(this);Bf(this);this.dispatchEvent("change")};function Cf(a){if(a.F&&!a.ld){var b=Mf(a,If(a,a.F)),c=Mf(a,If(a,a.aa));if(a.v=="vertical"){a.F.style.top=b.y+"px";a.aa.style.top=c.y+"px"}else{a.F.style.left=b.x+"px";a.aa.style.left=c.x+"px"}}}
function Mf(a,b){var c=new D;if(a.F){var d=a.P(),f=a.T();d=b==d&&d==f?0:(b-d)/(f-d);if(a.v=="vertical"){f=a.F.offsetHeight;f=a.b().clientHeight-f;c.y=f-Math.round(d*f)}else{f=a.b().clientWidth-a.F.offsetWidth;c.x=Math.round(d*f)}}return c}function Ef(a,b){b=Math.min(a.T(),Math.max(b,a.P()));a.Fb&&a.Fb.stop(true);var c=Hf(a,b),d=Mf(a,b);d=new wf(c,a.v=="vertical"?[c.offsetLeft,d.y]:[d.x,c.offsetTop],100);a.Fb=d;a.Z().h(d,"end",a.$e);a.ld=true;Df(a,c,b);d.play(false)}s.$e=function(){this.ld=false};
s.Cd=function(a){if(this.v!=a){var b=this.g(this.v),c=this.g(a);this.v=a;if(this.b()){a=this.b();for(var d=Pa(a),f=false,g=0;g<d.length;g++)if(d[g]==b){Ma(d,g--,1);f=true}if(f){d.push(c);a.className=d.join(" ")}this.F.style.left=this.F.style.top="";this.aa.style.left=this.aa.style.top="";Cf(this)}}};
s.c=function(){zf.a.c.call(this);this.Na&&this.Na.B();delete this.Na;this.Fb&&this.Fb.B();delete this.Fb;delete this.F;delete this.aa;this.j.B();delete this.j;if(this.V){this.V.B();delete this.V}if(this.yc){this.yc.B();delete this.yc}};s.Kd=1;s.Fd=function(a){this.j.Fd(a)};s.o=function(){return this.j.o()};s.z=function(a){Df(this,this.F,a)};s.Da=function(){return this.j.Da()};s.xb=function(a){Df(this,this.aa,this.j.o()+a)};s.ka=function(a){Zc(this.b(),a);a&&Cf(this)};
function Bf(a){var b=a.b();if(b){jd(b,"valuemin",a.P());jd(b,"valuemax",a.T());jd(b,"valuenow",a.o())}}function Nf(a){zf.call(this,a);this.j.z(this.P());this.j.xb(this.T()-this.P())}A(Nf,zf);Nf.prototype.g=function(a){return"goog-twothumbslider-"+a};function Af(a,b){var c=a.C().f("div",b);id(c,"button");return c}function Of(a){if(typeof a.pc=="function")return a.pc();if(y(a))return a.split("");if(fa(a)){for(var b=[],c=a.length,d=0;d<c;d++)b.push(a[d]);return b}return Va(a)}
function Pf(a,b,c){if(typeof a.forEach=="function")a.forEach(b,c);else if(fa(a)||y(a))C(a,b,c);else{var d;if(typeof a.Xc=="function")d=a.Xc();else if(typeof a.pc!="function")if(fa(a)||y(a)){d=[];for(var f=a.length,g=0;g<f;g++)d.push(g);d=d}else d=Wa(a);else d=void 0;f=Of(a);g=f.length;for(var h=0;h<g;h++)b.call(c,f[h],d&&d[h],a)}}
function Qf(a){this.Pa={};this.p=[];var b=arguments.length;if(b>1){if(b%2)throw Error("Uneven number of arguments");for(var c=0;c<b;c+=2)Rf(this,arguments[c],arguments[c+1])}else if(a){if(a instanceof Qf){b=a.Xc();c=a.pc()}else{b=Wa(a);c=Va(a)}for(var d=0;d<b.length;d++)Rf(this,b[d],c[d])}}s=Qf.prototype;s.Y=0;s.Oe=0;s.pc=function(){Sf(this);for(var a=[],b=0;b<this.p.length;b++)a.push(this.Pa[this.p[b]]);return a};s.Xc=function(){Sf(this);return this.p.concat()};
s.clear=function(){this.Pa={};this.Oe=this.Y=this.p.length=0};function Sf(a){if(a.Y!=a.p.length){for(var b=0,c=0;b<a.p.length;){var d=a.p[b];if(Object.prototype.hasOwnProperty.call(a.Pa,d))a.p[c++]=d;b++}a.p.length=c}if(a.Y!=a.p.length){var f={};for(c=b=0;b<a.p.length;){d=a.p[b];if(!Object.prototype.hasOwnProperty.call(f,d)){a.p[c++]=d;f[d]=1}b++}a.p.length=c}}s.Vc=function(a,b){if(Object.prototype.hasOwnProperty.call(this.Pa,a))return this.Pa[a];return b};
function Rf(a,b,c){if(!Object.prototype.hasOwnProperty.call(a.Pa,b)){a.Y++;a.p.push(b);a.Oe++}a.Pa[b]=c}s.Ja=function(){return new Qf(this)};function Tf(a){return Uf(a||arguments.callee.caller,[])}
function Uf(a,b){var c=[];if(Ha(b,a))c.push("[...circular reference...]");else if(a&&b.length<50){c.push(Vf(a)+"(");for(var d=a.arguments,f=0;f<d.length;f++){f>0&&c.push(", ");var g;g=d[f];switch(typeof g){case "object":g=g?"object":"null";break;case "string":g=g;break;case "number":g=String(g);break;case "boolean":g=g?"true":"false";break;case "function":g=(g=Vf(g))?g:"[fn]";break;case "undefined":default:g=typeof g;break}if(g.length>40)g=g.substr(0,40)+"...";c.push(g)}b.push(a);c.push(")\n");try{c.push(Uf(a.caller,
b))}catch(h){c.push("[exception trying to get caller]\n")}}else a?c.push("[...long stack...]"):c.push("[end]");return c.join("")}function Vf(a){a=String(a);if(!Wf[a]){var b=/function ([^\(]+)/.exec(a);Wf[a]=b?b[1]:"[Anonymous]"}return Wf[a]}var Wf={};function Xf(a,b,c,d,f){this.reset(a,b,c,d,f)}Xf.prototype.Nf=0;Xf.prototype.ae=null;Xf.prototype.$d=null;var Yf=0;Xf.prototype.reset=function(a,b,c,d,f){this.Nf=typeof f=="number"?f:Yf++;this.jg=d||oa();this.Tb=a;this.gg=b;this.eg=c;delete this.ae;delete this.$d};
Xf.prototype.Ee=ba("Tb");function Zf(a){this.Df=a}Zf.prototype.t=null;Zf.prototype.Tb=null;Zf.prototype.M=null;Zf.prototype.oe=null;function $f(a,b){this.name=a;this.value=b}$f.prototype.toString=e("name");var ag=new $f("SEVERE",1E3),bg=new $f("WARNING",900),cg=new $f("CONFIG",700),dg=new $f("FINE",500),eg=new $f("FINEST",300);Zf.prototype.Ee=ba("Tb");function fg(a){if(a.Tb)return a.Tb;if(a.t)return fg(a.t);Da("Root logger has no level set.");return null}
Zf.prototype.log=function(a,b,c){if(a.value>=fg(this).value){a=this.df(a,b,c);for(b=this;b;){c=b;var d=a;if(c.oe)for(var f=0,g=void 0;g=c.oe[f];f++)g(d);b=b.t}}};
Zf.prototype.df=function(a,b,c){var d=new Xf(a,String(b),this.Df);if(c){d.ae=c;var f;var g=arguments.callee.caller;try{var h,j=da("window.location.href");h=typeof c=="string"?{message:c,name:"Unknown error",lineNumber:"Not available",fileName:j,stack:"Not available"}:!c.lineNumber||!c.fileName||!c.stack?{message:c.message,name:c.name,lineNumber:c.lineNumber||c.dg||"Not available",fileName:c.fileName||c.filename||c.sourceURL||j,stack:c.stack||"Not available"}:c;f="Message: "+sa(h.message)+'\nUrl: <a href="view-source:'+
h.fileName+'" target="_new">'+h.fileName+"</a>\nLine: "+h.lineNumber+"\n\nBrowser stack:\n"+sa(h.stack+"-> ")+"[end]\n\nJS stack traversal:\n"+sa(Tf(g)+"-> ")}catch(i){f="Exception trying to expose exception! You win, we lose. "+i}d.$d=f}return d};function Z(a,b,c){a.log(dg,b,c)}var gg={},hg=null;
function ig(a){if(!hg){hg=new Zf("");gg[""]=hg;hg.Ee(cg)}var b;if(!(b=gg[a])){b=new Zf(a);var c=a.lastIndexOf("."),d=a.substr(0,c);c=a.substr(c+1);d=ig(d);if(!d.M)d.M={};d.M[c]=b;b.t=d;b=gg[a]=b}return b}function jg(){}jg.prototype.ic=null;function kg(){return lg(mg)}var mg;function ng(){}A(ng,jg);function lg(a){return(a=og(a))?new ActiveXObject(a):new XMLHttpRequest}function pg(a){var b={};if(og(a)){b[0]=true;b[1]=true}return b}ng.prototype.hd=null;
function og(a){if(!a.hd&&typeof XMLHttpRequest=="undefined"&&typeof ActiveXObject!="undefined"){for(var b=["MSXML2.XMLHTTP.6.0","MSXML2.XMLHTTP.3.0","MSXML2.XMLHTTP","Microsoft.XMLHTTP"],c=0;c<b.length;c++){var d=b[c];try{new ActiveXObject(d);return a.hd=d}catch(f){}}throw Error("Could not create ActiveXObject. ActiveX might be disabled, or MSXML might not be installed");}return a.hd}mg=new ng;function qg(){if(G){this.Va={};this.Nc={};this.Hc=[]}}qg.prototype.Q=ig("goog.net.xhrMonitor");
qg.prototype.S=G;qg.prototype.Ga=function(a){this.S=G&&a};function rg(a,b){if(a.S){var c=y(b)?b:ia(b)?z(b):"";a.Q.log(eg,"Pushing context: "+b+" ("+c+")",void 0);a.Hc.push(c)}}function sg(a){if(a.S){var b=a.Hc.pop();a.Q.log(eg,"Popping context: "+b,void 0);tg(a,b)}}function ug(a,b){if(a.S){var c=z(b);Z(a.Q,"Opening XHR : "+c);for(var d=0;d<a.Hc.length;d++){var f=a.Hc[d];vg(a,a.Va,f,c);vg(a,a.Nc,c,f)}}}
function tg(a,b){var c=a.Nc[b],d=a.Va[b];if(c&&d){a.Q.log(eg,"Updating dependent contexts",void 0);C(c,function(f){C(d,function(g){vg(this,this.Va,f,g);vg(this,this.Nc,g,f)},this)},a)}}function vg(a,b,c,d){b[c]||(b[c]=[]);Ha(b[c],d)||b[c].push(d)}var $=new qg;function wg(a){this.headers=new Qf;this.Db=a||null}A(wg,P);wg.prototype.Q=ig("goog.net.XhrIo");var xg=[];function yg(a,b,c,d,f,g){var h=new wg;xg.push(h);b&&N(h,"complete",b);N(h,"ready",na(zg,h));if(g)h.cc=Math.max(0,g);h.send(a,c,d,f)}
function zg(a){a.B();Ia(xg,a)}s=wg.prototype;s.Aa=false;s.u=null;s.Mc=null;s.ue="";s.te="";s.Qb=0;s.Rb="";s.Tc=false;s.sc=false;s.jd=false;s.$a=false;s.cc=0;s.gb=null;
s.send=function(a,b,c,d){if(this.Aa)throw Error("[goog.net.XhrIo] Object is active with another request");b=b||"GET";this.ue=a;this.Rb="";this.Qb=0;this.te=b;this.Tc=false;this.Aa=true;this.u=this.Db?lg(this.Db):new kg;this.Mc=this.Db?this.Db.ic||(this.Db.ic=pg(this.Db)):mg.ic||(mg.ic=pg(mg));ug($,this.u);this.u.onreadystatechange=ma(this.Be,this);try{Z(this.Q,Ag(this,"Opening Xhr"));this.jd=true;this.u.open(b,a,true);this.jd=false}catch(f){Z(this.Q,Ag(this,"Error opening Xhr: "+f.message));Bg(this,
5,f);return}a=c||"";var g=this.headers.Ja();d&&Pf(d,function(j,i){Rf(g,i,j)});b=="POST"&&!Object.prototype.hasOwnProperty.call(g.Pa,"Content-Type")&&Rf(g,"Content-Type","application/x-www-form-urlencoded;charset=utf-8");Pf(g,function(j,i){this.u.setRequestHeader(i,j)},this);try{if(this.gb){Ce.clearTimeout(this.gb);this.gb=null}if(this.cc>0){Z(this.Q,Ag(this,"Will abort after "+this.cc+"ms if incomplete"));this.gb=Ce.setTimeout(ma(this.Vf,this),this.cc)}Z(this.Q,Ag(this,"Sending request"));this.sc=
true;this.u.send(a);this.sc=false}catch(h){Z(this.Q,Ag(this,"Send error: "+h.message));Bg(this,5,h)}};s.dispatchEvent=function(a){if(this.u){rg($,this.u);try{return wg.a.dispatchEvent.call(this,a)}finally{sg($)}}else return wg.a.dispatchEvent.call(this,a)};s.Vf=function(){if(typeof ca!="undefined")if(this.u){this.Rb="Timed out after "+this.cc+"ms, aborting";this.Qb=8;Z(this.Q,Ag(this,this.Rb));this.dispatchEvent("timeout");this.abort(8)}};
function Bg(a,b,c){a.Aa=false;if(a.u){a.$a=true;a.u.abort();a.$a=false}a.Rb=c;a.Qb=b;Cg(a);Dg(a)}function Cg(a){if(!a.Tc){a.Tc=true;a.dispatchEvent("complete");a.dispatchEvent("error")}}s.abort=function(a){if(this.u){Z(this.Q,Ag(this,"Aborting"));this.Aa=false;this.$a=true;this.u.abort();this.$a=false;this.Qb=a||7;this.dispatchEvent("complete");this.dispatchEvent("abort");Dg(this)}};s.c=function(){if(this.u){if(this.Aa){this.Aa=false;this.$a=true;this.u.abort();this.$a=false}Dg(this,true)}wg.a.c.call(this)};
s.Be=function(){!this.jd&&!this.sc&&!this.$a?this.vd():Eg(this)};s.vd=function(){Eg(this)};
function Eg(a){if(a.Aa)if(typeof ca!="undefined")if(a.Mc[1]&&Fg(a)==4&&Gg(a)==2)Z(a.Q,Ag(a,"Local request error detected and ignored"));else if(a.sc&&Fg(a)==4)Ce.setTimeout(ma(a.Be,a),0);else{a.dispatchEvent("readystatechange");if(Fg(a)==4){Z(a.Q,Ag(a,"Request complete"));a.Aa=false;var b;a:switch(Gg(a)){case 0:case 200:case 204:case 304:b=true;break a;default:b=false;break a}if(b){a.dispatchEvent("complete");a.dispatchEvent("success")}else{a.Qb=6;var c;try{c=Fg(a)>2?a.u.statusText:""}catch(d){Z(a.Q,
"Can not get status: "+d.message);c=""}a.Rb=c+" ["+Gg(a)+"]";Cg(a)}Dg(a)}}}function Dg(a,b){if(a.u){var c=a.u,d=a.Mc[0]?u:null;a.u=null;a.Mc=null;if(a.gb){Ce.clearTimeout(a.gb);a.gb=null}if(!b){rg($,c);a.dispatchEvent("ready");sg($)}if($.S){var f=z(c);Z($.Q,"Closing XHR : "+f);delete $.Nc[f];for(var g in $.Va){Ia($.Va[g],f);$.Va[g].length==0&&delete $.Va[g]}}try{c.onreadystatechange=d}catch(h){a.Q.log(ag,"Problem encountered resetting onreadystatechange: "+h.message,void 0)}}}s.Pb=e("Aa");
function Fg(a){return a.u?a.u.readyState:0}function Gg(a){try{return Fg(a)>2?a.u.status:-1}catch(b){a.Q.log(bg,"Can not get status: "+b.message,void 0);return-1}}function Ag(a,b){return b+" ["+a.te+" "+a.ue+" "+Gg(a)+"]"}Vb[Vb.length]=function(a){wg.prototype.vd=a.Xf(wg.prototype.vd)};hte2.ib=function(a){return document.getElementById(a)};hte2.Ld=function(a,b){var c=[],d,f,g;d=b.getElementsByTagName("*");f=d.length;for(g=0;g<f;g+=1)d[g].className===a&&c.push(d[g]);return c};ig("goog.dom.SavedRange");
ig("goog.dom.browserrange.IeRange");hte2.fc=function(){N(hte2.K.Xa(),"click",this.Ad)};hte2.fc.prototype={Ad:function(a){var b;b=a.target;a=a.clientX;a-=hte2.K.Xa().offsetLeft;if(b.nodeName==="SPAN"){a-=parseInt(b.parentNode.style.paddingLeft,10);hte2.k.Fe(b.parentNode,a-8)}}};hte2.ec=function(){var a=new md(document);N(a,"key",this.kd)};
hte2.ec.prototype={kd:function(a){var b;a.preventDefault();switch(a.keyCode){case 37:hte2.k.Ic();break;case 39:hte2.k.Bb();break;case 38:hte2.k.rd();break;case 40:hte2.k.qd();break;case 8:hte2.k.Ic();hte2.K.Dc(hte2.A.X(hte2.k.Ma()).ca);break;case 46:hte2.K.Dc(hte2.A.X(hte2.k.Ma()).ca);break;case 13:hte2.K.gc(hte2.A.X(hte2.k.Ma()).ca-1);hte2.k.Bb();break;default:if(a.charCode!==undefined&&a.charCode!==0){b=hte2.A.X(hte2.k.Ma()).ca-1;hte2.K.Od(a.charCode,b);hte2.k.Bb()}break}hte2.k.xd()}};
hte2.Md=function(){this.Of=new bd;this.yd={id:Math.round(Math.random()*1E5),jsonrpc:"2.0"}};hte2.Md.prototype={Kf:function(a,b){this.yd.method=b;this.yd.params={document:a};yg("/",function(c){console.log(c)},"POST",cd(this.Of,this.yd),{"Content-Type":"application/json"})}};hte2.l=new hd;hte2.fc=function(){N(hte2.K.Xa(),"click",this.Ad)};
hte2.fc.prototype={Ad:function(a){var b;b=a.target;a=a.clientX;a-=hte2.K.Xa().offsetLeft;if(b.nodeName==="SPAN"){a-=parseInt(b.parentNode.style.paddingLeft,10);hte2.k.Fe(b.parentNode,a-8)}}};
hte2.k=function(){var a,b=0,c=0,d,f=[],g;g=function(h){var j=f.length,i;for(i=0;i<j;i+=1)f[i].Hf(h)};return d={Ma:function(){return b},ef:function(){return c},Gc:function(h){c=h;hte2.l.J("positionSet",c)},Ue:function(h){f.push(h)},Fe:function(h,j){a=h;var i=hte2.A.X(j,true);b=i.wd;d.Gc(i.ca);g(i)},Rf:function(h,j){a=h;var i=hte2.A.X(j);b=i.wd;d.Gc(i.ca);g(i)},fe:function(){return a},rd:function(){if(a.previousSibling.id!=="hte-cursor"){a=a.previousSibling;var h=hte2.A.X(b);hte2.l.J("positionSet",
h.ca);g(h)}},qd:function(){if(a.nextSibling){a=a.nextSibling;var h=hte2.A.X(b);hte2.l.J("positionSet",h.ca);g(h)}},Ic:function(){var h;b-=1;if(b<0){d.rd();b=a.firstChild.firstChild.nodeValue.length}h=hte2.A.X(b);d.Gc(h.ca);g(h)},Bb:function(){var h,j,i=0;b+=1;h=a.childNodes;for(j=0;j<h.length;j+=1)if(h[j].firstChild)i+=h[j].firstChild.nodeValue.length;if(b>i){d.qd();b-=i}h=hte2.A.X(b);d.Gc(h.ca);g(h)},xd:function(){g(hte2.A.X(b))}}}();
hte2.Se=function(){var a,b,c=0,d,f;a=hte2.ib("hte-cursor");setInterval(function(){a.style.display=a.style.display==="block"?"none":"block"},600);return b={Ge:function(g,h){a.style.left=g+"px";a.style.top=h+"px";d=g;f=h;a.style.display="block"},hf:function(){return{x:d,y:f}},Qf:function(g){a.style.height=g+"px"},Sf:function(g){c=g},cg:function(){return c},Hf:function(g){b.Ge(g.x,g.y);b.Qf(g.height);b.Sf(g.wd)}}}();
hte2.A=function(){var a,b,c,d;a=hte2.ib("hte-measurer");b=function(){var f,g,h,j=0;for(f=hte2.k.fe().previousSibling;f&&f.id!=="hte-cursor";){g=f.childNodes;for(h=0;h<g.length;h+=1)if(g[h].firstChild)j+=g[h].firstChild.nodeValue.length;f=f.previousSibling}return j-1};c=function(f){return f.offsetTop};d=function(f){return f.offsetHeight};return{X:function(f,g){var h=0,j,i=0,k,m,l,o,q=1,v;i=parseInt(hte2.K.Xa().style.paddingLeft,10);m=hte2.k.fe();o=m.childNodes;j=function(){return q<f};k=function(){return i<=
f};k=g?k:j;for(j=0;j<o.length;j+=1){l=o[j].firstChild;if(l!==null)for(l=l.nodeValue;k();){a.innerHTML='<span style="'+hte2.$.Ze(o[j])+'">'+l.charAt(h)+"</span>";i+=a.firstChild.offsetWidth;h+=1;q+=1;v=o[j];if(h===l.length)break}h=0}v||(v=o[0]);return{x:i+parseInt(m.style.paddingLeft,10),y:c(v),height:d(v),wd:q,ca:b()+q}},Kb:function(f){a.innerHTML=f;return a.offsetWidth}}}();
hte2.$=function(){var a,b=hte2.dataStorage.styling,c,d,f,g=false,h,j=hte2.dataStorage.paragraphs;f=d={style:{fs:12,ff:"Arial",fw:"normal",fst:"normal"},start:0,end:13};c={ff:["font-family","","fontFamily"],fw:["font-weight","","fontWeight"],fs:["font-size","pt","fontSize"],td:["text-decoration","","textDecoration"],fst:["font-style","","fontStyle"]};h=function(i,k,m){var l,o;for(l=0;l<b.length;l+=1)if(b[l].start<i&&b[l].end>=i){o=b[l].end;b[l].end=i-1;b.splice(l+1,0,{style:m,start:i,end:k});b[l+2]?
b.splice(l+2,0,{style:b[l].style,start:k+1,end:b[l+2].start-1}):b.splice(l+2,0,{style:b[l].style,start:k+1,end:o})}};return a={ie:function(){return b},gc:function(i){var k;for(k=0;k<j.length;k+=1)if(i<j[k].end){j.splice(k+1,0,{width:j[k].width,pl:j[k].pl,pr:j[k].pr,start:i,end:j[k].end});j[k].end=i-1;break}},Pf:function(i){var k,m=b;if(i){for(k=0;k<b.length;k+=1)if(b[k].start<=i-1)m=b[k];f=m.style;d=$a(m.style);g=false;hte2.l.J("styleChanged",d)}return d},Ye:function(i){d[i[0]]=i[1];g=true},Ne:function(i,
k){var m,l=[];for(m=0;m<b.length;m+=1){if(i<b[m].start&&b[m].start!==0)b[m].start+=k==="add"?1:-1;if(i<=b[m].end)b[m].end+=k==="add"?1:-1;l.push(b[m])}b=l;l=[];for(m=0;m<j.length;m+=1){if(k!=="add"&&i===j[m].start){j[m-1].end=j[m].end-1;j[m+1].start=j[m].end+1;j.splice(m,1)}if(i<j[m].start)j[m].start+=k==="add"?1:-1;if(i<=j[m].end)j[m].end+=k==="add"?1:-1;l.push(j[m])}j=l;g&&h(i+1,i+1,$a(d))},bf:function(i){var k,m="";for(k in i)if(i.hasOwnProperty(k))m+=c[k][0]+":"+i[k]+c[k][1]+";";return m},Ze:function(i){var k,
m="";for(k in c)if(c.hasOwnProperty(k))if(i.style[c[k][2]])m+=c[k][0]+":"+i.style[c[k][2]]+";";return m},cf:function(){return j},gf:function(i){return j[i]?j[i]:j[j.length-1]},ge:function(i){var k,m=0;for(k=0;k<j.length;k+=1)if(j[k].start<=i&&i<=j[k].end){m=k;break}return j[m]},Tf:function(i,k,m){var l=a.ge(hte2.k.ef());if(l.width!==i){l.width=i;l.pl=k;l.pr=m;hte2.l.J("rerender")}}}}();
hte2.K=function(){var a,b,c,d,f,g;a=(new Ab).ib("hte-workbench");c=hte2.dataStorage.docText.split("");f=function(){var h;h=c.join("").split("\n");h=h.join(" \n ");return h.split(" ")};d=function(h,j){var i,k;i=c.slice(0,j+1);k=c.slice(j+1);i.push(h);c=i.concat(k);hte2.$.Ne(j,"add")};g=hte2.$.bf;return{wb:function(){var h=hte2.$.ie(),j,i,k=0,m,l="",o=0,q,v,ta,r,p,rb,ja,Wd,Xd,Kf=0,Sb;q=f();m=i=0;p=hte2.Ld("hte-line",a);rb=false;for(j=0;j<q.length;j+=1){Sb=hte2.$.gf(Kf);b=parseInt(Sb.width,10);r=q[j]+
String.fromCharCode(160);v=o;ta=o+(r.length-1);if(r!=="\n"+String.fromCharCode(160))if(h[i].start<v&&ta<=h[i].end){ja=hte2.A.Kb('<span style="'+g(h[i].style)+'">'+r+"</span>");if(m+ja<b){m+=ja;l+=r}else{j-=1;rb=true;o-=r.length}}else if(ta>h[i].end){for(Xd="";r.length!==0;){ta-=1;r=r.split("");Xd+=r.pop();r=r.join("");if(ta===h[i].end){if(v<=h[i].start){r=r.split("");r.splice(0,h[i].start-v);r=r.join("");ja=hte2.A.Kb('<span style="'+g(h[i].style)+'">'+r+"</span>");Wd='<span style="'+g(h[i].style)+
'">'+r+"</span>"}else{ja=hte2.A.Kb('<span style="'+g(h[i].style)+'">'+r+"</span>");Wd=r+"</span>"}i+=1;j-=1;break}}v=hte2.A.Kb('<span style="'+g(h[i].style)+'">'+Xd+"</span>");if(m+(ja+v)<b){m+=ja;l+=Wd}else{i-=1;rb=true}o-=r.length}else{ja=hte2.A.Kb('<span style="'+g(h[i].style)+'">'+r.substr(h[i].start-v)+"</span>");if(m+ja<b){l+='<span style="'+g(h[i].style)+'">'+r.substr(h[i].start-v);m+=ja}else{j-=1;rb=true;o-=r.length}}else o-=2;o+=r.length;if(rb||r==="\n"+String.fromCharCode(160)){rb=false;
l+="</span>";if(p.length===0){m=(new hte2.Oc(Sb.pl)).Vc();a.appendChild(m);m.innerHTML=l}else if(p[k]){p[k].style.paddingLeft=Sb.pl+"px";p[k].innerHTML=l;k+=1}else{m=(new hte2.Oc(Sb.pl)).Vc();a.appendChild(m);m.innerHTML=l}l='<span style="'+g(h[i].style)+'">';m=0;if(r==="\n"+String.fromCharCode(160))Kf+=1}}if(p.length!==0&&p.length>k)for(j=k;j<p.length;j+=1)p[k].parentNode&&p[k].parentNode.removeChild(p[k])},Dc:function(h){c.splice(h,1);hte2.$.Ne(h,"remove");hte2.l.J("rerender")},gc:function(h){d("\n",
h);hte2.$.gc(h);hte2.l.J("rerender")},Od:function(h,j){d(String.fromCharCode(h),j);hte2.l.J("rerender")},Xa:function(){return a},jf:function(){return c}}}();hte2.Oc=function(a){var b;b=document.createElement("div");b.className="hte-line";b.style.paddingLeft=a+"px";this.zf=b};hte2.Oc.prototype={Vc:e("zf")};hte2.ec=function(){var a=new md(document);N(a,"key",this.kd)};
hte2.ec.prototype={kd:function(a){var b;a.preventDefault();switch(a.keyCode){case 37:hte2.k.Ic();break;case 39:hte2.k.Bb();break;case 38:hte2.k.rd();break;case 40:hte2.k.qd();break;case 8:hte2.k.Ic();hte2.K.Dc(hte2.A.X(hte2.k.Ma()).ca);break;case 46:hte2.K.Dc(hte2.A.X(hte2.k.Ma()).ca);break;case 13:hte2.K.gc(hte2.A.X(hte2.k.Ma()).ca-1);hte2.k.Bb();break;default:if(a.charCode!==undefined&&a.charCode!==0){b=hte2.A.X(hte2.k.Ma()).ca-1;hte2.K.Od(a.charCode,b);hte2.k.Bb()}break}hte2.k.xd()}};
hte2.Te=function(){var a,b=new Ab,c,d,f,g,h,j,i,k,m;c=new ze(b.f("div",{id:"hte-boldbutton"},b.createTextNode(String.fromCharCode(160))));Q(hte2.l,"styleChanged",function(l){l.fw==="bold"?Ud(c,true):Ud(c,false)});N(c,"action",function(){c.i&16?hte2.l.J("updateComputedStyle",["fw","bold"]):hte2.l.J("updateComputedStyle",["fw","normal"])});d=new ze(b.f("div",{id:"hte-italicbutton"},b.createTextNode(String.fromCharCode(160))));Q(hte2.l,"styleChanged",function(l){l.fst==="italic"?Ud(d,true):Ud(d,false)});
N(d,"action",function(){d.i&16?hte2.l.J("updateComputedStyle",["fst","italic"]):hte2.l.J("updateComputedStyle",["fst","normal"])});g=new ze(b.f("div",{id:"hte-underlinebutton"},b.createTextNode(String.fromCharCode(160))));Q(hte2.l,"styleChanged",function(l){l.td==="underline"?Ud(g,true):Ud(g,false)});N(g,"action",function(){g.i&16?hte2.l.J("updateComputedStyle",["td","underline"]):hte2.l.J("updateComputedStyle",["td","none"])});h=new ze(b.f("div",{id:"hte-linethroughbutton"},b.createTextNode(String.fromCharCode(160))));
Q(hte2.l,"styleChanged",function(l){l.td==="line-through"?Ud(h,true):Ud(h,false)});N(h,"action",function(){h.i&16?hte2.l.J("updateComputedStyle",["td","line-through"]):hte2.l.J("updateComputedStyle",["td","none"])});j=new $e("");j.L(new W("8"));j.L(new W("10"));j.L(new W("11"));j.L(new W("12"));j.L(new W("14"));j.L(new W("18"));j.L(new W("24"));j.L(new W("36"));j.z("12");Q(hte2.l,"styleChanged",function(l){j.z(l.fs)});N(j,"action",function(){hte2.l.J("updateComputedStyle",["fs",j.o()])});i=new $e("");
i.L(new W("Arial"));i.L(new W("Courier new"));i.L(new W("Times New Roman"));i.z("Arial");Q(hte2.l,"styleChanged",function(l){i.z(l.ff)});N(i,"action",function(){hte2.l.J("updateComputedStyle",["ff",i.o()])});f=new Ae(b.f("div",{id:"hte-savebutton"},b.createTextNode("Save")));N(f,"action",function(){var l={docText:hte2.K.jf().join(""),styling:hte2.$.ie(),paragraphs:hte2.$.cf()};(new hte2.Md).Kf(l,"save")});a=new qe;a.ia(f,true);a.ia(c,true);a.ia(d,true);a.ia(g,true);a.ia(h,true);a.ia(j,true);a.ia(i,
true);a.wb(b.ib("hte-panel"));k=new Nf;k.f();a=k.b();a.style.width="100%";a.style.height="10px";k.Fd(1);m=parseInt(hte2.K.Xa().style.width,10)/100;k.addEventListener("change",function(){var l,o;l=k.o()*m;o=(k.o()+k.Da())*m;hte2.l.J("pWidth",o-l,l,o)});k.wb(b.ib("hte-slider"));return{Wf:function(l){l=hte2.$.ge(l);Lf(k,l.pl/m,(l.pr-l.pl)/m)}}}();
(function(){var a=new Gc,b;b=function(){var c=a.he().height-60;Wc(y("hte-workbench-container")?document.getElementById("hte-workbench-container"):"hte-workbench-container",c)};b();N(a,"resize",function(){b()});hte2.K.wb();hte2.k.Ue(hte2.Se);hte2.k.Rf(hte2.Ld("hte-line",hte2.K.Xa())[0],1);new hte2.fc;new hte2.ec;Q(hte2.l,"rerender",hte2.K.wb);Q(hte2.l,"rangeReady",hte2.$.Yf);Q(hte2.l,"positionSet",hte2.$.Pf);Q(hte2.l,"positionSet",hte2.Te.Wf);Q(hte2.l,"updateComputedStyle",hte2.$.Ye);Q(hte2.l,"pWidth",
hte2.$.Tf);Q(hte2.l,"pWidth",hte2.k.xd)})();
