function aa(){return function(){}}function ba(a){return function(b){this[a]=b}}function e(a){return function(){return this[a]}}function p(a){return function(){return a}}var r,ca=ca||{},s=this;function da(a,b){for(var c=a.split("."),d=b||s,f;f=c.shift();)if(d[f])d=d[f];else return null;return d}function t(){}function u(a){a.Y=function(){return a.Df||(a.Df=new a)}}
function ea(a){var b=typeof a;if(b=="object")if(a){if(a instanceof Array||!(a instanceof Object)&&Object.prototype.toString.call(a)=="[object Array]"||typeof a.length=="number"&&typeof a.splice!="undefined"&&typeof a.propertyIsEnumerable!="undefined"&&!a.propertyIsEnumerable("splice"))return"array";if(!(a instanceof Object)&&(Object.prototype.toString.call(a)=="[object Function]"||typeof a.call!="undefined"&&typeof a.propertyIsEnumerable!="undefined"&&!a.propertyIsEnumerable("call")))return"function"}else return"null";
else if(b=="function"&&typeof a.call=="undefined")return"object";return b}function v(a){return ea(a)=="array"}function ga(a){var b=ea(a);return b=="array"||b=="object"&&typeof a.length=="number"}function w(a){return typeof a=="string"}function ha(a){return typeof a=="number"}function ia(a){return ea(a)=="function"}function ja(a){a=ea(a);return a=="object"||a=="array"||a=="function"}function x(a){if(a.hasOwnProperty&&a.hasOwnProperty(la))return a[la];a[la]||(a[la]=++ma);return a[la]}
var la="closure_uid_"+Math.floor(Math.random()*2147483648).toString(36),ma=0;function na(a,b){var c=b||s;if(arguments.length>2){var d=Array.prototype.slice.call(arguments,2);return function(){var f=Array.prototype.slice.call(arguments);Array.prototype.unshift.apply(f,d);return a.apply(c,f)}}else return function(){return a.apply(c,arguments)}}
function oa(a){var b=Array.prototype.slice.call(arguments,1);return function(){var c=Array.prototype.slice.call(arguments);c.unshift.apply(c,b);return a.apply(this,c)}}var pa=Date.now||function(){return+new Date};function y(a,b){function c(){}c.prototype=b.prototype;a.a=b.prototype;a.prototype=new c;a.prototype.constructor=a}function qa(a){this.stack=Error().stack||"";if(a)this.message=String(a)}y(qa,Error);qa.prototype.name="CustomError";
function ra(a){for(var b=1;b<arguments.length;b++){var c=String(arguments[b]).replace(/\$/g,"$$$$");a=a.replace(/\%s/,c)}return a}function sa(a){return a.replace(/^[\s\xa0]+|[\s\xa0]+$/g,"")}
function ta(a,b){if(b)return a.replace(ua,"&amp;").replace(va,"&lt;").replace(wa,"&gt;").replace(xa,"&quot;");else{if(!ya.test(a))return a;if(a.indexOf("&")!=-1)a=a.replace(ua,"&amp;");if(a.indexOf("<")!=-1)a=a.replace(va,"&lt;");if(a.indexOf(">")!=-1)a=a.replace(wa,"&gt;");if(a.indexOf('"')!=-1)a=a.replace(xa,"&quot;");return a}}var ua=/&/g,va=/</g,wa=/>/g,xa=/\"/g,ya=/[&<>\"]/;
function za(a,b){for(var c=0,d=sa(String(a)).split("."),f=sa(String(b)).split("."),g=Math.max(d.length,f.length),h=0;c==0&&h<g;h++){var i=d[h]||"",k=f[h]||"",j=RegExp("(\\d*)(\\D*)","g"),m=RegExp("(\\d*)(\\D*)","g");do{var l=j.exec(i)||["","",""],o=m.exec(k)||["","",""];if(l[0].length==0&&o[0].length==0)break;c=Aa(l[1].length==0?0:parseInt(l[1],10),o[1].length==0?0:parseInt(o[1],10))||Aa(l[2].length==0,o[2].length==0)||Aa(l[2],o[2])}while(c==0)}return c}
function Aa(a,b){if(a<b)return-1;else if(a>b)return 1;return 0}function Ba(a,b){b.unshift(a);qa.call(this,ra.apply(null,b));b.shift();this.ig=a}y(Ba,qa);Ba.prototype.name="AssertionError";function Ca(a,b){if(!a){var c=Array.prototype.slice.call(arguments,2),d="Assertion failed";if(b){d+=": "+b;var f=c}throw new Ba(""+d,f||[]);}}function Da(a){throw new Ba("Failure"+(a?": "+a:""),Array.prototype.slice.call(arguments,1));}
var z=Array.prototype,Ea=z.indexOf?function(a,b,c){Ca(a.length!=null);return z.indexOf.call(a,b,c)}:function(a,b,c){c=c==null?0:c<0?Math.max(0,a.length+c):c;if(w(a)){if(!w(b)||b.length!=1)return-1;return a.indexOf(b,c)}for(c=c;c<a.length;c++)if(c in a&&a[c]===b)return c;return-1},A=z.forEach?function(a,b,c){Ca(a.length!=null);z.forEach.call(a,b,c)}:function(a,b,c){for(var d=a.length,f=w(a)?a.split(""):a,g=0;g<d;g++)g in f&&b.call(c,f[g],g,a)},Fa=z.map?function(a,b,c){Ca(a.length!=null);return z.map.call(a,
b,c)}:function(a,b,c){for(var d=a.length,f=Array(d),g=w(a)?a.split(""):a,h=0;h<d;h++)if(h in g)f[h]=b.call(c,g[h],h,a);return f},Ga=z.every?function(a,b,c){Ca(a.length!=null);return z.every.call(a,b,c)}:function(a,b,c){for(var d=a.length,f=w(a)?a.split(""):a,g=0;g<d;g++)if(g in f&&!b.call(c,f[g],g,a))return false;return true};function Ha(a,b){return Ea(a,b)>=0}function Ia(a,b){var c=Ea(a,b),d;if(d=c>=0){Ca(a.length!=null);z.splice.call(a,c,1)}return d}
function Ja(){return z.concat.apply(z,arguments)}function Ka(a){if(v(a))return Ja(a);else{for(var b=[],c=0,d=a.length;c<d;c++)b[c]=a[c];return b}}function La(a){for(var b=1;b<arguments.length;b++){var c=arguments[b],d;if(v(c)||(d=ga(c))&&c.hasOwnProperty("callee"))a.push.apply(a,c);else if(d)for(var f=a.length,g=c.length,h=0;h<g;h++)a[f+h]=c[h];else a.push(c)}}function Na(a){Ca(a.length!=null);return z.splice.apply(a,Oa(arguments,1))}
function Oa(a,b,c){Ca(a.length!=null);return arguments.length<=2?z.slice.call(a,b):z.slice.call(a,b,c)}var Pa;function Qa(a){return(a=a.className)&&typeof a.split=="function"?a.split(/\s+/):[]}function Ra(a){var b=Qa(a),c;c=Oa(arguments,1);for(var d=0,f=0;f<c.length;f++)if(!Ha(b,c[f])){b.push(c[f]);d++}c=d==c.length;a.className=b.join(" ");return c}
function Sa(a){var b=Qa(a),c;c=Oa(arguments,1);for(var d=0,f=0;f<b.length;f++)if(Ha(c,b[f])){Na(b,f--,1);d++}c=d==c.length;a.className=b.join(" ");return c}function B(a,b){this.x=a!==undefined?a:0;this.y=b!==undefined?b:0}B.prototype.Ma=function(){return new B(this.x,this.y)};B.prototype.toString=function(){return"("+this.x+", "+this.y+")"};function Ta(a,b){return new B(a.x-b.x,a.y-b.y)}function D(a,b){this.width=a;this.height=b}
function Ua(a,b){if(a==b)return true;if(!a||!b)return false;return a.width==b.width&&a.height==b.height}D.prototype.Ma=function(){return new D(this.width,this.height)};D.prototype.toString=function(){return"("+this.width+" x "+this.height+")"};D.prototype.floor=function(){this.width=Math.floor(this.width);this.height=Math.floor(this.height);return this};D.prototype.round=function(){this.width=Math.round(this.width);this.height=Math.round(this.height);return this};
function Va(a,b,c){for(var d in a)b.call(c,a[d],d,a)}function Wa(a){var b=[],c=0;for(var d in a)b[c++]=a[d];return b}function Xa(a){var b=[],c=0;for(var d in a)b[c++]=d;return b}function Ya(a){for(var b in a)return false;return true}function Za(a,b){var c;if(c=b in a)delete a[b];return c}function $a(a,b,c){if(b in a)throw Error('The object already contains the key "'+b+'"');a[b]=c}function ab(a){var b={};for(var c in a)b[c]=a[c];return b}
var bb=["constructor","hasOwnProperty","isPrototypeOf","propertyIsEnumerable","toLocaleString","toString","valueOf"];function cb(a){for(var b,c,d=1;d<arguments.length;d++){c=arguments[d];for(b in c)a[b]=c[b];for(var f=0;f<bb.length;f++){b=bb[f];if(Object.prototype.hasOwnProperty.call(c,b))a[b]=c[b]}}}
function db(){var a=arguments.length;if(a==1&&v(arguments[0]))return db.apply(null,arguments[0]);if(a%2)throw Error("Uneven number of arguments");for(var b={},c=0;c<a;c+=2)b[arguments[c]]=arguments[c+1];return b}var eb,fb,gb,hb,ib,jb,kb;function lb(){return s.navigator?s.navigator.userAgent:null}function mb(){return s.navigator}ib=hb=gb=fb=eb=false;var nb;
if(nb=lb()){var ob=mb();eb=nb.indexOf("Opera")==0;fb=!eb&&nb.indexOf("MSIE")!=-1;hb=(gb=!eb&&nb.indexOf("WebKit")!=-1)&&nb.indexOf("Mobile")!=-1;ib=!eb&&!gb&&ob.product=="Gecko"}var pb=eb,E=fb,F=ib,G=gb,qb=hb,rb,tb=mb();rb=tb&&tb.platform||"";jb=rb.indexOf("Mac")!=-1;kb=rb.indexOf("Win")!=-1;var ub=!!mb()&&(mb().appVersion||"").indexOf("X11")!=-1,vb,wb="",xb;
if(pb&&s.opera){var yb=s.opera.version;wb=typeof yb=="function"?yb():yb}else{if(F)xb=/rv\:([^\);]+)(\)|;)/;else if(E)xb=/MSIE\s+([^\);]+)(\)|;)/;else if(G)xb=/WebKit\/(\S+)/;if(xb){var zb=xb.exec(lb());wb=zb?zb[1]:""}}vb=wb;var Ab={};function H(a){return Ab[a]||(Ab[a]=za(vb,a)>=0)}function I(a){return a?new Bb(J(a)):Pa||(Pa=new Bb)}
function Cb(a,b){var c=b||document;if(Db(c))return c.querySelectorAll("."+a);else if(c.getElementsByClassName)return c.getElementsByClassName(a);return Eb(document,"*",a,b)}function Db(a){return a.querySelectorAll&&a.querySelector&&(!G||Fb(document)||H("528"))}
function Eb(a,b,c,d){a=d||a;b=b&&b!="*"?b.toUpperCase():"";if(Db(a)&&(b||c))return a.querySelectorAll(b+(c?"."+c:""));if(c&&a.getElementsByClassName){a=a.getElementsByClassName(c);if(b){d={};for(var f=0,g=0,h;h=a[g];g++)if(b==h.nodeName)d[f++]=h;d.length=f;return d}else return a}a=a.getElementsByTagName(b||"*");if(c){d={};for(g=f=0;h=a[g];g++){b=h.className;if(typeof b.split=="function"&&Ha(b.split(/\s+/),c))d[f++]=h}d.length=f;return d}else return a}
function Gb(a,b){Va(b,function(c,d){if(d=="style")a.style.cssText=c;else if(d=="class")a.className=c;else if(d=="for")a.htmlFor=c;else if(d in Hb)a.setAttribute(Hb[d],c);else a[d]=c})}var Hb={cellpadding:"cellPadding",cellspacing:"cellSpacing",colspan:"colSpan",rowspan:"rowSpan",valign:"vAlign",height:"height",width:"width",usemap:"useMap",frameborder:"frameBorder",type:"type"};
function Ib(a){var b=a.document;if(G&&!H("500")&&!qb){if(typeof a.innerHeight=="undefined")a=window;b=a.innerHeight;var c=a.document.documentElement.scrollHeight;if(a==a.top)if(c<b)b-=15;return new D(a.innerWidth,b)}a=Fb(b);if(pb&&!H("9.50"))a=false;a=a?b.documentElement:b.body;return new D(a.clientWidth,a.clientHeight)}function Jb(a,b,c,d){function f(h){if(h)b.appendChild(w(h)?a.createTextNode(h):h)}for(d=d;d<c.length;d++){var g=c[d];ga(g)&&!(ja(g)&&g.nodeType>0)?A(Kb(g)?Ka(g):g,f):f(g)}}
function Fb(a){return a.compatMode=="CSS1Compat"}function Lb(a){for(var b;b=a.firstChild;)a.removeChild(b)}function Mb(a){return a&&a.parentNode?a.parentNode.removeChild(a):null}function Nb(a){for(a=a.firstChild;a&&a.nodeType!=1;)a=a.nextSibling;return a}function Ob(a,b){if(a.contains&&b.nodeType==1)return a==b||a.contains(b);if(typeof a.compareDocumentPosition!="undefined")return a==b||Boolean(a.compareDocumentPosition(b)&16);for(;b&&a!=b;)b=b.parentNode;return b==a}
function J(a){return a.nodeType==9?a:a.ownerDocument||a.document}function Pb(a,b){if("textContent"in a)a.textContent=b;else if(a.firstChild&&a.firstChild.nodeType==3){for(;a.lastChild!=a.firstChild;)a.removeChild(a.lastChild);a.firstChild.data=b}else{Lb(a);a.appendChild(J(a).createTextNode(b))}}var Qb={SCRIPT:1,STYLE:1,HEAD:1,IFRAME:1,OBJECT:1},Rb={IMG:" ",BR:"\n"};function Sb(a){var b=a.getAttributeNode("tabindex");if(b&&b.specified){a=a.tabIndex;return ha(a)&&a>=0}return false}
function Tb(a){if(E&&"innerText"in a)a=a.innerText.replace(/(\r\n|\r|\n)/g,"\n");else{var b=[];Ub(a,b,true);a=b.join("")}a=a.replace(/\xAD/g,"");a=a.replace(/ +/g," ");if(a!=" ")a=a.replace(/^\s*/,"");return a}function Ub(a,b,c){if(!(a.nodeName in Qb))if(a.nodeType==3)c?b.push(String(a.nodeValue).replace(/(\r\n|\r|\n)/g,"")):b.push(a.nodeValue);else if(a.nodeName in Rb)b.push(Rb[a.nodeName]);else for(a=a.firstChild;a;){Ub(a,b,c);a=a.nextSibling}}
function Kb(a){if(a&&typeof a.length=="number")if(ja(a))return typeof a.item=="function"||typeof a.item=="string";else if(ia(a))return typeof a.item=="function";return false}function Bb(a){this.l=a||s.document||document}r=Bb.prototype;r.D=I;function Vb(a){return a.l}r.b=function(a){return w(a)?this.l.getElementById(a):a};r.jc=Bb.prototype.b;
r.f=function(){var a=this.l,b=arguments,c=b[0],d=b[1];if(E&&d&&(d.name||d.type)){c=["<",c];d.name&&c.push(' name="',ta(d.name),'"');if(d.type){c.push(' type="',ta(d.type),'"');var f={};cb(f,d);d=f;delete d.type}c.push(">");c=c.join("")}c=a.createElement(c);if(d)if(w(d))c.className=d;else v(d)?Ra.apply(null,[c].concat(d)):Gb(c,d);b.length>2&&Jb(a,c,b,2);return c};r.createElement=function(a){return this.l.createElement(a)};r.createTextNode=function(a){return this.l.createTextNode(a)};
function Xb(a){a=!G&&Fb(a.l)?a.l.documentElement:a.l.body;return new B(a.scrollLeft,a.scrollTop)}r.appendChild=function(a,b){a.appendChild(b)};r.le=Nb;r.contains=Ob;var Yb=[];function Zb(){}Zb.prototype.Zc=false;Zb.prototype.C=function(){if(!this.Zc){this.Zc=true;this.c()}};Zb.prototype.c=aa();var $b;function K(a,b){this.type=a;this.currentTarget=this.target=b}y(K,Zb);r=K.prototype;r.c=function(){delete this.type;delete this.target;delete this.currentTarget};r.gb=false;r.cc=true;
r.stopPropagation=function(){this.gb=true};r.preventDefault=function(){this.cc=false};function ac(a){a.preventDefault()}function bc(a,b){a&&this.vb(a,b)}y(bc,K);var cc=[1,4,2];r=bc.prototype;r.target=null;r.relatedTarget=null;r.offsetX=0;r.offsetY=0;r.clientX=0;r.clientY=0;r.screenX=0;r.screenY=0;r.button=0;r.keyCode=0;r.charCode=0;r.ctrlKey=false;r.altKey=false;r.shiftKey=false;r.metaKey=false;r.Of=false;r.za=null;
r.vb=function(a,b){var c=this.type=a.type;this.target=a.target||a.srcElement;this.currentTarget=b;var d=a.relatedTarget;if(d){if(F)try{d=d.nodeName&&d}catch(f){d=null}}else if(c=="mouseover")d=a.fromElement;else if(c=="mouseout")d=a.toElement;this.relatedTarget=d;this.offsetX=a.offsetX!==undefined?a.offsetX:a.layerX;this.offsetY=a.offsetY!==undefined?a.offsetY:a.layerY;this.clientX=a.clientX!==undefined?a.clientX:a.pageX;this.clientY=a.clientY!==undefined?a.clientY:a.pageY;this.screenX=a.screenX||
0;this.screenY=a.screenY||0;this.button=a.button;this.keyCode=a.keyCode||0;this.charCode=a.charCode||(c=="keypress"?a.keyCode:0);this.ctrlKey=a.ctrlKey;this.altKey=a.altKey;this.shiftKey=a.shiftKey;this.metaKey=a.metaKey;this.Of=jb?a.metaKey:a.ctrlKey;this.za=a;delete this.cc;delete this.gb};function dc(a,b){return E?a.type=="click"?b==0:!!(a.za.button&cc[b]):a.za.button==b}
r.stopPropagation=function(){bc.a.stopPropagation.call(this);if(this.za.stopPropagation)this.za.stopPropagation();else this.za.cancelBubble=true};var ec=E&&!H("8");bc.prototype.preventDefault=function(){bc.a.preventDefault.call(this);var a=this.za;if(a.preventDefault)a.preventDefault();else{a.returnValue=false;if(ec)try{if(a.ctrlKey||a.keyCode>=112&&a.keyCode<=123)a.keyCode=-1}catch(b){}}};bc.prototype.c=function(){bc.a.c.call(this);this.relatedTarget=this.currentTarget=this.target=this.za=null};
function fc(){}var gc=0;r=fc.prototype;r.key=0;r.zb=false;r.Zd=false;r.vb=function(a,b,c,d,f,g){if(ia(a))this.xe=true;else if(a&&a.handleEvent&&ia(a.handleEvent))this.xe=false;else throw Error("Invalid listener argument");this.xb=a;this.Ie=b;this.src=c;this.type=d;this.capture=!!f;this.la=g;this.Zd=false;this.key=++gc;this.zb=false};r.handleEvent=function(a){if(this.xe)return this.xb.call(this.la||this.src,a);return this.xb.handleEvent.call(this.xb,a)};
function hc(a,b){this.De=b;this.Ya=[];if(a>this.De)throw Error("[goog.structs.SimplePool] Initial cannot be greater than max");for(var c=0;c<a;c++)this.Ya.push(this.Fa?this.Fa():{})}y(hc,Zb);hc.prototype.Fa=null;hc.prototype.de=null;function ic(a){if(a.Ya.length)return a.Ya.pop();return a.Fa?a.Fa():{}}function jc(a,b){a.Ya.length<a.De?a.Ya.push(b):kc(a,b)}function kc(a,b){if(a.de)a.de(b);else if(ja(b))if(ia(b.C))b.C();else for(var c in b)delete b[c]}
hc.prototype.c=function(){hc.a.c.call(this);for(var a=this.Ya;a.length;)kc(this,a.pop());delete this.Ya};var lc;var mc=(lc="ScriptEngine"in s&&s.ScriptEngine()=="JScript")?s.ScriptEngineMajorVersion()+"."+s.ScriptEngineMinorVersion()+"."+s.ScriptEngineBuildVersion():"0",nc,oc,pc,qc,rc,sc,tc,uc,vc,wc,xc;
(function(){function a(){return{$:0,ua:0}}function b(){return[]}function c(){function o(q){return h.call(o.src,o.key,q)}return o}function d(){return new fc}function f(){return new bc}var g=lc&&!(za(mc,"5.7")>=0),h;sc=function(o){h=o};if(g){nc=function(){return ic(i)};oc=function(o){jc(i,o)};pc=function(){return ic(k)};qc=function(o){jc(k,o)};rc=function(){return ic(j)};tc=function(){jc(j,c())};uc=function(){return ic(m)};vc=function(o){jc(m,o)};wc=function(){return ic(l)};xc=function(o){jc(l,o)};
var i=new hc(0,600);i.Fa=a;var k=new hc(0,600);k.Fa=b;var j=new hc(0,600);j.Fa=c;var m=new hc(0,600);m.Fa=d;var l=new hc(0,600);l.Fa=f}else{nc=a;oc=t;pc=b;qc=t;rc=c;tc=t;uc=d;vc=t;wc=f;xc=t}})();var yc={},L={},zc={},Ac={};
function M(a,b,c,d,f){if(b)if(v(b)){for(var g=0;g<b.length;g++)M(a,b[g],c,d,f);return null}else{d=!!d;var h=L;b in h||(h[b]=nc());h=h[b];if(!(d in h)){h[d]=nc();h.$++}h=h[d];var i=x(a),k;h.ua++;if(h[i]){k=h[i];for(g=0;g<k.length;g++){h=k[g];if(h.xb==c&&h.la==f){if(h.zb)break;return k[g].key}}}else{k=h[i]=pc();h.$++}g=rc();g.src=a;h=uc();h.vb(c,g,a,b,d,f);c=h.key;g.key=c;k.push(h);yc[c]=h;zc[i]||(zc[i]=pc());zc[i].push(h);if(a.addEventListener){if(a==s||!a.ce)a.addEventListener(b,g,d)}else a.attachEvent(Bc(b),
g);return c}else throw Error("Invalid event type");}function Cc(a,b,c,d,f){if(v(b)){for(var g=0;g<b.length;g++)Cc(a,b[g],c,d,f);return null}d=!!d;a=Dc(a,b,d);if(!a)return false;for(g=0;g<a.length;g++)if(a[g].xb==c&&a[g].capture==d&&a[g].la==f)return N(a[g].key);return false}
function N(a){if(!yc[a])return false;var b=yc[a];if(b.zb)return false;var c=b.src,d=b.type,f=b.Ie,g=b.capture;if(c.removeEventListener){if(c==s||!c.ce)c.removeEventListener(d,f,g)}else c.detachEvent&&c.detachEvent(Bc(d),f);c=x(c);f=L[d][g][c];if(zc[c]){var h=zc[c];Ia(h,b);h.length==0&&delete zc[c]}b.zb=true;f.Ge=true;Ec(d,g,c,f);delete yc[a];return true}
function Ec(a,b,c,d){if(!d.Dc)if(d.Ge){for(var f=0,g=0;f<d.length;f++)if(d[f].zb){var h=d[f].Ie;h.src=null;tc(h);vc(d[f])}else{if(f!=g)d[g]=d[f];g++}d.length=g;d.Ge=false;if(g==0){qc(d);delete L[a][b][c];L[a][b].$--;if(L[a][b].$==0){oc(L[a][b]);delete L[a][b];L[a].$--}if(L[a].$==0){oc(L[a]);delete L[a]}}}}
function Fc(a,b,c){var d=0,f=a==null,g=b==null,h=c==null;c=!!c;if(f)Va(zc,function(k){for(var j=k.length-1;j>=0;j--){var m=k[j];if((g||b==m.type)&&(h||c==m.capture)){N(m.key);d++}}});else{a=x(a);if(zc[a]){a=zc[a];for(f=a.length-1;f>=0;f--){var i=a[f];if((g||b==i.type)&&(h||c==i.capture)){N(i.key);d++}}}}return d}function Dc(a,b,c){var d=L;if(b in d){d=d[b];if(c in d){d=d[c];a=x(a);if(d[a])return d[a]}}return null}function Bc(a){if(a in Ac)return Ac[a];return Ac[a]="on"+a}
function Gc(a,b,c,d,f){var g=1;b=x(b);if(a[b]){a.ua--;a=a[b];if(a.Dc)a.Dc++;else a.Dc=1;try{for(var h=a.length,i=0;i<h;i++){var k=a[i];if(k&&!k.zb)g&=Hc(k,f)!==false}}finally{a.Dc--;Ec(c,d,b,a)}}return Boolean(g)}function Hc(a,b){var c=a.handleEvent(b);a.Zd&&N(a.key);return c}
function Ic(a,b){if(!yc[a])return true;var c=yc[a],d=c.type,f=L;if(!(d in f))return true;f=f[d];var g,h;if($b===undefined)$b=E&&!s.addEventListener;if($b){g=b||da("window.event");var i=true in f,k=false in f;if(i){if(g.keyCode<0||g.returnValue!=undefined)return true;a:{var j=false;if(g.keyCode==0)try{g.keyCode=-1;break a}catch(m){j=true}if(j||g.returnValue==undefined)g.returnValue=true}}j=wc();j.vb(g,this);g=true;try{if(i){for(var l=pc(),o=j.currentTarget;o;o=o.parentNode)l.push(o);h=f[true];h.ua=
h.$;for(var q=l.length-1;!j.gb&&q>=0&&h.ua;q--){j.currentTarget=l[q];g&=Gc(h,l[q],d,true,j)}if(k){h=f[false];h.ua=h.$;for(q=0;!j.gb&&q<l.length&&h.ua;q++){j.currentTarget=l[q];g&=Gc(h,l[q],d,false,j)}}}else g=Hc(c,j)}finally{if(l){l.length=0;qc(l)}j.C();xc(j)}return g}d=new bc(b,this);try{g=Hc(c,d)}finally{d.C()}return g}sc(Ic);Yb[Yb.length]=function(a){Ic=a.bg(Ic);sc(Ic)};function O(){}y(O,Zb);r=O.prototype;r.ce=true;r.Hc=null;r.Jd=ba("Hc");r.addEventListener=function(a,b,c,d){M(this,a,b,c,d)};
r.removeEventListener=function(a,b,c,d){Cc(this,a,b,c,d)};
r.dispatchEvent=function(a){a=a;if(w(a))a=new K(a,this);else if(a instanceof K)a.target=a.target||this;else{var b=a;a=new K(a.type,this);cb(a,b)}b=1;var c,d=a.type,f=L;if(d in f){f=f[d];d=true in f;var g;if(d){c=[];for(g=this;g;g=g.Hc)c.push(g);g=f[true];g.ua=g.$;for(var h=c.length-1;!a.gb&&h>=0&&g.ua;h--){a.currentTarget=c[h];b&=Gc(g,c[h],a.type,true,a)&&a.cc!=false}}if(false in f){g=f[false];g.ua=g.$;if(d)for(h=0;!a.gb&&h<c.length&&g.ua;h++){a.currentTarget=c[h];b&=Gc(g,c[h],a.type,false,a)&&a.cc!=
false}else for(c=this;!a.gb&&c&&g.ua;c=c.Hc){a.currentTarget=c;b&=Gc(g,c,a.type,false,a)&&a.cc!=false}}a=Boolean(b)}else a=true;return a};r.c=function(){O.a.c.call(this);Fc(this);this.Hc=null};function Jc(a){this.lb=a||window;this.Cc=M(this.lb,"resize",this.zf,false,this);this.Db=Ib(this.lb||window);if(G&&kb||pb&&this.lb.self!=this.lb.top)this.Rc=window.setInterval(na(this.ae,this),Kc)}y(Jc,O);var Kc=500;r=Jc.prototype;r.Cc=null;r.lb=null;r.Db=null;r.Rc=null;
r.ne=function(){return this.Db?this.Db.Ma():null};r.c=function(){Jc.a.c.call(this);if(this.Cc){N(this.Cc);this.Cc=null}if(this.Rc){window.clearInterval(this.Rc);this.Rc=null}this.Db=this.lb=null};r.zf=function(){this.ae()};r.ae=function(){var a=Ib(this.lb||window);if(!Ua(a,this.Db)){this.Db=a;this.dispatchEvent("resize")}};function Lc(a,b,c,d){this.top=a;this.right=b;this.bottom=c;this.left=d}Lc.prototype.Ma=function(){return new Lc(this.top,this.right,this.bottom,this.left)};
Lc.prototype.toString=function(){return"("+this.top+"t, "+this.right+"r, "+this.bottom+"b, "+this.left+"l)"};Lc.prototype.contains=function(a){return!this||!a?false:a instanceof Lc?a.left>=this.left&&a.right<=this.right&&a.top>=this.top&&a.bottom<=this.bottom:a.x>=this.left&&a.x<=this.right&&a.y>=this.top&&a.y<=this.bottom};function Mc(a,b,c,d){this.left=a;this.top=b;this.width=c;this.height=d}Mc.prototype.Ma=function(){return new Mc(this.left,this.top,this.width,this.height)};
Mc.prototype.toString=function(){return"("+this.left+", "+this.top+" - "+this.width+"w x "+this.height+"h)"};Mc.prototype.contains=function(a){return a instanceof Mc?this.left<=a.left&&this.left+this.width>=a.left+a.width&&this.top<=a.top&&this.top+this.height>=a.top+a.height:a.x>=this.left&&a.x<=this.left+this.width&&a.y>=this.top&&a.y<=this.top+this.height};Mc.prototype.ne=function(){return new D(this.width,this.height)};
function Nc(a,b){var c=J(a);if(c.defaultView&&c.defaultView.getComputedStyle)if(c=c.defaultView.getComputedStyle(a,""))return c[b];return null}function Oc(a,b){return Nc(a,b)||(a.currentStyle?a.currentStyle[b]:null)||a.style[b]}function Pc(a,b,c){var d,f=F&&(jb||ub)&&H("1.9");if(b instanceof B){d=b.x;b=b.y}else{d=b;b=c}Qc("left",f,a,d);Qc("top",f,a,b)}
function Rc(a){var b=a.getBoundingClientRect();if(E){a=a.ownerDocument;b.left-=a.documentElement.clientLeft+a.body.clientLeft;b.top-=a.documentElement.clientTop+a.body.clientTop}return b}
function Sc(a){if(E)return a.offsetParent;var b=J(a),c=Oc(a,"position"),d=c=="fixed"||c=="absolute";for(a=a.parentNode;a&&a!=b;a=a.parentNode){c=Oc(a,"position");d=d&&c=="static"&&a!=b.documentElement&&a!=b.body;if(!d&&(a.scrollWidth>a.clientWidth||a.scrollHeight>a.clientHeight||c=="fixed"||c=="absolute"))return a}return null}
function Tc(a){var b=new Lc(0,Infinity,Infinity,0),c=I(a),d=c.l.body,f=!G&&Fb(c.l)?c.l.documentElement:c.l.body,g;for(a=a;a=Sc(a);)if((!E||a.clientWidth!=0)&&(!G||a.clientHeight!=0||a!=d)&&(a.scrollWidth!=a.clientWidth||a.scrollHeight!=a.clientHeight)&&Oc(a,"overflow")!="visible"){var h=Uc(a),i;i=a;if(F&&!H("1.9")){var k=parseFloat(Nc(i,"borderLeftWidth"));if(Vc(i)){var j=i.offsetWidth-i.clientWidth-k-parseFloat(Nc(i,"borderRightWidth"));k+=j}i=new B(k,parseFloat(Nc(i,"borderTopWidth")))}else i=new B(i.clientLeft,
i.clientTop);h.x+=i.x;h.y+=i.y;b.top=Math.max(b.top,h.y);b.right=Math.min(b.right,h.x+a.clientWidth);b.bottom=Math.min(b.bottom,h.y+a.clientHeight);b.left=Math.max(b.left,h.x);g=g||a!=f}d=f.scrollLeft;f=f.scrollTop;if(G){b.left+=d;b.top+=f}else{b.left=Math.max(b.left,d);b.top=Math.max(b.top,f)}if(!g||G){b.right+=d;b.bottom+=f}c=Ib(c.l.parentWindow||c.l.defaultView||window);b.right=Math.min(b.right,d+c.width);b.bottom=Math.min(b.bottom,f+c.height);return b.top>=0&&b.left>=0&&b.bottom>b.top&&b.right>
b.left?b:null}
function Uc(a){var b,c=J(a),d=Oc(a,"position"),f=F&&c.getBoxObjectFor&&!a.getBoundingClientRect&&d=="absolute"&&(b=c.getBoxObjectFor(a))&&(b.screenX<0||b.screenY<0),g=new B(0,0),h;b=c?c.nodeType==9?c:J(c):document;if(h=E){h=I(b);h=!Fb(h.l)}h=h?b.body:b.documentElement;if(a==h)return g;if(a.getBoundingClientRect){b=Rc(a);a=Xb(I(c));g.x=b.left+a.x;g.y=b.top+a.y}else if(c.getBoxObjectFor&&!f){b=c.getBoxObjectFor(a);a=c.getBoxObjectFor(h);g.x=b.screenX-a.screenX;g.y=b.screenY-a.screenY}else{f=a;do{g.x+=
f.offsetLeft;g.y+=f.offsetTop;if(f!=a){g.x+=f.clientLeft||0;g.y+=f.clientTop||0}if(G&&Oc(f,"position")=="fixed"){g.x+=c.body.scrollLeft;g.y+=c.body.scrollTop;break}f=f.offsetParent}while(f&&f!=a);if(pb||G&&d=="absolute")g.y-=c.body.offsetTop;for(f=a;(f=Sc(f))&&f!=c.body&&f!=h;){g.x-=f.scrollLeft;if(!pb||f.tagName!="TR")g.y-=f.scrollTop}}return g}
function Wc(a){var b=new B;if(a.nodeType==1)if(a.getBoundingClientRect){var c=Rc(a);b.x=c.left;b.y=c.top}else{c=Xb(I(a));a=Uc(a);b.x=a.x-c.x;b.y=a.y-c.y}else{b.x=a.clientX;b.y=a.clientY}return b}function Xc(a,b,c){if(b instanceof D){c=b.height;b=b.width}else{if(c==undefined)throw Error("missing height argument");c=c}Yc(a,b);Zc(a,c)}function Qc(a,b,c,d){if(typeof d=="number")d=(b?Math.round(d):d)+"px";c.style[a]=d}var Zc=oa(Qc,"height",true),Yc=oa(Qc,"width",true);
function $c(a){var b=pb&&!H("10");if(Oc(a,"display")!="none")return b?new D(a.offsetWidth||a.clientWidth,a.offsetHeight||a.clientHeight):new D(a.offsetWidth,a.offsetHeight);var c=a.style,d=c.display,f=c.visibility,g=c.position;c.visibility="hidden";c.position="absolute";c.display="inline";if(b){b=a.offsetWidth||a.clientWidth;a=a.offsetHeight||a.clientHeight}else{b=a.offsetWidth;a=a.offsetHeight}c.display=d;c.position=g;c.visibility=f;return new D(b,a)}
function ad(a){var b=Uc(a);a=$c(a);return new Mc(b.x,b.y,a.width,a.height)}function bd(a,b){a.style.display=b?"":"none"}function Vc(a){return"rtl"==Oc(a,"direction")}var cd=F?"MozUserSelect":G?"WebkitUserSelect":null;function dd(a,b,c){c=!c?a.getElementsByTagName("*"):null;if(cd){b=b?"none":"";a.style[cd]=b;if(c){a=0;for(var d;d=c[a];a++)d.style[cd]=b}}else if(E||pb){b=b?"on":"";a.setAttribute("unselectable",b);if(c)for(a=0;d=c[a];a++)d.setAttribute("unselectable",b)}}function ed(){}
function fd(a,b){var c=[];gd(a,b,c);return c.join("")}
function gd(a,b,c){switch(typeof b){case "string":hd(a,b,c);break;case "number":c.push(isFinite(b)&&!isNaN(b)?b:"null");break;case "boolean":c.push(b);break;case "undefined":c.push("null");break;case "object":if(b==null){c.push("null");break}if(v(b)){var d=b.length;c.push("[");for(var f="",g=0;g<d;g++){c.push(f);gd(a,b[g],c);f=","}c.push("]");break}c.push("{");d="";for(f in b)if(b.hasOwnProperty(f)){g=b[f];if(typeof g!="function"){c.push(d);hd(a,f,c);c.push(":");gd(a,g,c);d=","}}c.push("}");break;
case "function":break;default:throw Error("Unknown type: "+typeof b);}}var id={'"':'\\"',"\\":"\\\\","/":"\\/","\u0008":"\\b","\u000c":"\\f","\n":"\\n","\r":"\\r","\t":"\\t","\u000b":"\\u000b"},jd=/\uffff/.test("\uffff")?/[\\\"\x00-\x1f\x7f-\uffff]/g:/[\\\"\x00-\x1f\x7f-\xff]/g;function hd(a,b,c){c.push('"',b.replace(jd,function(d){if(d in id)return id[d];var f=d.charCodeAt(0),g="\\u";if(f<16)g+="000";else if(f<256)g+="00";else if(f<4096)g+="0";return id[d]=g+f.toString(16)}),'"')}
function kd(){this.va=[];this.Va={}}y(kd,Zb);r=kd.prototype;r.sa=1;r.Ic=0;function P(a,b,c,d){var f=a.Va[b];f||(f=a.Va[b]=[]);var g=a.sa;a.va[g]=b;a.va[g+1]=c;a.va[g+2]=d;a.sa=g+3;f.push(g);return g}r.Se=function(a){if(this.Ic!=0){if(!this.ac)this.ac=[];this.ac.push(a);return false}var b=this.va[a];if(b){var c=this.Va[b];c&&Ia(c,a);delete this.va[a];delete this.va[a+1];delete this.va[a+2]}return!!b};
r.K=function(a){var b=this.Va[a];if(b){this.Ic++;for(var c=Oa(arguments,1),d=0,f=b.length;d<f;d++){var g=b[d];this.va[g+1].apply(this.va[g+2],c)}this.Ic--;if(this.ac&&this.Ic==0)for(;b=this.ac.pop();)this.Se(b);return d!=0}return false};r.clear=function(a){if(a){var b=this.Va[a];if(b){A(b,this.Se,this);delete this.Va[a]}}else{this.va.length=0;this.Va={}}};r.c=function(){kd.a.c.call(this);delete this.va;delete this.Va;delete this.ac};function ld(a,b){if(F){a.setAttribute("role",b);a.kg=b}}
function md(a,b,c){F&&a.setAttribute("aria-"+b,c)}function nd(a,b,c,d,f){if(!E&&!(G&&H("525")))return true;if(jb&&f)return od(a);if(f&&!d)return false;if(!c&&(b==17||b==18))return false;if(E&&d&&b==a)return false;switch(a){case 13:return true;case 27:return!G}return od(a)}
function od(a){if(a>=48&&a<=57)return true;if(a>=96&&a<=106)return true;if(a>=65&&a<=90)return true;if(G&&a==0)return true;switch(a){case 32:case 63:case 107:case 109:case 110:case 111:case 186:case 189:case 187:case 188:case 190:case 191:case 192:case 222:case 219:case 220:case 221:return true;default:return false}}function pd(a){a&&qd(this,a)}y(pd,O);r=pd.prototype;r.n=null;r.zc=null;r.ud=null;r.Ac=null;r.Wb=-1;r.db=-1;
var rd={"3":13,"12":144,"63232":38,"63233":40,"63234":37,"63235":39,"63236":112,"63237":113,"63238":114,"63239":115,"63240":116,"63241":117,"63242":118,"63243":119,"63244":120,"63245":121,"63246":122,"63247":123,"63248":44,"63272":46,"63273":36,"63275":35,"63276":33,"63277":34,"63289":144,"63302":45},sd={Up:38,Down:40,Left:37,Right:39,Enter:13,F1:112,F2:113,F3:114,F4:115,F5:116,F6:117,F7:118,F8:119,F9:120,F10:121,F11:122,F12:123,"U+007F":46,Home:36,End:35,PageUp:33,PageDown:34,Insert:45},td={61:187,
59:186},ud=E||G&&H("525");r=pd.prototype;r.hd=function(a){if(ud&&!nd(a.keyCode,this.Wb,a.shiftKey,a.ctrlKey,a.altKey))this.handleEvent(a);else this.db=F&&a.keyCode in td?td[a.keyCode]:a.keyCode};r.tf=function(){this.db=this.Wb=-1};
r.handleEvent=function(a){var b=a.za,c,d;if(E&&a.type=="keypress"){c=this.db;d=c!=13&&c!=27?b.keyCode:0}else if(G&&a.type=="keypress"){c=this.db;d=b.charCode>=0&&b.charCode<63232&&od(c)?b.charCode:0}else if(pb){c=this.db;d=od(c)?b.keyCode:0}else{c=b.keyCode||this.db;d=b.charCode||0;if(jb&&d==63&&!c)c=191}var f=c,g=b.keyIdentifier;if(c)if(c>=63232&&c in rd)f=rd[c];else{if(c==25&&a.shiftKey)f=9}else if(g&&g in sd)f=sd[g];a=f==this.Wb;this.Wb=f;b=new vd(f,d,a,b);try{this.dispatchEvent(b)}finally{b.C()}};
r.b=e("n");function qd(a,b){a.Ac&&a.detach();a.n=b;a.zc=M(a.n,"keypress",a);a.ud=M(a.n,"keydown",a.hd,false,a);a.Ac=M(a.n,"keyup",a.tf,false,a)}r.detach=function(){if(this.zc){N(this.zc);N(this.ud);N(this.Ac);this.Ac=this.ud=this.zc=null}this.n=null;this.db=this.Wb=-1};r.c=function(){pd.a.c.call(this);this.detach()};function vd(a,b,c,d){d&&this.vb(d,void 0);this.type="key";this.keyCode=a;this.charCode=b;this.repeat=c}y(vd,bc);function wd(a){this.te=a}y(wd,Zb);var xd=new hc(0,100);
wd.prototype.h=function(a,b,c,d,f){if(v(b))for(var g=0;g<b.length;g++)this.h(a,b[g],c,d,f);else{a=M(a,b,c||this,d||false,f||this.te||this);if(this.p)this.p[a]=true;else if(this.sa){this.p=ic(xd);this.p[this.sa]=true;this.sa=null;this.p[a]=true}else this.sa=a}return this};
wd.prototype.ja=function(a,b,c,d,f){if(this.sa||this.p)if(v(b))for(var g=0;g<b.length;g++)this.ja(a,b[g],c,d,f);else{a:{c=c||this;f=f||this.te||this;d=!!(d||false);if(a=Dc(a,b,d))for(b=0;b<a.length;b++)if(a[b].xb==c&&a[b].capture==d&&a[b].la==f){a=a[b];break a}a=null}if(a){a=a.key;N(a);if(this.p)Za(this.p,a);else if(this.sa==a)this.sa=null}}return this};function yd(a){if(a.p){for(var b in a.p){N(b);delete a.p[b]}jc(xd,a.p);a.p=null}else a.sa&&N(a.sa)}wd.prototype.c=function(){wd.a.c.call(this);yd(this)};
wd.prototype.handleEvent=function(){throw Error("EventHandler.handleEvent not implemented");};function zd(){}u(zd);zd.prototype.Jf=0;zd.Y();function Q(a){this.Na=a||I();this.dc=Ad}y(Q,O);Q.prototype.Bf=zd.Y();var Ad=null;
function Bd(a,b){switch(a){case 1:return b?"disable":"enable";case 2:return b?"highlight":"unhighlight";case 4:return b?"activate":"deactivate";case 8:return b?"select":"unselect";case 16:return b?"check":"uncheck";case 32:return b?"focus":"blur";case 64:return b?"open":"close";default:}throw Error("Invalid component state");}r=Q.prototype;r.ub=null;r.Na=null;r.r=false;r.n=null;r.dc=null;r.Ad=null;r.u=null;r.N=null;r.qa=null;r.We=false;
function Cd(a){return a.ub||(a.ub=":"+(a.Bf.Jf++).toString(36))}function Dd(a,b){if(a.u&&a.u.qa){Za(a.u.qa,a.ub);$a(a.u.qa,b,a)}a.ub=b}r.b=e("n");r.aa=function(){return this.sb||(this.sb=new wd(this))};function Ed(a,b){if(a==b)throw Error("Unable to set parent component");if(b&&a.u&&a.ub&&Fd(a.u,a.ub)&&a.u!=b)throw Error("Unable to set parent component");a.u=b;Q.a.Jd.call(a,b)}r.Jd=function(a){if(this.u&&this.u!=a)throw Error("Method not supported");Q.a.Jd.call(this,a)};r.D=e("Na");
r.f=function(){this.n=this.Na.createElement("div")};r.Ab=function(a){Gd(this,a)};function Gd(a,b,c){if(a.r)throw Error("Component already rendered");a.n||a.f();b?b.insertBefore(a.n,c||null):a.Na.l.body.appendChild(a.n);if(!a.u||a.u.r)a.O()}r.H=function(a){if(this.r)throw Error("Component already rendered");else if(a&&this.pa(a)){this.We=true;if(!this.Na||this.Na.l!=J(a))this.Na=I(a);this.xa(a);this.O()}else throw Error("Invalid element to decorate");};r.pa=p(true);r.xa=ba("n");
r.O=function(){this.r=true;Hd(this,function(a){!a.r&&a.b()&&a.O()})};r.Aa=function(){Hd(this,function(a){a.r&&a.Aa()});this.sb&&yd(this.sb);this.r=false};r.c=function(){Q.a.c.call(this);this.r&&this.Aa();if(this.sb){this.sb.C();delete this.sb}Hd(this,function(a){a.C()});!this.We&&this.n&&Mb(this.n);this.u=this.Ad=this.n=this.qa=this.N=null};r.ka=function(a,b){this.Ib(a,Id(this),b)};
r.Ib=function(a,b,c){if(a.r&&(c||!this.r))throw Error("Component already rendered");if(b<0||b>Id(this))throw Error("Child component index out of bounds");if(!this.qa||!this.N){this.qa={};this.N=[]}if(a.u==this){this.qa[Cd(a)]=a;Ia(this.N,a)}else $a(this.qa,Cd(a),a);Ed(a,this);Na(this.N,b,0,a);if(a.r&&this.r&&a.u==this){c=this.P();c.insertBefore(a.b(),c.childNodes[b]||null)}else if(c){this.n||this.f();b=R(this,b+1);Gd(a,this.P(),b?b.n:null)}else this.r&&!a.r&&a.n&&a.O()};r.P=e("n");
function Jd(a){if(a.dc==null)a.dc=Vc(a.r?a.n:a.Na.l.body);return a.dc}r.Cb=function(a){if(this.r)throw Error("Component already rendered");this.dc=a};function Id(a){return a.N?a.N.length:0}function Fd(a,b){var c;if(a.qa&&b){c=a.qa;c=b in c?c[b]:void 0;c=c||null}else c=null;return c}function R(a,b){return a.N?a.N[b]||null:null}function Hd(a,b,c){a.N&&A(a.N,b,c)}function Kd(a,b){return a.N&&b?Ea(a.N,b):-1}
r.removeChild=function(a,b){if(a){var c=w(a)?a:Cd(a);a=Fd(this,c);if(c&&a){Za(this.qa,c);Ia(this.N,a);if(b){a.Aa();a.n&&Mb(a.n)}Ed(a,null)}}if(!a)throw Error("Child is not in parent component");return a};function Ld(){}var Md;u(Ld);r=Ld.prototype;r.Ba=aa();r.f=function(a){return a.D().f("div",this.rb(a).join(" "),a.Ea)};r.P=function(a){return a};r.Kb=function(a,b,c){if(a=a.b?a.b():a)if(E&&!H("7")){var d=Nd(this,Qa(a),b);d.push(b);oa(c?Ra:Sa,a).apply(null,d)}else c?Ra(a,b):Sa(a,b)};r.pa=p(true);
r.H=function(a,b){b.id&&Dd(a,b.id);var c=this.P(b);if(c&&c.firstChild)Od(a,c.firstChild.nextSibling?Ka(c.childNodes):c.firstChild);else a.Ea=null;var d=0,f=this.g(),g=this.g(),h=false,i=false;c=false;var k=Qa(b);A(k,function(l){if(!h&&l==f){h=true;if(g==f)i=true}else if(!i&&l==g)i=true;else d|=this.ed(l)},this);a.i=d;if(!h){k.push(f);if(g==f)i=true}i||k.push(g);var j=a.ra;j&&k.push.apply(k,j);if(E&&!H("7")){var m=Nd(this,k);if(m.length>0){k.push.apply(k,m);c=true}}if(!h||!i||j||c)b.className=k.join(" ");
return b};r.wb=function(a){Jd(a)&&this.Cb(a.b(),true);a.F()&&this.Ta(a,a.s)};r.ec=function(a,b){dd(a,!b,!E&&!pb)};r.Cb=function(a,b){this.Kb(a,this.g()+"-rtl",b)};r.Qa=function(a){var b;if(a.S&32&&(b=a.I()))return Sb(b);return false};r.Ta=function(a,b){var c;if(a.S&32&&(c=a.I())){if(!b&&a.i&32){try{c.blur()}catch(d){}a.i&32&&a.$a(null)}if(Sb(c)!=b){c=c;if(b)c.tabIndex=0;else c.removeAttribute("tabIndex")}}};r.na=function(a,b){bd(a,b)};
r.ia=function(a,b,c){var d=a.b();if(d){var f=this.Mb(b);f&&this.Kb(a,f,c);this.Gb(d,b,c)}};r.Gb=function(a,b,c){if(F){Md||(Md=db(1,"disabled",4,"pressed",8,"selected",16,"checked",64,"expanded"));(b=Md[b])&&md(a,b,c)}};r.hb=function(a,b){var c=this.P(a);if(c){Lb(c);if(b)if(w(b))Pb(c,b);else{var d=function(f){if(f){var g=J(c);c.appendChild(w(f)?g.createTextNode(f):f)}};if(v(b))A(b,d);else ga(b)&&!("nodeType"in b)?A(Ka(b),d):d(b)}}};r.I=function(a){return a.b()};r.g=p("goog-control");
r.rb=function(a){var b=this.g(),c=[b],d=this.g();d!=b&&c.push(d);b=a.i;for(d=[];b;){var f=b&-b;d.push(this.Mb(f));b&=~f}c.push.apply(c,d);(a=a.ra)&&c.push.apply(c,a);E&&!H("7")&&c.push.apply(c,Nd(this,c));return c};function Nd(a,b,c){var d=[];if(c)b=b.concat([c]);A([],function(f){if(Ga(f,oa(Ha,b))&&(!c||Ha(f,c)))d.push(f.join("_"))});return d}r.Mb=function(a){this.qc||Pd(this);return this.qc[a]};
r.ed=function(a){if(!this.Re){this.qc||Pd(this);var b=this.qc,c={};for(var d in b)c[b[d]]=d;this.Re=c}a=parseInt(this.Re[a],10);return isNaN(a)?0:a};function Pd(a){var b=a.g();a.qc=db(1,b+"-disabled",2,b+"-hover",4,b+"-active",8,b+"-selected",16,b+"-checked",32,b+"-focused",64,b+"-open")}function Qd(a,b){if(!a)throw Error("Invalid class name "+a);if(!ia(b))throw Error("Invalid decorator function "+b);Rd[a]=b}var Sd={},Rd={};
function S(a,b,c){Q.call(this,c);if(!(b=b)){b=this.constructor;for(var d;b;){d=x(b);if(d=Sd[d])break;b=b.a?b.a.constructor:null}b=d?ia(d.Y)?d.Y():new d:null}this.e=b;this.Ea=a}y(S,Q);r=S.prototype;r.Ea=null;r.i=0;r.S=39;r.Xd=255;r.Nd=0;r.s=true;r.ra=null;r.kd=true;r.oc=false;function Td(a,b){a.r&&b!=a.kd&&Ud(a,b);a.kd=b}r.I=function(){return this.e.I(this)};r.uc=function(){return this.W||(this.W=new pd)};
r.Kb=function(a,b){if(b){if(a){if(this.ra)Ha(this.ra,a)||this.ra.push(a);else this.ra=[a];this.e.Kb(this,a,true)}}else if(a&&this.ra){Ia(this.ra,a);if(this.ra.length==0)this.ra=null;this.e.Kb(this,a,false)}};r.f=function(){var a=this.e.f(this);this.n=a;if(F){var b=this.e.Ba();b&&ld(a,b)}this.oc||this.e.ec(a,false);this.s||this.e.na(a,false)};r.P=function(){return this.e.P(this.b())};r.pa=function(a){return this.e.pa(a)};
r.xa=function(a){this.n=a=this.e.H(this,a);if(F){var b=this.e.Ba();b&&ld(a,b)}this.oc||this.e.ec(a,false);this.s=a.style.display!="none"};r.O=function(){S.a.O.call(this);this.e.wb(this);if(this.S&-2){this.kd&&Ud(this,true);if(this.S&32){var a=this.I();if(a){var b=this.uc();qd(b,a);this.aa().h(b,"key",this.Ha).h(a,"focus",this.xc).h(a,"blur",this.$a)}}}};
function Ud(a,b){var c=a.aa(),d=a.b();if(b){c.h(d,"mouseover",a.md).h(d,"mousedown",a.ab).h(d,"mouseup",a.Rb).h(d,"mouseout",a.ld);E&&c.h(d,"dblclick",a.qe)}else{c.ja(d,"mouseover",a.md).ja(d,"mousedown",a.ab).ja(d,"mouseup",a.Rb).ja(d,"mouseout",a.ld);E&&c.ja(d,"dblclick",a.qe)}}r.Aa=function(){S.a.Aa.call(this);this.W&&this.W.detach();this.s&&this.F()&&this.e.Ta(this,false)};r.c=function(){S.a.c.call(this);if(this.W){this.W.C();delete this.W}delete this.e;this.ra=this.Ea=null};
r.hb=function(a){this.e.hb(this.b(),a);this.Ea=a};function Od(a,b){a.Ea=b}function Vd(a,b){var c=a.Ea;if(!c||w(c))return c;return(c=v(c)?Fa(c,b).join(""):Tb(c))&&sa(c)}r.Lb=function(){return Vd(this,Tb)};r.Cb=function(a){S.a.Cb.call(this,a);var b=this.b();b&&this.e.Cb(b,a)};r.ec=function(a){this.oc=a;var b=this.b();b&&this.e.ec(b,a)};r.na=function(a,b){if(b||this.s!=a&&this.dispatchEvent(a?"show":"hide")){var c=this.b();c&&this.e.na(c,a);this.F()&&this.e.Ta(this,a);this.s=a;return true}return false};
r.F=function(){return!!!(this.i&1)};r.Ja=function(a){var b=this.u;if(!(b&&typeof b.F=="function"&&!b.F())&&Wd(this,1,!a)){if(!a){this.setActive(false);this.Ca(false)}this.s&&this.e.Ta(this,a);this.ia(1,!a)}};r.Ca=function(a){Wd(this,2,a)&&this.ia(2,a)};r.Tb=function(){return!!(this.i&4)};r.setActive=function(a){Wd(this,4,a)&&this.ia(4,a)};r.Kd=function(a){Wd(this,8,a)&&this.ia(8,a)};function Zd(a,b){Wd(a,16,b)&&a.ia(16,b)}r.z=function(a){Wd(this,64,a)&&this.ia(64,a)};
r.ia=function(a,b){if(this.S&a&&b!=!!(this.i&a)){this.e.ia(this,a,b);this.i=b?this.i|a:this.i&~a}};function $d(a,b,c){if(a.r&&a.i&b&&!c)throw Error("Component already rendered");!c&&a.i&b&&a.ia(b,false);a.S=c?a.S|b:a.S&~b}function T(a,b){return!!(a.Xd&b)&&!!(a.S&b)}function Wd(a,b,c){return!!(a.S&b)&&!!(a.i&b)!=c&&(!(a.Nd&b)||a.dispatchEvent(Bd(b,c)))&&!a.Zc}r.md=function(a){!ae(a,this.b())&&this.dispatchEvent("enter")&&this.F()&&T(this,2)&&this.Ca(true)};
r.ld=function(a){if(!ae(a,this.b())&&this.dispatchEvent("leave")){T(this,4)&&this.setActive(false);T(this,2)&&this.Ca(false)}};function ae(a,b){return!!a.relatedTarget&&Ob(b,a.relatedTarget)}r.ab=function(a){if(this.F()){T(this,2)&&this.Ca(true);if(dc(a,0)){T(this,4)&&this.setActive(true);this.e.Qa(this)&&this.I().focus()}}!this.oc&&dc(a,0)&&a.preventDefault()};r.Rb=function(a){if(this.F()){T(this,2)&&this.Ca(true);this.Tb()&&this.yb(a)&&T(this,4)&&this.setActive(false)}};
r.qe=function(a){this.F()&&this.yb(a)};r.yb=function(a){T(this,16)&&Zd(this,!!!(this.i&16));T(this,8)&&this.Kd(true);T(this,64)&&this.z(!!!(this.i&64));var b=new K("action",this);if(a)for(var c=["altKey","ctrlKey","metaKey","shiftKey","platformModifierKey"],d,f=0;d=c[f];f++)b[d]=a[d];return this.dispatchEvent(b)};r.xc=function(){T(this,32)&&Wd(this,32,true)&&this.ia(32,true)};r.$a=function(){T(this,4)&&this.setActive(false);T(this,32)&&Wd(this,32,false)&&this.ia(32,false)};
r.Ha=function(a){if(this.s&&this.F()&&this.tb(a)){a.preventDefault();a.stopPropagation();return true}return false};r.tb=function(a){return a.keyCode==13&&this.yb(a)};if(!ia(S))throw Error("Invalid component class "+S);if(!ia(Ld))throw Error("Invalid renderer class "+Ld);var be=x(S);Sd[be]=Ld;Qd("goog-control",function(){return new S(null)});function ce(){}y(ce,Ld);u(ce);ce.prototype.f=function(a){return a.D().f("div",this.g())};
ce.prototype.H=function(a,b){if(b.tagName=="HR"){var c=b;b=this.f(a);c.parentNode&&c.parentNode.insertBefore(b,c);Mb(c)}else Ra(b,this.g());return b};ce.prototype.hb=aa();ce.prototype.g=p("goog-menuseparator");function de(a,b){S.call(this,null,a||ce.Y(),b);$d(this,1,false);$d(this,2,false);$d(this,4,false);$d(this,32,false);this.i=1}y(de,S);de.prototype.O=function(){de.a.O.call(this);ld(this.b(),"separator")};Qd("goog-menuseparator",function(){return new de});function ee(){}u(ee);r=ee.prototype;
r.Ba=aa();function fe(a,b,c){if(b)b.tabIndex=c?0:-1}r.f=function(a){return a.D().f("div",this.rb(a).join(" "))};r.P=function(a){return a};r.pa=function(a){return a.tagName=="DIV"};r.H=function(a,b){b.id&&Dd(a,b.id);var c=this.g(),d=false,f=Qa(b);f&&A(f,function(g){if(g==c)d=true;else if(g)if(g==c+"-disabled")a.Ja(false);else if(g==c+"-horizontal")a.Id(ge);else g==c+"-vertical"&&a.Id(he)},this);d||Ra(b,c);ie(this,a,b);return b};
function ie(a,b,c,d){if(c){d=d||c.firstChild;for(var f;d&&d.parentNode==c;){f=d.nextSibling;if(d.nodeType==1){var g=a.Nb(d);if(g){g.n=d;b.F()||g.Ja(false);b.ka(g);g.H(d)}}else if(!d.nodeValue||sa(d.nodeValue)=="")c.removeChild(d);d=f}}}r.Nb=function(a){a:{for(var b=Qa(a),c=0,d=b.length;c<d;c++)if(a=b[c]in Rd?Rd[b[c]]():null){a=a;break a}a=null}return a};r.wb=function(a){a=a.b();dd(a,true,F);if(E)a.hideFocus=true;var b=this.Ba();b&&ld(a,b)};r.I=function(a){return a.b()};r.g=p("goog-container");
r.rb=function(a){var b=this.g(),c=[b,a.w==ge?b+"-horizontal":b+"-vertical"];a.F()||c.push(b+"-disabled");return c};r.ke=function(){return he};function U(a,b,c){Q.call(this,c);this.e=b||ee.Y();this.w=a||this.e.ke()}y(U,Q);var ge="horizontal",he="vertical";r=U.prototype;r.ye=null;r.W=null;r.e=null;r.w=null;r.s=true;r.T=true;r.ad=true;r.V=-1;r.J=null;r.Ia=false;r.af=false;r.Nf=true;r.La=null;r.I=function(){return this.ye||this.e.I(this)};r.uc=function(){return this.W||(this.W=new pd(this.I()))};
r.f=function(){this.n=this.e.f(this)};r.P=function(){return this.e.P(this.b())};r.pa=function(a){return this.e.pa(a)};r.xa=function(a){this.n=this.e.H(this,a);if(a.style.display=="none")this.s=false};
r.O=function(){U.a.O.call(this);Hd(this,function(b){b.r&&je(this,b)},this);var a=this.b();this.e.wb(this);this.na(this.s,true);this.aa().h(this,"enter",this.fd).h(this,"highlight",this.gd).h(this,"unhighlight",this.nd).h(this,"open",this.xf).h(this,"close",this.qf).h(a,"mousedown",this.ab).h(J(a),"mouseup",this.sf).h(a,["mousedown","mouseup","mouseover","mouseout"],this.pf);this.Qa()&&ke(this,true)};
function ke(a,b){var c=a.aa(),d=a.I();b?c.h(d,"focus",a.xc).h(d,"blur",a.$a).h(a.uc(),"key",a.Ha):c.ja(d,"focus",a.xc).ja(d,"blur",a.$a).ja(a.uc(),"key",a.Ha)}r.Aa=function(){le(this,-1);this.J&&this.J.z(false);this.Ia=false;U.a.Aa.call(this)};r.c=function(){U.a.c.call(this);if(this.W){this.W.C();this.W=null}this.e=this.J=this.La=null};r.fd=p(true);
r.gd=function(a){var b=Kd(this,a.target);if(b>-1&&b!=this.V){var c=R(this,this.V);c&&c.Ca(false);this.V=b;c=R(this,this.V);this.Ia&&c.setActive(true);if(this.Nf&&this.J&&c!=this.J)c.S&64?c.z(true):this.J.z(false)}md(this.b(),"activedescendant",a.target.b().id)};r.nd=function(a){if(a.target==R(this,this.V))this.V=-1;md(this.b(),"activedescendant","")};r.xf=function(a){if((a=a.target)&&a!=this.J&&a.u==this){this.J&&this.J.z(false);this.J=a}};r.qf=function(a){if(a.target==this.J)this.J=null};
r.ab=function(a){if(this.T)this.Ia=true;var b=this.I(),c;a:{if(b)if((c=b.getAttributeNode("tabindex"))&&c.specified){c=b.tabIndex;c=ha(c)&&c>=0;break a}c=false}c?b.focus():a.preventDefault()};r.sf=function(){this.Ia=false};
r.pf=function(a){var b;a:{b=a.target;if(this.La)for(var c=this.b();b&&b.parentNode&&b!=c;){var d=b.id;if(d in this.La){b=this.La[d];break a}b=b.parentNode}b=null}if(b)switch(a.type){case "mousedown":b.ab(a);break;case "mouseup":b.Rb(a);break;case "mouseover":b.md(a);break;case "mouseout":b.ld(a);break}};r.xc=aa();r.$a=function(){le(this,-1);this.Ia=false;this.J&&this.J.z(false)};r.Ha=function(a){if(this.F()&&this.s&&(Id(this)!=0||this.ye)&&this.tb(a)){a.preventDefault();a.stopPropagation();return true}return false};
r.tb=function(a){var b=R(this,this.V);if(b&&typeof b.Ha=="function"&&b.Ha(a))return true;if(this.J&&this.J!=b&&typeof this.J.Ha=="function"&&this.J.Ha(a))return true;switch(a.keyCode){case 27:if(this.Qa())this.I().blur();else return false;break;case 36:me(this);break;case 35:ne(this);break;case 38:if(this.w==he)oe(this);else return false;break;case 37:if(this.w==ge)Jd(this)?pe(this):oe(this);else return false;break;case 40:if(this.w==he)pe(this);else return false;break;case 39:if(this.w==ge)Jd(this)?
oe(this):pe(this);else return false;break;default:return false}return true};function je(a,b){var c=b.b();c=c.id||(c.id=Cd(b));if(!a.La)a.La={};a.La[c]=b}r.ka=function(a,b){U.a.ka.call(this,a,b)};r.Ib=function(a,b,c){a.Nd|=2;a.Nd|=64;if(this.Qa()||!this.af)$d(a,32,false);Td(a,false);U.a.Ib.call(this,a,b,c);c&&this.r&&je(this,a);b<=this.V&&this.V++};
r.removeChild=function(a,b){if(a=w(a)?Fd(this,a):a){var c=Kd(this,a);if(c!=-1)if(c==this.V)a.Ca(false);else c<this.V&&this.V--;(c=a.b())&&c.id&&Za(this.La,c.id)}a=U.a.removeChild.call(this,a,b);Td(a,true);return a};r.Id=function(a){if(this.b())throw Error("Component already rendered");this.w=a};r.na=function(a,b){if(b||this.s!=a&&this.dispatchEvent(a?"show":"hide")){this.s=a;var c=this.b();if(c){bd(c,a);this.Qa()&&fe(this.e,this.I(),this.T&&this.s);b||this.dispatchEvent(this.s?"aftershow":"afterhide")}return true}return false};
r.F=e("T");r.Ja=function(a){if(this.T!=a&&this.dispatchEvent(a?"enable":"disable")){if(a){this.T=true;Hd(this,function(b){if(b.Xe)delete b.Xe;else b.Ja(true)})}else{Hd(this,function(b){if(b.F())b.Ja(false);else b.Xe=true});this.Ia=this.T=false}this.Qa()&&fe(this.e,this.I(),a&&this.s)}};r.Qa=e("ad");r.Ta=function(a){a!=this.ad&&this.r&&ke(this,a);this.ad=a;this.T&&this.s&&fe(this.e,this.I(),a)};function le(a,b){var c=R(a,b);if(c)c.Ca(true);else a.V>-1&&R(a,a.V).Ca(false)}
r.Ca=function(a){le(this,Kd(this,a))};function me(a){qe(a,function(b,c){return(b+1)%c},Id(a)-1)}function ne(a){qe(a,function(b,c){b--;return b<0?c-1:b},0)}function pe(a){qe(a,function(b,c){return(b+1)%c},a.V)}function oe(a){qe(a,function(b,c){b--;return b<0?c-1:b},a.V)}function qe(a,b,c){c=c<0?Kd(a,a.J):c;var d=Id(a);c=b.call(a,c,d);for(var f=0;f<=d;){var g=R(a,c);if(g&&a.$d(g)){le(a,c);return true}f++;c=b.call(a,c,d)}return false}r.$d=function(a){return a.s&&a.F()&&!!(a.S&2)};function re(){}
y(re,ce);u(re);re.prototype.f=function(a){return a.D().f("div",this.g()+" goog-inline-block","\u00a0")};re.prototype.H=function(a,b){b=re.a.H.call(this,a,b);Ra(b,"goog-inline-block");return b};re.prototype.g=p("goog-toolbar-separator");function se(){}y(se,ee);u(se);se.prototype.Ba=p("toolbar");se.prototype.Nb=function(a){return a.tagName=="HR"?new de(re.Y()):se.a.Nb.call(this,a)};se.prototype.g=p("goog-toolbar");se.prototype.ke=function(){return ge};function te(a,b,c){U.call(this,b,a||se.Y(),c)}
y(te,U);function ue(){}y(ue,Ld);u(ue);r=ue.prototype;r.Ba=p("button");r.Gb=function(a,b,c){if(F)b==16?md(a,"pressed",c):ue.a.Gb.call(this,a,b,c)};r.f=function(a){var b=ue.a.f.call(this,a),c=a.Qb();c&&this.Md(b,c);(c=a.o())&&this.A(b,c);a.S&16&&this.Gb(b,16,false);return b};r.H=function(a,b){b=ue.a.H.call(this,a,b);var c=this.o(b);a.wa=c;a.Pd=this.Qb(b);a.S&16&&this.Gb(b,16,false);return b};r.o=t;r.A=t;r.Qb=function(a){return a.title};r.Md=function(a,b){if(a)a.title=b||""};r.g=p("goog-button");
function ve(){}y(ve,ue);u(ve);r=ve.prototype;r.Ba=aa();r.f=function(a){we(this,a);return a.D().f("button",{"class":this.rb(a).join(" "),disabled:!a.F(),title:a.Qb()||"",value:a.o()||""},a.Lb()||"")};r.pa=function(a){return a.tagName=="BUTTON"||a.tagName=="INPUT"&&(a.type=="button"||a.type=="submit"||a.type=="reset")};r.H=function(a,b){we(this,a);b.disabled&&Ra(b,this.Mb(1));return ve.a.H.call(this,a,b)};r.wb=function(a){a.aa().h(a.b(),"click",a.yb)};r.ec=t;r.Cb=t;r.Qa=function(a){return a.F()};
r.Ta=t;r.ia=function(a,b,c){ve.a.ia.call(this,a,b,c);if((a=a.b())&&b==1)a.disabled=c};r.o=function(a){return a.value};r.A=function(a,b){if(a)a.value=b};r.Gb=t;function we(a,b){Td(b,false);b.Xd&=-256;$d(b,32,false)}function xe(a,b,c){S.call(this,a,b||ve.Y(),c)}y(xe,S);r=xe.prototype;r.o=e("wa");r.A=function(a){this.wa=a;this.e.A(this.b(),a)};r.Qb=e("Pd");r.Md=function(a){this.Pd=a;this.e.Md(this.b(),a)};r.c=function(){xe.a.c.call(this);delete this.wa;delete this.Pd};
r.O=function(){xe.a.O.call(this);if(this.S&32){var a=this.I();a&&this.aa().h(a,"keyup",this.tb)}};r.tb=function(a){if(a.keyCode==13&&a.type=="key"||a.keyCode==32&&a.type=="keyup")return this.yb(a);return a.keyCode==32};Qd("goog-button",function(){return new xe(null)});function ye(){}y(ye,ue);u(ye);r=ye.prototype;r.f=function(a){var b={"class":"goog-inline-block "+this.rb(a).join(" "),title:a.Qb()||""};return a.D().f("div",b,this.rc(a.Ea,a.D()))};r.P=function(a){return a&&a.firstChild.firstChild};
r.rc=function(a,b){return b.f("div","goog-inline-block "+(this.g()+"-outer-box"),b.f("div","goog-inline-block "+(this.g()+"-inner-box"),a))};r.pa=function(a){return a.tagName=="DIV"};r.H=function(a,b){ze(b,true);ze(b,false);var c;a:{if((c=a.D().le(b))&&c.className.indexOf(this.g()+"-outer-box")!=-1)if((c=a.D().le(c))&&c.className.indexOf(this.g()+"-inner-box")!=-1){c=true;break a}c=false}c||b.appendChild(this.rc(b.childNodes,a.D()));Ra(b,"goog-inline-block",this.g());return ye.a.H.call(this,a,b)};
r.g=p("goog-custom-button");function ze(a,b){if(a)for(var c=b?a.firstChild:a.lastChild,d;c&&c.parentNode==a;){d=b?c.nextSibling:c.previousSibling;if(c.nodeType==3){var f=c.nodeValue;if(sa(f)=="")a.removeChild(c);else{c.nodeValue=b?f.replace(/^[\s\xa0]+/,""):f.replace(/[\s\xa0]+$/,"");break}}else break;c=d}}function Ae(a,b,c){xe.call(this,a,b||ye.Y(),c);$d(this,16,true)}y(Ae,xe);Qd("goog-toggle-button",function(){return new Ae(null)});function Be(){}y(Be,ye);u(Be);Be.prototype.g=p("goog-toolbar-button");
function Ce(a,b,c){Ae.call(this,a,b||Be.Y(),c)}y(Ce,Ae);Qd("goog-toolbar-toggle-button",function(){return new Ce(null)});function De(a,b,c){xe.call(this,a,b||Be.Y(),c)}y(De,xe);Qd("goog-toolbar-button",function(){return new De(null)});function Ee(a,b){this.Sb=a||1;this.ic=b||Fe;this.Wc=na(this.Zf,this);this.wd=pa()}y(Ee,O);Ee.prototype.enabled=false;var Fe=s.window;r=Ee.prototype;r.ea=null;r.setInterval=function(a){this.Sb=a;if(this.ea&&this.enabled){this.stop();this.start()}else this.ea&&this.stop()};
r.Zf=function(){if(this.enabled){var a=pa()-this.wd;if(a>0&&a<this.Sb*0.8)this.ea=this.ic.setTimeout(this.Wc,this.Sb-a);else{this.dispatchEvent(Ge);if(this.enabled){this.ea=this.ic.setTimeout(this.Wc,this.Sb);this.wd=pa()}}}};r.start=function(){this.enabled=true;if(!this.ea){this.ea=this.ic.setTimeout(this.Wc,this.Sb);this.wd=pa()}};r.stop=function(){this.enabled=false;if(this.ea){this.ic.clearTimeout(this.ea);this.ea=null}};r.c=function(){Ee.a.c.call(this);this.stop();delete this.ic};var Ge="tick";
function He(a,b,c,d,f,g,h,i){var k,j=c.offsetParent;if(j){var m=j.tagName=="HTML"||j.tagName=="BODY";if(!m||Oc(j,"position")!="static"){k=Uc(j);m||(k=Ta(k,new B(j.scrollLeft,j.scrollTop)))}}j=ad(a);if(m=Tc(a)){var l=new Mc(m.left,m.top,m.right-m.left,m.bottom-m.top);m=Math.max(j.left,l.left);var o=Math.min(j.left+j.width,l.left+l.width);if(m<=o){var q=Math.max(j.top,l.top);l=Math.min(j.top+j.height,l.top+l.height);if(q<=l){j.left=m;j.top=q;j.width=o-m;j.height=l-q}}}m=I(a);q=I(c);if(m.l!=q.l){o=m.l.body;
q=q.l.parentWindow||q.l.defaultView;l=new B(0,0);var C=J(o)?J(o).parentWindow||J(o).defaultView:window,X=o;do{var Ma=C==q?Uc(X):Wc(X);l.x+=Ma.x;l.y+=Ma.y}while(C&&C!=q&&(X=C.frameElement)&&(C=C.parent));q=l;q=Ta(q,Uc(o));if(E&&!Fb(m.l))q=Ta(q,Xb(m));j.left+=q.x;j.top+=q.y}a=(b&4&&Vc(a)?b^2:b)&-5;b=new B(a&2?j.left+j.width:j.left,a&1?j.top+j.height:j.top);if(k)b=Ta(b,k);if(f){b.x+=(a&2?-1:1)*f.x;b.y+=(a&1?-1:1)*f.y}var n;if(h)if((n=Tc(c))&&k){n.top=Math.max(0,n.top-k.y);n.right-=k.x;n.bottom-=k.y;
n.left=Math.max(0,n.left-k.x)}a:{f=b;n=n;f=f.Ma();k=0;a=(d&4&&Vc(c)?d^2:d)&-5;d=$c(c);i=i?i.Ma():d;if(g||a!=0){if(a&2)f.x-=i.width+(g?g.right:0);else if(g)f.x+=g.left;if(a&1)f.y-=i.height+(g?g.bottom:0);else if(g)f.y+=g.top}if(h){if(n){g=f;k=0;if(g.x<n.left&&h&1){g.x=n.left;k|=1}if(g.x<n.left&&g.x+i.width>n.right&&h&16){i.width-=g.x+i.width-n.right;k|=4}if(g.x+i.width>n.right&&h&1){g.x=Math.max(n.right-i.width,n.left);k|=1}if(h&2)k|=(g.x<n.left?16:0)|(g.x+i.width>n.right?32:0);if(g.y<n.top&&h&4){g.y=
n.top;k|=2}if(g.y>=n.top&&g.y+i.height>n.bottom&&h&32){i.height-=g.y+i.height-n.bottom;k|=8}if(g.y+i.height>n.bottom&&h&4){g.y=Math.max(n.bottom-i.height,n.top);k|=2}if(h&8)k|=(g.y<n.top?64:0)|(g.y+i.height>n.bottom?128:0);h=k}else h=256;k=h;if(k&496){c=k;break a}}Pc(c,f);Ua(d,i)||Xc(c,i);c=k}return c}function Ie(){}Ie.prototype.bc=aa();function Je(a,b){this.element=a;this.nb=b}y(Je,Ie);Je.prototype.bc=function(a,b,c){He(this.element,this.nb,a,b,undefined,c)};
function Ke(a,b,c){Je.call(this,a,b);this.$e=c}y(Ke,Je);Ke.prototype.bc=function(a,b,c,d){var f=He(this.element,this.nb,a,b,null,c,10,d);if(f&496){var g=this.nb,h=b;if(f&48){g^=2;h^=2}if(f&192){g^=1;h^=1}f=He(this.element,g,a,h,null,c,10,d);if(f&496)this.$e?He(this.element,this.nb,a,b,null,c,5,d):He(this.element,this.nb,a,b,null,c,0,d)}};function Le(a,b,c,d){Ke.call(this,a,b,c);this.Qf=d}y(Le,Ke);
Le.prototype.bc=function(a,b,c,d){this.Qf?He(this.element,this.nb,a,b,null,c,33,d):Le.a.bc.call(this,a,b,c,d)};function Me(){this.be=[]}y(Me,Ld);u(Me);function Ne(a,b){var c=a.be[b];if(!c){switch(b){case 0:c=a.g()+"-highlight";break;case 1:c=a.g()+"-checkbox";break;case 2:c=a.g()+"-content";break}a.be[b]=c}return c}r=Me.prototype;r.Ba=p("menuitem");r.f=function(a){var b=a.D().f("div",this.rb(a).join(" "),Oe(this,a.Ea,a.D()));Pe(this,a,b,!!(a.S&8)||!!(a.S&16));return b};r.P=function(a){return a&&a.firstChild};
r.H=function(a,b){var c=Nb(b),d=Ne(this,2);c&&c.className.indexOf(d)!=-1||b.appendChild(Oe(this,b.childNodes,a.D()));if(Ha(Qa(b),"goog-option")){a.Kc(true);this.Kc(a,b,true)}return Me.a.H.call(this,a,b)};r.hb=function(a,b){var c=this.P(a),d=Qe(this,a)?c.firstChild:null;Me.a.hb.call(this,a,b);if(d&&!Qe(this,a))c.insertBefore(d,c.firstChild||null)};function Oe(a,b,c){a=Ne(a,2);return c.f("div",a,b)}r.Kc=function(a,b,c){if(b){ld(b,c?"menuitemcheckbox":this.Ba());Pe(this,a,b,c)}};
function Qe(a,b){var c=a.P(b);if(c){c=c.firstChild;var d=Ne(a,1);return!!c&&!!c.className&&c.className.indexOf(d)!=-1}return false}function Pe(a,b,c,d){if(d!=Qe(a,c)){d?Ra(c,"goog-option"):Sa(c,"goog-option");c=a.P(c);if(d){a=Ne(a,1);c.insertBefore(b.D().f("div",a),c.firstChild||null)}else c.removeChild(c.firstChild)}}r.Mb=function(a){switch(a){case 2:return Ne(this,0);case 16:case 8:return"goog-option-selected";default:return Me.a.Mb.call(this,a)}};
r.ed=function(a){var b=Ne(this,0);switch(a){case "goog-option-selected":return 16;case b:return 2;default:return Me.a.ed.call(this,a)}};r.g=p("goog-menuitem");function V(a,b,c,d){S.call(this,a,d||Me.Y(),c);this.A(b)}y(V,S);V.prototype.o=function(){var a=this.Ad;return a!=null?a:this.Lb()};V.prototype.A=ba("Ad");V.prototype.Kc=function(a){$d(this,16,a);var b=this.b();b&&this.e.Kc(this,b,a)};V.prototype.Lb=function(){return Vd(this,function(a){return Ha(Qa(a),"goog-menuitem-accel")?"":Tb(a)})};
Qd("goog-menuitem",function(){return new V(null)});function Re(){}y(Re,ee);u(Re);r=Re.prototype;r.Ba=p("menu");r.pa=function(a){return a.tagName=="UL"||Re.a.pa.call(this,a)};r.Nb=function(a){return a.tagName=="HR"?new de:Re.a.Nb.call(this,a)};r.Wa=function(a,b){return Ob(a.b(),b)};r.g=p("goog-menu");r.wb=function(a){Re.a.wb.call(this,a);a=a.b();md(a,"haspopup","true")};Qd("goog-menuseparator",function(){return new de});function Se(a,b){U.call(this,he,b||Re.Y(),a);this.Ta(false)}y(Se,U);r=Se.prototype;
r.Vc=true;r.bf=false;r.g=function(){return this.e.g()};r.Wa=function(a){if(this.e.Wa(this,a))return true;for(var b=0,c=Id(this);b<c;b++){var d=R(this,b);if(typeof d.Wa=="function"&&d.Wa(a))return true}return false};r.M=function(a){this.ka(a,true)};r.mb=function(a,b){this.Ib(a,b,true)};r.Pb=function(a){return R(this,a)};r.bd=function(){return Id(this)};
r.Me=function(a,b){var c=this.s;c||bd(this.b(),true);var d=this.b(),f=a,g=b,h=Uc(d);if(f instanceof B){g=f.y;f=f.x}Pc(d,d.offsetLeft+(f-h.x),d.offsetTop+(g-h.y));c||bd(this.b(),false)};r.na=function(a,b){var c=Se.a.na.call(this,a,b);c&&a&&this.r&&this.Vc&&this.I().focus();return c};r.fd=function(a){this.Vc&&this.I().focus();return Se.a.fd.call(this,a)};r.$d=function(a){return(this.bf||a.F())&&a.s&&!!(a.S&2)};
r.xa=function(a){var b=this.e,c;c=this.D();c=Eb(c.l,"div",b.g()+"-content",a);for(var d,f=0;d=c[f];f++)ie(b,this,d);Se.a.xa.call(this,a)};function Te(){}y(Te,ye);u(Te);if(F)Te.prototype.hb=function(a,b){var c=Te.a.P.call(this,a&&a.firstChild);if(c){var d=this.createCaption(b,I(a)),f=c.parentNode;f&&f.replaceChild(d,c)}};r=Te.prototype;r.P=function(a){a=Te.a.P.call(this,a&&a.firstChild);if(F&&a&&a.__goog_wrapper_div)a=a.firstChild;return a};
r.H=function(a,b){var c=Eb(document,"*","goog-menu",b)[0];if(c){bd(c,false);J(c).body.appendChild(c);var d=new Se;d.H(c);a.fc(d)}return Te.a.H.call(this,a,b)};r.rc=function(a,b){return Te.a.rc.call(this,[this.createCaption(a,b),b.f("div","goog-inline-block "+(this.g()+"-dropdown"),"\u00a0")],b)};r.createCaption=function(a,b){return b.f("div","goog-inline-block "+(this.g()+"-caption"),a)};r.g=p("goog-menu-button");
function W(a,b,c,d){xe.call(this,a,c||Te.Y(),d);$d(this,64,true);b&&this.fc(b);this.ea=new Ee(500)}y(W,xe);r=W.prototype;r.Wd=true;r.Fd=false;r.sd=false;r.O=function(){W.a.O.call(this);this.d&&Ue(this,this.d,true);md(this.b(),"haspopup","true")};r.Aa=function(){W.a.Aa.call(this);if(this.d){this.z(false);this.d.Aa();Ue(this,this.d,false);var a=this.d.b();a&&Mb(a)}};r.c=function(){W.a.c.call(this);if(this.d){this.d.C();delete this.d}this.ea.C()};
r.ab=function(a){W.a.ab.call(this,a);if(this.Tb()){this.z(!!!(this.i&64));if(this.d)this.d.Ia=!!(this.i&64)}};r.Rb=function(a){W.a.Rb.call(this,a);if(this.d&&!this.Tb())this.d.Ia=false};r.yb=function(){this.setActive(false);return true};r.rf=function(a){this.d&&this.d.s&&!this.Wa(a.target)&&this.z(false)};r.Wa=function(a){return a&&Ob(this.b(),a)||this.d&&this.d.Wa(a)||false};
r.tb=function(a){if(a.keyCode==32){a.preventDefault();if(a.type!="keyup")return false}else if(a.type!="key")return false;if(this.d&&this.d.s){var b=this.d.Ha(a);if(a.keyCode==27){this.z(false);return true}return b}if(a.keyCode==40||a.keyCode==38||a.keyCode==32){this.z(true);return true}return false};r.jd=function(){this.z(false)};r.uf=function(){this.Tb()||this.z(false)};r.$a=function(a){this.sd||this.z(false);W.a.$a.call(this,a)};function Ve(a){a.d||a.fc(new Se(a.D()));return a.d||null}
r.fc=function(a){var b=this.d;if(a!=b){if(b){this.z(false);this.r&&Ue(this,b,false);delete this.d}if(a){this.d=a;Ed(a,this);a.na(false);var c=this.sd;(a.Vc=c)&&a.Ta(true);this.r&&Ue(this,a,true)}}return b};r.M=function(a){Ve(this).ka(a,true)};r.mb=function(a,b){Ve(this).Ib(a,b,true)};r.Pb=function(a){return this.d?R(this.d,a):null};r.bd=function(){return this.d?Id(this.d):0};r.na=function(a,b){var c=W.a.na.call(this,a,b);c&&!this.s&&this.z(false);return c};
r.Ja=function(a){W.a.Ja.call(this,a);this.F()||this.z(false)};
r.z=function(a){W.a.z.call(this,a);if(this.d&&!!(this.i&64)==a){if(a){this.d.r||this.d.Ab();this.Ve=Tc(this.b());this.Yd=ad(this.b());We(this);le(this.d,-1)}else{this.setActive(false);this.d.Ia=false;if(this.Gc!=null){this.Gc=undefined;var b=this.d.b();b&&Xc(b,"","")}}this.d.na(a);b=this.aa();var c=a?b.h:b.ja;c.call(b,Vb(this.D()),"mousedown",this.rf,true);this.sd&&c.call(b,this.d,"blur",this.uf);c.call(b,this.ea,Ge,this.Lf);a?this.ea.start():this.ea.stop()}};
function We(a){if(a.d.r){var b=a.Wd?5:7;b=new Le(a.b(),b,!a.Fd,a.Fd);var c=a.d.b();if(!a.d.s){c.style.visibility="hidden";bd(c,true)}if(!a.Gc&&a.Fd)a.Gc=$c(c);b.bc(c,a.Wd?4:6,null,a.Gc);if(!a.d.s){bd(c,false);c.style.visibility="visible"}}}
r.Lf=function(){var a=ad(this.b()),b=Tc(this.b()),c;c=this.Yd;c=c==a?true:!c||!a?false:c.left==a.left&&c.width==a.width&&c.top==a.top&&c.height==a.height;if(!(c=!c)){c=this.Ve;c=c==b?true:!c||!b?false:c.top==b.top&&c.right==b.right&&c.bottom==b.bottom&&c.left==b.left;c=!c}if(c){this.Yd=a;this.Ve=b;We(this)}};function Ue(a,b,c){var d=a.aa();c=c?d.h:d.ja;c.call(d,b,"action",a.jd);c.call(d,b,"highlight",a.gd);c.call(d,b,"unhighlight",a.nd)}r.gd=function(a){md(this.b(),"activedescendant",a.target.b().id)};
r.nd=function(){R(this.d,this.d.V)||md(this.b(),"activedescendant","")};Qd("goog-menu-button",function(){return new W(null)});function Xe(a){this.cb=[];Ye(this,a)}y(Xe,O);r=Xe.prototype;r.Sa=null;r.Je=null;r.bd=function(){return this.cb.length};r.Pb=function(a){return this.cb[a]||null};function Ye(a,b){if(b){A(b,function(c){Ze(this,c,false)},a);La(a.cb,b)}}r.M=function(a){this.mb(a,this.bd())};r.mb=function(a,b){if(a){Ze(this,a,false);Na(this.cb,b,0,a)}};r.vc=e("Sa");
r.ib=function(a){if(a!=this.Sa){Ze(this,this.Sa,false);this.Sa=a;Ze(this,a,true)}this.dispatchEvent("select")};r.dd=function(){return this.Sa?Ea(this.cb,this.Sa):-1};r.Ne=function(a){this.ib(this.Pb(a))};r.clear=function(){var a=this.cb;if(!v(a))for(var b=a.length-1;b>=0;b--)delete a[b];a.length=0;this.Sa=null};r.c=function(){Xe.a.c.call(this);delete this.cb;this.Sa=null};function Ze(a,b,c){if(b)if(typeof a.Je=="function")a.Je(b,c);else typeof b.Kd=="function"&&b.Kd(c)}
function Y(a,b,c,d){W.call(this,a,b,c,d);this.sc=a;$e(this)}y(Y,W);r=Y.prototype;r.t=null;r.sc=null;r.O=function(){Y.a.O.call(this);$e(this)};r.xa=function(a){Y.a.xa.call(this,a);if(a=this.Lb()){this.sc=a;$e(this)}else this.Ne(0)};r.c=function(){Y.a.c.call(this);if(this.t){this.t.C();this.t=null}this.sc=null};r.jd=function(a){this.ib(a.target);Y.a.jd.call(this,a);a.stopPropagation();this.dispatchEvent("action")};r.Af=function(){var a=this.vc();Y.a.A.call(this,a&&a.o());$e(this)};
r.fc=function(a){var b=Y.a.fc.call(this,a);if(a!=b){this.t&&this.t.clear();if(a)this.t?Hd(a,function(c){this.t.M(c)},this):af(this,a)}return b};r.M=function(a){Y.a.M.call(this,a);this.t?this.t.M(a):af(this,Ve(this))};r.mb=function(a,b){Y.a.mb.call(this,a,b);this.t?this.t.mb(a,b):af(this,Ve(this))};r.ib=function(a){this.t&&this.t.ib(a)};r.Ne=function(a){this.t&&this.ib(this.t.Pb(a))};
r.A=function(a){if(a!=null&&this.t)for(var b=0,c;c=this.t.Pb(b);b++)if(c&&typeof c.o=="function"&&c.o()==a){this.ib(c);return}this.ib(null)};r.vc=function(){return this.t?this.t.vc():null};r.dd=function(){return this.t?this.t.dd():-1};function af(a,b){a.t=new Xe;b&&Hd(b,function(c){this.t.M(c)},a);a.aa().h(a.t,"select",a.Af)}function $e(a){var b=a.vc();a.hb(b?b.Lb():a.sc)}r.z=function(a){Y.a.z.call(this,a);this.i&64&&le(Ve(this),this.dd())};Qd("goog-select",function(){return new Y(null)});
function bf(){}y(bf,Te);u(bf);bf.prototype.g=p("goog-toolbar-menu-button");function cf(a,b,c,d){Y.call(this,a,b,c||bf.Y(),d)}y(cf,Y);Qd("goog-toolbar-select",function(){return new cf(null)});function df(a){this.n=a;this.Ce=M(this.n,F?"DOMMouseScroll":"mousewheel",this)}y(df,O);
df.prototype.handleEvent=function(a){var b=0,c=0,d=0;a=a.za;if(a.type=="mousewheel"){c=1;if(E||G&&(kb||H("532.0")))c=40;d=-a.wheelDelta/c;if(a.wheelDeltaX!==undefined){b=-a.wheelDeltaX/c;c=-a.wheelDeltaY/c}else c=d}else{d=a.detail;if(d>100)d=3;else if(d<-100)d=-3;if(a.axis!==undefined&&a.axis===a.HORIZONTAL_AXIS)b=d;else c=d}if(ha(this.Ee))b=Math.min(Math.max(b,-this.Ee),this.Ee);if(ha(this.Fe))c=Math.min(Math.max(c,-this.Fe),this.Fe);b=new ef(d,a,b,c);try{this.dispatchEvent(b)}finally{b.C()}};
df.prototype.c=function(){df.a.c.call(this);N(this.Ce);delete this.Ce};function ef(a,b,c,d){b&&this.vb(b,void 0);this.type="mousewheel";this.detail=a;this.ob=c;this.pb=d}y(ef,bc);function ff(a,b,c,d){if(!v(a)||!v(b))throw Error("Start and end parameters must be arrays");if(a.length!=b.length)throw Error("Start and end points must be the same length");this.Eb=a;this.jf=b;this.duration=c;this.Ud=d;this.coords=[]}y(ff,O);var gf={},hf=null;
function jf(){Fe.clearTimeout(hf);var a=pa();for(var b in gf)kf(gf[b],a);hf=Ya(gf)?null:Fe.setTimeout(jf,20)}function lf(a){a=x(a);delete gf[a];if(hf&&Ya(gf)){Fe.clearTimeout(hf);hf=null}}r=ff.prototype;r.i=0;r.je=0;r.ha=0;r.startTime=null;r.fe=null;r.vd=null;
r.play=function(a){if(a||this.i==0){this.ha=0;this.coords=this.Eb}else if(this.i==1)return false;lf(this);this.startTime=pa();if(this.i==-1)this.startTime-=this.duration*this.ha;this.fe=this.startTime+this.duration;this.vd=this.startTime;this.ha||this.Zb();mf(this,"play");this.i==-1&&mf(this,"resume");this.i=1;a=x(this);a in gf||(gf[a]=this);hf||(hf=Fe.setTimeout(jf,20));kf(this,this.startTime);return true};r.stop=function(a){lf(this);this.i=0;if(a)this.ha=1;nf(this,this.ha);mf(this,"stop");this.Fc()};
r.c=function(){this.i!=0&&this.stop(false);mf(this,"destroy");ff.a.c.call(this)};function kf(a,b){a.ha=(b-a.startTime)/(a.fe-a.startTime);if(a.ha>=1)a.ha=1;a.je=1E3/(b-a.vd);a.vd=b;ia(a.Ud)?nf(a,a.Ud(a.ha)):nf(a,a.ha);if(a.ha==1){a.i=0;lf(a);mf(a,"finish");a.Fc()}else a.i==1&&a.Bd()}function nf(a,b){a.coords=Array(a.Eb.length);for(var c=0;c<a.Eb.length;c++)a.coords[c]=(a.jf[c]-a.Eb[c])*b+a.Eb[c]}r.Bd=function(){mf(this,"animate")};r.Zb=function(){mf(this,"begin")};r.Fc=function(){mf(this,"end")};
function mf(a,b){a.dispatchEvent(new of(b,a))}function of(a,b){K.call(this,a);this.coords=b.coords;this.x=b.coords[0];this.y=b.coords[1];this.ng=b.coords[2];this.duration=b.duration;this.ha=b.ha;this.gg=b.je;this.lg=b.i;this.dg=b}y(of,K);function pf(a,b,c){this.target=a;this.handle=b||a;this.Be=c||new Mc(NaN,NaN,NaN,NaN);this.l=J(a);this.ya=new wd(this);M(this.handle,"mousedown",this.Oe,false,this)}y(pf,O);var qf=E||F&&H("1.9.3");r=pf.prototype;r.screenX=0;r.screenY=0;r.Pe=0;r.Qe=0;r.ob=0;r.pb=0;
r.T=true;r.Oa=false;r.ve=0;r.Ff=0;r.Cf=false;r.aa=e("ya");r.Ja=ba("T");r.c=function(){pf.a.c.call(this);Cc(this.handle,"mousedown",this.Oe,false,this);this.ya.C();delete this.target;delete this.handle;delete this.ya};
r.Oe=function(a){if(this.T&&!this.Oa&&(a.type!="mousedown"||dc(a,0))){if(this.ve==0){rf(this,a);if(this.Oa)a.preventDefault();else return}else a.preventDefault();var b=this.l,c=b.documentElement,d=!qf;this.ya.h(b,"mousemove",this.Gf,d);this.ya.h(b,"mouseup",this.tc,d);if(qf){c.setCapture(false);this.ya.h(c,"losecapture",this.tc)}else this.ya.h(b?b.parentWindow||b.defaultView:window,"blur",this.tc);E&&this.Cf&&this.ya.h(b,"dragstart",ac);this.Rf&&this.ya.h(this.Rf,"scroll",this.Kf,d);this.screenX=
this.Pe=a.screenX;this.screenY=this.Qe=a.screenY;this.ob=this.target.offsetLeft;this.pb=this.target.offsetTop;this.$b=Xb(I(this.l));this.Ff=pa()}};function rf(a,b){if(a.dispatchEvent(new sf("start",a,b.clientX,b.clientY,b))!==false)a.Oa=true}r.tc=function(a,b){yd(this.ya);qf&&this.l.releaseCapture();if(this.Oa){this.Oa=false;this.dispatchEvent(new sf("end",this,a.clientX,a.clientY,a,tf(this,this.ob),uf(this,this.pb),b))}};
r.Gf=function(a){if(this.T){var b=a.screenX-this.screenX,c=a.screenY-this.screenY;this.screenX=a.screenX;this.screenY=a.screenY;if(!this.Oa){var d=this.Pe-this.screenX,f=this.Qe-this.screenY;if(d*d+f*f>this.ve){rf(this,a);if(!this.Oa){this.tc(a);return}}}c=vf(this,b,c);b=c.x;c=c.y;if(this.Oa)if(this.dispatchEvent(new sf("beforedrag",this,a.clientX,a.clientY,a,b,c))!==false){wf(this,a,b,c,false);a.preventDefault()}}};
function vf(a,b,c){var d=Xb(I(a.l));b+=d.x-a.$b.x;c+=d.y-a.$b.y;a.$b=d;a.ob+=b;a.pb+=c;return new B(tf(a,a.ob),uf(a,a.pb))}r.Kf=function(a){var b=vf(this,0,0);a.clientX=this.$b.x-this.screenX;a.clientY=this.$b.x-this.screenY;wf(this,a,b.x,b.y,true)};function wf(a,b,c,d){a.Yc(c,d);a.dispatchEvent(new sf("drag",a,b.clientX,b.clientY,b,c,d))}function tf(a,b){var c=a.Be,d=!isNaN(c.left)?c.left:null;c=!isNaN(c.width)?c.width:0;return Math.min(d!=null?d+c:Infinity,Math.max(d!=null?d:-Infinity,b))}
function uf(a,b){var c=a.Be,d=!isNaN(c.top)?c.top:null;c=!isNaN(c.height)?c.height:0;return Math.min(d!=null?d+c:Infinity,Math.max(d!=null?d:-Infinity,b))}r.Yc=function(a,b){this.target.style.left=a+"px";this.target.style.top=b+"px"};function sf(a,b,c,d,f,g,h,i){K.call(this,a);this.clientX=c;this.clientY=d;this.eg=f;this.left=g!==undefined?g:b.ob;this.top=h!==undefined?h:b.pb;this.ee=b;this.fg=!!i}y(sf,K);function xf(a,b,c,d,f){ff.call(this,b,c,d,f);this.element=a}y(xf,ff);xf.prototype.Pc=t;
xf.prototype.Bd=function(){this.Pc();xf.a.Bd.call(this)};xf.prototype.Fc=function(){this.Pc();xf.a.Fc.call(this)};xf.prototype.Zb=function(){this.Pc();xf.a.Zb.call(this)};function yf(a,b,c){if(b.length!=2||c.length!=2)throw Error("Start and end points must be 2D");xf.apply(this,arguments)}y(yf,xf);yf.prototype.Pc=function(){this.element.style.left=Math.round(this.coords[0])+"px";this.element.style.top=Math.round(this.coords[1])+"px"};
function zf(a,b,c,d){yf.call(this,a,[a.offsetLeft,a.offsetTop],b,c,d)}y(zf,yf);zf.prototype.Zb=function(){this.Eb=[this.element.offsetLeft,this.element.offsetTop];zf.a.Zb.call(this)};function Af(){}y(Af,O);r=Af.prototype;r.wa=0;r.ta=0;r.ma=100;r.fa=0;r.Ua=1;r.da=false;r.eb=false;r.A=function(a){a=Bf(this,a);if(this.wa!=a){this.wa=a+this.fa>this.ma?this.ma-this.fa:a<this.ta?this.ta:a;!this.da&&!this.eb&&this.dispatchEvent("change")}};r.o=function(){return Bf(this,this.wa)};
r.Bb=function(a){a=Bf(this,a);if(this.fa!=a){this.fa=a<0?0:this.wa+a>this.ma?this.ma-this.wa:a;!this.da&&!this.eb&&this.dispatchEvent("change")}};r.Ga=function(){var a;a=this.fa;a=this.Ua==null?a:Math.round(a/this.Ua)*this.Ua;return a};r.Hd=function(a){if(this.ta!=a){var b=this.da;this.da=true;this.ta=a;if(a+this.fa>this.ma)this.fa=this.ma-this.ta;a>this.wa&&this.A(a);if(a>this.ma){this.fa=0;this.Lc(a);this.A(a)}this.da=b;!this.da&&!this.eb&&this.dispatchEvent("change")}};
r.Q=function(){return Bf(this,this.ta)};r.Lc=function(a){a=Bf(this,a);if(this.ma!=a){var b=this.da;this.da=true;this.ma=a;a<this.wa+this.fa&&this.A(a-this.fa);if(a<this.ta){this.fa=0;this.Hd(a);this.A(this.ma)}if(a<this.ta+this.fa)this.fa=this.ma-this.ta;this.da=b;!this.da&&!this.eb&&this.dispatchEvent("change")}};r.U=function(){return Bf(this,this.ma)};
r.Ld=function(a){if(this.Ua!=a){this.Ua=a;a=this.da;this.da=true;this.Lc(this.U());this.Bb(this.Ga());this.A(this.o());this.da=a;!this.da&&!this.eb&&this.dispatchEvent("change")}};function Bf(a,b){if(a.Ua==null)return b;return a.ta+Math.round((b-a.ta)/a.Ua)*a.Ua}function Cf(a){Q.call(this,a);this.k=new Af;M(this.k,"change",this.yf,false,this)}y(Cf,Q);r=Cf.prototype;r.w="horizontal";r.rd=false;r.Hf=false;r.Ka=10;r.Yb=0;r.f=function(){Cf.a.f.call(this);this.xa(this.D().f("div",this.g(this.w)))};
r.xa=function(a){Cf.a.xa.call(this,a);Ra(a,this.g(this.w));a=this.b();a=Eb(document,null,"goog-twothumbslider-value-thumb",a)[0];var b=this.b();b=Eb(document,null,"goog-twothumbslider-extent-thumb",b)[0];if(!a){a=Df(this,"goog-twothumbslider-value-thumb");this.b().appendChild(a)}if(!b){b=Df(this,"goog-twothumbslider-extent-thumb");this.b().appendChild(b)}this.G=a;this.ca=b;ld(this.b(),"slider");Ef(this)};
r.O=function(){Cf.a.O.call(this);this.Qc=new pf(this.G);this.ie=new pf(this.ca);this.Qc.Yc=this.ie.Yc=t;this.W=new pd(this.b());this.Ec=new df(this.b());this.aa().h(this.Qc,"beforedrag",this.pe).h(this.ie,"beforedrag",this.pe).h(this.W,"key",this.hd).h(this.b(),"mousedown",this.vf).h(this.Ec,"mousewheel",this.wf);this.b().tabIndex=0;Ff(this)};
r.pe=function(a){var b=a.ee==this.Qc?this.G:this.ca,c;if(this.w=="vertical"){c=this.b().clientHeight-b.offsetHeight;c=(c-a.top)/c*(this.U()-this.Q())+this.Q()}else{c=this.b().clientWidth-b.offsetWidth;c=a.left/c*(this.U()-this.Q())+this.Q()}c=a.ee==this.Qc?Math.min(Math.max(c,this.Q()),this.o()+this.Ga()):Math.min(Math.max(c,this.o()),this.U());Gf(this,b,c)};
r.hd=function(a){var b=true;switch(a.keyCode){case 36:Hf(this,this.Q());break;case 35:Hf(this,this.U());break;case 33:If(this,this.Ka);break;case 34:If(this,-this.Ka);break;case 37:case 40:If(this,a.shiftKey?-this.Ka:-this.Qd);break;case 39:case 38:If(this,a.shiftKey?this.Ka:this.Qd);break;default:b=false}b&&a.preventDefault()};
r.vf=function(a){this.b().focus&&this.b().focus();var b=a.target;if(!Ob(this.G,b)&&!Ob(this.ca,b))if(this.Hf)Hf(this,Jf(this,a));else{this.Od(a);this.oa=Kf(this,Jf(this,a));this.we=this.w=="vertical"?this.Bc<this.oa.offsetTop:this.Bc>this.oa.offsetLeft+this.oa.offsetWidth;a=J(this.b());this.aa().h(a,"mouseup",this.re,true).h(this.b(),"mousemove",this.Od);if(!this.Pa){this.Pa=new Ee(200);this.aa().h(this.Pa,Ge,this.se)}this.se();this.Pa.start()}};
r.wf=function(a){If(this,(a.detail>0?-1:1)*this.Qd);a.preventDefault()};r.se=function(){var a;if(this.w=="vertical"){var b=this.Bc,c=this.oa.offsetTop;if(this.we){if(b<c)a=Lf(this,this.oa)+this.Ka}else if(b>c+this.oa.offsetHeight)a=Lf(this,this.oa)-this.Ka}else{b=this.Bc;c=this.oa.offsetLeft;if(this.we){if(b>c+this.oa.offsetWidth)a=Lf(this,this.oa)+this.Ka}else if(b<c)a=Lf(this,this.oa)-this.Ka}a!==undefined&&Gf(this,this.oa,a)};
r.re=function(){this.Pa&&this.Pa.stop();var a=J(this.b());this.aa().ja(a,"mouseup",this.re,true).ja(this.b(),"mousemove",this.Od)};function Mf(a,b){var c,d=a.b();c=Wc(b);d=Wc(d);c=new B(c.x-d.x,c.y-d.y);return a.w=="vertical"?c.y:c.x}r.Od=function(a){this.Bc=Mf(this,a)};function Jf(a,b){var c=a.Q(),d=a.U();if(a.w=="vertical"){var f=a.G.offsetHeight,g=a.b().clientHeight-f;f=Mf(a,b)-f/2;return(d-c)*(g-f)/g+c}else{f=a.G.offsetWidth;g=a.b().clientWidth-f;f=Mf(a,b)-f/2;return(d-c)*f/g+c}}
function Lf(a,b){if(b==a.G)return a.k.o();else if(b==a.ca)return a.k.o()+a.k.Ga();else throw Error("Illegal thumb element. Neither minThumb nor maxThumb");}function If(a,b){var c=Lf(a,a.G)+b,d=Lf(a,a.ca)+b;c=Math.min(Math.max(c,a.Q()),a.U()-a.Yb);d=Math.min(Math.max(d,a.Q()+a.Yb),a.U());Of(a,c,d-c)}
function Gf(a,b,c){var d=null;if(b==a.ca&&c<=a.k.U()&&c>=a.k.o()+a.Yb)d=c-a.k.o();var f=d||a.k.Ga();if(b==a.G&&c>=a.Q()&&c<=a.k.o()+f-a.Yb){b=f-(c-a.k.o());if(Bf(a.k,c)+Bf(a.k,b)==Bf(a.k,c+b)){Of(a,c,b);d=null}}d!=null&&a.k.Bb(d)}function Of(a,b,c){if(a.Q()<=b&&b<=a.U()-c&&a.Yb<=c&&c<=a.U()-b)if(!(b==a.o()&&c==a.Ga())){a.k.eb=true;a.k.Bb(0);a.k.A(b);a.k.Bb(c);a.k.eb=false;Ff(a);a.dispatchEvent("change")}}r.Q=function(){return this.k.Q()};r.Hd=function(a){this.k.Hd(a)};r.U=function(){return this.k.U()};
r.Lc=function(a){this.k.Lc(a)};function Kf(a,b){return b<=a.k.o()+a.k.Ga()/2?a.G:a.ca}r.yf=function(){Ff(this);Ef(this);this.dispatchEvent("change")};function Ff(a){if(a.G&&!a.rd){var b=Pf(a,Lf(a,a.G)),c=Pf(a,Lf(a,a.ca));if(a.w=="vertical"){a.G.style.top=b.y+"px";a.ca.style.top=c.y+"px"}else{a.G.style.left=b.x+"px";a.ca.style.left=c.x+"px"}}}
function Pf(a,b){var c=new B;if(a.G){var d=a.Q(),f=a.U();d=b==d&&d==f?0:(b-d)/(f-d);if(a.w=="vertical"){f=a.G.offsetHeight;f=a.b().clientHeight-f;c.y=f-Math.round(d*f)}else{f=a.b().clientWidth-a.G.offsetWidth;c.x=Math.round(d*f)}}return c}function Hf(a,b){b=Math.min(a.U(),Math.max(b,a.Q()));a.Jb&&a.Jb.stop(true);var c=Kf(a,b),d=Pf(a,b);d=new zf(c,a.w=="vertical"?[c.offsetLeft,d.y]:[d.x,c.offsetTop],100);a.Jb=d;a.aa().h(d,"end",a.hf);a.rd=true;Gf(a,c,b);d.play(false)}r.hf=function(){this.rd=false};
r.Id=function(a){if(this.w!=a){var b=this.g(this.w),c=this.g(a);this.w=a;if(this.b()){a=this.b();for(var d=Qa(a),f=false,g=0;g<d.length;g++)if(d[g]==b){Na(d,g--,1);f=true}if(f){d.push(c);a.className=d.join(" ")}this.G.style.left=this.G.style.top="";this.ca.style.left=this.ca.style.top="";Ff(this)}}};
r.c=function(){Cf.a.c.call(this);this.Pa&&this.Pa.C();delete this.Pa;this.Jb&&this.Jb.C();delete this.Jb;delete this.G;delete this.ca;this.k.C();delete this.k;if(this.W){this.W.C();delete this.W}if(this.Ec){this.Ec.C();delete this.Ec}};r.Qd=1;r.Ld=function(a){this.k.Ld(a)};r.o=function(){return this.k.o()};r.A=function(a){Gf(this,this.G,a)};r.Ga=function(){return this.k.Ga()};r.Bb=function(a){Gf(this,this.ca,this.k.o()+a)};r.na=function(a){bd(this.b(),a);a&&Ff(this)};
function Ef(a){var b=a.b();if(b){md(b,"valuemin",a.Q());md(b,"valuemax",a.U());md(b,"valuenow",a.o())}}function Qf(a){Cf.call(this,a);this.k.A(this.Q());this.k.Bb(this.U()-this.Q())}y(Qf,Cf);Qf.prototype.g=function(a){return"goog-twothumbslider-"+a};function Df(a,b){var c=a.D().f("div",b);ld(c,"button");return c}function Rf(a){if(typeof a.wc=="function")return a.wc();if(w(a))return a.split("");if(ga(a)){for(var b=[],c=a.length,d=0;d<c;d++)b.push(a[d]);return b}return Wa(a)}
function Sf(a,b,c){if(typeof a.forEach=="function")a.forEach(b,c);else if(ga(a)||w(a))A(a,b,c);else{var d;if(typeof a.cd=="function")d=a.cd();else if(typeof a.wc!="function")if(ga(a)||w(a)){d=[];for(var f=a.length,g=0;g<f;g++)d.push(g);d=d}else d=Xa(a);else d=void 0;f=Rf(a);g=f.length;for(var h=0;h<g;h++)b.call(c,f[h],d&&d[h],a)}}
function Tf(a){this.Ra={};this.p=[];var b=arguments.length;if(b>1){if(b%2)throw Error("Uneven number of arguments");for(var c=0;c<b;c+=2)Uf(this,arguments[c],arguments[c+1])}else if(a){if(a instanceof Tf){b=a.cd();c=a.wc()}else{b=Xa(a);c=Wa(a)}for(var d=0;d<b.length;d++)Uf(this,b[d],c[d])}}r=Tf.prototype;r.$=0;r.Ue=0;r.wc=function(){Vf(this);for(var a=[],b=0;b<this.p.length;b++)a.push(this.Ra[this.p[b]]);return a};r.cd=function(){Vf(this);return this.p.concat()};
r.clear=function(){this.Ra={};this.Ue=this.$=this.p.length=0};function Vf(a){if(a.$!=a.p.length){for(var b=0,c=0;b<a.p.length;){var d=a.p[b];if(Object.prototype.hasOwnProperty.call(a.Ra,d))a.p[c++]=d;b++}a.p.length=c}if(a.$!=a.p.length){var f={};for(c=b=0;b<a.p.length;){d=a.p[b];if(!Object.prototype.hasOwnProperty.call(f,d)){a.p[c++]=d;f[d]=1}b++}a.p.length=c}}r.qb=function(a,b){if(Object.prototype.hasOwnProperty.call(this.Ra,a))return this.Ra[a];return b};
function Uf(a,b,c){if(!Object.prototype.hasOwnProperty.call(a.Ra,b)){a.$++;a.p.push(b);a.Ue++}a.Ra[b]=c}r.Ma=function(){return new Tf(this)};function Wf(a){return Xf(a||arguments.callee.caller,[])}
function Xf(a,b){var c=[];if(Ha(b,a))c.push("[...circular reference...]");else if(a&&b.length<50){c.push(Yf(a)+"(");for(var d=a.arguments,f=0;f<d.length;f++){f>0&&c.push(", ");var g;g=d[f];switch(typeof g){case "object":g=g?"object":"null";break;case "string":g=g;break;case "number":g=String(g);break;case "boolean":g=g?"true":"false";break;case "function":g=(g=Yf(g))?g:"[fn]";break;case "undefined":default:g=typeof g;break}if(g.length>40)g=g.substr(0,40)+"...";c.push(g)}b.push(a);c.push(")\n");try{c.push(Xf(a.caller,
b))}catch(h){c.push("[exception trying to get caller]\n")}}else a?c.push("[...long stack...]"):c.push("[end]");return c.join("")}function Yf(a){a=String(a);if(!Zf[a]){var b=/function ([^\(]+)/.exec(a);Zf[a]=b?b[1]:"[Anonymous]"}return Zf[a]}var Zf={};function $f(a,b,c,d,f){this.reset(a,b,c,d,f)}$f.prototype.Sf=0;$f.prototype.he=null;$f.prototype.ge=null;var ag=0;$f.prototype.reset=function(a,b,c,d,f){this.Sf=typeof f=="number"?f:ag++;this.mg=d||pa();this.Xb=a;this.jg=b;this.hg=c;delete this.he;delete this.ge};
$f.prototype.Ke=ba("Xb");function bg(a){this.If=a}bg.prototype.u=null;bg.prototype.Xb=null;bg.prototype.N=null;bg.prototype.ue=null;function cg(a,b){this.name=a;this.value=b}cg.prototype.toString=e("name");var dg=new cg("SEVERE",1E3),eg=new cg("WARNING",900),fg=new cg("CONFIG",700),gg=new cg("FINE",500),hg=new cg("FINEST",300);bg.prototype.Ke=ba("Xb");function ig(a){if(a.Xb)return a.Xb;if(a.u)return ig(a.u);Da("Root logger has no level set.");return null}
bg.prototype.log=function(a,b,c){if(a.value>=ig(this).value){a=this.mf(a,b,c);for(b=this;b;){c=b;var d=a;if(c.ue)for(var f=0,g=void 0;g=c.ue[f];f++)g(d);b=b.u}}};
bg.prototype.mf=function(a,b,c){var d=new $f(a,String(b),this.If);if(c){d.he=c;var f;var g=arguments.callee.caller;try{var h,i=da("window.location.href");h=typeof c=="string"?{message:c,name:"Unknown error",lineNumber:"Not available",fileName:i,stack:"Not available"}:!c.lineNumber||!c.fileName||!c.stack?{message:c.message,name:c.name,lineNumber:c.lineNumber||c.ga||"Not available",fileName:c.fileName||c.filename||c.sourceURL||i,stack:c.stack||"Not available"}:c;f="Message: "+ta(h.message)+'\nUrl: <a href="view-source:'+
h.fileName+'" target="_new">'+h.fileName+"</a>\nLine: "+h.lineNumber+"\n\nBrowser stack:\n"+ta(h.stack+"-> ")+"[end]\n\nJS stack traversal:\n"+ta(Wf(g)+"-> ")}catch(k){f="Exception trying to expose exception! You win, we lose. "+k}d.ge=f}return d};function Z(a,b,c){a.log(gg,b,c)}var jg={},kg=null;
function lg(a){if(!kg){kg=new bg("");jg[""]=kg;kg.Ke(fg)}var b;if(!(b=jg[a])){b=new bg(a);var c=a.lastIndexOf("."),d=a.substr(0,c);c=a.substr(c+1);d=lg(d);if(!d.N)d.N={};d.N[c]=b;b.u=d;b=jg[a]=b}return b}function mg(){}mg.prototype.pc=null;function ng(){return og(pg)}var pg;function qg(){}y(qg,mg);function og(a){return(a=rg(a))?new ActiveXObject(a):new XMLHttpRequest}function sg(a){var b={};if(rg(a)){b[0]=true;b[1]=true}return b}qg.prototype.od=null;
function rg(a){if(!a.od&&typeof XMLHttpRequest=="undefined"&&typeof ActiveXObject!="undefined"){for(var b=["MSXML2.XMLHTTP.6.0","MSXML2.XMLHTTP.3.0","MSXML2.XMLHTTP","Microsoft.XMLHTTP"],c=0;c<b.length;c++){var d=b[c];try{new ActiveXObject(d);return a.od=d}catch(f){}}throw Error("Could not create ActiveXObject. ActiveX might be disabled, or MSXML might not be installed");}return a.od}pg=new qg;function tg(){if(F){this.Xa={};this.Tc={};this.Nc=[]}}tg.prototype.R=lg("goog.net.xhrMonitor");
tg.prototype.T=F;tg.prototype.Ja=function(a){this.T=F&&a};function ug(a,b){if(a.T){var c=w(b)?b:ja(b)?x(b):"";a.R.log(hg,"Pushing context: "+b+" ("+c+")",void 0);a.Nc.push(c)}}function vg(a){if(a.T){var b=a.Nc.pop();a.R.log(hg,"Popping context: "+b,void 0);wg(a,b)}}function xg(a,b){if(a.T){var c=x(b);Z(a.R,"Opening XHR : "+c);for(var d=0;d<a.Nc.length;d++){var f=a.Nc[d];yg(a,a.Xa,f,c);yg(a,a.Tc,c,f)}}}
function wg(a,b){var c=a.Tc[b],d=a.Xa[b];if(c&&d){a.R.log(hg,"Updating dependent contexts",void 0);A(c,function(f){A(d,function(g){yg(this,this.Xa,f,g);yg(this,this.Tc,g,f)},this)},a)}}function yg(a,b,c,d){b[c]||(b[c]=[]);Ha(b[c],d)||b[c].push(d)}var $=new tg;function zg(a){this.headers=new Tf;this.Hb=a||null}y(zg,O);zg.prototype.R=lg("goog.net.XhrIo");var Ag=[];function Bg(a,b,c,d,f,g){var h=new zg;Ag.push(h);b&&M(h,"complete",b);M(h,"ready",oa(Cg,h));if(g)h.hc=Math.max(0,g);h.send(a,c,d,f)}
function Cg(a){a.C();Ia(Ag,a)}r=zg.prototype;r.Da=false;r.v=null;r.Sc=null;r.Ae="";r.ze="";r.Ub=0;r.Vb="";r.$c=false;r.yc=false;r.pd=false;r.bb=false;r.hc=0;r.jb=null;
r.send=function(a,b,c,d){if(this.Da)throw Error("[goog.net.XhrIo] Object is active with another request");b=b||"GET";this.Ae=a;this.Vb="";this.Ub=0;this.ze=b;this.$c=false;this.Da=true;this.v=this.Hb?og(this.Hb):new ng;this.Sc=this.Hb?this.Hb.pc||(this.Hb.pc=sg(this.Hb)):pg.pc||(pg.pc=sg(pg));xg($,this.v);this.v.onreadystatechange=na(this.He,this);try{Z(this.R,Dg(this,"Opening Xhr"));this.pd=true;this.v.open(b,a,true);this.pd=false}catch(f){Z(this.R,Dg(this,"Error opening Xhr: "+f.message));Eg(this,
5,f);return}a=c||"";var g=this.headers.Ma();d&&Sf(d,function(i,k){Uf(g,k,i)});b=="POST"&&!Object.prototype.hasOwnProperty.call(g.Ra,"Content-Type")&&Uf(g,"Content-Type","application/x-www-form-urlencoded;charset=utf-8");Sf(g,function(i,k){this.v.setRequestHeader(k,i)},this);try{if(this.jb){Fe.clearTimeout(this.jb);this.jb=null}if(this.hc>0){Z(this.R,Dg(this,"Will abort after "+this.hc+"ms if incomplete"));this.jb=Fe.setTimeout(na(this.$f,this),this.hc)}Z(this.R,Dg(this,"Sending request"));this.yc=
true;this.v.send(a);this.yc=false}catch(h){Z(this.R,Dg(this,"Send error: "+h.message));Eg(this,5,h)}};r.dispatchEvent=function(a){if(this.v){ug($,this.v);try{return zg.a.dispatchEvent.call(this,a)}finally{vg($)}}else return zg.a.dispatchEvent.call(this,a)};r.$f=function(){if(typeof ca!="undefined")if(this.v){this.Vb="Timed out after "+this.hc+"ms, aborting";this.Ub=8;Z(this.R,Dg(this,this.Vb));this.dispatchEvent("timeout");this.abort(8)}};
function Eg(a,b,c){a.Da=false;if(a.v){a.bb=true;a.v.abort();a.bb=false}a.Vb=c;a.Ub=b;Fg(a);Gg(a)}function Fg(a){if(!a.$c){a.$c=true;a.dispatchEvent("complete");a.dispatchEvent("error")}}r.abort=function(a){if(this.v){Z(this.R,Dg(this,"Aborting"));this.Da=false;this.bb=true;this.v.abort();this.bb=false;this.Ub=a||7;this.dispatchEvent("complete");this.dispatchEvent("abort");Gg(this)}};r.c=function(){if(this.v){if(this.Da){this.Da=false;this.bb=true;this.v.abort();this.bb=false}Gg(this,true)}zg.a.c.call(this)};
r.He=function(){!this.pd&&!this.yc&&!this.bb?this.Cd():Hg(this)};r.Cd=function(){Hg(this)};
function Hg(a){if(a.Da)if(typeof ca!="undefined")if(a.Sc[1]&&Ig(a)==4&&Jg(a)==2)Z(a.R,Dg(a,"Local request error detected and ignored"));else if(a.yc&&Ig(a)==4)Fe.setTimeout(na(a.He,a),0);else{a.dispatchEvent("readystatechange");if(Ig(a)==4){Z(a.R,Dg(a,"Request complete"));a.Da=false;var b;a:switch(Jg(a)){case 0:case 200:case 204:case 304:b=true;break a;default:b=false;break a}if(b){a.dispatchEvent("complete");a.dispatchEvent("success")}else{a.Ub=6;var c;try{c=Ig(a)>2?a.v.statusText:""}catch(d){Z(a.R,
"Can not get status: "+d.message);c=""}a.Vb=c+" ["+Jg(a)+"]";Fg(a)}Gg(a)}}}function Gg(a,b){if(a.v){var c=a.v,d=a.Sc[0]?t:null;a.v=null;a.Sc=null;if(a.jb){Fe.clearTimeout(a.jb);a.jb=null}if(!b){ug($,c);a.dispatchEvent("ready");vg($)}if($.T){var f=x(c);Z($.R,"Closing XHR : "+f);delete $.Tc[f];for(var g in $.Xa){Ia($.Xa[g],f);$.Xa[g].length==0&&delete $.Xa[g]}}try{c.onreadystatechange=d}catch(h){a.R.log(dg,"Problem encountered resetting onreadystatechange: "+h.message,void 0)}}}r.Tb=e("Da");
function Ig(a){return a.v?a.v.readyState:0}function Jg(a){try{return Ig(a)>2?a.v.status:-1}catch(b){a.R.log(eg,"Can not get status: "+b.message,void 0);return-1}}function Dg(a,b){return b+" ["+a.ze+" "+a.Ae+" "+Jg(a)+"]"}Yb[Yb.length]=function(a){zg.prototype.Cd=a.bg(zg.prototype.Cd)};lg("goog.dom.SavedRange");lg("goog.dom.browserrange.IeRange");hte2.lc=function(){this.kb=hte2.L.Za();this.kb.j=null;M(this.kb,"click",this.Gd);this.j=null};
hte2.lc.prototype={gc:function(a){this.kb.j=a},Gd:function(a){var b;b=a.target;a=a.clientX;a-=hte2.L.Za().offsetLeft;if(b.nodeName==="SPAN"){a-=parseInt(b.parentNode.style.paddingLeft,10);this.j.Le(b.parentNode,a-8)}}};hte2.kc=function(){this.la=new pd(document);this.la.j=null;M(this.la,"key",this.qd)};
hte2.kc.prototype={gc:function(a){this.la.j=a},qd:function(a){var b;a.preventDefault();switch(a.keyCode){case 37:this.j.Oc();break;case 39:this.j.Fb();break;case 38:this.j.yd();break;case 40:this.j.xd();break;case 8:this.j.Oc();hte2.L.Jc(hte2.B.Z(this.j.q).X);break;case 46:hte2.L.Jc(hte2.B.Z(this.j.q).X);break;case 13:hte2.L.nc(hte2.B.Z(this.j.q).X-1);this.j.Fb();break;default:if(a.charCode!==undefined&&a.charCode!==0){b=hte2.B.Z(this.j.q).X-1;hte2.L.Vd(a.charCode,b);this.j.Fb()}break}this.j.Dd()}};
hte2.Sd=function(){this.Tf=new ed;this.Ed={id:Math.round(Math.random()*1E5),jsonrpc:"2.0"}};hte2.Sd.prototype={Pf:function(a,b){this.Ed.method=b;this.Ed.params={document:a};Bg("/",aa(),"POST",fd(this.Tf,this.Ed),{"Content-Type":"application/json"})}};hte2.m=new kd;hte2.lc=function(){this.kb=hte2.L.Za();this.kb.j=null;M(this.kb,"click",this.Gd);this.j=null};
hte2.lc.prototype={gc:function(a){this.kb.j=a},Gd:function(a){var b;b=a.target;a=a.clientX;a-=hte2.L.Za().offsetLeft;if(b.nodeName==="SPAN"){a-=parseInt(b.parentNode.style.paddingLeft,10);this.j.Le(b.parentNode,a-8)}}};hte2.mc=new Tf;hte2.Td=function(){this.X=this.q=0;this.zd=[];this.ga=null};
hte2.Td.prototype={fb:function(a){var b=this.zd.length,c;for(c=0;c<b;c+=1)this.zd[c].Mf(a)},Mc:function(a){this.X=a;hte2.m.K("positionSet",a)},Ze:function(a){this.zd.push(a)},Le:function(a,b){this.ga=a;var c=hte2.B.Z(b,true);this.q=c.q;this.Mc(c.X);this.fb(c)},Wf:function(a,b){this.ga=a;var c=hte2.B.Z(b);this.q=c.q;this.Mc(c.X);this.fb(c)},yd:function(){if(this.ga.previousSibling.id!=="hte-cursor"){this.ga=this.ga.previousSibling;var a=hte2.B.Z(this.q);hte2.m.K("positionSet",a.X);this.fb(a)}},xd:function(){if(this.ga.nextSibling){this.ga=
this.ga.nextSibling;var a=hte2.B.Z(this.q);hte2.m.K("positionSet",a.X);this.fb(a)}},Oc:function(){var a;this.q-=1;if(this.q<0){this.yd();this.q=this.ga.firstChild.firstChild.nodeValue.length}a=hte2.B.Z(this.q);this.Mc(a.X);this.fb(a)},Fb:function(){var a,b,c=0;this.q+=1;a=this.ga.childNodes;for(b=0;b<a.length;b+=1)if(a[b].firstChild)c+=a[b].firstChild.nodeValue.length;if(this.q>c){this.xd();this.q-=c}a=hte2.B.Z(this.q);this.Mc(a.X);this.fb(a)},Dd:function(){this.fb(hte2.B.Z(this.q))}};
hte2.Rd=function(){var a;this.Xc=(new Bb).jc("hte-cursor");a=function(b){return function(){b.style.display=b.style.display==="block"?"none":"block"}}(this.Xc);this.gf=this.ef=this.q=0;setInterval(a,600)};hte2.Rd.prototype={Me:function(a,b){var c=this.Xc.style;c.left=a+"px";c.top=b+"px";this.ef=a;this.gf=b;c.display="block"},Vf:function(a){this.Xc.style.height=a+"px"},Xf:ba("q"),Mf:function(a){this.Me(a.x,a.y);this.Vf(a.height);this.Xf(a.q)}};
hte2.B=function(){var a,b,c,d;a=(new Bb).b("hte-measurer");b=function(){var f,g,h,i=0;for(f=hte2.mc.qb("_lcl_").ga.previousSibling;f&&f.id!=="hte-cursor";){g=f.childNodes;for(h=0;h<g.length;h+=1)if(g[h].firstChild)i+=g[h].firstChild.nodeValue.length;f=f.previousSibling}return i-1};c=function(f){return f.offsetTop};d=function(f){return f.offsetHeight};return{Z:function(f,g){var h=0,i,k=0,j,m,l,o,q=1,C;k=parseInt(hte2.L.Za().style.paddingLeft,10);m=hte2.mc.qb("_lcl_").ga;o=m.childNodes;i=function(){return q<
f};j=function(){return k<=f};j=g?j:i;for(i=0;i<o.length;i+=1){l=o[i].firstChild;if(l!==null)for(l=l.nodeValue;j();){a.innerHTML='<span style="'+hte2.ba.df(o[i])+'">'+l.charAt(h)+"</span>";k+=a.firstChild.offsetWidth;h+=1;q+=1;C=o[i];if(h===l.length)break}h=0}C||(C=o[0]);return{x:k+parseInt(m.style.paddingLeft,10),y:c(C),height:d(C),q:q,X:b()+q}},Ob:function(f){a.innerHTML=f;return a.offsetWidth}}}();
hte2.ba=function(){var a,b=hte2.dataStorage.styling,c,d,f,g=false,h,i=hte2.dataStorage.paragraphs;f=d={style:{fs:12,ff:"Arial",fw:"normal",fst:"normal"},start:0,end:13};c={ff:["font-family","","fontFamily"],fw:["font-weight","","fontWeight"],fs:["font-size","pt","fontSize"],td:["text-decoration","","textDecoration"],fst:["font-style","","fontStyle"]};h=function(k,j,m){var l,o;for(l=0;l<b.length;l+=1)if(b[l].start<k&&b[l].end>=k){o=b[l].end;b[l].end=k-1;b.splice(l+1,0,{style:m,start:k,end:j});b[l+
2]?b.splice(l+2,0,{style:b[l].style,start:j+1,end:b[l+2].start-1}):b.splice(l+2,0,{style:b[l].style,start:j+1,end:o})}};return a={oe:function(){return b},nc:function(k){var j;for(j=0;j<i.length;j+=1)if(k<i[j].end){i.splice(j+1,0,{width:i[j].width,pl:i[j].pl,pr:i[j].pr,start:k,end:i[j].end});i[j].end=k-1;break}},Uf:function(k){var j,m=b;if(k){for(j=0;j<b.length;j+=1)if(b[j].start<=k-1)m=b[j];f=m.style;d=ab(m.style);g=false;hte2.m.K("styleChanged",d)}return d},cf:function(k){d[k[0]]=k[1];g=true},Te:function(k,
j){var m,l=[];for(m=0;m<b.length;m+=1){if(k<b[m].start&&b[m].start!==0)b[m].start+=j==="add"?1:-1;if(k<=b[m].end)b[m].end+=j==="add"?1:-1;l.push(b[m])}b=l;l=[];for(m=0;m<i.length;m+=1){if(j!=="add"&&k===i[m].start){i[m-1].end=i[m].end-1;i[m+1].start=i[m].end+1;i.splice(m,1)}if(k<i[m].start)i[m].start+=j==="add"?1:-1;if(k<=i[m].end)i[m].end+=j==="add"?1:-1;l.push(i[m])}i=l;g&&h(k+1,k+1,ab(d))},kf:function(k){var j,m="";for(j in k)if(k.hasOwnProperty(j))m+=c[j][0]+":"+k[j]+c[j][1]+";";return m},df:function(k){var j,
m="";for(j in c)if(c.hasOwnProperty(j))if(k.style[c[j][2]])m+=c[j][0]+":"+k.style[c[j][2]]+";";return m},lf:function(){return i},nf:function(k){return i[k]?i[k]:i[i.length-1]},me:function(k){var j,m=0;for(j=0;j<i.length;j+=1)if(i[j].start<=k&&k<=i[j].end){m=j;break}return i[m]},Yf:function(k,j,m){var l=a.me(hte2.mc.qb("_lcl_").X);if(l.width!==k){l.width=k;l.pl=j;l.pr=m;hte2.m.K("rerender")}}}}();
hte2.L=function(){var a,b,c,d,f,g=new Bb,h;a=g.jc("hte-workbench");c=hte2.dataStorage.docText.split("");f=function(){var i;i=c.join("").split("\n");i=i.join(" \n ");return i.split(" ")};d=function(i,k){var j,m;j=c.slice(0,k+1);m=c.slice(k+1);j.push(i);c=j.concat(m);hte2.ba.Te(k,"add")};h=hte2.ba.kf;return{Ab:function(){var i=hte2.ba.oe(),k,j,m=0,l,o="",q=0,C,X,Ma,n,fa,sb,ka,Xd,Yd,Nf=0,Wb;C=f();l=j=0;fa=Cb("hte-line",a||g.l);sb=false;for(k=0;k<C.length;k+=1){Wb=hte2.ba.nf(Nf);b=parseInt(Wb.width,10);
n=C[k]+String.fromCharCode(160);X=q;Ma=q+(n.length-1);if(n!=="\n"+String.fromCharCode(160))if(i[j].start<X&&Ma<=i[j].end){ka=hte2.B.Ob('<span style="'+h(i[j].style)+'">'+n+"</span>");if(l+ka<b){l+=ka;o+=n}else{k-=1;sb=true;q-=n.length}}else if(Ma>i[j].end){for(Yd="";n.length!==0;){Ma-=1;n=n.split("");Yd+=n.pop();n=n.join("");if(Ma===i[j].end){if(X<=i[j].start){n=n.split("");n.splice(0,i[j].start-X);n=n.join("");ka=hte2.B.Ob('<span style="'+h(i[j].style)+'">'+n+"</span>");Xd='<span style="'+h(i[j].style)+
'">'+n+"</span>"}else{ka=hte2.B.Ob('<span style="'+h(i[j].style)+'">'+n+"</span>");Xd=n+"</span>"}j+=1;k-=1;break}}X=hte2.B.Ob('<span style="'+h(i[j].style)+'">'+Yd+"</span>");if(l+(ka+X)<b){l+=ka;o+=Xd}else{j-=1;sb=true}q-=n.length}else{ka=hte2.B.Ob('<span style="'+h(i[j].style)+'">'+n.substr(i[j].start-X)+"</span>");if(l+ka<b){o+='<span style="'+h(i[j].style)+'">'+n.substr(i[j].start-X);l+=ka}else{k-=1;sb=true;q-=n.length}}else q-=2;q+=n.length;if(sb||n==="\n"+String.fromCharCode(160)){sb=false;
o+="</span>";if(fa.length===0){l=(new hte2.Uc(Wb.pl)).qb();a.appendChild(l);l.innerHTML=o}else if(fa[m]){fa[m].style.paddingLeft=Wb.pl+"px";fa[m].innerHTML=o;m+=1}else{l=(new hte2.Uc(Wb.pl)).qb();a.appendChild(l);l.innerHTML=o}o='<span style="'+h(i[j].style)+'">';l=0;if(n==="\n"+String.fromCharCode(160))Nf+=1}}if(fa.length!==0&&fa.length>m)for(k=m;k<fa.length;k+=1)fa[m].parentNode&&fa[m].parentNode.removeChild(fa[m])},Jc:function(i){c.splice(i,1);hte2.ba.Te(i,"remove");hte2.m.K("rerender")},nc:function(i){d("\n",
i);hte2.ba.nc(i);hte2.m.K("rerender")},Vd:function(i,k){d(String.fromCharCode(i),k);hte2.m.K("rerender")},Za:function(){return a},of:function(){return c}}}();hte2.Uc=function(a){var b;b=document.createElement("div");b.className="hte-line";b.style.paddingLeft=a+"px";this.Ef=b};hte2.Uc.prototype={qb:e("Ef")};hte2.kc=function(){this.la=new pd(document);this.la.j=null;M(this.la,"key",this.qd)};
hte2.kc.prototype={gc:function(a){this.la.j=a},qd:function(a){var b;a.preventDefault();switch(a.keyCode){case 37:this.j.Oc();break;case 39:this.j.Fb();break;case 38:this.j.yd();break;case 40:this.j.xd();break;case 8:this.j.Oc();hte2.L.Jc(hte2.B.Z(this.j.q).X);break;case 46:hte2.L.Jc(hte2.B.Z(this.j.q).X);break;case 13:hte2.L.nc(hte2.B.Z(this.j.q).X-1);this.j.Fb();break;default:if(a.charCode!==undefined&&a.charCode!==0){b=hte2.B.Z(this.j.q).X-1;hte2.L.Vd(a.charCode,b);this.j.Fb()}break}this.j.Dd()}};
hte2.Ye=function(){var a,b=new Bb,c,d,f,g,h,i,k,j,m;c=new Ce(b.f("div",{id:"hte-boldbutton"},b.createTextNode(String.fromCharCode(160))));P(hte2.m,"styleChanged",function(l){l.fw==="bold"?Zd(c,true):Zd(c,false)});M(c,"action",function(){c.i&16?hte2.m.K("updateComputedStyle",["fw","bold"]):hte2.m.K("updateComputedStyle",["fw","normal"])});d=new Ce(b.f("div",{id:"hte-italicbutton"},b.createTextNode(String.fromCharCode(160))));P(hte2.m,"styleChanged",function(l){l.fst==="italic"?Zd(d,true):Zd(d,false)});
M(d,"action",function(){d.i&16?hte2.m.K("updateComputedStyle",["fst","italic"]):hte2.m.K("updateComputedStyle",["fst","normal"])});g=new Ce(b.f("div",{id:"hte-underlinebutton"},b.createTextNode(String.fromCharCode(160))));P(hte2.m,"styleChanged",function(l){l.td==="underline"?Zd(g,true):Zd(g,false)});M(g,"action",function(){g.i&16?hte2.m.K("updateComputedStyle",["td","underline"]):hte2.m.K("updateComputedStyle",["td","none"])});h=new Ce(b.f("div",{id:"hte-linethroughbutton"},b.createTextNode(String.fromCharCode(160))));
P(hte2.m,"styleChanged",function(l){l.td==="line-through"?Zd(h,true):Zd(h,false)});M(h,"action",function(){h.i&16?hte2.m.K("updateComputedStyle",["td","line-through"]):hte2.m.K("updateComputedStyle",["td","none"])});i=new cf("");i.M(new V("8"));i.M(new V("10"));i.M(new V("11"));i.M(new V("12"));i.M(new V("14"));i.M(new V("18"));i.M(new V("24"));i.M(new V("36"));i.A("12");P(hte2.m,"styleChanged",function(l){i.A(l.fs)});M(i,"action",function(){hte2.m.K("updateComputedStyle",["fs",i.o()])});k=new cf("");
k.M(new V("Arial"));k.M(new V("Courier new"));k.M(new V("Times New Roman"));k.A("Arial");P(hte2.m,"styleChanged",function(l){k.A(l.ff)});M(k,"action",function(){hte2.m.K("updateComputedStyle",["ff",k.o()])});f=new De(b.f("div",{id:"hte-savebutton"},b.createTextNode("Save")));M(f,"action",function(){var l={docText:hte2.L.of().join(""),styling:hte2.ba.oe(),paragraphs:hte2.ba.lf()};(new hte2.Sd).Pf(l,"save")});a=new te;a.ka(f,true);a.ka(c,true);a.ka(d,true);a.ka(g,true);a.ka(h,true);a.ka(i,true);a.ka(k,
true);a.Ab(b.jc("hte-panel"));j=new Qf;j.f();a=j.b();a.style.width="100%";a.style.height="10px";j.Ld(1);m=parseInt(hte2.L.Za().style.width,10)/100;j.addEventListener("change",function(){var l,o;l=j.o()*m;o=(j.o()+j.Ga())*m;hte2.m.K("pWidth",o-l,l,o)});j.Ab(b.jc("hte-slider"));return{ag:function(l){l=hte2.ba.me(l);Of(j,l.pl/m,(l.pr-l.pl)/m)}}}();
(function(){var a=new Jc,b,c=new Bb,d;b=function(){var f=a.ne().height-60;Zc(w("hte-workbench-container")?document.getElementById("hte-workbench-container"):"hte-workbench-container",f)};b();M(a,"resize",function(){b()});d=new hte2.Td;d.Ze(new hte2.Rd);(new hte2.lc).gc(d);(new hte2.kc).gc(d);P(hte2.m,"rerender",hte2.L.Ab);P(hte2.m,"rangeReady",hte2.ba.cg);P(hte2.m,"positionSet",hte2.ba.Uf);P(hte2.m,"positionSet",hte2.Ye.ag);P(hte2.m,"updateComputedStyle",hte2.ba.cf);P(hte2.m,"pWidth",hte2.ba.Yf);
P(hte2.m,"pWidth",d.Dd,d);Uf(hte2.mc,"_lcl_",d);hte2.L.Ab();d.Wf(Cb("hte-line",hte2.L.Za()||c.l)[0],1)})();
